// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukwkNiggjGhIEtQp_RaZ9tZ2HFy845cM',
    appId: '1:968578397566:web:b035e517e88398b5e3ef2f',
    messagingSenderId: '968578397566',
    projectId: 'my-gift-pool',
    authDomain: 'my-gift-pool.firebaseapp.com',
    storageBucket: 'my-gift-pool.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0UNkbXzMD2rfuTK46koZDuFZneYM7KHM',
    appId: '1:968578397566:android:e0a178617e653de6e3ef2f',
    messagingSenderId: '968578397566',
    projectId: 'my-gift-pool',
    storageBucket: 'my-gift-pool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuUKdOgpZEU9tACVdsqE01MomcMhEzDx8',
    appId: '1:968578397566:ios:e4c5529283abd613e3ef2f',
    messagingSenderId: '968578397566',
    projectId: 'my-gift-pool',
    storageBucket: 'my-gift-pool.firebasestorage.app',
    iosBundleId: 'com.linguistpro.chirpPolly',
  );
}
