const fs = require('fs');
const path = require('path');

const corpus = JSON.parse(fs.readFileSync('firestore_data/zh_a1_a2_corpus.json', 'utf8'));
const seen = new Set(corpus);

const replacements = [
    // Objects & Home
    { word: "本子", translation: "Notebook", phonetic: "Běnzi" },
    { word: "布", translation: "Cloth", phonetic: "Bù" },
    { word: "被单", translation: "Bed sheet", phonetic: "Bèidān" },
    { word: "枕头", translation: "Pillow", phonetic: "Zhěntou" },
    { word: "勺子", translation: "Spoon", phonetic: "Sháozi" },
    { word: "筷子", translation: "Chopsticks", phonetic: "Kuàizi" },
    { word: "盘子", translation: "Plate", phonetic: "Pánzi" },
    { word: "碗", translation: "Bowl", phonetic: "Wǎn" },
    { word: "瓶子", translation: "Bottle", phonetic: "Píngzi" },
    { word: "罐子", translation: "Jar/Can", phonetic: "Guànzi" },
    { word: "箱子", translation: "Box/Trunk", phonetic: "Xiāngzi" },
    { word: "袋子", translation: "Bag", phonetic: "Dàizi" },
    { word: "绳子", translation: "Rope", phonetic: "Shéngzi" },
    { word: "盒子", translation: "Small box", phonetic: "Hézi" },
    { word: "镜子", translation: "Mirror", phonetic: "Jìngzi" },
    { word: "台灯", translation: "Desk lamp", phonetic: "Táidēng" },
    { word: "电池", translation: "Battery", phonetic: "Diànchí" },
    { word: "插头", translation: "Plug", phonetic: "Chātóu" },
    { word: "开关", translation: "Switch", phonetic: "Kāiguān" },
    { word: "插座", translation: "Socket", phonetic: "Chāzuò" },
    { word: "电线", translation: "Wire", phonetic: "Diànxiàn" },
    { word: "剪刀", translation: "Scissors", phonetic: "Jiǎndāo" },
    { word: "钉子", translation: "Nail", phonetic: "Dīngzi" },
    { word: "锁", translation: "Lock", phonetic: "Suǒ" },
    { word: "钥匙", translation: "Key", phonetic: "Yàoshi" },

    // Clothing & Fashion
    { word: "由于", translation: "Due to", phonetic: "Yóuyú" }, // Re-checking
    { word: "衬衫", translation: "Shirt", phonetic: "Chènshān" },
    { word: "裤子", translation: "Pants", phonetic: "Kùzi" },
    { word: "裙子", translation: "Skirt/Dress", phonetic: "Qúnzi" },
    { word: "毛衣", translation: "Sweater", phonetic: "Máoyī" },
    { word: "内衣", translation: "Underwear", phonetic: "Nèiyī" },
    { word: "袜子", translation: "Socks", phonetic: "Wàzi" },
    { word: "鞋", translation: "Shoes", phonetic: "Xié" },
    { word: "皮带", translation: "Belt", phonetic: "Pídài" },
    { word: "扣子", translation: "Button", phonetic: "Kòuzi" },
    { word: "拉链", translation: "Zipper", phonetic: "Lāliàn" },
    { word: "口袋", translation: "Pocket", phonetic: "Kǒudài" },
    { word: "手提包", translation: "Handbag", phonetic: "Shǒutíbāo" },
    { word: "领带", translation: "Necktie", phonetic: "Lǐngdài" },

    // Body Parts
    { word: "胳膊", translation: "Arm", phonetic: "Gēbo" },
    { word: "手掌", translation: "Palm", phonetic: "Shǒuzhǎng" },
    { word: "手指", translation: "Finger", phonetic: "Shǒuzhǐ" },
    { word: "腿", translation: "Leg", phonetic: "Tuǐ" },
    { word: "脚", translation: "Foot", phonetic: "Jiǎo" },
    { word: "膝盖", translation: "Knee", phonetic: "Xīgài" },
    { word: "肩膀", translation: "Shoulder", phonetic: "Jiānbǎng" },
    { word: "背", translation: "Back", phonetic: "Bèi" },
    { word: "腰", translation: "Waist", phonetic: "Yāo" },
    { word: "肚子", translation: "Stomach/Belly", phonetic: "Dùzi" },
    { word: "胸", translation: "Chest", phonetic: "Xiōng" },
    { word: "脖子", translation: "Neck", phonetic: "Bózi" },
    { word: "头发", translation: "Hair", phonetic: "Tóufa" },
    { word: "眉毛", translation: "Eyebrow", phonetic: "Méimao" },
    { word: "睫毛", translation: "Eyelash", phonetic: "Jiémáo" },
    { word: "耳朵", translation: "Ear", phonetic: "Ěrduo" },
    { word: "鼻子", translation: "Nose", phonetic: "Bízi" },
    { word: "嘴巴", translation: "Mouth", phonetic: "Zuǐba" },
    { word: "牙齿", translation: "Tooth", phonetic: "Yáchǐ" },
    { word: "皮肤", translation: "Skin", phonetic: "Pífū" },

    // Food & Groceries
    { word: "大米", translation: "Raw rice", phonetic: "Dàmǐ" },
    { word: "面粉", translation: "Flour", phonetic: "Miànfěn" },
    { word: "食盐", translation: "Salt", phonetic: "Shíyán" },
    { word: "白糖", translation: "Sugar", phonetic: "Báitáng" },
    { word: "酱油", translation: "Soy sauce", phonetic: "Jiàngyóu" },
    { word: "醋", translation: "Vinegar", phonetic: "Cù" },
    { word: "食用油", translation: "Cooking oil", phonetic: "Shíyòngyóu" },
    { word: "生姜", translation: "Ginger", phonetic: "Shēngjiāng" },
    { word: "大蒜", translation: "Garlic", phonetic: "Dàsuàn" },
    { word: "葱", translation: "Green onion", phonetic: "Cōng" },
    { word: "辣椒", translation: "Chili", phonetic: "Làjiāo" },
    { word: "土豆", translation: "Potato", phonetic: "Tǔdòu" },
    { word: "西红柿", translation: "Tomato", phonetic: "Xīhóngshì" },
    { word: "胡萝卜", translation: "Carrot", phonetic: "Húluóbo" },
    { word: "洋葱", translation: "Onion", phonetic: "Yángcōng" },
    { word: "蘑菇", translation: "Mushroom", phonetic: "Mógu" },
    { word: "菠菜", translation: "Spinach", phonetic: "Bōcài" },
    { word: "黄瓜", translation: "Cucumber", phonetic: "Huángguā" },
    { word: "茄子", translation: "Eggplant", phonetic: "Qiézi" },
    { word: "南瓜", translation: "Pumpkin", phonetic: "Nánguā" },

    // Fruit
    { word: "苹果", translation: "Apple", phonetic: "Píngguǒ" },
    { word: "香蕉", translation: "Banana", phonetic: "Xiāngjiāo" },
    { word: "西瓜", translation: "Watermelon", phonetic: "Xīguā" },
    { word: "葡萄", translation: "Grape", phonetic: "Pútáo" },
    { word: "桃子", translation: "Peach", phonetic: "Táozi" },
    { word: "李子", translation: "Plum", phonetic: "Lǐzi" },
    { word: "杏", translation: "Apricot", phonetic: "Xìng" },
    { word: "芒果", translation: "Mango", phonetic: "Mángguǒ" },
    { word: "菠萝", translation: "Pineapple", phonetic: "Bōluó" },
    { word: "草莓", translation: "Strawberry", phonetic: "Cǎoméi" },
    { word: "蓝莓", translation: "Blueberry", phonetic: "Lánméi" },
    { word: "樱桃", translation: "Cherry", phonetic: "Yīngtáo" },
    { word: "柠檬", translation: "Lemon", phonetic: "Níngméng" },
    { word: "椰子", translation: "Coconut", phonetic: "Yēzi" },
    { word: "榴莲", translation: "Durian", phonetic: "Liúlián" },

    // Verbs (Daily Life)
    { word: "洗脸", translation: "Wash face", phonetic: "Xǐliǎn" },
    { word: "刷牙", translation: "Brush teeth", phonetic: "Shuāyá" },
    { word: "洗澡", translation: "Take a bath", phonetic: "Xǐzǎo" },
    { word: "梳头", translation: "Comb hair", phonetic: "Shūtóu" },
    { word: "穿衣", translation: "Get dressed", phonetic: "Chuānyī" },
    { word: "脱鞋", translation: "Take off shoes", phonetic: "Tuōxié" },
    { word: "倒水", translation: "Pour water", phonetic: "Dàoshuǐ" },
    { word: "端饭", translation: "Bring food/tray", phonetic: "Duānfàn" },
    { word: "收拾", translation: "Clean up/Pack", phonetic: "Shōushi" },
    { word: "打扫", translation: "Sweep/Clean", phonetic: "Dǎsǎo" },
    { word: "浇花", translation: "Water flowers", phonetic: "Jiāohuā" },
    { word: "喂猫", translation: "Feed the cat", phonetic: "Wèimāo" },
    { word: "遛狗", translation: "Walk the dog", phonetic: "Liùgǒu" },
    { word: "修剪", translation: "Trim/Prune", phonetic: "Xiūjiǎn" },
    { word: "搬运", translation: "Carry/Move", phonetic: "Bānyùn" },
    { word: "储存", translation: "Store/Deposit", phonetic: "Chǔcún" },
    { word: "寻找", translation: "Search for", phonetic: "Xúnzhǎo" },
    { word: "计算", translation: "Calculate", phonetic: "Jìsuàn" },
    { word: "标记", translation: "Mark", phonetic: "Biāojì" },
    { word: "打印", translation: "Print", phonetic: "Dǎyìn" },

    // Emotions & States
    { word: "兴奋", translation: "Excited", phonetic: "Xīngfèn" },
    { word: "紧张", translation: "Nervous", phonetic: "Jǐnzhāng" },
    { word: "吃惊", translation: "Surprised", phonetic: "Chījīng" },
    { word: "害羞", translation: "Shy", phonetic: "Hàixiū" },
    { word: "害怕", translation: "Scared", phonetic: "Hàipà" },
    { word: "愤怒", translation: "Angry", phonetic: "Fènnù" },
    { word: "伤心", translation: "Sad", phonetic: "Shāngxīn" },
    { word: "无聊", translation: "Bored", phonetic: "Wúliáo" },
    { word: "寂寞", translation: "Lonely", phonetic: "Jìmò" },
    { word: "得意", translation: "Proud/Smug", phonetic: "Déyì" },
    { word: "后悔", translation: "Regret", phonetic: "Hòuhuǐ" },
    { word: "烦恼", translation: "Worried/Annoyed", phonetic: "Fánnǎo" },
    { word: "耐心", translation: "Patient", phonetic: "Nàixīn" },
    { word: "专心", translation: "Concentrated", phonetic: "Zhuānxīn" },
    { word: "仔细", translation: "Careful/Detailed", phonetic: "Zǐxì" },
    { word: "马虎", translation: "Careless", phonetic: "Mǎhu" },

    // Abstract Concepts
    { word: "能量", translation: "Energy", phonetic: "Néngliàng" },
    { word: "物质", translation: "Matter/Material", phonetic: "Wùzhì" },
    { word: "速度", translation: "Speed", phonetic: "Sùdù" },
    { word: "角度", translation: "Angle", phonetic: "Jiǎodù" },
    { word: "比例", translation: "Proportion", phonetic: "Bǐlì" },
    { word: "趋势", translation: "Trend", phonetic: "Qūshì" },
    { word: "标准", translation: "Standard", phonetic: "Biāozhǔn" },
    { word: "质量", translation: "Quality", phonetic: "Zhìliàng" },
    { word: "数量", phonetic: "Shùliàng", translation: "Quantity" },
    { word: "类型", phonetic: "Lèixíng", translation: "Type/Category" },
    { word: "结构", phonetic: "Jiégòu", translation: "Structure" },
    { word: "功能", phonetic: "Gōngnéng", translation: "Function" },
    { word: "价值", phonetic: "Jiàzhí", translation: "Value" },
    { word: "影响", phonetic: "Yǐngxiǎng", translation: "Influence/Effect" },
    { word: "联系", phonetic: "Liánxì", translation: "Connection/Contact" },
    { word: "区别", phonetic: "Qūbié", translation: "Difference" },
    { word: "一致", phonetic: "Yīzhì", translation: "Consistent" },
    { word: "典型", phonetic: "Diǎnxíng", translation: "Typical" },
    { word: "核心", phonetic: "Héxīn", translation: "Core" },
    { word: "极端", phonetic: "Jíduān", translation: "Extreme" },

    // More common Objects
    { word: "塑料", translation: "Plastic", phonetic: "Sùliào" },
    { word: "金属", translation: "Metal", phonetic: "Jīnshǔ" },
    { word: "木头", translation: "Wood", phonetic: "Mùtou" },
    { word: "玻璃", translation: "Glass", phonetic: "Bōli" },
    { word: "陶瓷", translation: "Ceramic", phonetic: "Táocí" },
    { word: "皮革", translation: "Leather", phonetic: "Pígé" },
    { word: "棉花", translation: "Cotton", phonetic: "Miánhua" },
    { word: "丝绸", translation: "Silk", phonetic: "Sīchóu" },
    { word: "羊毛", translation: "Wool", phonetic: "Yángmáo" },
    { word: "燃料", translation: "Fuel", phonetic: "Ránliào" },

    // Weather & Nature
    { word: "彩虹", translation: "Rainbow", phonetic: "Cǎihóng" },
    { word: "雪花", translation: "Snowflake", phonetic: "Xuěhuā" },
    { word: "冰层", translation: "Ice layer", phonetic: "Bīngcéng" },
    { word: "雾霭", translation: "Mist/Haze", phonetic: "Wù'ǎi" },
    { word: "露水", translation: "Dew", phonetic: "Lùshuǐ" },
    { word: "潮汐", translation: "Tide", phonetic: "Cháoxī" },
    { word: "地震", translation: "Earthquake", phonetic: "Dìzhèn" },
    { word: "海啸", translation: "Tsunami", phonetic: "Hǎixiào" },
    { word: "飓风", translation: "Hurricane", phonetic: "Jùfēng" },
    { word: "干旱", translation: "Drought", phonetic: "Gānhàn" },
    { word: "洪水", translation: "Flood", phonetic: "Hóngshuǐ" },
    { word: "岩浆", translation: "Magma", phonetic: "Yánjiāng" },
    { word: "珊瑚", translation: "Coral", phonetic: "Shānhú" },
    { word: "珍珠", translation: "Pearl", phonetic: "Zhēnzhū" },
    { word: "化石", translation: "Fossil", phonetic: "Huàshí" },

    // Tools
    { word: "榔头", translation: "Hammer", phonetic: "Lángtou" },
    { word: "改锥", translation: "Screwdriver", phonetic: "Gǎizhuī" },
    { word: "扳手", translation: "Wrench", phonetic: "Bānshǒu" },
    { word: "电钻", translation: "Electric drill", phonetic: "Diànzuàn" },
    { word: "锯子", translation: "Saw", phonetic: "Jùzi" },
    { word: "梯子", translation: "Ladder", phonetic: "Tīzi" },
    { word: "绳索", translation: "Rope/Cable", phonetic: "Shéngsuǒ" },
    { word: "钩子", translation: "Hook", phonetic: "Gōuzi" },
    { word: "镊子", translation: "Tweezers", phonetic: "Nièzi" },
    { word: "放大镜", translation: "Magnifying glass", phonetic: "Fàngdàjìng" },

    // Tech/Internet
    { word: "服务器", translation: "Server", phonetic: "Fúwùqì" },
    { word: "终端", translation: "Terminal", phonetic: "Zhōngduān" },
    { word: "信号", translation: "Signal", phonetic: "Xìnhào" },
    { word: "基站", translation: "Base station", phonetic: "Jīzhàn" },
    { word: "卫星", translation: "Satellite", phonetic: "Wèixīng" },
    { word: "光纤", translation: "Optical fiber", phonetic: "Guāngqiān" },
    { word: "协议", translation: "Protocol", phonetic: "Xiéyì" },
    { word: "算法", translation: "Algorithm", phonetic: "Suànfǎ" },
    { word: "缓存", translation: "Cache", phonetic: "Huǎncún" },
    { word: "防火墙", translation: "Firewall", phonetic: "Fánghuǒqiáng" },
    { word: "病毒", translation: "Virus (comp)", phonetic: "Bìngdú" },
    { word: "漏洞", translation: "Vulnerability/Leak", phonetic: "Lòudòng" },
    { word: "补丁", translation: "Patch", phonetic: "Bǔdīng" },
    { word: "版本", translation: "Version", phonetic: "Bǎnběn" },
    { word: "界面", translation: "Interface", phonetic: "Jièmiàn" },
    { word: "按钮", translation: "Button", phonetic: "Ànniǔ" },
    { word: "窗口", translation: "Window (comp)", phonetic: "Chuāngkǒu" },
    { word: "后台", translation: "Backend", phonetic: "Hòutái" },
    { word: "前端", translation: "Frontend", phonetic: "Qiánduān" },
    { word: "数据库", translation: "Database", phonetic: "Shùjùkù" },

    // Finance
    { word: "余额", translation: "Balance (money)", phonetic: "Yú'é" },
    { word: "账单", translation: "Bill", phonetic: "Zhàngdān" },
    { word: "发票", translation: "Invoice/Receipt", phonetic: "Fāpiào" },
    { word: "存款", translation: "Deposit", phonetic: "Cúnkuǎn" },
    { word: "贷款", translation: "Loan", phonetic: "Dàikuǎn" },
    { word: "利息", translation: "Interest", phonetic: "Lìxī" },
    { word: "本金", translation: "Principal (finance)", phonetic: "Běnjīn" },
    { word: "股票", translation: "Stock", phonetic: "Gǔpiào" },
    { word: "基金", translation: "Fund", phonetic: "Jījīn" },
    { word: "保险", translation: "Insurance", phonetic: "Bǎoxiǎn" },
    { word: "税收", translation: "Tax", phonetic: "Shuìshōu" },
    { word: "成本", translation: "Cost", phonetic: "Chéngběn" },
    { word: "利润", translation: "Profit", phonetic: "Lìrùn" },
    { word: "预算", translation: "Budget", phonetic: "Yùsuàn" },
    { word: "投资", translation: "Investment", phonetic: "Tóuzī" },

    // More Nouns
    { word: "英雄", translation: "Hero", phonetic: "Yīngxióng" },
    { word: "梦想", translation: "Dream", phonetic: "Mèngxiǎng" },
    { word: "机会", translation: "Opportunity", phonetic: "Jīhuì" },
    { word: "知识", translation: "Knowledge", phonetic: "Zhīshi" },
    { word: "技术", translation: "Technology", phonetic: "Jìshù" },
    { word: "经验", translation: "Experience", phonetic: "Jīngyàn" },
    { word: "传统", translation: "Tradition", phonetic: "Chuántǒng" },
    { word: "艺术", translation: "Art", phonetic: "Yìshù" },
    { word: "文化", translation: "Culture", phonetic: "Wénhuà" },
    { word: "历史", translation: "History", phonetic: "Lìshǐ" },

    // Animals
    { word: "企鹅", translation: "Penguin", phonetic: "Qǐ'é" },
    { word: "鸵鸟", translation: "Ostrich", phonetic: "Tuóniǎo" },
    { word: "鳄鱼", translation: "Crocodile", phonetic: "Èyú" },
    { word: "鲸鱼", translation: "Whale", phonetic: "Jīngyú" },
    { word: "鲨鱼", translation: "Shark", phonetic: "Shāyú" },
    { word: "海豚", translation: "Dolphin", phonetic: "Hǎitún" },
    { word: "章鱼", translation: "Octopus", phonetic: "Zhāngyú" },
    { word: "水母", translation: "Jellyfish", phonetic: "Shuǐmǔ" },
    { word: "龙虾", translation: "Lobster", phonetic: "Lóngxiā" },
    { word: "螃蟹", translation: "Crab", phonetic: "Pángxiè" },
    { word: "贝壳", translation: "Shell", phonetic: "Bèiké" },
    { word: "海星", translation: "Starfish", phonetic: "Hǎixīng" },
    { word: "海马", translation: "Seahorse", phonetic: "Hǎimǎ" },
    { word: "水獭", translation: "Otter", phonetic: "Shuǐtǎ" },
    { word: "海狮", translation: "Sea lion", phonetic: "Hǎishī" }
];

const processed = [];
const internalSeen = new Set();
replacements.forEach(r => {
    if (!seen.has(r.word) && !internalSeen.has(r.word)) {
        processed.push(r);
        internalSeen.add(r.word);
    }
});

fs.writeFileSync(path.join('firestore_data', 'zh_replacement_pool.json'), JSON.stringify(processed, null, 2));

console.log(`✅ Generated replacement pool with ${processed.length} unique words.`);
