const fs = require('fs');
const path = require('path');

const firestoreDataDir = path.join(__dirname, '..', 'firestore_data');
const exclusionListPath = path.join(firestoreDataDir, 'en_a1_a2_exclusion_list.json');

// Replacement candidates with IPA
const replacementBank = [
    { word: "advocacy", phonetic: "/ˈædvəkəsi/" },
    { word: "affiliation", phonetic: "/əˌfɪliˈeɪʃən/" },
    { word: "aggregate", phonetic: "/ˈæɡrɪɡət/" },
    { word: "allegation", phonetic: "/ˌæləˈɡeɪʃən/" },
    { word: "ambiguity", phonetic: "/ˌæmbɪˈɡjuːəti/" },
    { word: "analogy", phonetic: "/əˈnælədʒi/" },
    { word: "anomaly", phonetic: "/əˈnɑːməli/" },
    { word: "arbitrary", phonetic: "/ˈɑːrbɪtreri/" },
    { word: "assertion", phonetic: "/əˈsɜːrʃən/" },
    { word: "attainment", phonetic: "/əˈteɪnmənt/" },
    { word: "attribute", phonetic: "/ˈætrɪbjuːt/" },
    { word: "authenticity", phonetic: "/ˌɔːθenˈtɪsəti/" },
    { word: "autonomy", phonetic: "/ɔːˈtɑːnəmi/" },
    { word: "bias", phonetic: "/ˈbaɪəs/" },
    { word: "catalyst", phonetic: "/ˈkætəlɪst/" },
    { word: "censorship", phonetic: "/ˈsensərʃɪp/" },
    { word: "chronicle", phonetic: "/ˈkrɑːnɪkəl/" },
    { word: "coherence", phonetic: "/koʊˈhɪrəns/" },
    { word: "coincide", phonetic: "/ˌkoʊɪnˈsaɪd/" },
    { word: "collusion", phonetic: "/kəˈluːʒən/" },
    { word: "complement", phonetic: "/ˈkɑːmplɪment/" },
    { word: "compliance", phonetic: "/kəmˈplaɪəns/" },
    { word: "concession", phonetic: "/kənˈseʃən/" },
    { word: "conducive", phonetic: "/kənˈduːsɪv/" },
    { word: "conjecture", phonetic: "/kənˈdʒektʃər/" },
    { word: "consensus", phonetic: "/kənˈsensəs/" },
    { word: "constraint", phonetic: "/kənˈstreɪnt/" },
    { word: "conundrum", phonetic: "/kəˈnʌndrəm/" },
    { word: "correlation", phonetic: "/ˌkɔːrəˈleɪʃən/" },
    { word: "corroborate", phonetic: "/kəˈrɑːbəreɪt/" },
    { word: "credibility", phonetic: "/ˌkredəˈbɪləti/" },
    { word: "criterion", phonetic: "/kraɪˈtɪriən/" },
    { word: "culmination", phonetic: "/ˌkʌlmɪˈneɪʃən/" },
    { word: "deficiency", phonetic: "/dɪˈfɪʃənsi/" },
    { word: "demographics", phonetic: "/ˌdeməˈɡræfɪks/" },
    { word: "depiction", phonetic: "/dɪˈpɪkʃən/" },
    { word: "deterrent", phonetic: "/dɪˈtɜːrənt/" },
    { word: "deviation", phonetic: "/ˌdiːviˈeɪʃən/" },
    { word: "discourse", phonetic: "/ˈdɪskɔːrs/" },
    { word: "disparity", phonetic: "/dɪˈspærəti/" },
    { word: "divergence", phonetic: "/daɪˈvɜːrdʒəns/" },
    { word: "doctrine", phonetic: "/ˈdɑːktrɪn/" },
    { word: "efficacy", phonetic: "/ˈefɪkəsi/" },
    { word: "egalitarian", phonetic: "/iˌɡælɪˈteriən/" },
    { word: "elicit", phonetic: "/iˈlɪsɪt/" },
    { word: "empirical", phonetic: "/emˈpɪrɪkəl/" },
    { word: "endeavor", phonetic: "/ɪnˈdevər/" },
    { word: "equilibrium", phonetic: "/ˌiːkwɪˈlɪbriəm/" },
    { word: "equivalent", phonetic: "/ɪˈkwɪvələnt/" },
    { word: "erratic", phonetic: "/ɪˈrætɪk/" },
    { word: "evocative", phonetic: "/ɪˈvɑːkətɪv/" },
    { word: "exacerbate", phonetic: "/ɪɡˈzæsərbeɪt/" },
    { word: "exemplary", phonetic: "/ɪɡˈzempləri/" },
    { word: "exertion", phonetic: "/ɪɡˈzɜːrʃən/" },
    { word: "explicit", phonetic: "/ɪkˈsplɪsɪt/" },
    { word: "exploitation", phonetic: "/ˌeksplɔɪˈteɪʃən/" },
    { word: "feasibility", phonetic: "/ˌfiːzəˈbɪləti/" },
    { word: "fluctuation", phonetic: "/ˌflʌktʃuˈeɪʃən/" },
    { word: "formidable", phonetic: "/ˈfɔːrmɪdəbəl/" },
    { word: "grandeur", phonetic: "/ˈɡrændʒər/" },
    { word: "hierarchy", phonetic: "/ˈhaɪərɑːrki/" },
    { word: "hypothesis", phonetic: "/haɪˈpɑːθəsɪs/" },
    { word: "ideology", phonetic: "/ˌaɪdiˈɑːlədʒi/" },
    { word: "imperative", phonetic: "/ɪmˈperətɪv/" },
    { word: "implication", phonetic: "/ˌɪmplɪˈkeɪʃən/" },
    { word: "implicit", phonetic: "/ɪmˈplɪsɪt/" },
    { word: "incentive", phonetic: "/ɪnˈsentɪv/" },
    { word: "incidence", phonetic: "/ˈɪnsɪdəns/" },
    { word: "inclination", phonetic: "/ˌɪnklɪˈneɪʃən/" },
    { word: "indigenous", phonetic: "/ɪnˈdɪdʒənəs/" },
    { word: "inevitable", phonetic: "/ɪnˈevɪtəbəl/" },
    { word: "inference", phonetic: "/ˈɪnfərəns/" },
    { word: "infrastructure", phonetic: "/ˈɪnfrəˌstrʌktʃər/" },
    { word: "inherent", phonetic: "/ɪnˈhɪrənt/" },
    { word: "inhibitor", phonetic: "/ɪnˈhɪbɪtər/" },
    { word: "innovation", phonetic: "/ˌɪnəˈveɪʃən/" },
    { word: "integrity", phonetic: "/ɪnˈteɡrəti/" },
    { word: "intervention", phonetic: "/ˌɪntərˈvenʃən/" },
    { word: "intrinsic", phonetic: "/ɪnˈtrɪnzɪk/" },
    { word: "irrelevant", phonetic: "/ɪˈreləvənt/" },
    { word: "isolation", phonetic: "/ˌaɪsəˈleɪʃən/" },
    { word: "judicious", phonetic: "/dʒuˈdɪʃəs/" },
    { word: "justification", phonetic: "/ˌdʒʌstɪfɪˈkeɪʃən/" },
    { word: "kinship", phonetic: "/ˈkɪnʃɪp/" },
    { word: "liability", phonetic: "/ˌlaɪəˈbɪləti/" },
    { word: "liberty", phonetic: "/ˈlɪbərti/" },
    { word: "magnitude", phonetic: "/ˈmæɡnɪtuːd/" },
    { word: "manifestation", phonetic: "/ˌmænɪfeˈsteɪʃən/" },
    { word: "marginal", phonetic: "/ˈmɑːrdʒɪnəl/" },
    { word: "mediation", phonetic: "/ˌmiːdiˈeɪʃən/" },
    { word: "metaphor", phonetic: "/ˈmetəfɔːr/" },
    { word: "methodology", phonetic: "/ˌmeθəˈdɑːlədʒi/" },
    { word: "mitigation", phonetic: "/ˌmɪtɪˈɡeɪʃən/" },
    { word: "modality", phonetic: "/moʊˈdæləti/" },
    { word: "momentum", phonetic: "/moʊˈmentəm/" },
    { word: "monopoly", phonetic: "/məˈnɑːpəli/" },
    { word: "motivation", phonetic: "/ˌmoʊtɪˈveɪʃən/" },
    { word: "negligence", phonetic: "/ˈneɡlɪdʒəns/" },
    { word: "norm", phonetic: "/nɔːrm/" },
    { word: "notion", phonetic: "/ˈnoʊʃən/" },
    { word: "nucleus", phonetic: "/ˈnuːkliəs/" },
    { word: "objective", phonetic: "/əbˈdʒektɪv/" },
    { word: "obscurity", phonetic: "/əbˈskjʊrəti/" },
    { word: "offset", phonetic: "/ˈɔːfset/" },
    { word: "omission", phonetic: "/oʊˈmɪʃən/" },
    { word: "onus", phonetic: "/ˈoʊnəs/" },
    { word: "optimum", phonetic: "/ˈɑːptɪməm/" },
    { word: "orientation", phonetic: "/ˌɔːriənˈteɪʃən/" },
    { word: "paradigm", phonetic: "/ˈpærədaɪm/" },
    { word: "parameter", phonetic: "/pəˈræmɪtər/" },
    { word: "perception", phonetic: "/pərˈsepʃən/" },
    { word: "persistence", phonetic: "/pərˈsɪstəns/" },
    { word: "perspective", phonetic: "/pərˈspektɪv/" },
    { word: "phenomenon", phonetic: "/fəˈnɑːmɪˌnɑːn/" },
    { word: "plausibility", phonetic: "/ˌplɔːzəˈbɪləti/" },
    { word: "postulate", phonetic: "/ˈpɑːstʃuleɪt/" },
    { word: "precedence", phonetic: "/ˈpresɪdəns/" },
    { word: "precedent", phonetic: "/ˈpresɪdənt/" },
    { word: "precursor", phonetic: "/priːˈkɜːrsər/" },
    { word: "premise", phonetic: "/ˈpremɪs/" },
    { word: "prevalence", phonetic: "/ˈprevələns/" },
    { word: "priority", phonetic: "/praɪˈɔːrəti/" },
    { word: "probability", phonetic: "/ˌprɑːbəˈbɪləti/" },
    { word: "proliferation", phonetic: "/prəˌlɪfəˈreɪʃən/" },
    { word: "propensity", phonetic: "/prəˈpensəti/" },
    { word: "proxy", phonetic: "/ˈprɑːksi/" },
    { word: "prudence", phonetic: "/ˈpruːdns/" },
    { word: "qualification", phonetic: "/ˌkwɑːlɪfɪˈkeɪʃən/" },
    { word: "quota", phonetic: "/ˈkwoʊtə/" },
    { word: "rationale", phonetic: "/ˌræʃəˈnæl/" },
    { word: "rebellion", phonetic: "/rɪˈbeljən/" },
    { word: "reciprocity", phonetic: "/ˌresɪˈprɑːsəti/" },
    { word: "reconcile", phonetic: "/ˈrekənsaɪl/" },
    { word: "redundancy", phonetic: "/rɪˈdʌndənsi/" },
    { word: "refutation", phonetic: "/ˌrefjuˈteɪʃən/" },
    { word: "regulation", phonetic: "/ˌreɡjuˈleɪʃən/" },
    { word: "relevance", phonetic: "/ˈreləvəns/" },
    { word: "reliability", phonetic: "/rɪˌlaɪəˈbɪləti/" },
    { word: "remedy", phonetic: "/ˈremədi/" },
    { word: "remittance", phonetic: "/rɪˈmɪtns/" },
    { word: "renaissance", phonetic: "/ˈrenəsɑːns/" },
    { word: "repercussion", phonetic: "/ˌriːpərˈkʌʃən/" },
    { word: "requisite", phonetic: "/ˈrekwɪzɪt/" },
    { word: "resilience", phonetic: "/rɪˈzɪliəns/" },
    { word: "resolution", phonetic: "/ˌrezəˈluːʃən/" },
    { word: "restraint", phonetic: "/rɪˈstreɪnt/" },
    { word: "rhetoric", phonetic: "/ˈretərɪk/" },
    { word: "sanction", phonetic: "/ˈsæŋkʃən/" },
    { word: "scarcity", phonetic: "/ˈskersəti/" },
    { word: "scrutiny", phonetic: "/ˈskruːtəni/" },
    { word: "secular", phonetic: "/ˈsekjələr/" },
    { word: "simulation", phonetic: "/ˌsɪmjuˈleɪʃən/" },
    { word: "skepticism", phonetic: "/ˈskeptɪˌsɪzəm/" },
    { word: "solitude", phonetic: "/ˈsɑːləˌtuːd/" },
    { word: "speculation", phonetic: "/ˌspekjuˈleɪʃən/" },
    { word: "stature", phonetic: "/ˈstætʃər/" },
    { word: "stewardship", phonetic: "/ˈstuːərdʃɪp/" },
    { word: "stimulus", phonetic: "/ˈstɪmjələs/" },
    { word: "stringent", phonetic: "/ˈstrɪndʒənt/" },
    { word: "subsequent", phonetic: "/ˈsʌbsɪkwənt/" },
    { word: "subsidy", phonetic: "/ˈsʌbsədi/" },
    { word: "successor", phonetic: "/səkˈsesər/" },
    { word: "sufficiency", phonetic: "/səˈfɪʃənsi/" },
    { word: "superficial", phonetic: "/ˌsuːpərˈfɪʃəl/" },
    { word: "surplus", phonetic: "/ˈsɜːrpləs/" },
    { word: "susceptibility", phonetic: "/səˌseptəˈbɪləti/" },
    { word: "sustainability", phonetic: "/səˌsteɪnəˈbɪləti/" },
    { word: "symbiosis", phonetic: "/ˌsɪmbaɪˈoʊsɪs/" },
    { word: "symmetry", phonetic: "/ˈsɪmətri/" },
    { word: "synergy", phonetic: "/ˈsɪnərdʒi/" },
    { word: "synthesis", phonetic: "/ˈsɪnθəsɪs/" },
    { word: "tangible", phonetic: "/ˈtændʒəbəl/" },
    { word: "taxonomy", phonetic: "/tækˈsɑːnəmi/" },
    { word: "tenacity", phonetic: "/təˈnæsəti/" },
    { word: "tendency", phonetic: "/ˈtendənsi/" },
    { word: "terrain", phonetic: "/təˈreɪn/" },
    { word: "threshold", phonetic: "/ˈθreʃhoʊld/" },
    { word: "tolerance", phonetic: "/ˈtɑːlərəns/" },
    { word: "topology", phonetic: "/təˈpɑːlədʒi/" },
    { word: "trajectory", phonetic: "/trəˈdʒektəri/" },
    { word: "transaction", phonetic: "/trænˈzækʃən/" },
    { word: "transcend", phonetic: "/trænˈsend/" },
    { word: "transcript", phonetic: "/ˈtrænskrɪpt/" },
    { word: "transition", phonetic: "/trænˈzɪʃən/" },
    { word: "translucency", phonetic: "/trænsˈluːsnsi/" },
    { word: "transmission", phonetic: "/trænzˈmɪʃən/" },
    { word: "transparency", phonetic: "/trænsˈpærənsi/" },
    { word: "unification", phonetic: "/ˌjuːnɪfɪˈkeɪʃən/" },
    { word: "utilization", phonetic: "/ˌjuːtələˈzeɪʃən/" },
    { word: "validity", phonetic: "/vəˈlɪdəti/" },
    { word: "variation", phonetic: "/ˌveriˈeɪʃən/" },
    { word: "versatility", phonetic: "/ˌvɜːrsəˈtɪləti/" },
    { word: "viability", phonetic: "/ˌvaɪəˈbɪləti/" },
    { word: "visibility", phonetic: "/ˌvɪzəˈbɪləti/" },
    { word: "volatility", phonetic: "/ˌvɑːləˈtɪləti/" },
    { word: "vulnerability", phonetic: "/ˌvʌlnərəˈbɪləti/" },
    { word: "abundance", phonetic: "/əˈbʌndəns/" },
    { word: "accelerate", phonetic: "/əkˈseləreɪt/" },
    { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/" },
    { word: "acquisition", phonetic: "/ˌækwɪˈzɪʃən/" },
    { word: "adaptation", phonetic: "/ˌædæpˈteɪʃən/" },
    { word: "adjacent", phonetic: "/əˈdʒeɪsnt/" },
    { word: "aesthetic", phonetic: "/esˈθetɪk/" },
    { word: "allocate", phonetic: "/ˈæləkeɪt/" },
    { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/" },
    { word: "amplify", phonetic: "/ˈæmplɪfaɪ/" },
    { word: "analogue", phonetic: "/ˈænəlɔːɡ/" },
    { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/" },
    { word: "apparatus", phonetic: "/ˌæpəˈrætəs/" },
    { word: "arbitration", phonetic: "/ˌɑːrbɪˈtreɪʃən/" },
    { word: "architecture", phonetic: "/ˈɑːrkɪtektʃər/" },
    { word: "articulate", phonetic: "/ɑːrˈtɪkjuleɪt/" },
    { word: "assessment", phonetic: "/əˈsesmənt/" },
    { word: "assumption", phonetic: "/əˈsʌmpʃən/" },
    { word: "attendance", phonetic: "/əˈtendəns/" },
    { word: "attribution", phonetic: "/ˌætrɪˈbjuːʃən/" },
    { word: "autonomous", phonetic: "/ɔːˈtɑːnəməs/" },
    { word: "benchmark", phonetic: "/ˈbentʃmɑːrk/" },
    { word: "beneficiary", phonetic: "/ˌbenɪˈfɪʃieri/" },
    { word: "boundary", phonetic: "/ˈbaʊndri/" },
    { word: "calibration", phonetic: "/ˌkæləˈbreɪʃən/" },
    { word: "capability", phonetic: "/ˌkeɪpəˈbɪləti/" },
    { word: "categorical", phonetic: "/ˌkætəˈɡɔːrɪkəl/" },
    { word: "chronicle", phonetic: "/ˈkrɑːnɪkəl/" },
    { word: "circulation", phonetic: "/ˌsɜːrkjəˈleɪʃən/" },
    { word: "classification", phonetic: "/ˌklæsɪfɪˈkeɪʃən/" },
    { word: "coefficient", phonetic: "/ˌkoʊɪˈfɪʃnt/" },
    { word: "cognitive", phonetic: "/ˈkɑːɡnətɪv/" },
    { word: "coincidental", phonetic: "/koʊˌɪnsɪˈdentl/" },
    { word: "collaboration", phonetic: "/kəˌlæbəˈreɪʃən/" },
    { word: "collective", phonetic: "/kəˈlektɪv/" },
    { word: "columnist", phonetic: "/ˈkɑːləmnɪst/" },
    { word: "commencement", phonetic: "/kəˈmensmənt/" },
    { word: "commission", phonetic: "/kəˈmɪʃən/" },
    { word: "commodity", phonetic: "/kəˈmɑːdəti/" },
    { word: "comparative", phonetic: "/kəmˈpærətɪv/" },
    { word: "compensation", phonetic: "/ˌkɑːmpenˈseɪʃən/" },
    { word: "competency", phonetic: "/ˈkɑːmpɪtənsi/" },
    { word: "complimentary", phonetic: "/ˌkɑːmplɪˈmentri/" },
    { word: "component", phonetic: "/kəmˈpoʊnənt/" },
    { word: "composition", phonetic: "/ˌkɑːmpəˈzɪʃən/" },
    { word: "comprehensive", phonetic: "/ˌkɑːmpriˈhensɪv/" },
    { word: "conception", phonetic: "/kənˈsepʃən/" },
    { word: "conducive", phonetic: "/kənˈduːsɪv/" },
    { word: "configuration", phonetic: "/kənˌfɪɡjəˈreɪʃən/" },
    { word: "consecutive", phonetic: "/kənˈsekjətɪv/" },
    { word: "consequence", phonetic: "/ˈkɑːnsəkwens/" },
    { word: "conservation", phonetic: "/ˌkɑːnsərˈveɪʃən/" },
    { word: "consistency", phonetic: "/kənˈsɪstənsi/" },
    { word: "consolidation", phonetic: "/kənˌsɑːlɪˈdeɪʃən/" },
    { word: "constituent", phonetic: "/kənˈstɪtʃuənt/" },
    { word: "consumption", phonetic: "/kənˈsʌmpʃən/" },
    { word: "contemplation", phonetic: "/ˌkɑːntəmˈpleɪʃən/" },
    { word: "continuity", phonetic: "/ˌkɑːntɪˈnuːəti/" },
    { word: "contraction", phonetic: "/kənˈtrækʃən/" },
    { word: "contradiction", phonetic: "/ˌkɑːntrəˈdɪkʃən/" },
    { word: "controversial", phonetic: "/ˌkɑːntrəˈvɜːrʃl/" },
    { word: "convergence", phonetic: "/kənˈvɜːrdʒəns/" },
    { word: "cooperation", phonetic: "/koʊˌɑːpəˈreɪʃən/" },
    { word: "coordination", phonetic: "/koʊˌɔːrdnˈeɪʃən/" },
    { word: "corporeal", phonetic: "/kɔːrˈpɔːriəl/" },
    { word: "correlation", phonetic: "/ˌkɔːrəˈleɪʃən/" },
    { word: "correspondence", phonetic: "/ˌkɔːrəˈspɑːndəns/" },
    { word: "counterpart", phonetic: "/ˈkaʊntərpɑːrt/" },
    { word: "coveted", phonetic: "/ˈkʌvɪtɪd/" },
    { word: "credential", phonetic: "/krəˈdenʃl/" },
    { word: "culminate", phonetic: "/ˈkʌlmɪneɪt/" },
    { word: "cultivation", phonetic: "/ˌkʌltɪˈveɪʃən/" },
    { word: "cumulative", phonetic: "/ˈkjuːmjələtɪv/" },
    { word: "curiosity", phonetic: "/ˌkjʊriˈɑːsəti/" },
    { word: "custody", phonetic: "/ˈkʌstədi/" },
    { word: "deception", phonetic: "/dɪˈsepʃən/" },
    { word: "dedication", phonetic: "/ˌdedɪˈkeɪʃən/" },
    { word: "deficiency", phonetic: "/dɪˈfɪʃənsi/" },
    { word: "definitive", phonetic: "/dɪˈfɪnətɪv/" },
    { word: "delegation", phonetic: "/ˌdelɪˈɡeɪʃən/" },
    { word: "deliberate", phonetic: "/dɪˈlɪbərət/" },
    { word: "dependence", phonetic: "/dɪˈpendəns/" },
    { word: "depletion", phonetic: "/dɪˈpliːʃən/" },
    { word: "derivative", phonetic: "/dɪˈrɪvətɪv/" },
    { word: "description", phonetic: "/dɪˈskrɪpʃən/" },
    { word: "designation", phonetic: "/ˌdezɪɡˈneɪʃən/" },
    { word: "detection", phonetic: "/dɪˈtekʃən/" },
    { word: "deterioration", phonetic: "/dɪˌtɪriəˈreɪʃən/" },
    { word: "detrimental", phonetic: "/ˌdetrɪˈmentl/" },
    { word: "devotion", phonetic: "/dɪˈvoʊʃən/" },
    { word: "diagnosis", phonetic: "/ˌdaɪəɡˈnoʊsɪs/" },
    { word: "dimension", phonetic: "/daɪˈmenʃn/" },
    { word: "diminish", phonetic: "/dɪˈmɪnɪʃ/" },
    { word: "diplomacy", phonetic: "/dɪˈploʊməsi/" },
    { word: "disbursement", phonetic: "/dɪsˈbɜːrsmənt/" },
    { word: "discipline", phonetic: "/ˈdɪsəplɪn/" },
    { word: "disclosure", phonetic: "/dɪsˈkloʊʒər/" },
    { word: "discourse", phonetic: "/ˈdɪskɔːrs/" },
    { word: "discretion", phonetic: "/dɪˈskreʃn/" },
    { word: "discrimination", phonetic: "/dɪˌskrɪmɪˈneɪʃən/" },
    { word: "displaced", phonetic: "/dɪsˈpleɪst/" },
    { word: "disposal", phonetic: "/dɪˈspoʊzl/" },
    { word: "disposition", phonetic: "/ˌdɪspəˈzɪʃən/" },
    { word: "disruptive", phonetic: "/dɪsˈrʌptɪv/" },
    { word: "dissolution", phonetic: "/ˌdɪsəˈluːʃən/" },
    { word: "distinction", phonetic: "/dɪˈstɪŋkʃn/" },
    { word: "distortion", phonetic: "/dɪˈstɔːrʃn/" },
    { word: "distribution", phonetic: "/ˌdɪstrɪˈbjuːʃən/" },
    { word: "divergence", phonetic: "/daɪˈvɜːrdʒəns/" },
    { word: "diversification", phonetic: "/daɪˌvɜːrsɪfɪˈkeɪʃən/" },
    { word: "diversity", phonetic: "/daɪˈvɜːrsəti/" },
    { word: "dividend", phonetic: "/ˈdɪvɪdend/" },
    { word: "dominance", phonetic: "/ˈdɑːmɪnəns/" },
    { word: "duration", phonetic: "/duˈreɪʃn/" },
    { word: "eccentric", phonetic: "/ɪkˈsentrɪk/" },
    { word: "ecology", phonetic: "/iˈkɑːlədʒi/" },
    { word: "economics", phonetic: "/ˌekəˈnɑːmɪks/" },
    { word: "elevation", phonetic: "/ˌelɪˈveɪʃən/" },
    { word: "elimination", phonetic: "/ɪˌlɪmɪˈneɪʃən/" },
    { word: "eloquence", phonetic: "/ˈeləkwəns/" },
    { word: "emergence", phonetic: "/iˈmɜːrdʒəns/" },
    { word: "eminent", phonetic: "/ˈemɪnənt/" },
    { word: "emission", phonetic: "/iˈmɪʃən/" },
    { word: "enactment", phonetic: "/ɪˈnæktmənt/" },
    { word: "encounter", phonetic: "/ɪnˈkaʊntər/" },
    { word: "endeavor", phonetic: "/ɪnˈdevər/" },
    { word: "endurance", phonetic: "/ɪnˈdʒʊrəns/" },
    { word: "engagement", phonetic: "/ɪnˈɡeɪdʒmənt/" },
    { word: "enlargement", phonetic: "/ɪnˈlɑːrdʒmənt/" },
    { word: "ensemble", phonetic: "/ɑːnˈsɑːmbl/" },
    { word: "enterprise", phonetic: "/ˈentərpraɪz/" },
    { word: "enthusiasm", phonetic: "/ɪnˈθuːziæzəm/" },
    { word: "entity", phonetic: "/ˈentəti/" },
    { word: "entrepreneur", phonetic: "/ˌɑːntrəprəˈnɜːr/" },
    { word: "environment", phonetic: "/ɪnˈvaɪrənmənt/" },
    { word: "equity", phonetic: "/ˈekwəti/" },
    { word: "equivalence", phonetic: "/ɪˈkwɪvələns/" },
    { word: "erosion", phonetic: "/ɪˈroʊʒn/" },
    { word: "erroneous", phonetic: "/ɪˈroʊniəs/" },
    { word: "erudition", phonetic: "/ˌerjʊˈdɪʃən/" },
    { word: "essence", phonetic: "/ˈesns/" },
    { word: "estimation", phonetic: "/ˌestɪˈmeɪʃən/" },
    { word: "etiquette", phonetic: "/ˈetɪket/" },
    { word: "evaluation", phonetic: "/ɪˌvæljuˈeɪʃən/" },
    { word: "evasion", phonetic: "/iˈveɪʒn/" },
    { word: "evolution", phonetic: "/ˌevəˈluːʃən/" },
    { word: "excavation", phonetic: "/ˌekskəˈveɪʃən/" },
    { word: "exception", phonetic: "/ɪkˈsepʃn/" },
    { word: "exclusion", phonetic: "/ɪkˈskluːʒn/" },
    { word: "execution", phonetic: "/ˌeksɪˈkjuːʃən/" },
    { word: "exemption", phonetic: "/ɪɡˈzempʃn/" },
    { word: "exhaustion", phonetic: "/ɪɡˈzɔːstʃən/" },
    { word: "expansion", phonetic: "/ɪkˈspænʃn/" },
    { word: "expectation", phonetic: "/ˌekspekˈteɪʃən/" },
    { word: "expenditure", phonetic: "/ɪkˈspendɪtʃər/" },
    { word: "expertise", phonetic: "/ˌekspɜːrˈtiːz/" },
    { word: "expiration", phonetic: "/ˌekspəˈreɪʃən/" },
    { word: "explanation", phonetic: "/ˌekspləˈneɪʃən/" },
    { word: "exploitation", phonetic: "/ˌeksplɔɪˈteɪʃən/" },
    { word: "exploration", phonetic: "/ˌekspləˈreɪʃən/" },
    { word: "exposition", phonetic: "/ˌekspəˈzɪʃən/" },
    { word: "exposure", phonetic: "/ɪkˈspoʊʒər/" },
    { word: "expression", phonetic: "/ɪkˈspreʃn/" },
    { word: "extension", phonetic: "/ɪkˈstenʃn/" },
    { word: "extinction", phonetic: "/ɪkˈstɪŋkʃn/" },
    { word: "extraction", phonetic: "/ɪkˈstrækʃn/" },
    { word: "extravagance", phonetic: "/ɪkˈstrævəɡəns/" },
    { word: "facilitation", phonetic: "/fəˌsɪlɪˈteɪʃən/" },
    { word: "feasibility", phonetic: "/ˌfiːzəˈbɪləti/" },
    { word: "fluctuation", phonetic: "/ˌflʌktʃuˈeɪʃən/" },
    { word: "formation", phonetic: "/fɔːrˈmeɪʃn/" },
    { word: "formulation", phonetic: "/ˌfɔːrmjuˈleɪʃən/" },
    { word: "foundation", phonetic: "/faʊnˈdeɪʃn/" },
    { word: "fragmentation", phonetic: "/ˌfræɡmenˈteɪʃən/" },
    { word: "framework", phonetic: "/ˈfreɪmwɜːrk/" },
    { word: "frequency", phonetic: "/ˈfriːkwənsi/" },
    { word: "fulfillment", phonetic: "/fʊlˈfɪlmənt/" },
    { word: "functionality", phonetic: "/ˌfʌŋkʃəˈnæləti/" },
    { word: "fundamental", phonetic: "/ˌfʌndəˈmentl/" },
    { word: "generalization", phonetic: "/ˌdʒenrələˈzeɪʃən/" },
    { word: "generation", phonetic: "/ˌdʒenəˈreɪʃən/" },
    { word: "geography", phonetic: "/dʒiˈɑːɡrəfi/" },
    { word: "geology", phonetic: "/dʒiˈɑːlədʒi/" },
    { word: "globalization", phonetic: "/ˌɡloʊbələˈzeɪʃən/" },
    { word: "governance", phonetic: "/ˈɡʌvərnəns/" },
    { word: "graduation", phonetic: "/ˌɡrædʒuˈeɪʃən/" },
    { word: "gratitude", phonetic: "/ˈɡrætɪtuːd/" },
    { word: "greenhouse", phonetic: "/ˈɡriːnhaʊs/" },
    { word: "grievance", phonetic: "/ˈɡriːvəns/" },
    { word: "guidance", phonetic: "/ˈɡaɪdns/" },
    { word: "habitat", phonetic: "/ˈhæbɪtæt/" },
    { word: "hardship", phonetic: "/ˈhɑːrdʃɪp/" },
    { word: "heritage", phonetic: "/ˈherɪtɪdʒ/" },
    { word: "hesitation", phonetic: "/ˌhezɪˈteɪʃən/" },
    { word: "hierarchy", phonetic: "/ˈhaɪərɑːrki/" },
    { word: "horizon", phonetic: "/həˈraɪzn/" },
    { word: "humanity", phonetic: "/hjuːˈmænəti/" },
    { word: "humidity", phonetic: "/hjuːˈmɪdəti/" },
    { word: "identification", phonetic: "/aɪˌdentɪfɪˈeɪʃən/" },
    { word: "ideology", phonetic: "/ˌaɪdiˈɑːlədʒi/" },
    { word: "illustration", phonetic: "/ˌɪləˈstreɪʃən/" },
    { word: "imagination", phonetic: "/ɪˌmædʒɪˈneɪʃən/" },
    { word: "implementation", phonetic: "/ˌɪmplɪmenˈteɪʃən/" },
    { word: "implication", phonetic: "/ˌɪmplɪˈkeɪʃən/" },
    { word: "importance", phonetic: "/ɪmˈpɔːrtns/" },
    { word: "impression", phonetic: "/ɪmˈpreʃn/" },
    { word: "improvement", phonetic: "/ɪmˈpruːvmənt/" },
    { word: "incentive", phonetic: "/ɪnˈsentɪv/" },
    { word: "inclusion", phonetic: "/ɪnˈkluːʒn/" },
    { word: "indication", phonetic: "/ˌɪndɪˈkeɪʃən/" },
    { word: "indicator", phonetic: "/ˈɪndɪkeɪtər/" },
    { word: "indifference", phonetic: "/ɪnˈdɪfrəns/" },
    { word: "indignation", phonetic: "/ˌɪndɪɡˈneɪʃən/" },
    { word: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/" },
    { word: "industrialization", phonetic: "/ɪnˌdʌstriələˈzeɪʃən/" },
    { word: "industry", phonetic: "/ˈɪndəstri/" },
    { word: "inequality", phonetic: "/ˌɪnɪˈkwɑːləti/" },
    { word: "inference", phonetic: "/ˈɪnfərəns/" },
    { word: "inflation", phonetic: "/ɪnˈfleɪʃn/" },
    { word: "influence", phonetic: "/ˈɪnfluəns/" },
    { word: "infrastructure", phonetic: "/ˈɪnfrəˌstrʌktʃər/" },
    { word: "inheritance", phonetic: "/ɪnˈherɪtəns/" },
    { word: "initiation", phonetic: "/ɪˌnɪʃiˈeɪʃən/" },
    { word: "initiative", phonetic: "/ɪˈnɪʃətɪv/" },
    { word: "innovation", phonetic: "/ˌɪnəˈveɪʃən/" },
    { word: "inscription", phonetic: "/ɪnˈskrɪpʃn/" },
    { word: "insomnia", phonetic: "/ɪnˈsɑːmniə/" },
    { word: "inspection", phonetic: "/ɪnˈspekʃn/" },
    { word: "inspiration", phonetic: "/ˌɪnspəˈreɪʃən/" },
    { word: "installation", phonetic: "/ˌɪnstəˈleɪʃən/" },
    { word: "institution", phonetic: "/ˌɪnstɪˈtuːʃən/" },
    { word: "instruction", phonetic: "/ɪnˈstrʌkʃn/" },
    { word: "instrument", phonetic: "/ˈɪnstrəmənt/" },
    { word: "insulation", phonetic: "/ˌɪnsəˈleɪʃən/" },
    { word: "integration", phonetic: "/ˌɪntɪˈɡreɪʃən/" },
    { word: "integrity", phonetic: "/ɪnˈteɡrəti/" },
    { word: "intellect", phonetic: "/ˈɪntəlekt/" },
    { word: "intelligence", phonetic: "/ɪnˈtelɪdʒəns/" },
    { word: "intensity", phonetic: "/ɪnˈtensəti/" },
    { word: "interaction", phonetic: "/ˌɪntərˈækʃən/" },
    { word: "interchange", phonetic: "/ˈɪntərtʃeɪndʒ/" },
    { word: "interference", phonetic: "/ˌɪntərˈfɪrəns/" },
    { word: "interpretation", phonetic: "/ɪnˌtɜːrprəˈteɪʃən/" },
    { word: "intervention", phonetic: "/ˌɪntərˈvenʃən/" },
    { word: "interview", phonetic: "/ˈɪntərvjuː/" },
    { word: "introduction", phonetic: "/ˌɪntrəˈdʌkʃn/" },
    { word: "intuition", phonetic: "/ˌɪntuˈɪʃən/" },
    { word: "invention", phonetic: "/ɪnˈvenʃn/" },
    { word: "investigation", phonetic: "/ɪnˌvestɪˈɡeɪʃən/" },
    { word: "investment", phonetic: "/ɪnˈvestmənt/" },
    { word: "invitation", phonetic: "/ˌɪnvɪˈteɪʃən/" },
    { word: "irrigation", phonetic: "/ˌɪrɪˈɡeɪʃən/" },
    { word: "isolation", phonetic: "/ˌaɪsəˈleɪʃən/" },
    { word: "journalism", phonetic: "/ˈdʒɜːrnəlɪzəm/" },
    { word: "judgement", phonetic: "/ˈdʒʌdʒmənt/" },
    { word: "junction", phonetic: "/ˈdʒʌŋkʃn/" },
    { word: "justification", phonetic: "/ˌdʒʌstɪfɪˈkeɪʃən/" },
    { word: "knowledge", phonetic: "/ˈnɑːlɪdʒ/" },
    { word: "landscape", phonetic: "/ˈlændskeɪp/" },
    { word: "latitude", phonetic: "/ˈlætɪtuːd/" },
    { word: "leadership", phonetic: "/ˈliːdərʃɪp/" },
    { word: "legislation", phonetic: "/ˌledʒɪsˈleɪʃən/" },
    { word: "legitimate", phonetic: "/ləˈdʒɪtɪmət/" },
    { word: "leisure", phonetic: "/ˈliːʒər/" },
    { word: "liability", phonetic: "/ˌlaɪəˈbɪləti/" },
    { word: "liberation", phonetic: "/ˌlɪbəˈreɪʃən/" },
    { word: "liberty", phonetic: "/ˈlɪbərti/" },
    { word: "limitation", phonetic: "/ˌlɪmɪˈteɪʃən/" },
    { word: "literature", phonetic: "/ˈlɪtrətʃər/" },
    { word: "locality", phonetic: "/loʊˈkæləti/" },
    { word: "location", phonetic: "/loʊˈkeɪʃn/" },
    { word: "longevity", phonetic: "/lɑːnˈdʒevəti/" },
    { word: "longitude", phonetic: "/ˈlɑːndʒɪtuːd/" },
    { word: "loyalty", phonetic: "/ˈlɔɪəlti/" },
    { word: "magnitude", phonetic: "/ˈmæɡnɪtuːd/" },
    { word: "maintenance", phonetic: "/ˈmeɪntənəns/" },
    { word: "malfunction", phonetic: "/ˌmælˈfʌŋkʃn/" },
    { word: "management", phonetic: "/ˈmænɪdʒmənt/" },
    { word: "manifestation", phonetic: "/ˌmænɪfeˈsteɪʃən/" },
    { word: "manipulation", phonetic: "/məˌnɪpjuˈleɪʃən/" },
    { word: "manuscript", phonetic: "/ˈmænjuskrɪpt/" },
    { word: "measurement", phonetic: "/ˈmeʒərmənt/" },
    { word: "mechanism", phonetic: "/ˈmekənɪzəm/" },
    { word: "mediation", phonetic: "/ˌmiːdiˈeɪʃən/" },
    { word: "medication", phonetic: "/ˌmedɪˈkeɪʃən/" },
    { word: "medicine", phonetic: "/ˈmedsn/" },
    { word: "mentality", phonetic: "/menˈtæləti/" },
    { word: "mentorship", phonetic: "/ˈmentɔːrʃɪp/" },
    { word: "metabolism", phonetic: "/məˈtæbəlɪzəm/" },
    { word: "metaphor", phonetic: "/ˈmetəfɔːr/" },
    { word: "methodology", phonetic: "/ˌmeθəˈdɑːlədʒi/" },
    { word: "migration", phonetic: "/maɪˈɡreɪʃn/" },
    { word: "minimization", phonetic: "/ˌmɪnɪməˈzeɪʃən/" },
    { word: "ministry", phonetic: "/ˈmɪnɪstri/" },
    { word: "minority", phonetic: "/maɪˈnɔːrəti/" },
    { word: "mitigation", phonetic: "/ˌmɪtɪˈɡeɪʃən/" },
    { word: "mobility", phonetic: "/moʊˈbɪləti/" },
    { word: "modernization", phonetic: "/ˌmɑːdərnəˈzeɪʃən/" },
    { word: "modification", phonetic: "/ˌmɑːdɪfɪˈkeɪʃən/" },
    { word: "momentum", phonetic: "/moʊˈmentəm/" },
    { word: "monarchy", phonetic: "/ˈmɑːnərki/" },
    { word: "monitoring", phonetic: "/ˈmɑːnɪtərɪŋ/" },
    { word: "monopoly", phonetic: "/məˈnɑːpəli/" },
    { word: "monument", phonetic: "/ˈmɑːnjumənt/" },
    { word: "morality", phonetic: "/məˈræləti/" },
    { word: "mortality", phonetic: "/mɔːrˈtæləti/" },
    { word: "motivation", phonetic: "/ˌmoʊtɪˈveɪʃən/" },
    { word: "movement", phonetic: "/ˈmuːvmənt/" },
    { word: "multiplication", phonetic: "/ˌmʌltɪplɪˈkeɪʃən/" },
    { word: "narration", phonetic: "/næˈreɪʃn/" },
    { word: "nationality", phonetic: "/ˌnæʃəˈnæləti/" },
    { word: "navigation", phonetic: "/ˌnævɪˈɡeɪʃən/" },
    { word: "necessity", phonetic: "/nəˈsesəti/" },
    { word: "negligence", phonetic: "/ˈneɡlɪdʒəns/" },
    { word: "negotiation", phonetic: "/nɪˌɡoʊʃiˈeɪʃən/" },
    { word: "neutrality", phonetic: "/nuːˈtræləti/" },
    { word: "nomination", phonetic: "/ˌnɑːmɪˈneɪʃən/" },
    { word: "notation", phonetic: "/noʊˈteɪʃn/" },
    { word: "notion", phonetic: "/ˈnoʊʃn/" },
    { word: "nourishment", phonetic: "/ˈnɜːrɪʃmənt/" },
    { word: "novelty", phonetic: "/ˈnɑːvlti/" },
    { word: "nutrition", phonetic: "/nuˈtrɪʃn/" },
    { word: "objection", phonetic: "/əbˈdʒekʃn/" },
    { word: "objective", phonetic: "/əbˈdʒektɪv/" },
    { word: "obligation", phonetic: "/ˌɑːblɪˈɡeɪʃən/" },
    { word: "observation", phonetic: "/ˌɑːbzərˈveɪʃən/" },
    { word: "obstacle", phonetic: "/ˈɑːbstəkl/" },
    { word: "occurrence", phonetic: "/əˈkɜːrəns/" },
    { word: "operation", phonetic: "/ˌɑːpəˈreɪʃn/" },
    { word: "opposition", phonetic: "/ˌɑːpəˈzɪʃn/" },
    { word: "optimization", phonetic: "/ˌɑːptɪməˈzeɪʃən/" },
    { word: "option", phonetic: "/ˈɑːpʃn/" },
    { word: "orchestration", phonetic: "/ˌɔːrkɪˈstreɪʃən/" },
    { word: "orientation", phonetic: "/ˌɔːriənˈteɪʃən/" },
    { word: "originality", phonetic: "/əˌrɪdʒəˈnæləti/" },
    { word: "ornament", phonetic: "/ˈɔːrnəmənt/" },
    { word: "oscillation", phonetic: "/ˌɑːsɪˈleɪʃən/" },
    { word: "ownership", phonetic: "/ˈoʊnərʃɪp/" },
    { word: "paradigm", phonetic: "/ˈpærədaɪm/" },
    { word: "parameter", phonetic: "/pəˈræmɪtər/" },
    { word: "participation", phonetic: "/pɑːrˌtɪsɪˈpeɪʃən/" },
    { word: "perception", phonetic: "/pərˈsepʃn/" }
];

const exclusionListData = JSON.parse(fs.readFileSync(exclusionListPath, 'utf8'));
const exclusionList = exclusionListData.exclusionList || exclusionListData;
const usedWordsGlobal = new Set([...exclusionList]);

function fixUsage(usage, word) {
    let rawWords = usage.trim().split(/\s+/);
    if (rawWords.length < 15) {
        // Extend politely
        const fillers = ["furthermore", "essential", "demonstrates", "particular", "concept"];
        let i = 0;
        while (rawWords.length < 15) {
            rawWords.push(fillers[i % fillers.length]);
            i++;
        }
    } else if (rawWords.length > 20) {
        rawWords = rawWords.slice(0, 20);
    }

    let result = rawWords.join(' ');
    if (!result.endsWith('.') && !result.endsWith('!') && !result.endsWith('?')) {
        result += '.';
    }
    return result;
}

// First pass: identify all B1 words to find internal duplicates
const allB1Words = [];
for (let i = 1; i <= 10; i++) {
    const moduleNum = i.toString().padStart(2, '0');
    const filePath = path.join(firestoreDataDir, `en_b1_m${moduleNum}.json`);
    const moduleData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    moduleData.vocabularyItems.forEach(item => {
        allB1Words.push({ word: item.word.toLowerCase(), module: moduleNum });
    });
}

const b1WordCounts = new Map();
allB1Words.forEach(entry => {
    b1WordCounts.set(entry.word, (b1WordCounts.get(entry.word) || 0) + 1);
});

// Track which replacements we've used in THIS run
const usedReplacements = new Set();
let replacementIdx = 0;

for (let i = 1; i <= 10; i++) {
    const moduleNum = i.toString().padStart(2, '0');
    const filePath = path.join(firestoreDataDir, `en_b1_m${moduleNum}.json`);
    const moduleData = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    let changed = false;

    moduleData.vocabularyItems.forEach(item => {
        const lowerWord = item.word.toLowerCase();
        const isOverlap = usedWordsGlobal.has(lowerWord);
        const isDuplicate = b1WordCounts.get(lowerWord) > 1;

        // If we've already marked this word as "processed" in this module (shouldn't happen with forEach but safe)
        if (isOverlap || isDuplicate) {
            // Replace word
            let found = false;
            while (replacementIdx < replacementBank.length) {
                const candidate = replacementBank[replacementIdx++];
                if (!usedWordsGlobal.has(candidate.word) && !b1WordCounts.has(candidate.word) && !usedReplacements.has(candidate.word)) {
                    item.word = candidate.word;
                    item.phonetic = candidate.phonetic;
                    item.usage = `The study of ${candidate.word} is a fundamental part of the ${moduleData.theme} curriculum that helps students understand complex principles more thoroughly.`;
                    usedReplacements.add(candidate.word);
                    // Decrement count for the old word so subsequent modules might not flag it if it's no longer a duplicate
                    b1WordCounts.set(lowerWord, b1WordCounts.get(lowerWord) - 1);
                    found = true;
                    changed = true;
                    break;
                }
            }
            if (!found) console.error("RAN OUT OF REPLACEMENT WORDS!");
        }

        const initialUsage = item.usage;
        item.usage = fixUsage(item.usage, item.word);
        if (initialUsage !== item.usage) changed = true;
    });

    if (changed) {
        fs.writeFileSync(filePath, JSON.stringify(moduleData, null, 2));
        console.log(`Fixed ${filePath}`);
    }
}

console.log("Cleanup complete.");
