const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100)
    };
}

// --- MODULE 15: Media & Technology (A2) ---
const m15_items = [
    { word: "Technologie", meaning: "Technology", reading: "tek-noh-loh-zhee", example_sentence: "La technologie évolue vite." },
    { word: "Numérique", meaning: "Digital", reading: "noo-may-reek", example_sentence: "L'ère du numérique." },
    { word: "Ordinateur", meaning: "Computer", reading: "or-dee-na-tur", example_sentence: "Allumer son ordinateur." },
    { word: "Portable", meaning: "Laptop / Cell phone", reading: "por-ta-bluh", example_sentence: "Mon portable est déchargé." },
    { word: "Tablette", meaning: "Tablet", reading: "ta-blet", example_sentence: "Lire sur une tablette." },
    { word: "Écran", meaning: "Screen", reading: "ay-krah", example_sentence: "Un écran tactile." },
    { word: "Clavier", meaning: "Keyboard", reading: "kla-vyay", example_sentence: "Taper sur le clavier." },
    { word: "Souris", meaning: "Mouse", reading: "soo-ree", example_sentence: "Cliquer avec la souris." },
    { word: "Imprimante", meaning: "Printer", reading: "am-pree-mahnt", example_sentence: "L'imprimante n'a plus de papier." },
    { word: "Scanner", meaning: "Scanner / To scan", reading: "ska-nay", example_sentence: "Scanner un document." },
    { word: "Logiciel", meaning: "Software", reading: "loh-zhee-syel", example_sentence: "Installer un nouveau logiciel." },
    { word: "Application", meaning: "Application (App)", reading: "a-plee-ka-syohn", example_sentence: "Télécharger une application." },
    { word: "Internet", meaning: "Internet", reading: "an-ter-net", example_sentence: "Naviguer sur Internet." },
    { word: "Réseau", meaning: "Network", reading: "ray-zoh", example_sentence: "Le réseau est lent." },
    { word: "Connexion", meaning: "Connection", reading: "koh-nek-syohn", example_sentence: "Perdre la connexion Wi-Fi." },
    { word: "Mot de passe", meaning: "Password", reading: "moh duh pahs", example_sentence: "Changer son mot de passe." },
    { word: "Compte", meaning: "Account", reading: "kohnt", example_sentence: "Créer un compte utilisateur." },
    { word: "Profil", meaning: "Profile", reading: "proh-feel", example_sentence: "Mettre à jour son profil." },
    { word: "Lien", meaning: "Link", reading: "lyah", example_sentence: "Cliquer sur le lien." },
    { word: "Site web", meaning: "Website", reading: "seet web", example_sentence: "Un site web interactif." },
    { word: "Blog", meaning: "Blog", reading: "blog", example_sentence: "Tenir un blog de cuisine." },
    { word: "Forum", meaning: "Forum", reading: "foh-room", example_sentence: "Participer à un forum." },
    { word: "Réseaux sociaux", meaning: "Social media", reading: "ray-zoh soh-syoh", example_sentence: "Passer du temps sur les réseaux sociaux." },
    { word: "Message", meaning: "Message", reading: "meh-sazh", example_sentence: "Envoyer un message privé." },
    { word: "Courriel", meaning: "Email", reading: "koo-ryel", example_sentence: "Répondre à un courriel." },
    { word: "Pièce jointe", meaning: "Attachment", reading: "pyes zhwant", example_sentence: "Ouvrir la pièce jointe." },
    { word: "Télécharger", meaning: "To download", reading: "tay-lay-shar-zhay", example_sentence: "Télécharger un film." },
    { word: "Partager", meaning: "To share", reading: "par-ta-zhay", example_sentence: "Partager une photo." },
    { word: "Commentaire", meaning: "Comment", reading: "koh-mahn-ter", example_sentence: "Laisser un commentaire." },
    { word: "Aimer", meaning: "To like", reading: "ay-may", example_sentence: "Aimer une publication." },
    { word: "Suivre", meaning: "To follow", reading: "swee-vruh", example_sentence: "Suivre quelqu'un sur Twitter." },
    { word: "S'abonner", meaning: "To subscribe", reading: "sa-boh-nay", example_sentence: "S'abonner à une chaîne." },
    { word: "Publicité", meaning: "Advertisement", reading: "poo-blee-see-tay", example_sentence: "Trop de publicités à la télé." },
    { word: "Information", meaning: "Information / News", reading: "an-for-ma-syohn", example_sentence: "Vérifier l'information." },
    { word: "Média", meaning: "Media", reading: "may-dyah", example_sentence: "Le rôle des médias." },
    { word: "Journal", meaning: "Newspaper", reading: "zhoor-nal", example_sentence: "Lire le journal du matin." },
    { word: "Magazine", meaning: "Magazine", reading: "ma-ga-zeen", example_sentence: "Un magazine de mode." },
    { word: "Presse", meaning: "Press", reading: "pres", example_sentence: "La liberté de la presse." },
    { word: "Article", meaning: "Article", reading: "ar-tee-kluh", example_sentence: "Un article intéressant." },
    { word: "Interview", meaning: "Interview", reading: "an-ter-vyooh", example_sentence: "Une interview exclusive." },
    { word: "Reportage", meaning: "Report / Documentary", reading: "ruh-por-tazh", example_sentence: "Regarder un reportage." },
    { word: "Documentaire", meaning: "Documentary", reading: "doh-koo-mahn-ter", example_sentence: "Un documentaire sur la nature." },
    { word: "Émission", meaning: "Program / Show", reading: "ay-mee-syohn", example_sentence: "Une émission de radio." },
    { word: "Série", meaning: "Series", reading: "say-ree", example_sentence: "Ma série préférée." },
    { word: "Canal", meaning: "Channel", reading: "ka-nal", example_sentence: "Changer de canal." },
    { word: "Chaîne", meaning: "Channel", reading: "shen", example_sentence: "Une chaîne d'information." },
    { word: "Télécommande", meaning: "Remote control", reading: "tay-lay-koh-mahnd", example_sentence: "Chercher la télécommande." },
    { word: "Volume", meaning: "Volume", reading: "voh-loom", example_sentence: "Baisser le volume." },
    { word: "Son", meaning: "Sound", reading: "soh", example_sentence: "Le son est mauvais." },
    { word: "Image", meaning: "Image", reading: "ee-mazh", example_sentence: "Une image nette." },
    { word: "Appareil photo", meaning: "Camera", reading: "a-pa-ray foh-toh", example_sentence: "Prendre une photo." },
    { word: "Vidéo", meaning: "Video", reading: "vee-day-oh", example_sentence: "Filmer une vidéo." },
    { word: "Caméra", meaning: "Camera (video)", reading: "ka-may-ra", example_sentence: "Une caméra de surveillance." },
    { word: "Micro", meaning: "Microphone", reading: "mee-kroh", example_sentence: "Parler dans le micro." },
    { word: "Casque", meaning: "Headphones / Helmet", reading: "kahsk", example_sentence: "Écouter avec un casque." },
    { word: "Enceinte", meaning: "Speaker / Pregnant", reading: "ahn-sant", example_sentence: "Une enceinte Bluetooth." },
    { word: "Bluetooth", meaning: "Bluetooth", reading: "bloo-tooz", example_sentence: "Connecter en Bluetooth." },
    { word: "Wi-Fi", meaning: "Wi-Fi", reading: "wee-fee", example_sentence: "Le code du Wi-Fi." },
    { word: "Charger", meaning: "To charge / To load", reading: "shar-zhay", example_sentence: "Charger la batterie." },
    { word: "Batterie", meaning: "Battery", reading: "ba-tree", example_sentence: "Ma batterie est faible." },
    { word: "Prise", meaning: "Socket", reading: "preez", example_sentence: "Une prise de courant." },
    { word: "Allumer", meaning: "To turn on", reading: "a-loo-may", example_sentence: "Allumer la lumière." },
    { word: "Éteindre", meaning: "To turn off", reading: "ay-tandruh", example_sentence: "Éteindre la télé." },
    { word: "Cliquer", meaning: "To click", reading: "klee-kay", example_sentence: "Cliquer sur valider." },
    { word: "Taper", meaning: "To type / To hit", reading: "ta-pay", example_sentence: "Taper un texte." },
    { word: "Sauvegarder", meaning: "To save", reading: "sohv-gar-day", example_sentence: "Sauvegarder son travail." },
    { word: "Supprimer", meaning: "To delete", reading: "soo-pree-may", example_sentence: "Supprimer un fichier." },
    { word: "Effacer", meaning: "To erase", reading: "ay-fa-say", example_sentence: "Effacer l'historique." },
    { word: "Copier", meaning: "To copy", reading: "koh-pyay", example_sentence: "Copier le texte." },
    { word: "Coller", meaning: "To paste", reading: "koh-lay", example_sentence: "Coller le lien." },
    { word: "Imprimer", meaning: "To print", reading: "am-pree-may", example_sentence: "Imprimer un document." },
    { word: "Ouvrir", meaning: "To open", reading: "oo-vreer", example_sentence: "Ouvrir une fenêtre." },
    { word: "Fermer", meaning: "To close", reading: "fer-may", example_sentence: "Fermer l'onglet." },
    { word: "Onglet", meaning: "Tab", reading: "ohn-glay", example_sentence: "Ouvrir un nouvel onglet." },
    { word: "Fichier", meaning: "File", reading: "fee-shyay", example_sentence: "Un fichier PDF." },
    { word: "Dossier", meaning: "Folder / File", reading: "doh-syay", example_sentence: "Ranger dans le dossier." },
    { word: "Mémoire", meaning: "Memory", reading: "may-mwahr", example_sentence: "Plus de mémoire disponible." },
    { word: "Stockage", meaning: "Storage", reading: "stoh-kazh", example_sentence: "Espace de stockage plein." },
    { word: "Cloud", meaning: "Cloud", reading: "klood", example_sentence: "Sauvegarder sur le cloud." },
    { word: "Données", meaning: "Data", reading: "doh-nay", example_sentence: "Protéger ses données." },
    { word: "Sécurité", meaning: "Security", reading: "say-koo-ree-tay", example_sentence: "La sécurité informatique." },
    { word: "Virus", meaning: "Virus", reading: "vee-roos", example_sentence: "Un virus informatique." },
    { word: "Arnaque", meaning: "Scam", reading: "ar-nak", example_sentence: "Attention à l'arnaque." },
    { word: "Faux", meaning: "False / Fake", reading: "foh", example_sentence: "Une fausse information." },
    { word: "Vrai", meaning: "True", reading: "vray", example_sentence: "C'est une info vraie." },
    { word: "Source", meaning: "Source", reading: "soors", example_sentence: "Citer ses sources." },
    { word: "Opinion", meaning: "Opinion", reading: "oh-pee-nyohn", example_sentence: "Donner son opinion." },
    { word: "Débat", meaning: "Debate", reading: "day-ba", example_sentence: "Un débat télévisé." },
    { word: "Public", meaning: "Public", reading: "poo-bleek", example_sentence: "Le grand public." },
    { word: "Privé", meaning: "Private", reading: "pree-vay", example_sentence: "Un message privé." },
    { word: "Communication", meaning: "Communication", reading: "koh-moo-nee-ka-syohn", example_sentence: "La communication est essentielle." },
    { word: "Invention", meaning: "Invention", reading: "an-vahn-syohn", example_sentence: "Une invention révolutionnaire." },
    { word: "Progrès", meaning: "Progress", reading: "proh-gray", example_sentence: "Le progrès technique." },
    { word: "Futur", meaning: "Future", reading: "foo-toor", example_sentence: "Penser au futur." },
    { word: "Moderne", meaning: "Modern", reading: "moh-dern", example_sentence: "Un monde moderne." },
    { word: "Ancien", meaning: "Ancient / Former", reading: "ahn-syah", example_sentence: "Un ancien modèle." },
    { word: "Rapide", meaning: "Fast", reading: "ra-peed", example_sentence: "Une connexion rapide." },
    { word: "Lent", meaning: "Slow", reading: "lah", example_sentence: "Un ordinateur très lent." },
    { word: "Pratique", meaning: "Practical / Convenient", reading: "pra-teek", example_sentence: "C'est très pratique." },
    { word: "Utile", meaning: "Useful", reading: "oo-teel", example_sentence: "Un outil utile." }
];

// --- MODULE 16: Environment & Geography (A2) ---
const m16_items = [
    { word: "Environnement", meaning: "Environment", reading: "ah-vee-rohn-mahn", example_sentence: "Protéger l'environnement." },
    { word: "Nature", meaning: "Nature", reading: "na-toor", example_sentence: "Se promener dans la nature." },
    { word: "Planète", meaning: "Planet", reading: "pla-net", example_sentence: "Sauver la planète." },
    { word: "Terre", meaning: "Earth / Soil", reading: "ter", example_sentence: "La Terre est ronde." },
    { word: "Monde", meaning: "World", reading: "mohnd", example_sentence: "Voyager à travers le monde." },
    { word: "Climat", meaning: "Climate", reading: "klee-ma", example_sentence: "Le changement climatique." },
    { word: "Météo", meaning: "Weather", reading: "may-tay-oh", example_sentence: "Regarder la météo." },
    { word: "Saison", meaning: "Season", reading: "say-zoh", example_sentence: "Ma saison préférée est l'automne." },
    { word: "Pollution", meaning: "Pollution", reading: "poh-loo-syohn", example_sentence: "La pollution de l'air." },
    { word: "Déchets", meaning: "Waste / Rubbish", reading: "day-shay", example_sentence: "Réduire ses déchets." },
    { word: "Recyclage", meaning: "Recycling", reading: "ruh-see-klazh", example_sentence: "Le recyclage des plastiques." },
    { word: "Énergie", meaning: "Energy", reading: "ay-ner-zhee", example_sentence: "Économiser l'énergie." },
    { word: "Écologie", meaning: "Ecology", reading: "ay-koh-loh-zhee", example_sentence: "Un geste pour l'écologie." },
    { word: "Durable", meaning: "Sustainable", reading: "doo-ra-bluh", example_sentence: "Le développement durable." },
    { word: "Propre", meaning: "Clean / Own", reading: "proh-pruh", example_sentence: "Une ville propre." },
    { word: "Sale", meaning: "Dirty", reading: "sal", example_sentence: "La mer est sale." },
    { word: "Danger", meaning: "Danger", reading: "dahn-zhay", example_sentence: "Un danger pour l'homme." },
    { word: "Risque", meaning: "Risk", reading: "reesk", example_sentence: "Un risque élevé." },
    { word: "Protection", meaning: "Protection", reading: "proh-tek-syohn", example_sentence: "La protection des animaux." },
    { word: "Préservation", meaning: "Preservation", reading: "pray-zer-va-syohn", example_sentence: "La préservation des forêts." },
    { word: "Continent", meaning: "Continent", reading: "kohn-tee-nah", example_sentence: "Le continent africain." },
    { word: "Océan", meaning: "Ocean", reading: "oh-say-ah", example_sentence: "L'océan Atlantique." },
    { word: "Mer", meaning: "Sea", reading: "mer", example_sentence: "Aller au bord de la mer." },
    { word: "Fleuve", meaning: "River (flows into sea)", reading: "fluhv", example_sentence: "La Seine est un fleuve." },
    { word: "Rivière", meaning: "River", reading: "ree-vyer", example_sentence: "Une petite rivière." },
    { word: "Lac", meaning: "Lake", reading: "lak", example_sentence: "Le lac d'Annecy." },
    { word: "Cascade", meaning: "Waterfall", reading: "kas-kad", example_sentence: "Une cascade magnifique." },
    { word: "Île", meaning: "Island", reading: "eel", example_sentence: "Vivre sur une île." },
    { word: "Plage", meaning: "Beach", reading: "plazh", example_sentence: "Une plage de sable fin." },
    { word: "Côte", meaning: "Coast", reading: "koht", example_sentence: "Habiter sur la côte." },
    { word: "Montagne", meaning: "Mountain", reading: "mohn-ta-nyuh", example_sentence: "Grander une montagne." },
    { word: "Colline", meaning: "Hill", reading: "koh-leen", example_sentence: "Une petite colline." },
    { word: "Vallée", meaning: "Valley", reading: "va-lay", example_sentence: "Une vallée profonde." },
    { word: "Plaine", meaning: "Plain", reading: "plen", example_sentence: "Une vaste plaine." },
    { word: "Forêt", meaning: "Forest", reading: "foh-ray", example_sentence: "La forêt tropicale." },
    { word: "Bois", meaning: "Wood (forest)", reading: "bwa", example_sentence: "Se promener dans les bois." },
    { word: "Désert", meaning: "Desert", reading: "day-zer", example_sentence: "Traverser le désert." },
    { word: "Végétation", meaning: "Vegetation", reading: "vay-zhay-ta-syohn", example_sentence: "Une végétation abondante." },
    { word: "Arbre", meaning: "Tree", reading: "ar-bruh", example_sentence: "Un arbre centenaire." },
    { word: "Fleur", meaning: "Flower", reading: "flur", example_sentence: "Une jolie fleur." },
    { word: "Plante", meaning: "Plant", reading: "plahnt", example_sentence: "Arroser ses plantes." },
    { word: "Feuille", meaning: "Leaf / Sheet", reading: "fuh-yuh", example_sentence: "Une feuille d'automne." },
    { word: "Herbe", meaning: "Grass", reading: "erb", example_sentence: "L'herbe est verte." },
    { word: "Pays", meaning: "Country", reading: "pay-ee", example_sentence: "Habiter son pays." },
    { word: "Région", meaning: "Region", reading: "ray-zhyohn", example_sentence: "Une région touristique." },
    { word: "Ville", meaning: "City", reading: "veel", example_sentence: "Une grande ville." },
    { word: "Village", meaning: "Village", reading: "vee-lazh", example_sentence: "Un petit village." },
    { word: "Capitale", meaning: "Capital city", reading: "ka-pee-tal", example_sentence: "Paris est la capitale." },
    { word: "Frontière", meaning: "Border", reading: "frohn-tyer", example_sentence: "Traverser la frontière." },
    { word: "Nord", meaning: "North", reading: "nor", example_sentence: "Aller vers le nord." },
    { word: "Sud", meaning: "South", reading: "sood", example_sentence: "Habiter au sud." },
    { word: "Est", meaning: "East", reading: "est", example_sentence: "Le soleil se lève à l'est." },
    { word: "Ouest", meaning: "West", reading: "west", example_sentence: "Le soleil se couche à l'ouest." },
    { word: "Distance", meaning: "Distance", reading: "dees-tahns", example_sentence: "Une longue distance." },
    { word: "Paysage", meaning: "Landscape", reading: "pay-ee-zazh", example_sentence: "Un paysage magnifique." },
    { word: "Horizon", meaning: "Horizon", reading: "oh-ree-zoh", example_sentence: "Regarder l'horizon." },
    { word: "Température", meaning: "Temperature", reading: "tahm-pay-ra-toor", example_sentence: "La température baisse." },
    { word: "Soleil", meaning: "Sun", reading: "soh-lay-yay", example_sentence: "Le soleil brille." },
    { word: "Lune", meaning: "Moon", reading: "loon", example_sentence: "La lune est pleine." },
    { word: "Étoile", meaning: "Star", reading: "ay-twal", example_sentence: "Regarder les étoiles." },
    { word: "Ciel", meaning: "Sky", reading: "syel", example_sentence: "Le ciel est bleu." },
    { word: "Nuage", meaning: "Cloud", reading: "noo-azh", example_sentence: "Il y a des nuages." },
    { word: "Pluie", meaning: "Rain", reading: "plwee", example_sentence: "Il y a beaucoup de pluie." },
    { word: "Neige", meaning: "Snow", reading: "nezh", example_sentence: "La neige tombe." },
    { word: "Vent", meaning: "Wind", reading: "vahn", example_sentence: "Le vent souffle fort." },
    { word: "Orage", meaning: "Thunderstorm", reading: "oh-razh", example_sentence: "Il y a de l'orage." },
    { word: "Tempête", meaning: "Storm", reading: "tahm-pet", example_sentence: "Une grosse tempête." },
    { word: "Brouillard", meaning: "Fog", reading: "broo-yar", example_sentence: "Il y a du brouillard." },
    { word: "Humidité", meaning: "Humidity", reading: "oo-mee-dee-tay", example_sentence: "Le taux d'humidité." },
    { word: "Chaleur", meaning: "Heat", reading: "sha-lur", example_sentence: "Une forte chaleur." },
    { word: "Froid", meaning: "Cold", reading: "frwa", example_sentence: "J'ai froid." },
    { word: "Glace", meaning: "Ice / Ice cream", reading: "glas", example_sentence: "Le lac est en glace." },
    { word: "Pierre", meaning: "Stone / Rock", reading: "pyer", example_sentence: "Une pierre précieuse." },
    { word: "Rocher", meaning: "Rock", reading: "roh-shay", example_sentence: "Grimper le rocher." },
    { word: "Sable", meaning: "Sand", reading: "sa-bluh", example_sentence: "Jouer dans le sable." },
    { word: "Poussière", meaning: "Dust", reading: "poo-syair", example_sentence: "La poussière s'accumule." },
    { word: "Sommet", meaning: "Summit / Peak", reading: "soh-may", example_sentence: "Le sommet de la montagne." },
    { word: "Campagne", meaning: "Countryside", reading: "kahm-pa-nyuh", example_sentence: "Vivre à la campagne." },
    { word: "Champ", meaning: "Field", reading: "shah", example_sentence: "Un champ de blé." },
    { word: "Ferme", meaning: "Farm", reading: "ferm", example_sentence: "Habiter dans une ferme." },
    { word: "Agriculture", meaning: "Agriculture", reading: "a-gree-kool-toor", example_sentence: "L'agriculture biologique." },
    { word: "Polluer", meaning: "To pollute", reading: "poh-loo-ay", example_sentence: "Ne pas polluer." },
    { word: "Protéger", meaning: "To protect", reading: "proh-tay-zhay", example_sentence: "Protéger la nature." },
    { word: "Sauver", meaning: "To save", reading: "soh-vay", example_sentence: "Sauver les océans." },
    { word: "Réduire", meaning: "To reduce", reading: "ray-dweer", example_sentence: "Réduire sa consommation." },
    { word: "Réutiliser", meaning: "To reuse", reading: "ray-oo-tee-lee-zay", example_sentence: "Réutiliser les bocaux." },
    { word: "Jeter", meaning: "To throw away", reading: "zhuh-tay", example_sentence: "Ne pas jeter par terre." },
    { word: "Ramasser", meaning: "To pick up", reading: "ra-ma-say", example_sentence: "Ramasser ses déchets." },
    { word: "Trier", meaning: "To sort", reading: "tree-ay", example_sentence: "Trier les poubelles." },
    { word: "Agir", meaning: "To act", reading: "a-zheer", example_sentence: "Agir pour le climat." },
    { word: "Penser", meaning: "To think", reading: "pahn-say", example_sentence: "Penser à l'avenir." },
    { word: "Futur", meaning: "Future", reading: "foo-toor", example_sentence: "Le futur de notre monde." },
    { word: "Espoir", meaning: "Hope", reading: "es-pwahr", example_sentence: "Garder l'espoir." },
    { word: "Espèce", meaning: "Species / Cash", reading: "es-pes", example_sentence: "Une espèce en danger." },
    { word: "Animal", meaning: "Animal", reading: "a-nee-mal", example_sentence: "Un animal sauvage." },
    { word: "Oiseau", meaning: "Bird", reading: "wa-zoh", example_sentence: "Un oiseau chante." },
    { word: "Poisson", meaning: "Fish", reading: "pwa-soh", example_sentence: "Un poisson nage." },
    { word: "Habitat", meaning: "Habitat", reading: "a-bee-ta", example_sentence: "Son habitat naturel." },
    { word: "Écosystème", meaning: "Ecosystem", reading: "ay-koh-sees-tem", example_sentence: "Un écosystème fragile." },
    { word: "Ressource", meaning: "Resource", reading: "ruh-soors", example_sentence: "Les ressources naturelles." }
];

// --- MODULE 17: Opinions & Emotions (A2) ---
const m17_items = [
    { word: "Opinion", meaning: "Opinion", reading: "oh-pee-nyohn", example_sentence: "Donner son opinion." },
    { word: "Avis", meaning: "Opinion / Advice", reading: "a-vee", example_sentence: "À mon avis." },
    { word: "Penser", meaning: "To think", reading: "pahn-say", example_sentence: "Qu'est-ce que tu penses ?" },
    { word: "Croire", meaning: "To believe", reading: "krwahr", example_sentence: "Je le crois." },
    { word: "D'accord", meaning: "Agreed", reading: "da-kor", example_sentence: "Je suis d'accord." },
    { word: "Pas d'accord", meaning: "Not agreed", reading: "pa da-kor", example_sentence: "Je ne suis pas d'accord." },
    { word: "Vrai", meaning: "True", reading: "vray", example_sentence: "C'est vrai." },
    { word: "Faux", meaning: "False", reading: "foh", example_sentence: "C'est faux." },
    { word: "Juste", meaning: "Just / Right", reading: "zhoost", example_sentence: "C'est juste." },
    { word: "Injuste", meaning: "Unjust / Unfair", reading: "an-zhoost", example_sentence: "C'est injuste." },
    { word: "Possible", meaning: "Possible", reading: "poh-see-bluh", example_sentence: "C'est possible." },
    { word: "Impossible", meaning: "Impossible", reading: "am-poh-see-bluh", example_sentence: "C'est impossible." },
    { word: "Sûr", meaning: "Sure / Safe", reading: "soor", example_sentence: "J'en suis sûr." },
    { word: "Incertain", meaning: "Uncertain", reading: "an-ser-tah", example_sentence: "C'est incertain." },
    { word: "Peut-être", meaning: "Maybe", reading: "puh-tetruh", example_sentence: "Peut-être demain." },
    { word: "Sans doute", meaning: "Without doubt / probably", reading: "sahn doot", example_sentence: "Sans doute." },
    { word: "Probablement", meaning: "Probably", reading: "proh-ba-bluh-mahn", example_sentence: "Probablement oui." },
    { word: "Certes", meaning: "Certainly / Admittedly", reading: "sert", example_sentence: "Certes, mais..." },
    { word: "Bien sûr", meaning: "Of course", reading: "byahn soor", example_sentence: "Bien sûr !" },
    { word: "Évidemment", meaning: "Obviously", reading: "ay-vee-da-mahn", example_sentence: "Évidemment." },
    { word: "Sentiment", meaning: "Feeling", reading: "sahn-tee-mahn", example_sentence: "Un sentiment étrange." },
    { word: "Émotion", meaning: "Emotion", reading: "ay-moh-syohn", example_sentence: "Une forte émotion." },
    { word: "Bonheur", meaning: "Happiness", reading: "boh-noor", example_sentence: "Le vrai bonheur." },
    { word: "Joie", meaning: "Joy", reading: "zhwa", example_sentence: "Une grande joie." },
    { word: "Tristesse", meaning: "Sadness", reading: "trees-tes", example_sentence: "Une profonde tristesse." },
    { word: "Colère", meaning: "Anger", reading: "koh-ler", example_sentence: "Être en colère." },
    { word: "Peur", meaning: "Fear", reading: "pur", example_sentence: "J'ai peur." },
    { word: "Surprise", meaning: "Surprise", reading: "soor-preez", example_sentence: "Quelle surprise !" },
    { word: "Honte", meaning: "Shame", reading: "ohnt", example_sentence: "Avoir honte." },
    { word: "Envie", meaning: "Desire / Envy", reading: "ahn-vee", example_sentence: "Avoir envie de sortir." },
    { word: "Jalousie", meaning: "Jealousy", reading: "zha-loo-zee", example_sentence: "La jalousie est mauvaise." },
    { word: "Amour", meaning: "Love", reading: "a-moor", example_sentence: "L'amour est beau." },
    { word: "Haine", meaning: "Hate", reading: "en", example_sentence: "La haine ne sert à rien." },
    { word: "Amitié", meaning: "Friendship", reading: "a-mee-tyay", example_sentence: "Une amitié solide." },
    { word: "Confiance", meaning: "Trust / Confidence", reading: "kohn-fyahns", example_sentence: "Avoir confiance." },
    { word: "Espoir", meaning: "Hope", reading: "es-pwahr", example_sentence: "Garder l'espoir." },
    { word: "Déception", meaning: "Disappointment", reading: "day-sep-syohn", example_sentence: "Une grosse déception." },
    { word: "Regret", meaning: "Regret", reading: "ruh-gray", example_sentence: "Sans regret." },
    { word: "Curiosité", meaning: "Curiosity", reading: "koo-ryoh-zee-tay", example_sentence: "La curiosité est un défaut." },
    { word: "Ennui", meaning: "Boredom / Trouble", reading: "ahn-nwee", example_sentence: "C'est l'ennui." },
    { word: "Heureux", meaning: "Happy", reading: "uh-ruh", example_sentence: "Je suis heureux." },
    { word: "Malheureux", meaning: "Unhappy", reading: "ma-luh-ruh", example_sentence: "Il est malheureux." },
    { word: "Content", meaning: "Glad / Happy", reading: "kohn-tah", example_sentence: "Content de te voir." },
    { word: "Triste", meaning: "Sad", reading: "treest", example_sentence: "Pourquoi es-tu triste ?" },
    { word: "Fâché", meaning: "Angry", reading: "fa-shay", example_sentence: "Ne sois pas fâché." },
    { word: "Inquiet", meaning: "Worried", reading: "an-kyay", example_sentence: "Je suis inquiet pour toi." },
    { word: "Rassuré", meaning: "Reassured", reading: "ra-soo-ray", example_sentence: "Je suis rassuré." },
    { word: "Étonné", meaning: "Astonished", reading: "ay-toh-nay", example_sentence: "Je suis étonné." },
    { word: "Déçu", meaning: "Disappointed", reading: "day-soo", example_sentence: "Il est déçu." },
    { word: "Surpris", meaning: "Surprised", reading: "soor-pree", example_sentence: "Elle est surprise." },
    { word: "Fatigué", meaning: "Tired", reading: "fa-tee-gay", example_sentence: "Je suis très fatigué." },
    { word: "Épuisé", meaning: "Exhausted", reading: "ay-pwee-zay", example_sentence: "Il est épuisé." },
    { word: "Excité", meaning: "Excited / Aroused", reading: "ek-see-tay", example_sentence: "Elle est excitée par le voyage." },
    { word: "Calme", meaning: "Calm", reading: "kal-muh", example_sentence: "Reste calme." },
    { word: "Énervé", meaning: "Annoyed / Irritated", reading: "ay-ner-vay", example_sentence: "Je suis un peu énervé." },
    { word: "Stressé", meaning: "Stressed", reading: "stres-ay", example_sentence: "Trop stressé au travail." },
    { word: "Détendu", meaning: "Relaxed", reading: "day-tahn-doo", example_sentence: "Je suis détendu." },
    { word: "Sérieux", meaning: "Serious", reading: "say-ryuh", example_sentence: "Un homme sérieux." },
    { word: "Drôle", meaning: "Funny", reading: "droh-luh", example_sentence: "C'est très drôle !" },
    { word: "Sympa", meaning: "Nice / Friendly", reading: "sam-pa", example_sentence: "Elle est très sympa." },
    { word: "Gentil", meaning: "Kind / Nice", reading: "zhahn-tee", example_sentence: "Sois gentil." },
    { word: "Méchant", meaning: "Mean / Bad", reading: "may-shah", example_sentence: "Il est méchant." },
    { word: "Honnête", meaning: "Honest", reading: "oh-net", example_sentence: "Une personne honnête." },
    { word: "Malhonnête", meaning: "Dishonest", reading: "ma-loh-net", example_sentence: "C'est malhonnête." },
    { word: "Généreux", meaning: "Generous", reading: "zhay-nay-ruh", example_sentence: "Il est très généreux." },
    { word: "Avare", meaning: "Greedy / Stingy", reading: "a-var", example_sentence: "Un vieil avare." },
    { word: "Intelligent", meaning: "Intelligent", reading: "an-te-lee-zhah", example_sentence: "Un élève intelligent." },
    { word: "Bête", meaning: "Stupid / Silly", reading: "bet", example_sentence: "Ne sois pas bête." },
    { word: "Courageux", meaning: "Courageous / Brave", reading: "koo-ra-zhuh", example_sentence: "Un soldat courageux." },
    { word: "Lâche", meaning: "Cowardly", reading: "lahsh", example_sentence: "C'est un lâche." },
    { word: "Timide", meaning: "Shy", reading: "tee-meed", example_sentence: "Il est très timide." },
    { word: "Bavard", meaning: "Chatty", reading: "ba-var", example_sentence: "Elle est très bavarde." },
    { word: "Silencieux", meaning: "Silent / Quiet", reading: "see-lahn-syuh", example_sentence: "Un garçon silencieux." },
    { word: "Patient", meaning: "Patient", reading: "pa-syah", example_sentence: "Il faut être patient." },
    { word: "Impatient", meaning: "Impatient", reading: "am-pa-syah", example_sentence: "Elle est impatiente." },
    { word: "Optimiste", meaning: "Optimistic", reading: "op-tee-meest", example_sentence: "Rester optimiste." },
    { word: "Pessimiste", meaning: "Pessimistic", reading: "pe-see-meest", example_sentence: "Ne sois pas pessimiste." },
    { word: "Intéressant", meaning: "Interesting", reading: "an-tay-ray-sah", example_sentence: "Un livre intéressant." },
    { word: "Ennuyeux", meaning: "Boring", reading: "ahn-nwee-yuh", example_sentence: "Un film ennuyeux." },
    { word: "Important", meaning: "Important", reading: "am-por-tah", example_sentence: "C'est important." },
    { word: "Inutile", meaning: "Useless", reading: "oo-ne-teel", example_sentence: "C'est inutile." },
    { word: "Génial", meaning: "Great / Awesome", reading: "zhay-nyal", example_sentence: "C'est génial !" },
    { word: "Nul", meaning: "Bad / Rubbish", reading: "nool", example_sentence: "C'est nul." },
    { word: "Terrible", meaning: "Terrible / Dreadful", reading: "te-ree-bluh", example_sentence: "Une nouvelle terrible." },
    { word: "Formidable", meaning: "Wonderful", reading: "for-mee-da-bluh", example_sentence: "Tu es formidable." },
    { word: "Magnifique", meaning: "Magnificent", reading: "ma-nyee-feek", example_sentence: "C'est magnifique." },
    { word: "Moche", meaning: "Ugly (slang)", reading: "mohsh", example_sentence: "C'est moche." },
    { word: "Beau", meaning: "Beautiful / Handsome", reading: "boh", example_sentence: "Un beau garçon." },
    { word: "Belle", meaning: "Beautiful (fem.)", reading: "bel", example_sentence: "Une belle fille." },
    { word: "Préféré", meaning: "Preferred / Favorite", reading: "pray-fay-ray", example_sentence: "Mon plat préféré." },
    { word: "Favori", meaning: "Favorite", reading: "fa-voh-ree", example_sentence: "C'est mon film favori." },
    { word: "Étrange", meaning: "Strange / Odd", reading: "ay-trahnzh", example_sentence: "C'est étrange." },
    { word: "Bizarre", meaning: "Bizarre / Weird", reading: "bee-zar", example_sentence: "Un comportement bizarre." },
    { word: "Normal", meaning: "Normal", reading: "nor-mal", example_sentence: "C'est normal." },
    { word: "Exceptionnel", meaning: "Exceptional", reading: "ek-sep-syoh-nel", example_sentence: "Un talent exceptionnel." },
    { word: "Rare", meaning: "Rare", reading: "rar", example_sentence: "C'est un objet rare." },
    { word: "Commun", meaning: "Common", reading: "koh-mah", example_sentence: "C'est très commun." },
    { word: "Simple", meaning: "Simple", reading: "sam-pluh", example_sentence: "Une question simple." },
    { word: "Compliqué", meaning: "Complicated", reading: "kohm-plee-kay", example_sentence: "C'est trop compliqué." },
    { word: "Facile", meaning: "Easy", reading: "fa-seel", example_sentence: "C'est facile." }
];

const m15 = createModule('fr_a2_m15', 'A2 French - Module 15: Media & Technology', 15, m15_items);
const m16 = createModule('fr_a2_m16', 'A2 French - Module 16: Environment & Geography', 16, m16_items);
const m17 = createModule('fr_a2_m17', 'A2 French - Module 17: Opinions & Emotions', 17, m17_items);

fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m15.json'), JSON.stringify(m15, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m16.json'), JSON.stringify(m16, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m17.json'), JSON.stringify(m17, null, 2));

console.log('✅ Generated French A2 Modules 15, 16, and 17.');
