const fs = require('fs');
const path = require('path');

const french_a1_m2 = {
    id: "fr_a1_m2",
    name: "A1 French - Module 2: Family & Home",
    description: "Vocabulary for family members, household items, and basic descriptions.",
    count: 100,
    vocabularyItems: [
        { word: "Famille", meaning: "Family", reading: "fa-mee", example_sentence: "J'aime ma famille." },
        { word: "Père", meaning: "Father", reading: "per", example_sentence: "Mon père est grand." },
        { word: "Mère", meaning: "Mother", reading: "mer", example_sentence: "Ma mère est gentille." },
        { word: "Frère", meaning: "Brother", reading: "frer", example_sentence: "J'ai un frère." },
        { word: "Sœur", meaning: "Sister", reading: "sur", example_sentence: "Ma sœur s'appelle Marie." },
        { word: "Fils", meaning: "Son", reading: "feess", example_sentence: "C'est mon fils unique." },
        { word: "Fille", meaning: "Daughter / Girl", reading: "fee", example_sentence: "Ma fille a cinq ans." },
        { word: "Enfant", meaning: "Child", reading: "ah-fah", example_sentence: "L'enfant joue dehors." }, // Word #8
        { word: "Maison", meaning: "House", reading: "may-zoh", example_sentence: "Notre maison est bleue." }, // Word #9 (Must be different from Word #1 'Famille')
        { word: "Appartement", meaning: "Apartment", reading: "ah-par-tuh-mah", example_sentence: "J'habite dans un petit appartement." },
        { word: "Chambre", meaning: "Bedroom", reading: "shah-bruh", example_sentence: "Ma chambre est au premier étage." },
        { word: "Cuisine", meaning: "Kitchen", reading: "kwee-zeen", example_sentence: "Il cuisine dans la cuisine." },
        { word: "Salon", meaning: "Living room", reading: "sa-loh", example_sentence: "Regardons la télé dans le salon." },
        { word: "Entrée", meaning: "Entrance", reading: "ah-tray", example_sentence: "L'entrée est fermée." },
        { word: "Jardin", meaning: "Garden", reading: "zhar-dah", example_sentence: "Les fleurs poussent dans le jardin." }, // Word #15

        { word: "Table", meaning: "Table", reading: "ta-bluh", example_sentence: "Le livre est sur la table." },
        { word: "Chaise", meaning: "Chair", reading: "shez", example_sentence: "Assieds-toi sur cette chaise." },
        { word: "Lit", meaning: "Bed", reading: "lee", example_sentence: "Je vais au lit." },
        { word: "Fenêtre", meaning: "Window", reading: "fuh-ne-truh", example_sentence: "Ouvre la fenêtre, s'il te plaît." },
        { word: "Porte", meaning: "Door", reading: "port", example_sentence: "Ferme la porte." },
        { word: "Clé", meaning: "Key", reading: "klay", example_sentence: "J'ai perdu ma clé." },
        { word: "Lampe", meaning: "Lamp", reading: "lahp", example_sentence: "Allume la lampe." },
        { word: "Miroir", meaning: "Mirror", reading: "mee-rwahr", example_sentence: "Regarde-toi dans le miroir." },
        { word: "Tapis", meaning: "Carpet / Rug", reading: "ta-pee", example_sentence: "Le tapis est sale." },
        { word: "Rideau", meaning: "Curtain", reading: "ree-doh", example_sentence: "Tire les rideaux." },
        { word: "Plancher", meaning: "Floor", reading: "plah-shay", example_sentence: "Le plancher est en bois." },
        { word: "Plafond", meaning: "Ceiling", reading: "pla-foh", example_sentence: "Regarde le plafond." },
        { word: "Escalier", meaning: "Stairs", reading: "es-ka-lyay", example_sentence: "Monte l'escalier." },
        { word: "Ascenseur", meaning: "Elevator", reading: "ah-sah-sur", example_sentence: "Prends l'ascenseur." },
        { word: "Balcon", meaning: "Balcony", reading: "bal-koh", example_sentence: "On peut voir la mer du balcon." },

        { word: "Grand-père", meaning: "Grandfather", reading: "grah-per", example_sentence: "Mon grand-père est vieux." },
        { word: "Grand-mère", meaning: "Grandmother", reading: "grah-mer", example_sentence: "Ma grand-mère cuisine bien." },
        { word: "Oncle", meaning: "Uncle", reading: "oh-kluh", example_sentence: "Mon oncle habite ici." },
        { word: "Tante", meaning: "Aunt", reading: "tahnt", example_sentence: "Ma tante est médecin." },
        { word: "Cousin", meaning: "Cousin (m)", reading: "koo-zah", example_sentence: "Mon cousin arrive demain." },
        { word: "Cousine", meaning: "Cousin (f)", reading: "koo-zeen", example_sentence: "Ma cousine est française." },
        { word: "Mari", meaning: "Husband", reading: "ma-ree", example_sentence: "C'est son mari." },
        { word: "Femme", meaning: "Wife / Woman", reading: "fam", example_sentence: "C'est ma femme." },
        { word: "Ami", meaning: "Friend", reading: "ah-mee", example_sentence: "C'est mon meilleur ami." },
        { word: "Voisin", meaning: "Neighbor", reading: "vwa-zah", example_sentence: "Le voisin est bruyant." },
        { word: "Petit-fils", meaning: "Grandson", reading: "puh-tee-feess", example_sentence: "Elle a un petit-fils." },
        { word: "Petite-fille", meaning: "Granddaughter", reading: "puh-teet-fee", example_sentence: "C'est ma petite-fille." },
        { word: "Neveu", meaning: "Nephew", reading: "nuh-vuh", example_sentence: "Mon neveu est drôle." },
        { word: "Nièce", meaning: "Niece", reading: "nyes", example_sentence: "Sa nièce étudie l'art." },
        { word: "Parents", meaning: "Parents", reading: "pa-rah", example_sentence: "Mes parents sont en vacances." },
        { word: "Bébé", meaning: "Baby", reading: "bay-bay", example_sentence: "Le bébé dort." },
        { word: "Jeune", meaning: "Young", reading: "zhun", example_sentence: "Il est très jeune." },
        { word: "Adulte", meaning: "Adult", reading: "a-doolt", example_sentence: "C'est un film pour adultes." },
        { word: "Personne", meaning: "Person", reading: "per-son", example_sentence: "Il n'y a personne." },
        { word: "Gens", meaning: "People", reading: "zhah", example_sentence: "Les gens sont gentils." },

        { word: "Canapé", meaning: "Sofa", reading: "ka-na-pay", example_sentence: "Assieds-toi sur le canapé." },
        { word: "Télévision", meaning: "Television", reading: "tay-lay-vee-zyoh", example_sentence: "Allume la télévision." },
        { word: "Ordinateur", meaning: "Computer", reading: "or-dee-na-tur", example_sentence: "J'utilise mon ordinateur." },
        { word: "Téléphone", meaning: "Phone", reading: "tay-lay-fohn", example_sentence: "Où est mon téléphone ?" },
        { word: "Internet", meaning: "Internet", reading: "ah-ter-net", example_sentence: "Je n'ai pas d'internet." },
        { word: "Livre", meaning: "Book", reading: "lee-vruh", example_sentence: "Je lis un livre." },
        { word: "Journal", meaning: "Newspaper", reading: "zhoor-nal", example_sentence: "Le journal du matin." },
        { word: "Lettre", meaning: "Letter", reading: "le-truh", example_sentence: "J'écris une lettre." },
        { word: "Papier", meaning: "Paper", reading: "pa-pyay", example_sentence: "Un morceau de papier." },
        { word: "Stylo", meaning: "Pen", reading: "stee-loh", example_sentence: "J'ai besoin d'un stylo." },
        { word: "Crayon", meaning: "Pencil", reading: "kray-yoh", example_sentence: "Un crayon à papier." },
        { word: "Sac", meaning: "Bag", reading: "sak", example_sentence: "Mon sac est lourd." },
        { word: "Vêtement", meaning: "Clothing", reading: "vet-mah", example_sentence: "Ce vêtement est neuf." },
        { word: "Chaussure", meaning: "Shoe", reading: "shoh-soor", example_sentence: "Où sont mes chaussures ?" },
        { word: "Chapeau", meaning: "Hat", reading: "sha-poh", example_sentence: "Mets ton chapeau." },

        { word: "Manger", meaning: "To eat", reading: "mah-zhay", example_sentence: "Je mange une pomme." },
        { word: "Dormir", meaning: "To sleep", reading: "dor-meer", example_sentence: "Il faut dormir." },
        { word: "Parler", meaning: "To speak", reading: "par-lay", example_sentence: "Elle parle vite." },
        { word: "Écouter", meaning: "To listen", reading: "ay-koo-tay", example_sentence: "Écoute la musique." },
        { word: "Regarder", meaning: "To watch", reading: "ruh-gar-day", example_sentence: "Regarde ce film." },
        { word: "Lire", meaning: "To read", reading: "leer", example_sentence: "Lisez ce texte." },
        { word: "Écrire", meaning: "To write", reading: "ay-kreer", example_sentence: "Écris ton nom." },
        { word: "Marcher", meaning: "To walk", reading: "mar-shay", example_sentence: "Marchons un peu." },
        { word: "Courir", meaning: "To run", reading: "koo-reer", example_sentence: "Il court vite." },
        { word: "Sauter", meaning: "To jump", reading: "soh-tay", example_sentence: "Sautons ensemble." },
        { word: "Jouer", meaning: "To play", reading: "zhway", example_sentence: "On va jouer ?" },
        { word: "Travailler", meaning: "To work", reading: "tra-va-yay", example_sentence: "Je dois travailler." },
        { word: "Étudier", meaning: "To study", reading: "ay-too-dyay", example_sentence: "J'étudie le français." },
        { word: "Aimer", meaning: "To like / love", reading: "ay-may", example_sentence: "J'aime le chocolat." },
        { word: "Détester", meaning: "To hate", reading: "day-tes-tay", example_sentence: "Je déteste la pluie." },

        { word: "Vrai", meaning: "True", reading: "vray", example_sentence: "C'est vrai." },
        { word: "Faux", meaning: "False", reading: "foh", example_sentence: "C'est faux." },
        { word: "Facile", meaning: "Easy", reading: "fa-seel", example_sentence: "Le français est facile." },
        { word: "Difficile", meaning: "Difficult", reading: "dee-fee-seel", example_sentence: "C'est difficile." },
        { word: "Possible", meaning: "Possible", reading: "poh-see-bluh", example_sentence: "C'est possible." },
        { word: "Impossible", meaning: "Impossible", reading: "ah-poh-see-bluh", example_sentence: "Rien n'est impossible." },
        { word: "Propre", meaning: "Clean", reading: "proh-pruh", example_sentence: "C'est très propre." },
        { word: "Sale", meaning: "Dirty", reading: "sal", example_sentence: "Mes mains sont sales." }, // Word #87
        { word: "Ouvert", meaning: "Open", reading: "oo-ver", example_sentence: "C'est ouvert." },
        { word: "Fermé", meaning: "Closed", reading: "fer-may", example_sentence: "C'est fermé." },
        { word: "Couloir", meaning: "Hallway", reading: "koo-lwahr", example_sentence: "Le couloir est sombre." }, // Word #90 (Fixed Duplicate)
        { word: "Mur", meaning: "Wall", reading: "moor", example_sentence: "Ce mur est blanc." },
        { word: "Sol", meaning: "Ground / Floor", reading: "sohl", example_sentence: "Ne jette rien au sol." },
        { word: "Étage", meaning: "Floor / Story", reading: "ay-tazh", example_sentence: "Le deuxième étage." },
        { word: "Bâtiment", meaning: "Building", reading: "ba-tee-mah", example_sentence: "C'est un vieux bâtiment." },
        { word: "Ville", meaning: "City / Town", reading: "veel", example_sentence: "J'habite en ville." },
        { word: "Village", meaning: "Village", reading: "vee-lazh", example_sentence: "Le village est petit." },
        { word: "Rue", meaning: "Street", reading: "roo", example_sentence: "C'est ma rue." },
        { word: "Route", meaning: "Road", reading: "root", example_sentence: "La route est longue." },
        { word: "Pont", meaning: "Bridge", reading: "poh", example_sentence: "Traverse le pont." } // Word #100
    ]
};

const outputPath = path.join(__dirname, '../firestore_data/french_a1_m2.json');
fs.writeFileSync(outputPath, JSON.stringify(french_a1_m2, null, 2));
console.log('Saved 100 UNIQUE French words to firestore_data/french_a1_m2.json');
