const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items, culturalTraps) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100),
        liarGameData: {
            culturalTraps: culturalTraps
        }
    };
}

// MODULE 28: Media & Communication
const m28_items = [
    { word: "Média", meaning: "Media", reading: "may-dya", example_sentence: "Les médias sociaux." },
    { word: "Presse", meaning: "Press", reading: "pres", example_sentence: "La liberté de la presse." },
    { word: "Journal", meaning: "Newspaper", reading: "zhoor-nal", example_sentence: "Lire le journal." },
    { word: "Journaliste", meaning: "Journalist", reading: "zhoor-na-leest", example_sentence: "Un journaliste d'investigation." },
    { word: "Journalisme", meaning: "Journalism", reading: "zhoor-na-leez-muh", example_sentence: "Le journalisme moderne." },
    { word: "Article", meaning: "Article", reading: "ar-tee-kluh", example_sentence: "Un article intéressant." },
    { word: "Reportage", meaning: "Report / Documentary", reading: "ruh-por-tazh", example_sentence: "Un reportage sur la guerre." },
    { word: "Interview", meaning: "Interview", reading: "an-ter-vyoo", example_sentence: "Une interview exclusive." },
    { word: "Enquête", meaning: "Investigation / Survey", reading: "ahn-ket", example_sentence: "Mener une enquête." },
    { word: "Information", meaning: "Information / News", reading: "an-for-ma-syoh", example_sentence: "Les informations du soir." },
    { word: "Actualité", meaning: "Current events / News", reading: "ak-too-a-lee-tay", example_sentence: "Suivre l'actualité." },
    { word: "Nouvelle", meaning: "News / Short story", reading: "noo-vel", example_sentence: "Une bonne nouvelle." },
    { word: "Fait divers", meaning: "News item", reading: "fay dee-ver", example_sentence: "Les faits divers du jour." },
    { word: "Événement", meaning: "Event", reading: "ay-vay-nuh-mah", example_sentence: "Un événement important." },
    { word: "Titre", meaning: "Title / Headline", reading: "tee-truh", example_sentence: "Le titre de l'article." },
    { word: "Manchette", meaning: "Headline", reading: "mahn-shet", example_sentence: "La manchette du journal." },
    { word: "Rubrique", meaning: "Column / Section", reading: "roo-breek", example_sentence: "La rubrique sportive." },
    { word: "Édition", meaning: "Edition", reading: "ay-dee-syoh", example_sentence: "L'édition du matin." },
    { word: "Rédacteur", meaning: "Editor / Writer", reading: "ray-dak-tur", example_sentence: "Le rédacteur en chef." },
    { word: "Correspondant", meaning: "Correspondent", reading: "koh-res-pohn-dah", example_sentence: "Un correspondant à l'étranger." },
    { word: "Télévision", meaning: "Television", reading: "tay-lay-vee-zyoh", example_sentence: "Regarder la télévision." },
    { word: "Chaîne", meaning: "Channel", reading: "shen", example_sentence: "Une chaîne de télévision." },
    { word: "Émission", meaning: "Program / Show", reading: "ay-mee-syoh", example_sentence: "Une émission populaire." },
    { word: "Diffusion", meaning: "Broadcasting", reading: "dee-foo-zyoh", example_sentence: "La diffusion en direct." },
    { word: "Diffuser", meaning: "To broadcast", reading: "dee-foo-zay", example_sentence: "Diffuser un programme." },
    { word: "Direct", meaning: "Live / Direct", reading: "dee-rekt", example_sentence: "En direct à la télévision." },
    { word: "Enregistrement", meaning: "Recording", reading: "ahn-ruh-zhees-truh-mah", example_sentence: "Un enregistrement vidéo." },
    { word: "Présentateur", meaning: "Presenter / Host", reading: "pray-zahn-ta-tur", example_sentence: "Le présentateur du journal." },
    { word: "Animateur", meaning: "Host / Presenter", reading: "a-nee-ma-tur", example_sentence: "Un animateur de radio." },
    { word: "Radio", meaning: "Radio", reading: "ra-dyoh", example_sentence: "Écouter la radio." },
    { word: "Podcast", meaning: "Podcast", reading: "pohd-kast", example_sentence: "Un podcast intéressant." },
    { word: "Internet", meaning: "Internet", reading: "an-ter-net", example_sentence: "Surfer sur Internet." },
    { word: "Site web", meaning: "Website", reading: "seet web", example_sentence: "Un site web informatif." },
    { word: "Blog", meaning: "Blog", reading: "blohg", example_sentence: "Tenir un blog." },
    { word: "Blogueur", meaning: "Blogger", reading: "bloh-gur", example_sentence: "Un blogueur célèbre." },
    { word: "Réseau social", meaning: "Social network", reading: "ray-zoh soh-syal", example_sentence: "Les réseaux sociaux." },
    { word: "Publication", meaning: "Publication / Post", reading: "poo-blee-ka-syoh", example_sentence: "Une publication virale." },
    { word: "Publier", meaning: "To publish / Post", reading: "poo-blee-ay", example_sentence: "Publier une photo." },
    { word: "Partager", meaning: "To share", reading: "par-ta-zhay", example_sentence: "Partager un article." },
    { word: "Commenter", meaning: "To comment", reading: "koh-mahn-tay", example_sentence: "Commenter une publication." },
    { word: "Commentaire", meaning: "Comment", reading: "koh-mahn-ter", example_sentence: "Laisser un commentaire." },
    { word: "Abonné", meaning: "Subscriber / Follower", reading: "a-boh-nay", example_sentence: "Avoir des abonnés." },
    { word: "Abonnement", meaning: "Subscription", reading: "a-bohn-mah", example_sentence: "Prendre un abonnement." },
    { word: "S'abonner", meaning: "To subscribe", reading: "sa-boh-nay", example_sentence: "S'abonner à une chaîne." },
    { word: "Suivre", meaning: "To follow", reading: "swee-vruh", example_sentence: "Suivre quelqu'un sur Twitter." },
    { word: "Influenceur", meaning: "Influencer", reading: "an-floo-ahn-sur", example_sentence: "Un influenceur populaire." },
    { word: "Viral", meaning: "Viral", reading: "vee-ral", example_sentence: "Une vidéo virale." },
    { word: "Tendance", meaning: "Trend", reading: "tahn-dahns", example_sentence: "Les tendances du moment." },
    { word: "Hashtag", meaning: "Hashtag", reading: "ash-tag", example_sentence: "Utiliser un hashtag." },
    { word: "Message", meaning: "Message", reading: "meh-sazh", example_sentence: "Envoyer un message." },
    { word: "Messagerie", meaning: "Messaging", reading: "meh-sa-zhuh-ree", example_sentence: "Une application de messagerie." },
    { word: "Courriel", meaning: "Email", reading: "koo-ryel", example_sentence: "Envoyer un courriel." },
    { word: "Email", meaning: "Email", reading: "ee-mel", example_sentence: "Vérifier ses emails." },
    { word: "Téléphone", meaning: "Telephone", reading: "tay-lay-fohn", example_sentence: "Appeler au téléphone." },
    { word: "Téléphoner", meaning: "To phone", reading: "tay-lay-foh-nay", example_sentence: "Téléphoner à quelqu'un." },
    { word: "Appel", meaning: "Call", reading: "a-pel", example_sentence: "Passer un appel." },
    { word: "Appeler", meaning: "To call", reading: "ap-lay", example_sentence: "Appeler un ami." },
    { word: "Portable", meaning: "Mobile phone", reading: "por-ta-bluh", example_sentence: "Un téléphone portable." },
    { word: "Smartphone", meaning: "Smartphone", reading: "smart-fohn", example_sentence: "Utiliser un smartphone." },
    { word: "Application", meaning: "Application / App", reading: "a-plee-ka-syoh", example_sentence: "Télécharger une application." },
    { word: "Télécharger", meaning: "To download", reading: "tay-lay-shar-zhay", example_sentence: "Télécharger un fichier." },
    { word: "Téléchargement", meaning: "Download", reading: "tay-lay-sharzh-mah", example_sentence: "Le téléchargement est terminé." },
    { word: "Connexion", meaning: "Connection", reading: "koh-nek-syoh", example_sentence: "Une connexion Internet." },
    { word: "Se connecter", meaning: "To connect / Log in", reading: "suh koh-nek-tay", example_sentence: "Se connecter à un réseau." },
    { word: "Déconnecter", meaning: "To disconnect / Log out", reading: "day-koh-nek-tay", example_sentence: "Se déconnecter du compte." },
    { word: "Mot de passe", meaning: "Password", reading: "moh duh pas", example_sentence: "Entrer le mot de passe." },
    { word: "Compte", meaning: "Account", reading: "kohnt", example_sentence: "Créer un compte." },
    { word: "Profil", meaning: "Profile", reading: "proh-feel", example_sentence: "Modifier son profil." },
    { word: "Paramètres", meaning: "Settings", reading: "pa-ra-metruh", example_sentence: "Ajuster les paramètres." },
    { word: "Notification", meaning: "Notification", reading: "noh-tee-fee-ka-syoh", example_sentence: "Recevoir une notification." },
    { word: "Alerte", meaning: "Alert", reading: "a-lert", example_sentence: "Une alerte importante." },
    { word: "Recherche", meaning: "Search", reading: "ruh-shersh", example_sentence: "Faire une recherche." },
    { word: "Rechercher", meaning: "To search", reading: "ruh-sher-shay", example_sentence: "Rechercher une information." },
    { word: "Moteur de recherche", meaning: "Search engine", reading: "moh-tur duh ruh-shersh", example_sentence: "Utiliser un moteur de recherche." },
    { word: "Lien", meaning: "Link", reading: "lya", example_sentence: "Cliquer sur un lien." },
    { word: "Cliquer", meaning: "To click", reading: "klee-kay", example_sentence: "Cliquer sur le bouton." },
    { word: "Naviguer", meaning: "To browse / Navigate", reading: "na-vee-gay", example_sentence: "Naviguer sur Internet." },
    { word: "Navigation", meaning: "Navigation / Browsing", reading: "na-vee-ga-syoh", example_sentence: "La navigation web." },
    { word: "Page", meaning: "Page", reading: "pazh", example_sentence: "Une page web." },
    { word: "Contenu", meaning: "Content", reading: "kohn-tuh-noo", example_sentence: "Du contenu intéressant." },
    { word: "Vidéo", meaning: "Video", reading: "vee-day-oh", example_sentence: "Regarder une vidéo." },
    { word: "Audio", meaning: "Audio", reading: "oh-dyoh", example_sentence: "Un fichier audio." },
    { word: "Image", meaning: "Image", reading: "ee-mazh", example_sentence: "Télécharger une image." },
    { word: "Photo", meaning: "Photo", reading: "foh-toh", example_sentence: "Prendre une photo." },
    { word: "Fichier", meaning: "File", reading: "fee-shyay", example_sentence: "Ouvrir un fichier." },
    { word: "Document", meaning: "Document", reading: "doh-koo-mah", example_sentence: "Un document important." },
    { word: "Texte", meaning: "Text", reading: "tekst", example_sentence: "Écrire un texte." },
    { word: "Envoyer", meaning: "To send", reading: "ahn-vwa-yay", example_sentence: "Envoyer un message." },
    { word: "Recevoir", meaning: "To receive", reading: "ruh-suh-vwahr", example_sentence: "Recevoir un email." },
    { word: "Répondre", meaning: "To reply / Answer", reading: "ray-pohn-druh", example_sentence: "Répondre à un message." },
    { word: "Transférer", meaning: "To forward", reading: "trahns-fay-ray", example_sentence: "Transférer un email." },
    { word: "Supprimer", meaning: "To delete", reading: "soo-pree-may", example_sentence: "Supprimer un fichier." },
    { word: "Sauvegarder", meaning: "To save", reading: "sohv-gar-day", example_sentence: "Sauvegarder un document." },
    { word: "Copier", meaning: "To copy", reading: "koh-pyay", example_sentence: "Copier un texte." },
    { word: "Coller", meaning: "To paste", reading: "koh-lay", example_sentence: "Coller le texte copié." },
    { word: "Imprimer", meaning: "To print", reading: "am-pree-may", example_sentence: "Imprimer un document." },
    { word: "Scanner", meaning: "To scan", reading: "ska-nay", example_sentence: "Scanner un document." },
    { word: "Numérique", meaning: "Digital", reading: "noo-may-reek", example_sentence: "La transformation numérique." },
    { word: "Virtuel", meaning: "Virtual", reading: "veer-too-el", example_sentence: "Une réunion virtuelle." },
    { word: "En ligne", meaning: "Online", reading: "ahn leenyuh", example_sentence: "Travailler en ligne." }
];

const m28_traps = [
    { trap: "French people use 'email' instead of 'courriel' in everyday speech.", correctVersion: "While 'email' is widely used informally, 'courriel' is the official French term. In Quebec, 'courriel' is strongly preferred.", explanation: "Language purists and Quebec French favor 'courriel'. Using French terms shows respect for the language." },
    { trap: "French social media culture is exactly like American social media culture.", correctVersion: "French social media users tend to be more private and less self-promotional. Oversharing is viewed negatively.", explanation: "French culture values privacy ('vie privée'). The American influencer culture is less prevalent in France." },
    { trap: "'Actualité' and 'Nouvelle' are completely interchangeable in French.", correctVersion: "'Actualité' refers to current events broadly, while 'nouvelle' is a specific piece of news. Context determines usage.", explanation: "'L'actualité' is 'the news' (general), while 'une nouvelle' is 'a news item' (specific)." }
];

// MODULE 29: Environment & Nature
const m29_items = [
    { word: "Environnement", meaning: "Environment", reading: "ahn-vee-rohn-mah", example_sentence: "Protéger l'environnement." },
    { word: "Nature", meaning: "Nature", reading: "na-toor", example_sentence: "La beauté de la nature." },
    { word: "Naturel", meaning: "Natural", reading: "na-too-rel", example_sentence: "Un produit naturel." },
    { word: "Écologie", meaning: "Ecology", reading: "ay-koh-loh-zhee", example_sentence: "L'écologie scientifique." },
    { word: "Écologique", meaning: "Ecological", reading: "ay-koh-loh-zheek", example_sentence: "Un mode de vie écologique." },
    { word: "Écologiste", meaning: "Environmentalist", reading: "ay-koh-loh-zheest", example_sentence: "Un militant écologiste." },
    { word: "Planète", meaning: "Planet", reading: "pla-net", example_sentence: "Sauver la planète." },
    { word: "Terre", meaning: "Earth / Land", reading: "ter", example_sentence: "La planète Terre." },
    { word: "Climat", meaning: "Climate", reading: "klee-ma", example_sentence: "Le changement climatique." },
    { word: "Climatique", meaning: "Climatic", reading: "klee-ma-teek", example_sentence: "Une crise climatique." },
    { word: "Réchauffement", meaning: "Warming", reading: "ray-shohf-mah", example_sentence: "Le réchauffement climatique." },
    { word: "Pollution", meaning: "Pollution", reading: "poh-loo-syoh", example_sentence: "La pollution de l'air." },
    { word: "Polluer", meaning: "To pollute", reading: "poh-loo-ay", example_sentence: "Polluer l'environnement." },
    { word: "Polluant", meaning: "Pollutant / Polluting", reading: "poh-loo-ah", example_sentence: "Un gaz polluant." },
    { word: "Déchets", meaning: "Waste / Garbage", reading: "day-shay", example_sentence: "Trier les déchets." },
    { word: "Ordures", meaning: "Garbage / Trash", reading: "or-door", example_sentence: "Jeter les ordures." },
    { word: "Poubelle", meaning: "Trash can", reading: "poo-bel", example_sentence: "Mettre à la poubelle." },
    { word: "Recyclage", meaning: "Recycling", reading: "ruh-see-klazh", example_sentence: "Le recyclage des plastiques." },
    { word: "Recycler", meaning: "To recycle", reading: "ruh-see-klay", example_sentence: "Recycler le papier." },
    { word: "Recyclable", meaning: "Recyclable", reading: "ruh-see-kla-bluh", example_sentence: "Un emballage recyclable." },
    { word: "Tri", meaning: "Sorting", reading: "tree", example_sentence: "Le tri sélectif." },
    { word: "Trier", meaning: "To sort", reading: "tree-ay", example_sentence: "Trier les déchets." },
    { word: "Compost", meaning: "Compost", reading: "kohm-pohst", example_sentence: "Faire du compost." },
    { word: "Biodégradable", meaning: "Biodegradable", reading: "byoh-day-gra-da-bluh", example_sentence: "Un sac biodégradable." },
    { word: "Durable", meaning: "Sustainable / Durable", reading: "doo-ra-bluh", example_sentence: "Le développement durable." },
    { word: "Durabilité", meaning: "Sustainability", reading: "doo-ra-bee-lee-tay", example_sentence: "La durabilité environnementale." },
    { word: "Renouvelable", meaning: "Renewable", reading: "ruh-noo-vuh-la-bluh", example_sentence: "L'énergie renouvelable." },
    { word: "Ressource", meaning: "Resource", reading: "ruh-soors", example_sentence: "Les ressources naturelles." },
    { word: "Énergie", meaning: "Energy", reading: "ay-ner-zhee", example_sentence: "L'énergie solaire." },
    { word: "Solaire", meaning: "Solar", reading: "soh-ler", example_sentence: "Un panneau solaire." },
    { word: "Éolien", meaning: "Wind (energy)", reading: "ay-oh-lya", example_sentence: "L'énergie éolienne." },
    { word: "Nucléaire", meaning: "Nuclear", reading: "noo-klay-er", example_sentence: "L'énergie nucléaire." },
    { word: "Fossile", meaning: "Fossil", reading: "foh-seel", example_sentence: "Les énergies fossiles." },
    { word: "Carbone", meaning: "Carbon", reading: "kar-bohn", example_sentence: "L'empreinte carbone." },
    { word: "Émission", meaning: "Emission", reading: "ay-mee-syoh", example_sentence: "Les émissions de CO2." },
    { word: "Gaz", meaning: "Gas", reading: "gaz", example_sentence: "Les gaz à effet de serre." },
    { word: "Effet de serre", meaning: "Greenhouse effect", reading: "ay-fay duh ser", example_sentence: "L'effet de serre s'intensifie." },
    { word: "Atmosphère", meaning: "Atmosphere", reading: "at-mohs-fer", example_sentence: "L'atmosphère terrestre." },
    { word: "Air", meaning: "Air", reading: "er", example_sentence: "La qualité de l'air." },
    { word: "Eau", meaning: "Water", reading: "oh", example_sentence: "L'eau potable." },
    { word: "Océan", meaning: "Ocean", reading: "oh-say-ah", example_sentence: "L'océan Atlantique." },
    { word: "Mer", meaning: "Sea", reading: "mer", example_sentence: "La mer Méditerranée." },
    { word: "Rivière", meaning: "River", reading: "ree-vyer", example_sentence: "Une rivière polluée." },
    { word: "Fleuve", meaning: "River (major)", reading: "fluhv", example_sentence: "Le fleuve Seine." },
    { word: "Lac", meaning: "Lake", reading: "lak", example_sentence: "Un lac de montagne." },
    { word: "Forêt", meaning: "Forest", reading: "foh-ray", example_sentence: "La forêt amazonienne." },
    { word: "Arbre", meaning: "Tree", reading: "ar-bruh", example_sentence: "Planter un arbre." },
    { word: "Plante", meaning: "Plant", reading: "plahnt", example_sentence: "Une plante verte." },
    { word: "Fleur", meaning: "Flower", reading: "flur", example_sentence: "Une belle fleur." },
    { word: "Végétation", meaning: "Vegetation", reading: "vay-zhay-ta-syoh", example_sentence: "La végétation luxuriante." },
    { word: "Faune", meaning: "Fauna / Wildlife", reading: "fohn", example_sentence: "La faune sauvage." },
    { word: "Flore", meaning: "Flora", reading: "flohr", example_sentence: "La flore locale." },
    { word: "Animal", meaning: "Animal", reading: "a-nee-mal", example_sentence: "Un animal sauvage." },
    { word: "Espèce", meaning: "Species", reading: "es-pes", example_sentence: "Une espèce menacée." },
    { word: "Biodiversité", meaning: "Biodiversity", reading: "byoh-dee-ver-see-tay", example_sentence: "Préserver la biodiversité." },
    { word: "Extinction", meaning: "Extinction", reading: "eks-tank-syoh", example_sentence: "L'extinction des espèces." },
    { word: "Menacé", meaning: "Threatened / Endangered", reading: "muh-na-say", example_sentence: "Une espèce menacée." },
    { word: "Protéger", meaning: "To protect", reading: "proh-tay-zhay", example_sentence: "Protéger la nature." },
    { word: "Protection", meaning: "Protection", reading: "proh-tek-syoh", example_sentence: "La protection de l'environnement." },
    { word: "Préserver", meaning: "To preserve", reading: "pray-zer-vay", example_sentence: "Préserver les ressources." },
    { word: "Préservation", meaning: "Preservation", reading: "pray-zer-va-syoh", example_sentence: "La préservation de la nature." },
    { word: "Conserver", meaning: "To conserve", reading: "kohn-ser-vay", example_sentence: "Conserver l'eau." },
    { word: "Conservation", meaning: "Conservation", reading: "kohn-ser-va-syoh", example_sentence: "La conservation des forêts." },
    { word: "Sauver", meaning: "To save", reading: "soh-vay", example_sentence: "Sauver la planète." },
    { word: "Réduire", meaning: "To reduce", reading: "ray-dweer", example_sentence: "Réduire les déchets." },
    { word: "Réduction", meaning: "Reduction", reading: "ray-dook-syoh", example_sentence: "La réduction des émissions." },
    { word: "Diminuer", meaning: "To decrease", reading: "dee-mee-noo-ay", example_sentence: "Diminuer la consommation." },
    { word: "Consommation", meaning: "Consumption", reading: "kohn-soh-ma-syoh", example_sentence: "La consommation d'énergie." },
    { word: "Consommer", meaning: "To consume", reading: "kohn-soh-may", example_sentence: "Consommer moins." },
    { word: "Gaspillage", meaning: "Waste / Wastage", reading: "gas-pee-yazh", example_sentence: "Éviter le gaspillage." },
    { word: "Gaspiller", meaning: "To waste", reading: "gas-pee-yay", example_sentence: "Gaspiller l'eau." },
    { word: "Économiser", meaning: "To save / Economize", reading: "ay-koh-noh-mee-zay", example_sentence: "Économiser l'énergie." },
    { word: "Économie", meaning: "Economy / Saving", reading: "ay-koh-noh-mee", example_sentence: "Faire des économies d'énergie." },
    { word: "Écologique", meaning: "Ecological", reading: "ay-koh-loh-zheek", example_sentence: "Un geste écologique." },
    { word: "Vert", meaning: "Green", reading: "ver", example_sentence: "L'économie verte." },
    { word: "Bio", meaning: "Organic / Bio", reading: "byoh", example_sentence: "Des produits bio." },
    { word: "Biologique", meaning: "Biological / Organic", reading: "byoh-loh-zheek", example_sentence: "L'agriculture biologique." },
    { word: "Agriculture", meaning: "Agriculture", reading: "a-gree-kool-toor", example_sentence: "L'agriculture durable." },
    { word: "Pesticide", meaning: "Pesticide", reading: "pes-tee-seed", example_sentence: "Éviter les pesticides." },
    { word: "Engrais", meaning: "Fertilizer", reading: "ahn-gray", example_sentence: "Un engrais chimique." },
    { word: "Chimique", meaning: "Chemical", reading: "shee-meek", example_sentence: "Un produit chimique." },
    { word: "Toxique", meaning: "Toxic", reading: "tohk-seek", example_sentence: "Une substance toxique." },
    { word: "Dangereux", meaning: "Dangerous", reading: "dahn-zhuh-ruh", example_sentence: "Un déchet dangereux." },
    { word: "Risque", meaning: "Risk", reading: "reesk", example_sentence: "Un risque environnemental." },
    { word: "Catastrophe", meaning: "Catastrophe / Disaster", reading: "ka-tas-trohf", example_sentence: "Une catastrophe naturelle." },
    { word: "Désastre", meaning: "Disaster", reading: "day-zastruh", example_sentence: "Un désastre écologique." },
    { word: "Inondation", meaning: "Flood", reading: "ee-nohn-da-syoh", example_sentence: "Une inondation dévastatrice." },
    { word: "Sécheresse", meaning: "Drought", reading: "say-shuh-res", example_sentence: "Une période de sécheresse." },
    { word: "Tempête", meaning: "Storm", reading: "tahm-pet", example_sentence: "Une violente tempête." },
    { word: "Ouragan", meaning: "Hurricane", reading: "oo-ra-gah", example_sentence: "Un ouragan dévastateur." },
    { word: "Cyclone", meaning: "Cyclone", reading: "see-klohn", example_sentence: "Un cyclone tropical." },
    { word: "Tremblement de terre", meaning: "Earthquake", reading: "trahm-bluh-mah duh ter", example_sentence: "Un tremblement de terre violent." },
    { word: "Tsunami", meaning: "Tsunami", reading: "tsoo-na-mee", example_sentence: "Un tsunami destructeur." },
    { word: "Incendie", meaning: "Fire", reading: "an-sahn-dee", example_sentence: "Un incendie de forêt." },
    { word: "Feu", meaning: "Fire", reading: "fuh", example_sentence: "Un feu de forêt." },
    { word: "Brûler", meaning: "To burn", reading: "broo-lay", example_sentence: "La forêt brûle." },
    { word: "Détruire", meaning: "To destroy", reading: "day-trweer", example_sentence: "Détruire l'habitat naturel." },
    { word: "Destruction", meaning: "Destruction", reading: "des-trook-syoh", example_sentence: "La destruction de la forêt." },
    { word: "Écosystème", meaning: "Ecosystem", reading: "ay-koh-sees-tem", example_sentence: "Préserver l'écosystème." },
    { word: "Habitat", meaning: "Habitat", reading: "a-bee-ta", example_sentence: "L'habitat naturel des animaux." }
];

const m29_traps = [
    { trap: "French people don't really care about the environment compared to other Europeans.", correctVersion: "France is very environmentally conscious. Nuclear energy, public transport, and environmental laws are taken seriously.", explanation: "France has strong green policies. Environmental issues are mainstream political topics, not fringe." },
    { trap: "'Bio' in French just means 'biography' like in English.", correctVersion: "'Bio' in French primarily means 'organic' (food/products). Biography is 'biographie'.", explanation: "This is a major false friend. 'Produits bio' means 'organic products', not biographical products!" },
    { trap: "French nuclear energy is viewed negatively like in Germany.", correctVersion: "France strongly supports nuclear energy as clean and efficient. It's a source of national pride, not controversy.", explanation: "France gets 70% of electricity from nuclear. The cultural attitude is very different from Germany's." }
];

// MODULE 30: Advanced Synthesis & Review
const m30_items = [
    { word: "Synthèse", meaning: "Synthesis", reading: "san-tez", example_sentence: "Faire une synthèse." },
    { word: "Résumé", meaning: "Summary", reading: "ray-zoo-may", example_sentence: "Un résumé du texte." },
    { word: "Récapitulation", meaning: "Recapitulation", reading: "ray-ka-pee-too-la-syoh", example_sentence: "Une récapitulation des points." },
    { word: "Révision", meaning: "Revision / Review", reading: "ray-vee-zyoh", example_sentence: "La révision des leçons." },
    { word: "Réviser", meaning: "To revise / Review", reading: "ray-vee-zay", example_sentence: "Réviser pour l'examen." },
    { word: "Examen", meaning: "Exam", reading: "eg-za-ma", example_sentence: "Passer un examen." },
    { word: "Test", meaning: "Test", reading: "test", example_sentence: "Un test de niveau." },
    { word: "Épreuve", meaning: "Test / Trial", reading: "ay-pruhv", example_sentence: "Une épreuve difficile." },
    { word: "Évaluation", meaning: "Evaluation / Assessment", reading: "ay-va-loo-a-syoh", example_sentence: "L'évaluation des compétences." },
    { word: "Évaluer", meaning: "To evaluate / Assess", reading: "ay-va-loo-ay", example_sentence: "Évaluer les progrès." },
    { word: "Note", meaning: "Grade / Note", reading: "noht", example_sentence: "Avoir une bonne note." },
    { word: "Résultat", meaning: "Result", reading: "ray-zool-ta", example_sentence: "Les résultats de l'examen." },
    { word: "Réussite", meaning: "Success", reading: "ray-oo-seet", example_sentence: "La réussite scolaire." },
    { word: "Réussir", meaning: "To succeed", reading: "ray-oo-seer", example_sentence: "Réussir l'examen." },
    { word: "Échec", meaning: "Failure", reading: "ay-shek", example_sentence: "Éviter l'échec." },
    { word: "Échouer", meaning: "To fail", reading: "ay-shoo-ay", example_sentence: "Échouer à l'examen." },
    { word: "Progrès", meaning: "Progress", reading: "proh-gray", example_sentence: "Faire des progrès." },
    { word: "Progresser", meaning: "To progress", reading: "proh-gre-say", example_sentence: "Progresser rapidement." },
    { word: "Amélioration", meaning: "Improvement", reading: "a-may-lyoh-ra-syoh", example_sentence: "Une amélioration notable." },
    { word: "Améliorer", meaning: "To improve", reading: "a-may-lyoh-ray", example_sentence: "Améliorer ses compétences." },
    { word: "Développement", meaning: "Development", reading: "day-vuh-lohp-mah", example_sentence: "Le développement personnel." },
    { word: "Développer", meaning: "To develop", reading: "day-vuh-loh-pay", example_sentence: "Développer ses talents." },
    { word: "Apprentissage", meaning: "Learning", reading: "a-prahn-tee-sazh", example_sentence: "L'apprentissage des langues." },
    { word: "Apprendre", meaning: "To learn", reading: "a-prahn-druh", example_sentence: "Apprendre le français." },
    { word: "Étudier", meaning: "To study", reading: "ay-too-dyay", example_sentence: "Étudier sérieusement." },
    { word: "Étude", meaning: "Study", reading: "ay-tood", example_sentence: "Les études supérieures." },
    { word: "Pratique", meaning: "Practice", reading: "pra-teek", example_sentence: "La pratique régulière." },
    { word: "Pratiquer", meaning: "To practice", reading: "pra-tee-kay", example_sentence: "Pratiquer tous les jours." },
    { word: "Exercice", meaning: "Exercise", reading: "eg-zer-sees", example_sentence: "Faire un exercice." },
    { word: "S'exercer", meaning: "To practice / Exercise", reading: "seg-zer-say", example_sentence: "S'exercer régulièrement." },
    { word: "Entraînement", meaning: "Training", reading: "ahn-tren-mah", example_sentence: "L'entraînement quotidien." },
    { word: "S'entraîner", meaning: "To train", reading: "sahn-tre-nay", example_sentence: "S'entraîner chaque jour." },
    { word: "Répétition", meaning: "Repetition / Rehearsal", reading: "ray-pay-tee-syoh", example_sentence: "La répétition est essentielle." },
    { word: "Répéter", meaning: "To repeat / Rehearse", reading: "ray-pay-tay", example_sentence: "Répéter plusieurs fois." },
    { word: "Mémoriser", meaning: "To memorize", reading: "may-moh-ree-zay", example_sentence: "Mémoriser du vocabulaire." },
    { word: "Mémoire", meaning: "Memory", reading: "may-mwahr", example_sentence: "Avoir une bonne mémoire." },
    { word: "Retenir", meaning: "To remember / Retain", reading: "ruh-tuh-neer", example_sentence: "Retenir une information." },
    { word: "Se souvenir", meaning: "To remember", reading: "suh soo-vuh-neer", example_sentence: "Se souvenir de quelque chose." },
    { word: "Oublier", meaning: "To forget", reading: "oo-blee-ay", example_sentence: "Oublier un mot." },
    { word: "Rappeler", meaning: "To remind / Recall", reading: "ra-puh-lay", example_sentence: "Se rappeler un détail." },
    { word: "Compréhension", meaning: "Comprehension / Understanding", reading: "kohm-pray-ahn-syoh", example_sentence: "La compréhension orale." },
    { word: "Comprendre", meaning: "To understand", reading: "kohm-prahn-druh", example_sentence: "Comprendre le français." },
    { word: "Expression", meaning: "Expression", reading: "eks-pray-syoh", example_sentence: "L'expression écrite." },
    { word: "Exprimer", meaning: "To express", reading: "eks-pree-may", example_sentence: "S'exprimer clairement." },
    { word: "Communication", meaning: "Communication", reading: "koh-moo-nee-ka-syoh", example_sentence: "La communication efficace." },
    { word: "Communiquer", meaning: "To communicate", reading: "koh-moo-nee-kay", example_sentence: "Communiquer en français." },
    { word: "Conversation", meaning: "Conversation", reading: "kohn-ver-sa-syoh", example_sentence: "Une conversation intéressante." },
    { word: "Converser", meaning: "To converse", reading: "kohn-ver-say", example_sentence: "Converser avec des natifs." },
    { word: "Dialogue", meaning: "Dialogue", reading: "dya-lohg", example_sentence: "Un dialogue authentique." },
    { word: "Discuter", meaning: "To discuss", reading: "dees-koo-tay", example_sentence: "Discuter d'un sujet." },
    { word: "Discussion", meaning: "Discussion", reading: "dees-koo-syoh", example_sentence: "Une discussion animée." },
    { word: "Parler", meaning: "To speak", reading: "par-lay", example_sentence: "Parler couramment." },
    { word: "Dire", meaning: "To say / Tell", reading: "deer", example_sentence: "Dire la vérité." },
    { word: "Raconter", meaning: "To tell / Narrate", reading: "ra-kohn-tay", example_sentence: "Raconter une histoire." },
    { word: "Décrire", meaning: "To describe", reading: "day-kreer", example_sentence: "Décrire une situation." },
    { word: "Description", meaning: "Description", reading: "des-kreep-syoh", example_sentence: "Une description détaillée." },
    { word: "Expliquer", meaning: "To explain", reading: "eks-plee-kay", example_sentence: "Expliquer clairement." },
    { word: "Explication", meaning: "Explanation", reading: "eks-plee-ka-syoh", example_sentence: "Demander une explication." },
    { word: "Définir", meaning: "To define", reading: "day-fee-neer", example_sentence: "Définir un mot." },
    { word: "Définition", meaning: "Definition", reading: "day-fee-nee-syoh", example_sentence: "La définition exacte." },
    { word: "Signifier", meaning: "To mean / Signify", reading: "see-nyee-fyay", example_sentence: "Que signifie ce mot ?" },
    { word: "Signification", meaning: "Meaning", reading: "see-nyee-fee-ka-syoh", example_sentence: "La signification du terme." },
    { word: "Sens", meaning: "Meaning / Sense", reading: "sahns", example_sentence: "Le sens d'une phrase." },
    { word: "Contexte", meaning: "Context", reading: "kohn-tekst", example_sentence: "Comprendre le contexte." },
    { word: "Exemple", meaning: "Example", reading: "eg-zahm-pluh", example_sentence: "Donner un exemple." },
    { word: "Illustration", meaning: "Illustration", reading: "ee-loos-tra-syoh", example_sentence: "Une illustration concrète." },
    { word: "Démonstration", meaning: "Demonstration", reading: "day-mohn-stra-syoh", example_sentence: "Faire une démonstration." },
    { word: "Montrer", meaning: "To show", reading: "mohn-tray", example_sentence: "Montrer un exemple." },
    { word: "Indiquer", meaning: "To indicate", reading: "an-dee-kay", example_sentence: "Indiquer la direction." },
    { word: "Préciser", meaning: "To specify", reading: "pray-see-zay", example_sentence: "Préciser un point." },
    { word: "Clarifier", meaning: "To clarify", reading: "kla-ree-fyay", example_sentence: "Clarifier une idée." },
    { word: "Simplifier", meaning: "To simplify", reading: "sam-plee-fyay", example_sentence: "Simplifier l'explication." },
    { word: "Compliquer", meaning: "To complicate", reading: "kohm-plee-kay", example_sentence: "Ne pas compliquer les choses." },
    { word: "Faciliter", meaning: "To facilitate", reading: "fa-see-lee-tay", example_sentence: "Faciliter l'apprentissage." },
    { word: "Difficulté", meaning: "Difficulty", reading: "dee-fee-kool-tay", example_sentence: "Surmonter une difficulté." },
    { word: "Difficile", meaning: "Difficult", reading: "dee-fee-seel", example_sentence: "Un exercice difficile." },
    { word: "Facile", meaning: "Easy", reading: "fa-seel", example_sentence: "Un texte facile." },
    { word: "Simple", meaning: "Simple", reading: "sam-pluh", example_sentence: "Une explication simple." },
    { word: "Complexe", meaning: "Complex", reading: "kohm-pleks", example_sentence: "Une structure complexe." },
    { word: "Compliqué", meaning: "Complicated", reading: "kohm-plee-kay", example_sentence: "C'est compliqué." },
    { word: "Clair", meaning: "Clear", reading: "kler", example_sentence: "Une explication claire." },
    { word: "Évident", meaning: "Obvious / Evident", reading: "ay-vee-dah", example_sentence: "C'est évident." },
    { word: "Logique", meaning: "Logical", reading: "loh-zheek", example_sentence: "Un raisonnement logique." },
    { word: "Cohérent", meaning: "Coherent", reading: "koh-ay-rah", example_sentence: "Un discours cohérent." },
    { word: "Précis", meaning: "Precise", reading: "pray-see", example_sentence: "Une réponse précise." },
    { word: "Exact", meaning: "Exact", reading: "eg-zakt", example_sentence: "La réponse exacte." },
    { word: "Correct", meaning: "Correct", reading: "koh-rekt", example_sentence: "Une phrase correcte." },
    { word: "Incorrect", meaning: "Incorrect", reading: "an-koh-rekt", example_sentence: "Une réponse incorrecte." },
    { word: "Erreur", meaning: "Error / Mistake", reading: "ay-rur", example_sentence: "Corriger une erreur." },
    { word: "Faute", meaning: "Mistake / Fault", reading: "foht", example_sentence: "Une faute de grammaire." },
    { word: "Correction", meaning: "Correction", reading: "koh-rek-syoh", example_sentence: "La correction des erreurs." },
    { word: "Corriger", meaning: "To correct", reading: "koh-ree-zhay", example_sentence: "Corriger les fautes." },
    { word: "Perfectionner", meaning: "To perfect", reading: "per-fek-syoh-nay", example_sentence: "Perfectionner son français." },
    { word: "Maîtrise", meaning: "Mastery", reading: "may-treez", example_sentence: "La maîtrise de la langue." },
    { word: "Maîtriser", meaning: "To master", reading: "may-tree-zay", example_sentence: "Maîtriser le français." },
    { word: "Compétence", meaning: "Competence / Skill", reading: "kohm-pay-tahns", example_sentence: "Développer ses compétences." },
    { word: "Capacité", meaning: "Capacity / Ability", reading: "ka-pa-see-tay", example_sentence: "La capacité d'apprendre." },
    { word: "Aptitude", meaning: "Aptitude", reading: "ap-tee-tood", example_sentence: "Une aptitude naturelle." },
    { word: "Talent", meaning: "Talent", reading: "ta-lah", example_sentence: "Avoir du talent." },
    { word: "Don", meaning: "Gift / Talent", reading: "doh", example_sentence: "Un don pour les langues." }
];

const m30_traps = [
    { trap: "Once you finish B1, you're fluent in French.", correctVersion: "B1 is intermediate. You can handle most situations, but fluency requires B2-C1. Native-like proficiency is C2.", explanation: "The CEFR levels are: A1-A2 (basic), B1-B2 (independent), C1-C2 (proficient). B1 is the midpoint, not the endpoint." },
    { trap: "'Réviser' means 'to revise' (change) in French like in English.", correctVersion: "'Réviser' means 'to review/study' in French. To revise (change) a text is 'modifier' or 'corriger'.", explanation: "This false friend trips up students. 'Réviser pour l'examen' means 'to study for the exam', not 'to change the exam'." },
    { trap: "French people will always correct your mistakes to help you learn.", correctVersion: "French people usually won't correct you unless asked. They prioritize communication over correction to avoid seeming rude.", explanation: "Unlike language teachers, native speakers generally let mistakes slide. If you want feedback, explicitly ask for it." }
];

// Generate and save all three modules
const modules = [
    createModule('fr_b1_m28', 'B1 French - Module 28: Media & Communication', 28, m28_items, m28_traps),
    createModule('fr_b1_m29', 'B1 French - Module 29: Environment & Nature', 29, m29_items, m29_traps),
    createModule('fr_b1_m30', 'B1 French - Module 30: Advanced Synthesis', 30, m30_items, m30_traps)
];

modules.forEach(module => {
    const outputPath = path.join(__dirname, `../firestore_data/${module.id}.json`);
    fs.writeFileSync(outputPath, JSON.stringify(module, null, 2));
    console.log(`✅ ${module.id} generated: ${module.vocabularyItems.length} words, ${module.liarGameData.culturalTraps.length} traps`);
});

console.log('\n🎯 All three modules generated successfully!');
console.log('🎊 French B1 curriculum is now COMPLETE!');
