const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items, culturalTraps) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100),
        liarGameData: {
            culturalTraps: culturalTraps
        }
    };
}

// MODULE 25: Politics & Society
const m25_items = [
    { word: "Politique", meaning: "Politics / Political", reading: "poh-lee-teek", example_sentence: "La politique française." },
    { word: "Gouvernement", meaning: "Government", reading: "goo-vern-mah", example_sentence: "Le gouvernement actuel." },
    { word: "État", meaning: "State", reading: "ay-ta", example_sentence: "L'État français." },
    { word: "Nation", meaning: "Nation", reading: "na-syoh", example_sentence: "La nation française." },
    { word: "Pays", meaning: "Country", reading: "pay-ee", example_sentence: "Un pays démocratique." },
    { word: "République", meaning: "Republic", reading: "ray-poo-bleek", example_sentence: "La République française." },
    { word: "Démocratie", meaning: "Democracy", reading: "day-moh-kra-see", example_sentence: "La démocratie représentative." },
    { word: "Monarchie", meaning: "Monarchy", reading: "moh-nar-shee", example_sentence: "Une monarchie constitutionnelle." },
    { word: "Dictature", meaning: "Dictatorship", reading: "deek-ta-toor", example_sentence: "Une dictature militaire." },
    { word: "Président", meaning: "President", reading: "pray-zee-dah", example_sentence: "Le président de la République." },
    { word: "Premier ministre", meaning: "Prime minister", reading: "pruh-myay mee-nees-truh", example_sentence: "Le Premier ministre français." },
    { word: "Ministre", meaning: "Minister", reading: "mee-nees-truh", example_sentence: "Le ministre de l'Éducation." },
    { word: "Député", meaning: "Deputy / Representative", reading: "day-poo-tay", example_sentence: "Un député de l'Assemblée." },
    { word: "Sénateur", meaning: "Senator", reading: "say-na-tur", example_sentence: "Un sénateur influent." },
    { word: "Parlement", meaning: "Parliament", reading: "par-luh-mah", example_sentence: "Le Parlement européen." },
    { word: "Assemblée", meaning: "Assembly", reading: "a-sahm-blay", example_sentence: "L'Assemblée nationale." },
    { word: "Sénat", meaning: "Senate", reading: "say-na", example_sentence: "Le Sénat français." },
    { word: "Élection", meaning: "Election", reading: "ay-lek-syoh", example_sentence: "Les élections présidentielles." },
    { word: "Vote", meaning: "Vote", reading: "voht", example_sentence: "Le droit de vote." },
    { word: "Voter", meaning: "To vote", reading: "voh-tay", example_sentence: "Voter aux élections." },
    { word: "Électeur", meaning: "Voter / Elector", reading: "ay-lek-tur", example_sentence: "Les électeurs français." },
    { word: "Candidat", meaning: "Candidate", reading: "kahn-dee-da", example_sentence: "Un candidat à la présidence." },
    { word: "Campagne", meaning: "Campaign", reading: "kahm-panyuh", example_sentence: "La campagne électorale." },
    { word: "Parti", meaning: "Party (political)", reading: "par-tee", example_sentence: "Un parti politique." },
    { word: "Gauche", meaning: "Left (political)", reading: "gohsh", example_sentence: "La gauche française." },
    { word: "Droite", meaning: "Right (political)", reading: "drwat", example_sentence: "La droite conservatrice." },
    { word: "Centre", meaning: "Center (political)", reading: "sahn-truh", example_sentence: "Le centre politique." },
    { word: "Extrême", meaning: "Extreme", reading: "eks-trem", example_sentence: "L'extrême droite." },
    { word: "Conservateur", meaning: "Conservative", reading: "kohn-ser-va-tur", example_sentence: "Un parti conservateur." },
    { word: "Progressiste", meaning: "Progressive", reading: "proh-gre-seest", example_sentence: "Une politique progressiste." },
    { word: "Libéral", meaning: "Liberal", reading: "lee-bay-ral", example_sentence: "Un libéral économique." },
    { word: "Socialiste", meaning: "Socialist", reading: "soh-sya-leest", example_sentence: "Le parti socialiste." },
    { word: "Communiste", meaning: "Communist", reading: "koh-moo-neest", example_sentence: "Le parti communiste." },
    { word: "Écologiste", meaning: "Environmentalist", reading: "ay-koh-loh-zheest", example_sentence: "Un parti écologiste." },
    { word: "Citoyen", meaning: "Citizen", reading: "see-twa-ya", example_sentence: "Un citoyen français." },
    { word: "Citoyenneté", meaning: "Citizenship", reading: "see-twa-yen-tay", example_sentence: "La citoyenneté française." },
    { word: "Droit", meaning: "Right / Law", reading: "drwa", example_sentence: "Les droits de l'homme." },
    { word: "Devoir", meaning: "Duty", reading: "duh-vwahr", example_sentence: "Les devoirs civiques." },
    { word: "Loi", meaning: "Law", reading: "lwa", example_sentence: "Une nouvelle loi." },
    { word: "Constitution", meaning: "Constitution", reading: "kohn-stee-too-syoh", example_sentence: "La Constitution française." },
    { word: "Justice", meaning: "Justice", reading: "zhoos-tees", example_sentence: "Le système de justice." },
    { word: "Tribunal", meaning: "Court / Tribunal", reading: "tree-boo-nal", example_sentence: "Le tribunal de grande instance." },
    { word: "Juge", meaning: "Judge", reading: "zhoozh", example_sentence: "Un juge impartial." },
    { word: "Avocat", meaning: "Lawyer", reading: "a-voh-ka", example_sentence: "Un avocat de la défense." },
    { word: "Procès", meaning: "Trial", reading: "proh-say", example_sentence: "Le procès a commencé." },
    { word: "Police", meaning: "Police", reading: "poh-lees", example_sentence: "La police nationale." },
    { word: "Sécurité", meaning: "Security / Safety", reading: "say-koo-ree-tay", example_sentence: "La sécurité publique." },
    { word: "Ordre", meaning: "Order", reading: "or-druh", example_sentence: "L'ordre public." },
    { word: "Manifestation", meaning: "Demonstration / Protest", reading: "ma-nee-fes-ta-syoh", example_sentence: "Une manifestation pacifique." },
    { word: "Grève", meaning: "Strike", reading: "grev", example_sentence: "Une grève générale." },
    { word: "Syndicat", meaning: "Union / Trade union", reading: "san-dee-ka", example_sentence: "Un syndicat de travailleurs." },
    { word: "Réforme", meaning: "Reform", reading: "ray-form", example_sentence: "Une réforme sociale." },
    { word: "Révolution", meaning: "Revolution", reading: "ray-voh-loo-syoh", example_sentence: "La Révolution française." },
    { word: "Crise", meaning: "Crisis", reading: "kreez", example_sentence: "Une crise politique." },
    { word: "Conflit", meaning: "Conflict", reading: "kohn-flee", example_sentence: "Un conflit d'intérêts." },
    { word: "Guerre", meaning: "War", reading: "ger", example_sentence: "La guerre mondiale." },
    { word: "Paix", meaning: "Peace", reading: "pay", example_sentence: "La paix mondiale." },
    { word: "Traité", meaning: "Treaty", reading: "tray-tay", example_sentence: "Un traité de paix." },
    { word: "Alliance", meaning: "Alliance", reading: "a-lyahns", example_sentence: "Une alliance stratégique." },
    { word: "Diplomatie", meaning: "Diplomacy", reading: "dee-ploh-ma-see", example_sentence: "La diplomatie française." },
    { word: "Ambassade", meaning: "Embassy", reading: "ahm-ba-sad", example_sentence: "L'ambassade de France." },
    { word: "Ambassadeur", meaning: "Ambassador", reading: "ahm-ba-sa-dur", example_sentence: "L'ambassadeur français." },
    { word: "International", meaning: "International", reading: "an-ter-na-syoh-nal", example_sentence: "Les relations internationales." },
    { word: "Mondial", meaning: "World / Global", reading: "mohn-dyal", example_sentence: "Une crise mondiale." },
    { word: "Européen", meaning: "European", reading: "uh-roh-pay-a", example_sentence: "L'Union européenne." },
    { word: "Immigration", meaning: "Immigration", reading: "ee-mee-gra-syoh", example_sentence: "La politique d'immigration." },
    { word: "Intégration", meaning: "Integration", reading: "an-tay-gra-syoh", example_sentence: "L'intégration sociale." },
    { word: "Discrimination", meaning: "Discrimination", reading: "dees-kree-mee-na-syoh", example_sentence: "La discrimination raciale." },
    { word: "Égalité", meaning: "Equality", reading: "ay-ga-lee-tay", example_sentence: "L'égalité des chances." },
    { word: "Inégalité", meaning: "Inequality", reading: "ee-nay-ga-lee-tay", example_sentence: "Les inégalités sociales." },
    { word: "Solidarité", meaning: "Solidarity", reading: "soh-lee-da-ree-tay", example_sentence: "La solidarité nationale." },
    { word: "Fraternité", meaning: "Fraternity / Brotherhood", reading: "fra-ter-nee-tay", example_sentence: "Liberté, égalité, fraternité." },
    { word: "Laïcité", meaning: "Secularism", reading: "la-ee-see-tay", example_sentence: "La laïcité française." },
    { word: "Religion", meaning: "Religion", reading: "ruh-lee-zhyoh", example_sentence: "La liberté de religion." },
    { word: "Minorité", meaning: "Minority", reading: "mee-noh-ree-tay", example_sentence: "Une minorité ethnique." },
    { word: "Majorité", meaning: "Majority", reading: "ma-zhoh-ree-tay", example_sentence: "La majorité parlementaire." },
    { word: "Opposition", meaning: "Opposition", reading: "oh-poh-zee-syoh", example_sentence: "L'opposition politique." },
    { word: "Pouvoir", meaning: "Power", reading: "poo-vwahr", example_sentence: "Le pouvoir exécutif." },
    { word: "Autorité", meaning: "Authority", reading: "oh-toh-ree-tay", example_sentence: "L'autorité de l'État." },
    { word: "Souveraineté", meaning: "Sovereignty", reading: "soo-vuh-ren-tay", example_sentence: "La souveraineté nationale." },
    { word: "Indépendance", meaning: "Independence", reading: "an-day-pahn-dahns", example_sentence: "L'indépendance du pays." },
    { word: "Autonomie", meaning: "Autonomy", reading: "oh-toh-noh-mee", example_sentence: "L'autonomie régionale." },
    { word: "Fédération", meaning: "Federation", reading: "fay-day-ra-syoh", example_sentence: "Une fédération d'États." },
    { word: "Province", meaning: "Province", reading: "proh-vans", example_sentence: "Les provinces françaises." },
    { word: "Région", meaning: "Region", reading: "ray-zhyoh", example_sentence: "La région Île-de-France." },
    { word: "Commune", meaning: "Municipality / Commune", reading: "koh-moon", example_sentence: "La commune de Paris." },
    { word: "Maire", meaning: "Mayor", reading: "mer", example_sentence: "Le maire de la ville." },
    { word: "Conseil", meaning: "Council", reading: "kohn-say", example_sentence: "Le conseil municipal." },
    { word: "Administration", meaning: "Administration", reading: "ad-mee-nees-tra-syoh", example_sentence: "L'administration publique." },
    { word: "Fonctionnaire", meaning: "Civil servant", reading: "fohnk-syoh-ner", example_sentence: "Un fonctionnaire d'État." },
    { word: "Service public", meaning: "Public service", reading: "ser-vees poo-bleek", example_sentence: "Le service public français." },
    { word: "Budget", meaning: "Budget", reading: "boo-zhay", example_sentence: "Le budget de l'État." },
    { word: "Impôt", meaning: "Tax", reading: "am-poh", example_sentence: "Payer ses impôts." },
    { word: "Taxe", meaning: "Tax / Duty", reading: "taks", example_sentence: "Une taxe sur la valeur ajoutée." },
    { word: "Économie", meaning: "Economy", reading: "ay-koh-noh-mee", example_sentence: "L'économie française." },
    { word: "Chômage", meaning: "Unemployment", reading: "shoh-mazh", example_sentence: "Le taux de chômage." },
    { word: "Emploi", meaning: "Employment / Job", reading: "ahm-plwa", example_sentence: "La création d'emplois." },
    { word: "Retraite", meaning: "Retirement / Pension", reading: "ruh-tret", example_sentence: "L'âge de la retraite." },
    { word: "Santé", meaning: "Health", reading: "sahn-tay", example_sentence: "Le système de santé." },
    { word: "Éducation", meaning: "Education", reading: "ay-doo-ka-syoh", example_sentence: "Le ministère de l'Éducation." }
];

const m25_traps = [
    { trap: "In France, you can openly discuss politics at dinner parties without any social consequences.", correctVersion: "While political discussion is common in France, it can be passionate and divisive. Tact and respect are still important, especially with new acquaintances.", explanation: "French people are politically engaged, but heated debates can strain relationships. Know your audience." },
    { trap: "'Gauche' and 'Droite' in French politics mean the same as 'Left' and 'Right' in American politics.", correctVersion: "French political spectrum is different. The French 'center-right' would be considered left-wing in the US. Political labels don't translate directly.", explanation: "French politics has a different Overton window. What's 'centrist' in France might be 'socialist' in America." },
    { trap: "French 'laïcité' is the same as American 'separation of church and state'.", correctVersion: "'Laïcité' is more assertive than American secularism. It actively removes religion from public space, not just separates institutions.", explanation: "Laïcité is a core French value that goes beyond mere separation. It's about keeping public space neutral." }
];

// MODULE 26: Economy & Business
const m26_items = [
    { word: "Entreprise", meaning: "Company / Business", reading: "ahn-truh-preez", example_sentence: "Une grande entreprise." },
    { word: "Société", meaning: "Company / Society", reading: "soh-syay-tay", example_sentence: "Une société anonyme." },
    { word: "Compagnie", meaning: "Company", reading: "kohm-pa-nyee", example_sentence: "Une compagnie aérienne." },
    { word: "Firme", meaning: "Firm", reading: "feerm", example_sentence: "Une firme internationale." },
    { word: "Commerce", meaning: "Commerce / Trade", reading: "koh-mers", example_sentence: "Le commerce international." },
    { word: "Affaires", meaning: "Business", reading: "a-fer", example_sentence: "Un homme d'affaires." },
    { word: "Industrie", meaning: "Industry", reading: "an-doos-tree", example_sentence: "L'industrie automobile." },
    { word: "Secteur", meaning: "Sector", reading: "sek-tur", example_sentence: "Le secteur privé." },
    { word: "Marché", meaning: "Market", reading: "mar-shay", example_sentence: "Le marché boursier." },
    { word: "Concurrence", meaning: "Competition", reading: "kohn-koo-rahns", example_sentence: "La concurrence est forte." },
    { word: "Concurrent", meaning: "Competitor", reading: "kohn-koo-rah", example_sentence: "Un concurrent direct." },
    { word: "Client", meaning: "Client / Customer", reading: "klee-ah", example_sentence: "Un client fidèle." },
    { word: "Clientèle", meaning: "Clientele / Customers", reading: "klee-ahn-tel", example_sentence: "Une clientèle variée." },
    { word: "Fournisseur", meaning: "Supplier", reading: "foor-nee-sur", example_sentence: "Un fournisseur fiable." },
    { word: "Partenaire", meaning: "Partner", reading: "par-tuh-ner", example_sentence: "Un partenaire commercial." },
    { word: "Contrat", meaning: "Contract", reading: "kohn-tra", example_sentence: "Signer un contrat." },
    { word: "Accord", meaning: "Agreement", reading: "a-kor", example_sentence: "Un accord commercial." },
    { word: "Négociation", meaning: "Negotiation", reading: "nay-goh-sya-syoh", example_sentence: "Une négociation difficile." },
    { word: "Négocier", meaning: "To negotiate", reading: "nay-goh-syay", example_sentence: "Négocier un prix." },
    { word: "Vendre", meaning: "To sell", reading: "vahn-druh", example_sentence: "Vendre un produit." },
    { word: "Vente", meaning: "Sale", reading: "vahnt", example_sentence: "Les ventes augmentent." },
    { word: "Vendeur", meaning: "Seller / Salesperson", reading: "vahn-dur", example_sentence: "Un vendeur expérimenté." },
    { word: "Acheter", meaning: "To buy", reading: "ash-tay", example_sentence: "Acheter en gros." },
    { word: "Achat", meaning: "Purchase", reading: "a-sha", example_sentence: "Un achat important." },
    { word: "Acheteur", meaning: "Buyer", reading: "ash-tur", example_sentence: "Un acheteur potentiel." },
    { word: "Prix", meaning: "Price", reading: "pree", example_sentence: "Le prix du marché." },
    { word: "Coût", meaning: "Cost", reading: "koo", example_sentence: "Le coût de production." },
    { word: "Tarif", meaning: "Rate / Price", reading: "ta-reef", example_sentence: "Le tarif horaire." },
    { word: "Remise", meaning: "Discount", reading: "ruh-meez", example_sentence: "Une remise de 20%." },
    { word: "Promotion", meaning: "Promotion / Special offer", reading: "proh-moh-syoh", example_sentence: "Une promotion exceptionnelle." },
    { word: "Offre", meaning: "Offer", reading: "oh-fruh", example_sentence: "Une offre spéciale." },
    { word: "Demande", meaning: "Demand / Request", reading: "duh-mahnd", example_sentence: "L'offre et la demande." },
    { word: "Produit", meaning: "Product", reading: "proh-dwee", example_sentence: "Un nouveau produit." },
    { word: "Service", meaning: "Service", reading: "ser-vees", example_sentence: "Un service de qualité." },
    { word: "Marchandise", meaning: "Merchandise / Goods", reading: "mar-shahn-deez", example_sentence: "Des marchandises importées." },
    { word: "Stock", meaning: "Stock / Inventory", reading: "stohk", example_sentence: "Gérer le stock." },
    { word: "Livraison", meaning: "Delivery", reading: "lee-vray-zoh", example_sentence: "La livraison gratuite." },
    { word: "Commande", meaning: "Order", reading: "koh-mahnd", example_sentence: "Passer une commande." },
    { word: "Facture", meaning: "Invoice / Bill", reading: "fak-toor", example_sentence: "Envoyer une facture." },
    { word: "Paiement", meaning: "Payment", reading: "pay-mah", example_sentence: "Le paiement en ligne." },
    { word: "Crédit", meaning: "Credit", reading: "kray-dee", example_sentence: "Acheter à crédit." },
    { word: "Dette", meaning: "Debt", reading: "det", example_sentence: "Rembourser une dette." },
    { word: "Prêt", meaning: "Loan", reading: "pray", example_sentence: "Demander un prêt." },
    { word: "Emprunt", meaning: "Loan / Borrowing", reading: "ahm-pra", example_sentence: "Un emprunt bancaire." },
    { word: "Investissement", meaning: "Investment", reading: "an-ves-tees-mah", example_sentence: "Un bon investissement." },
    { word: "Investir", meaning: "To invest", reading: "an-ves-teer", example_sentence: "Investir dans l'immobilier." },
    { word: "Capital", meaning: "Capital", reading: "ka-pee-tal", example_sentence: "Le capital de l'entreprise." },
    { word: "Bénéfice", meaning: "Profit / Benefit", reading: "bay-nay-fees", example_sentence: "Réaliser un bénéfice." },
    { word: "Profit", meaning: "Profit", reading: "proh-fee", example_sentence: "Augmenter les profits." },
    { word: "Perte", meaning: "Loss", reading: "pert", example_sentence: "Subir une perte." },
    { word: "Déficit", meaning: "Deficit", reading: "day-fee-see", example_sentence: "Un déficit budgétaire." },
    { word: "Excédent", meaning: "Surplus", reading: "ek-say-dah", example_sentence: "Un excédent commercial." },
    { word: "Chiffre d'affaires", meaning: "Turnover / Revenue", reading: "shee-fruh da-fer", example_sentence: "Le chiffre d'affaires annuel." },
    { word: "Revenu", meaning: "Income / Revenue", reading: "ruh-vuh-noo", example_sentence: "Les revenus de l'entreprise." },
    { word: "Dépense", meaning: "Expense / Expenditure", reading: "day-pahns", example_sentence: "Réduire les dépenses." },
    { word: "Comptabilité", meaning: "Accounting", reading: "kohm-ta-bee-lee-tay", example_sentence: "La comptabilité de l'entreprise." },
    { word: "Comptable", meaning: "Accountant", reading: "kohm-ta-bluh", example_sentence: "Un comptable agréé." },
    { word: "Bilan", meaning: "Balance sheet / Assessment", reading: "bee-lah", example_sentence: "Le bilan financier." },
    { word: "Rapport", meaning: "Report", reading: "ra-por", example_sentence: "Un rapport annuel." },
    { word: "Stratégie", meaning: "Strategy", reading: "stra-tay-zhee", example_sentence: "Une stratégie commerciale." },
    { word: "Objectif", meaning: "Objective / Goal", reading: "ob-zhek-teef", example_sentence: "Atteindre ses objectifs." },
    { word: "Projet", meaning: "Project", reading: "proh-zhay", example_sentence: "Un projet ambitieux." },
    { word: "Plan", meaning: "Plan", reading: "plah", example_sentence: "Un plan d'action." },
    { word: "Gestion", meaning: "Management", reading: "zhes-tyoh", example_sentence: "La gestion d'entreprise." },
    { word: "Gérer", meaning: "To manage", reading: "zhay-ray", example_sentence: "Gérer une équipe." },
    { word: "Gestionnaire", meaning: "Manager", reading: "zhes-tyoh-ner", example_sentence: "Un gestionnaire efficace." },
    { word: "Directeur", meaning: "Director / Manager", reading: "dee-rek-tur", example_sentence: "Le directeur général." },
    { word: "Direction", meaning: "Management / Direction", reading: "dee-rek-syoh", example_sentence: "La direction de l'entreprise." },
    { word: "Patron", meaning: "Boss", reading: "pa-troh", example_sentence: "Le patron de l'entreprise." },
    { word: "Employé", meaning: "Employee", reading: "ahm-plwa-yay", example_sentence: "Un employé dévoué." },
    { word: "Employeur", meaning: "Employer", reading: "ahm-plwa-yur", example_sentence: "Un bon employeur." },
    { word: "Personnel", meaning: "Staff / Personnel", reading: "per-soh-nel", example_sentence: "Le personnel de l'entreprise." },
    { word: "Équipe", meaning: "Team", reading: "ay-keep", example_sentence: "Une équipe soudée." },
    { word: "Collègue", meaning: "Colleague", reading: "koh-leg", example_sentence: "Un collègue sympathique." },
    { word: "Salaire", meaning: "Salary / Wage", reading: "sa-ler", example_sentence: "Un bon salaire." },
    { word: "Rémunération", meaning: "Remuneration / Pay", reading: "ray-moo-nay-ra-syoh", example_sentence: "La rémunération du travail." },
    { word: "Prime", meaning: "Bonus", reading: "preem", example_sentence: "Une prime de fin d'année." },
    { word: "Augmentation", meaning: "Raise / Increase", reading: "ohg-mahn-ta-syoh", example_sentence: "Demander une augmentation." },
    { word: "Licenciement", meaning: "Dismissal / Layoff", reading: "lee-sahn-see-mah", example_sentence: "Un licenciement économique." },
    { word: "Démission", meaning: "Resignation", reading: "day-mee-syoh", example_sentence: "Donner sa démission." },
    { word: "Embauche", meaning: "Hiring", reading: "ahm-bohsh", example_sentence: "L'embauche de nouveaux employés." },
    { word: "Recrutement", meaning: "Recruitment", reading: "ruh-kroot-mah", example_sentence: "Le recrutement de talents." },
    { word: "Formation", meaning: "Training", reading: "for-ma-syoh", example_sentence: "Une formation professionnelle." },
    { word: "Compétence", meaning: "Skill / Competence", reading: "kohm-pay-tahns", example_sentence: "Des compétences techniques." },
    { word: "Qualification", meaning: "Qualification", reading: "ka-lee-fee-ka-syoh", example_sentence: "Une qualification professionnelle." },
    { word: "Expérience", meaning: "Experience", reading: "eks-pay-ryahns", example_sentence: "Avoir de l'expérience." },
    { word: "Carrière", meaning: "Career", reading: "ka-ryer", example_sentence: "Une belle carrière." },
    { word: "Poste", meaning: "Position / Job", reading: "pohst", example_sentence: "Un poste à responsabilités." },
    { word: "Fonction", meaning: "Function / Position", reading: "fohnk-syoh", example_sentence: "Les fonctions du directeur." },
    { word: "Tâche", meaning: "Task", reading: "tash", example_sentence: "Accomplir une tâche." },
    { word: "Responsabilité", meaning: "Responsibility", reading: "res-pohn-sa-bee-lee-tay", example_sentence: "Avoir des responsabilités." },
    { word: "Réunion", meaning: "Meeting", reading: "ray-oo-nyoh", example_sentence: "Une réunion importante." },
    { word: "Rendez-vous", meaning: "Appointment / Meeting", reading: "rahn-day-voo", example_sentence: "Prendre un rendez-vous." },
    { word: "Présentation", meaning: "Presentation", reading: "pray-zahn-ta-syoh", example_sentence: "Faire une présentation." },
    { word: "Communication", meaning: "Communication", reading: "koh-moo-nee-ka-syoh", example_sentence: "La communication interne." },
    { word: "Marketing", meaning: "Marketing", reading: "mar-keh-teeng", example_sentence: "Une stratégie marketing." },
    { word: "Publicité", meaning: "Advertising", reading: "poo-blee-see-tay", example_sentence: "Une campagne de publicité." },
    { word: "Marque", meaning: "Brand", reading: "mark", example_sentence: "Une marque connue." },
    { word: "Image de marque", meaning: "Brand image", reading: "ee-mazh duh mark", example_sentence: "Soigner son image de marque." },
    { word: "Concurrentiel", meaning: "Competitive", reading: "kohn-koo-rahn-syel", example_sentence: "Un prix concurrentiel." }
];

const m26_traps = [
    { trap: "French business culture is very informal and casual like in Silicon Valley.", correctVersion: "French business culture is formal. Use 'vous', dress professionally, and respect hierarchy. Informality comes only after relationships are established.", explanation: "France values formality in professional settings. First-name basis and casual dress are earned, not assumed." },
    { trap: "'Entreprise' and 'Société' are completely interchangeable in French.", correctVersion: "While both mean 'company', 'société' often implies a legal entity (like 'corporation'), while 'entreprise' is more general. Context matters.", explanation: "Legal and business French has subtle distinctions. 'Société anonyme' (SA) is a specific legal structure." },
    { trap: "In France, business lunches are quick working meals like in America.", correctVersion: "French business lunches are long (1-2 hours) and relationship-building. Discussing business immediately is considered rude. Build rapport first.", explanation: "The French lunch is sacred. It's about building trust and relationships, not just closing deals." }
];

// MODULE 27: Culture & Arts
const m27_items = [
    { word: "Culture", meaning: "Culture", reading: "kool-toor", example_sentence: "La culture française." },
    { word: "Culturel", meaning: "Cultural", reading: "kool-too-rel", example_sentence: "Un événement culturel." },
    { word: "Art", meaning: "Art", reading: "ar", example_sentence: "L'art contemporain." },
    { word: "Artiste", meaning: "Artist", reading: "ar-teest", example_sentence: "Un artiste talentueux." },
    { word: "Artistique", meaning: "Artistic", reading: "ar-tees-teek", example_sentence: "Une création artistique." },
    { word: "Peinture", meaning: "Painting", reading: "pan-toor", example_sentence: "Une peinture à l'huile." },
    { word: "Peintre", meaning: "Painter", reading: "pantr", example_sentence: "Un peintre impressionniste." },
    { word: "Peindre", meaning: "To paint", reading: "pan-druh", example_sentence: "Peindre un tableau." },
    { word: "Tableau", meaning: "Painting / Picture", reading: "ta-bloh", example_sentence: "Un tableau de Monet." },
    { word: "Toile", meaning: "Canvas", reading: "twal", example_sentence: "Peindre sur toile." },
    { word: "Sculpture", meaning: "Sculpture", reading: "skool-toor", example_sentence: "Une sculpture en bronze." },
    { word: "Sculpteur", meaning: "Sculptor", reading: "skool-tur", example_sentence: "Un sculpteur renommé." },
    { word: "Sculpter", meaning: "To sculpt", reading: "skool-tay", example_sentence: "Sculpter le marbre." },
    { word: "Statue", meaning: "Statue", reading: "sta-too", example_sentence: "Une statue antique." },
    { word: "Dessin", meaning: "Drawing", reading: "duh-sa", example_sentence: "Un dessin au crayon." },
    { word: "Dessiner", meaning: "To draw", reading: "duh-see-nay", example_sentence: "Dessiner un portrait." },
    { word: "Photographie", meaning: "Photography", reading: "foh-toh-gra-fee", example_sentence: "La photographie artistique." },
    { word: "Photographe", meaning: "Photographer", reading: "foh-toh-graf", example_sentence: "Un photographe professionnel." },
    { word: "Photographier", meaning: "To photograph", reading: "foh-toh-gra-fyay", example_sentence: "Photographier un paysage." },
    { word: "Image", meaning: "Image / Picture", reading: "ee-mazh", example_sentence: "Une belle image." },
    { word: "Musée", meaning: "Museum", reading: "moo-zay", example_sentence: "Le musée du Louvre." },
    { word: "Galerie", meaning: "Gallery", reading: "ga-luh-ree", example_sentence: "Une galerie d'art." },
    { word: "Exposition", meaning: "Exhibition", reading: "eks-poh-zee-syoh", example_sentence: "Une exposition temporaire." },
    { word: "Collection", meaning: "Collection", reading: "koh-lek-syoh", example_sentence: "Une collection privée." },
    { word: "Musique", meaning: "Music", reading: "moo-zeek", example_sentence: "La musique classique." },
    { word: "Musicien", meaning: "Musician", reading: "moo-zee-sya", example_sentence: "Un musicien virtuose." },
    { word: "Musical", meaning: "Musical", reading: "moo-zee-kal", example_sentence: "Un instrument musical." },
    { word: "Chanson", meaning: "Song", reading: "shah-soh", example_sentence: "Une chanson populaire." },
    { word: "Chanter", meaning: "To sing", reading: "shah-tay", example_sentence: "Chanter une mélodie." },
    { word: "Chanteur", meaning: "Singer", reading: "shah-tur", example_sentence: "Un chanteur célèbre." },
    { word: "Orchestre", meaning: "Orchestra", reading: "or-kes-truh", example_sentence: "Un orchestre symphonique." },
    { word: "Concert", meaning: "Concert", reading: "kohn-ser", example_sentence: "Assister à un concert." },
    { word: "Opéra", meaning: "Opera", reading: "oh-pay-ra", example_sentence: "Un opéra de Mozart." },
    { word: "Ballet", meaning: "Ballet", reading: "ba-lay", example_sentence: "Un ballet classique." },
    { word: "Danse", meaning: "Dance", reading: "dahns", example_sentence: "La danse contemporaine." },
    { word: "Danser", meaning: "To dance", reading: "dahn-say", example_sentence: "Danser le tango." },
    { word: "Danseur", meaning: "Dancer", reading: "dahn-sur", example_sentence: "Un danseur professionnel." },
    { word: "Théâtre", meaning: "Theater", reading: "tay-ah-truh", example_sentence: "Le théâtre français." },
    { word: "Pièce", meaning: "Play / Piece", reading: "pyes", example_sentence: "Une pièce de Molière." },
    { word: "Acteur", meaning: "Actor", reading: "ak-tur", example_sentence: "Un acteur talentueux." },
    { word: "Actrice", meaning: "Actress", reading: "ak-trees", example_sentence: "Une actrice célèbre." },
    { word: "Jouer", meaning: "To play / Act", reading: "zhoo-ay", example_sentence: "Jouer un rôle." },
    { word: "Rôle", meaning: "Role", reading: "rohl", example_sentence: "Le rôle principal." },
    { word: "Scène", meaning: "Scene / Stage", reading: "sen", example_sentence: "Monter sur scène." },
    { word: "Spectacle", meaning: "Show / Performance", reading: "spek-ta-kluh", example_sentence: "Un spectacle magnifique." },
    { word: "Spectateur", meaning: "Spectator / Viewer", reading: "spek-ta-tur", example_sentence: "Les spectateurs applaudissent." },
    { word: "Public", meaning: "Audience / Public", reading: "poo-bleek", example_sentence: "Le public est enthousiaste." },
    { word: "Cinéma", meaning: "Cinema / Movie theater", reading: "see-nay-ma", example_sentence: "Aller au cinéma." },
    { word: "Film", meaning: "Film / Movie", reading: "feelm", example_sentence: "Un film français." },
    { word: "Réalisateur", meaning: "Director (film)", reading: "ray-a-lee-za-tur", example_sentence: "Un réalisateur célèbre." },
    { word: "Metteur en scène", meaning: "Director (theater)", reading: "meh-tur ahn sen", example_sentence: "Le metteur en scène du spectacle." },
    { word: "Scénario", meaning: "Screenplay / Script", reading: "say-na-ryoh", example_sentence: "Écrire un scénario." },
    { word: "Tournage", meaning: "Filming / Shooting", reading: "toor-nazh", example_sentence: "Le tournage du film." },
    { word: "Festival", meaning: "Festival", reading: "fes-tee-val", example_sentence: "Le Festival de Cannes." },
    { word: "Architecture", meaning: "Architecture", reading: "ar-shee-tek-toor", example_sentence: "L'architecture gothique." },
    { word: "Architecte", meaning: "Architect", reading: "ar-shee-tekt", example_sentence: "Un architecte renommé." },
    { word: "Monument", meaning: "Monument", reading: "moh-noo-mah", example_sentence: "Un monument historique." },
    { word: "Patrimoine", meaning: "Heritage", reading: "pa-tree-mwan", example_sentence: "Le patrimoine culturel." },
    { word: "Tradition", meaning: "Tradition", reading: "tra-dee-syoh", example_sentence: "Une tradition ancienne." },
    { word: "Traditionnel", meaning: "Traditional", reading: "tra-dee-syoh-nel", example_sentence: "Un costume traditionnel." },
    { word: "Folklore", meaning: "Folklore", reading: "folk-lor", example_sentence: "Le folklore régional." },
    { word: "Légende", meaning: "Legend", reading: "lay-zhahnd", example_sentence: "Une légende populaire." },
    { word: "Mythe", meaning: "Myth", reading: "meet", example_sentence: "Un mythe grec." },
    { word: "Mythologie", meaning: "Mythology", reading: "mee-toh-loh-zhee", example_sentence: "La mythologie romaine." },
    { word: "Conte", meaning: "Tale / Story", reading: "kohnt", example_sentence: "Un conte de fées." },
    { word: "Fable", meaning: "Fable", reading: "fa-bluh", example_sentence: "Les fables de La Fontaine." },
    { word: "Proverbe", meaning: "Proverb", reading: "proh-verb", example_sentence: "Un proverbe français." },
    { word: "Expression", meaning: "Expression", reading: "eks-pray-syoh", example_sentence: "Une expression idiomatique." },
    { word: "Langue", meaning: "Language / Tongue", reading: "lahng", example_sentence: "La langue française." },
    { word: "Linguistique", meaning: "Linguistics", reading: "lan-gwees-teek", example_sentence: "La linguistique moderne." },
    { word: "Dialecte", meaning: "Dialect", reading: "dya-lekt", example_sentence: "Un dialecte régional." },
    { word: "Accent", meaning: "Accent", reading: "ak-sah", example_sentence: "Un accent du sud." },
    { word: "Prononciation", meaning: "Pronunciation", reading: "proh-nohn-sya-syoh", example_sentence: "La prononciation correcte." },
    { word: "Gastronomie", meaning: "Gastronomy", reading: "gas-troh-noh-mee", example_sentence: "La gastronomie française." },
    { word: "Cuisine", meaning: "Cuisine / Kitchen", reading: "kwee-zeen", example_sentence: "La cuisine régionale." },
    { word: "Cuisinier", meaning: "Cook / Chef", reading: "kwee-zee-nyay", example_sentence: "Un cuisinier talentueux." },
    { word: "Chef", meaning: "Chef", reading: "shef", example_sentence: "Un chef étoilé." },
    { word: "Recette", meaning: "Recipe", reading: "ruh-set", example_sentence: "Une recette traditionnelle." },
    { word: "Plat", meaning: "Dish", reading: "pla", example_sentence: "Un plat typique." },
    { word: "Spécialité", meaning: "Specialty", reading: "spay-sya-lee-tay", example_sentence: "Une spécialité locale." },
    { word: "Vin", meaning: "Wine", reading: "va", example_sentence: "Un bon vin français." },
    { word: "Fromage", meaning: "Cheese", reading: "froh-mazh", example_sentence: "Un fromage de chèvre." },
    { word: "Mode", meaning: "Fashion", reading: "mohd", example_sentence: "La mode parisienne." },
    { word: "Couture", meaning: "Fashion / Sewing", reading: "koo-toor", example_sentence: "La haute couture." },
    { word: "Couturier", meaning: "Fashion designer", reading: "koo-too-ryay", example_sentence: "Un couturier célèbre." },
    { word: "Défilé", meaning: "Fashion show / Parade", reading: "day-fee-lay", example_sentence: "Un défilé de mode." },
    { word: "Style", meaning: "Style", reading: "steel", example_sentence: "Un style unique." },
    { word: "Élégance", meaning: "Elegance", reading: "ay-lay-gahns", example_sentence: "L'élégance française." },
    { word: "Luxe", meaning: "Luxury", reading: "looks", example_sentence: "Le luxe à la française." },
    { word: "Prestige", meaning: "Prestige", reading: "pres-teezh", example_sentence: "Une marque de prestige." },
    { word: "Raffinement", meaning: "Refinement", reading: "ra-feen-mah", example_sentence: "Le raffinement français." },
    { word: "Goût", meaning: "Taste", reading: "goo", example_sentence: "Le bon goût." },
    { word: "Esthétique", meaning: "Aesthetic", reading: "es-tay-teek", example_sentence: "Une esthétique moderne." },
    { word: "Beauté", meaning: "Beauty", reading: "boh-tay", example_sentence: "La beauté de l'art." },
    { word: "Harmonie", meaning: "Harmony", reading: "ar-moh-nee", example_sentence: "L'harmonie des couleurs." },
    { word: "Créativité", meaning: "Creativity", reading: "kray-a-tee-vee-tay", example_sentence: "La créativité artistique." },
    { word: "Inspiration", meaning: "Inspiration", reading: "an-spee-ra-syoh", example_sentence: "Trouver l'inspiration." },
    { word: "Œuvre d'art", meaning: "Work of art", reading: "uh-vruh dar", example_sentence: "Une œuvre d'art magistrale." },
    { word: "Chef-d'œuvre", meaning: "Masterpiece", reading: "shay-duh-vruh", example_sentence: "Un chef-d'œuvre de la peinture." },
    { word: "Talent", meaning: "Talent", reading: "ta-lah", example_sentence: "Un talent exceptionnel." }
];

const m27_traps = [
    { trap: "French people think American culture is superior and more modern.", correctVersion: "French people are proud of their culture and often view American culture as commercialized. They value their own cultural heritage deeply.", explanation: "Cultural pride is strong in France. Assuming American superiority will offend. Respect French culture." },
    { trap: "'Art' in French only refers to fine arts like painting and sculpture.", correctVersion: "'Art' in French has a broader meaning, including crafts, skills, and techniques. 'L'art de vivre' means 'the art of living'.", explanation: "French uses 'art' more broadly than English. It encompasses lifestyle and savoir-faire, not just visual arts." },
    { trap: "French cuisine is all about fancy, expensive restaurants.", correctVersion: "French cuisine values quality ingredients and technique at all levels. A simple bistro dish can be as respected as haute cuisine.", explanation: "French food culture prizes quality over price. A perfect baguette is as valued as a Michelin-starred meal." }
];

// Generate and save all three modules
const modules = [
    createModule('fr_b1_m25', 'B1 French - Module 25: Politics & Society', 25, m25_items, m25_traps),
    createModule('fr_b1_m26', 'B1 French - Module 26: Economy & Business', 26, m26_items, m26_traps),
    createModule('fr_b1_m27', 'B1 French - Module 27: Culture & Arts', 27, m27_items, m27_traps)
];

modules.forEach(module => {
    const outputPath = path.join(__dirname, `../firestore_data/${module.id}.json`);
    fs.writeFileSync(outputPath, JSON.stringify(module, null, 2));
    console.log(`✅ ${module.id} generated: ${module.vocabularyItems.length} words, ${module.liarGameData.culturalTraps.length} traps`);
});

console.log('\n🎯 All three modules generated successfully!');
