const fs = require('fs');
const path = require('path');

// Helper to fill up to 100 while keeping it unique and level appropriate
function completeModule(baseItems, moduleId, moduleName) {
    const seen = new Set(baseItems.map(i => i.word));
    const finalItems = [...baseItems];

    // Safety check for size
    if (finalItems.length >= 100) return finalItems.slice(0, 100);

    const fillerPool = {
        m4: [ // Travel direction extras
            { word: "Boussole", meaning: "Compass", reading: "boo-sohl", example_sentence: "Utilisez une boussole." },
            { word: "Sentier", meaning: "Path", reading: "sah-tyay", example_sentence: "Suivre le sentier." },
            { word: "Route", meaning: "Road", reading: "root", example_sentence: "La route est longue." },
            { word: "Autoroute", meaning: "Highway", reading: "oh-toh-root", example_sentence: "Prendre l'autoroute." }
        ],
        m5: [ // Work extras
            { word: "Ciseau", meaning: "Scissors", reading: "see-zoh", example_sentence: "Couper avec un ciseau." },
            { word: "Scotch", meaning: "Tape", reading: "skotch", example_sentence: "Coller avec du scotch." }
        ],
        m6: [ // Hobby extras
            { word: "Applaudir", meaning: "To applaud", reading: "a-ploh-deer", example_sentence: "Le public applaudit." },
            { word: "Siffler", meaning: "To whistle", reading: "see-flay", example_sentence: "Il siffle une mélodie." },
            { word: "Sourire", meaning: "To smile", reading: "soo-reer", example_sentence: "Elle sourit toujours." },
            { word: "Rire", meaning: "To laugh", reading: "reer", example_sentence: "C'est bon de rire." }
        ]
    };

    const extras = fillerPool[moduleId.split('_').pop()];
    if (extras) {
        for (const item of extras) {
            if (finalItems.length < 100 && !seen.has(item.word)) {
                finalItems.push(item);
                seen.add(item.word);
            }
        }
    }

    return finalItems;
}

// Data from previous turn manually refined to 100
const m4_items = completeModule([
    { word: "Voyage", meaning: "Travel / Trip", reading: "vwa-yazh", example_sentence: "Bon voyage !" },
    { word: "Aéroport", meaning: "Airport", reading: "a-ay-roh-por", example_sentence: "Je vais à l'aéroport." },
    { word: "Avion", meaning: "Airplane", reading: "a-vyoh", example_sentence: "L'avion décolle." },
    { word: "Gare", meaning: "Train station", reading: "gar", example_sentence: "Rendez-vous à la gare." },
    { word: "Train", meaning: "Train", reading: "trah", example_sentence: "Le train arrive." },
    { word: "Billet", meaning: "Ticket", reading: "bee-yeh", example_sentence: "J'ai mon billet." },
    { word: "Passeport", meaning: "Passport", reading: "pas-por", example_sentence: "Où est mon passeport ?" },
    { word: "Valise", meaning: "Suitcase", reading: "va-leez", example_sentence: "Ma valise est lourde." },
    { word: "Direction", meaning: "Direction", reading: "dee-rek-syoh", example_sentence: "Quelle est la direction ?" },
    { word: "Nord", meaning: "North", reading: "nor", example_sentence: "Le nord de la France." },
    { word: "Sud", meaning: "South", reading: "sood", example_sentence: "Le sud est chaud." },
    { word: "Est", meaning: "East", reading: "est", example_sentence: "L'est de l'Europe." },
    { word: "Ouest", meaning: "West", reading: "west", example_sentence: "L'ouest est beau." },
    { word: "Gauche", meaning: "Left", reading: "gohsh", example_sentence: "Tournez à gauche." },
    { word: "Droite", meaning: "Right", reading: "drwat", example_sentence: "C'est à droite." },
    { word: "Ticket", meaning: "Ticket (bus/metro)", reading: "tee-keh", example_sentence: "Un ticket de métro." },
    { word: "Métro", meaning: "Subway", reading: "may-troh", example_sentence: "Prends le métro." },
    { word: "Bus", meaning: "Bus", reading: "booss", example_sentence: "Le bus s'arrête ici." },
    { word: "Vélo", meaning: "Bicycle", reading: "vay-loh", example_sentence: "Je fais du vélo." },
    { word: "Voiture", meaning: "Car", reading: "vwa-toor", example_sentence: "Ma voiture est rouge." },
    { word: "Taxi", meaning: "Taxi", reading: "tak-see", example_sentence: "Appelez un taxi." },
    { word: "Bateau", meaning: "Boat", reading: "ba-toh", example_sentence: "Le bateau est sur l'eau." },
    { word: "Hélicoptère", meaning: "Helicopter", reading: "ay-lee-kop-ter", example_sentence: "Un vol en hélicoptère." },
    { word: "Hôtel", meaning: "Hotel", reading: "oh-tel", example_sentence: "Je cherche mon hôtel." },
    { word: "Réception", meaning: "Reception", reading: "ray-sep-syoh", example_sentence: "La réception est ouverte." },
    { word: "Chambre", meaning: "Room", reading: "shah-bruh", example_sentence: "Une chambre pour deux." },
    { word: "Sac à dos", meaning: "Backpack", reading: "sak a doh", example_sentence: "Mon sac à dos est bleu." },
    { word: "Carte de crédit", meaning: "Credit card", reading: "kart duh kray-dee", example_sentence: "Payer par carte de crédit." },
    { word: "Plan de ville", meaning: "City map", reading: "plah duh veel", example_sentence: "Un plan de Paris." },
    { word: "Rue", meaning: "Street", reading: "roo", example_sentence: "La rue est longue." },
    { word: "Avenue", meaning: "Avenue", reading: "a-vuh-noo", example_sentence: "Une belle avenue." },
    { word: "Place", meaning: "Square", reading: "plas", example_sentence: "La place du village." },
    { word: "Pont", meaning: "Bridge", reading: "poh", example_sentence: "Traversez le pont." },
    { word: "Feu rouge", meaning: "Traffic light", reading: "fuh roozh", example_sentence: "Stop au feu rouge." },
    { word: "Panneau", meaning: "Sign", reading: "pa-noh", example_sentence: "Regardez le panneau." },
    { word: "Près", meaning: "Near", reading: "preh", example_sentence: "C'est tout près." },
    { word: "Loin", meaning: "Far", reading: "lwah", example_sentence: "C'est trop loin." },
    { word: "Devant", meaning: "In front", reading: "duh-vah", example_sentence: "Attends-moi devant." },
    { word: "Derrière", meaning: "Behind", reading: "deh-ryer", example_sentence: "Regarde derrière toi." },
    { word: "Entre", meaning: "Between", reading: "ah-truh", example_sentence: "Entre toi et moi." },
    { word: "À côté de", meaning: "Next to", reading: "a koh-tay duh", example_sentence: "C'est à côté de la gare." },
    { word: "Tout droit", meaning: "Straight ahead", reading: "too drwa", example_sentence: "Allez tout droit." },
    { word: "Ici", meaning: "Here", reading: "ee-see", example_sentence: "Je suis ici." },
    { word: "Là-bas", meaning: "Over there", reading: "la bah", example_sentence: "C'est là-bas." },
    { word: "Partout", meaning: "Everywhere", reading: "par-too", example_sentence: "Il y a des fleurs partout." },
    { word: "Ailleurs", meaning: "Elsewhere", reading: "ah-yur", example_sentence: "Allons ailleurs." },
    { word: "Arriver", meaning: "To arrive", reading: "a-ree-vay", example_sentence: "Le train va arriver." },
    { word: "Partir", meaning: "To leave", reading: "par-teer", example_sentence: "Je dois partir." },
    { word: "Vendre", meaning: "To sell", reading: "vah-druh", example_sentence: "Il veut vendre son vélo." },
    { word: "Acheter", meaning: "To buy", reading: "ash-tay", example_sentence: "Acheter un billet." },
    { word: "Louer", meaning: "To rent", reading: "loo-way", example_sentence: "Louer une voiture." },
    { word: "Montagne", meaning: "Mountain", reading: "moh-tan-yuh", example_sentence: "La montagne est haute." },
    { word: "Mer", meaning: "Sea", reading: "mer", example_sentence: "J'aime la mer." },
    { word: "Plage", meaning: "Beach", reading: "plazh", example_sentence: "Allons à la plage." },
    { word: "Rivière", meaning: "River", reading: "ree-vyer", example_sentence: "L'eau de la rivière." },
    { word: "Forêt", meaning: "Forest", reading: "foh-ray", example_sentence: "Marcher dans la forêt." },
    { word: "Campagne", meaning: "Countryside", reading: "kah-pan-yuh", example_sentence: "La vie à la campagne." },
    { word: "Île", meaning: "Island", reading: "eel", example_sentence: "Une île déserte." },
    { word: "Lac", meaning: "Lake", reading: "lak", example_sentence: "Un lac calme." },
    { word: "Désert", meaning: "Desert", reading: "day-zer", example_sentence: "Le désert est sec." },
    { word: "Ciel", meaning: "Sky", reading: "syel", example_sentence: "Le ciel est bleu." },
    { word: "Soleil", meaning: "Sun", reading: "soh-lay", example_sentence: "Le soleil brille." },
    { word: "Lune", meaning: "Moon", reading: "loon", example_sentence: "La lune est pleine." },
    { word: "Étoile", meaning: "Star", reading: "ay-twal", example_sentence: "Regarde les étoiles." },
    { word: "Nuage", meaning: "Cloud", reading: "noo-azh", example_sentence: "Un gros nuage gris." },
    { word: "Pluie", meaning: "Rain", reading: "plwee", example_sentence: "J'aime la pluie." },
    { word: "Neige", meaning: "Snow", reading: "nezh", example_sentence: "Il y a de la neige." },
    { word: "Vent", meaning: "Wind", reading: "vah", example_sentence: "Le vent souffle." },
    { word: "Étranger", meaning: "Foreigner / Abroad", reading: "ay-trah-zhay", example_sentence: "Partir à l'étranger." },
    { word: "Langue", meaning: "Language", reading: "lah-guh", example_sentence: "Apprendre une langue." },
    { word: "Culture", meaning: "Culture", reading: "kool-toor", example_sentence: "Une culture différente." },
    { word: "Souvenir", meaning: "Memory /Souvenir", reading: "soo-vuh-neer", example_sentence: "Un bon souvenir." },
    { word: "Photos", meaning: "Photos", reading: "foh-toh", example_sentence: "Prendre des photos." },
    { word: "Appareil photo", meaning: "Camera", reading: "a-pa-ray foh-toh", example_sentence: "Mon appareil photo." },
    { word: "Aventure", meaning: "Adventure", reading: "a-vah-toor", example_sentence: "Une grande aventure." },
    { word: "Bagage", meaning: "Luggage", reading: "ba-gazh", example_sentence: "Enregistrez vos bagages." },
    { word: "Passager", meaning: "Passenger", reading: "pa-sa-zhay", example_sentence: "Un passager calme." },
    { word: "Pilote", meaning: "Pilote", reading: "pee-lot", example_sentence: "Le pilote parle." },
    { word: "Chauffeur", meaning: "Driver", reading: "shoh-fur", example_sentence: "Le chauffeur de taxi." },
    { word: "Retard", meaning: "Delay", reading: "ruh-tar", example_sentence: "Le train est en retard." },
    { word: "Annulation", meaning: "Cancellation", reading: "a-noo-la-syoh", example_sentence: "Une annulation de vol." },
    { word: "Départ", meaning: "Departure", reading: "day-par", example_sentence: "L'heure du départ." },
    { word: "Destination", meaning: "Destination", reading: "des-tee-na-syoh", example_sentence: "Quelle est votre destination ?" },
    { word: "Visite", meaning: "Visit", reading: "vee-zeet", example_sentence: "Une visite guidée." },
    { word: "Explorer", meaning: "To explore", reading: "ek-sploh-ray", example_sentence: "Explorer la ville." },
    { word: "Découvrir", meaning: "To discover", reading: "day-koo-vreer", example_sentence: "Découvrir de nouveaux lieux." },
    { word: "Traverser", meaning: "To cross", reading: "tra-ver-say", example_sentence: "Traverser la rue." },
    { word: "Marcher", meaning: "To walk", reading: "mar-shay", example_sentence: "J'aime marcher." },
    { word: "Conduire", meaning: "To drive", reading: "koh-dweer", example_sentence: "Savoir conduire." },
    { word: "Voler", meaning: "To fly", reading: "voh-lay", example_sentence: "L'oiseau vole." },
    { word: "Nager", meaning: "To swim", reading: "na-zhay", example_sentence: "Nager dans la mer." },
    { word: "Naviguer", meaning: "To navigate", reading: "na-vee-gay", example_sentence: "Naviguer sur internet." },
    { word: "Chercher", meaning: "To look for", reading: "sher-shay", example_sentence: "Je cherche ma clé." },
    { word: "Trouver", meaning: "To find", reading: "troo-vay", example_sentence: "J'ai trouvé mon chemin." },
    { word: "Paiement", meaning: "Payment", reading: "pay-mah", example_sentence: "Le paiement est fait." },
    { word: "Guichet", meaning: "Counter", reading: "gee-sheh", example_sentence: "Allez au guichet." },
    { word: "Boussole", meaning: "Compass", reading: "boo-sohl", example_sentence: "Utilisez une boussole." },
    { word: "Sentier", meaning: "Path", reading: "sah-tyay", example_sentence: "Suivre le sentier." },
    { word: "Route", meaning: "Road", reading: "root", example_sentence: "La route est longue." },
    { word: "Autoroute", meaning: "Highway", reading: "oh-toh-root", example_sentence: "Prendre l'autoroute." }
], 'fr_a1_m4');

const m5_items = completeModule([
    { word: "Travail", meaning: "Work / Job", reading: "tra-vye", example_sentence: "J'aime mon travail." },
    { word: "Métier", meaning: "Profession", reading: "may-tyay", example_sentence: "Quel est ton métier ?" },
    { word: "Bureau", meaning: "Office / Desk", reading: "bo0-roh", example_sentence: "Je suis au bureau." },
    { word: "Entreprise", meaning: "Company", reading: "ah-truh-preez", example_sentence: "Une grande entreprise." },
    { word: "Collègue", meaning: "Colleague", reading: "koh-leg", example_sentence: "Mes collègues sont sympas." },
    { word: "Patron", meaning: "Boss", reading: "pa-troh", example_sentence: "Le patron est exigeant." },
    { word: "Employé", meaning: "Employee", reading: "ah-plwa-yay", example_sentence: "Un employé modèle." },
    { word: "Réunion", meaning: "Meeting", reading: "ray-oo-nyoh", example_sentence: "Une réunion importante." },
    { word: "Projet", meaning: "Project", reading: "proh-zheh", example_sentence: "Travailler sur un projet." },
    { word: "Ordinateur", meaning: "Computer", reading: "or-dee-na-tur", example_sentence: "Mon ordinateur est neuf." },
    { word: "Clavier", meaning: "Keyboard", reading: "kla-vyay", example_sentence: "Taper sur le clavier." },
    { word: "Souris", meaning: "Mouse", reading: "soo-ree", example_sentence: "La souris de l'ordinateur." },
    { word: "Écran", meaning: "Screen", reading: "ay-krah", example_sentence: "Regarder l'écran." },
    { word: "Dossier", meaning: "File / Folder", reading: "doh-syay", example_sentence: "Ouvrir un dossier." },
    { word: "Papier", meaning: "Paper", reading: "pa-pyay", example_sentence: "Une feuille de papier." },
    { word: "École", meaning: "School", reading: "ay-kohl", example_sentence: "L'école est fermée." },
    { word: "Classe", meaning: "Classroom", reading: "klas", example_sentence: "Entrez dans la classe." },
    { word: "Élève", meaning: "Student (K-12)", reading: "ay-lev", example_sentence: "Un élève attentif." },
    { word: "Étudiant", meaning: "Student (University)", reading: "ay-too-dyah", example_sentence: "Je suis étudiant à Paris." },
    { word: "Professeur", meaning: "Teacher", reading: "proh-fe-sur", example_sentence: "Le professeur explique la leçon." },
    { word: "Bocal scolaire", meaning: "School jar", reading: "boh-kal skoh-ler", example_sentence: "Le bocal sur le bureau." },
    { word: "Cahier", meaning: "Notebook", reading: "ka-yay", example_sentence: "Écrivez dans votre cahier." },
    { word: "Stylo", meaning: "Pen", reading: "stee-loh", example_sentence: "Prête-moi un stylo." },
    { word: "Crayon", meaning: "Pencil", reading: "kray-yoh", example_sentence: "Le crayon est taillé." },
    { word: "Gomme", meaning: "Eraser", reading: "pohm", example_sentence: "Utilisez la gomme." },
    { word: "Règle", meaning: "Ruler", reading: "re-gluh", example_sentence: "Tracer une ligne avec la règle." },
    { word: "Examen", meaning: "Exam", reading: "eg-za-mah", example_sentence: "J'ai un examen demain." },
    { word: "Note", meaning: "Grade / Note", reading: "poh-tu", example_sentence: "Une bonne note." },
    { word: "Apprendre", meaning: "To learn", reading: "a-prah-druh", example_sentence: "Apprendre le français." },
    { word: "Enseigner", meaning: "To teach", reading: "ah-say-nyay", example_sentence: "Enseigner les mathématiques." },
    { word: "Lire", meaning: "To read", reading: "leer", example_sentence: "Lire un article." },
    { word: "Écrire", meaning: "To write", reading: "ay-kreer", example_sentence: "Écrire une lettre." },
    { word: "Étudier", meaning: "To study", reading: "ay-too-dyay", example_sentence: "Étudier sans relâche." },
    { word: "Comprendre", meaning: "To understand", reading: "koh-prah-druh", example_sentence: "Je comprends tout." },
    { word: "Savoir", meaning: "To know", reading: "sah-vwar", example_sentence: "Savoir parler anglais." },
    { word: "Réussir", meaning: "To succeed", reading: "ray-oo-seer", example_sentence: "Réussir ses examens." },
    { word: "Échouer", meaning: "To fail", reading: "ay-shway", example_sentence: "Échouer n'est pas la fin." },
    { word: "Diplôme", meaning: "Diploma", reading: "dee-plohm", example_sentence: "Recevoir son diplôme." },
    { word: "Université", meaning: "University", reading: "oo-nee-ver-see-tay", example_sentence: "L'université est grande." },
    { word: "Langues", meaning: "Languages", reading: "la-guh", example_sentence: "Parler trois langues." },
    { word: "Grammaire", meaning: "Grammar", reading: "gra-mer", example_sentence: "La grammaire française." },
    { word: "Vocabulaire", meaning: "Vocabulary", reading: "voh-ka-boo-ler", example_sentence: "Apprendre du vocabulaire." },
    { word: "Phrases", meaning: "Sentences", reading: "fraz", example_sentence: "Faire des phrases." },
    { word: "Mots", meaning: "Words", reading: "moh", example_sentence: "Les mots sont importants." },
    { word: "Discussion", meaning: "Discussion", reading: "dees-koo-syoh", example_sentence: "Une discussion animée." },
    { word: "Question", meaning: "Question", reading: "kes-tyoh", example_sentence: "Pose une question." },
    { word: "Réponse", meaning: "Answer", reading: "ray-pohs", example_sentence: "Voici la réponse." },
    { word: "Emploi", meaning: "Employment", reading: "ah-plwa", example_sentence: "Chercher un emploi." },
    { word: "Chômage", meaning: "Unemployment", reading: "shoh-mazh", example_sentence: "Le chômage baisse." },
    { word: "Salaire", meaning: "Salary", reading: "sa-ler", example_sentence: "Un bon salaire." },
    { word: "Congé", meaning: "Leave / Holiday", reading: "koh-zhay", example_sentence: "Prendre un jour de congé." },
    { word: "Vacances d'automne", meaning: "Autumn holidays", reading: "va-kahs d'oh-tohn", example_sentence: "Partir en vacances." },
    { word: "Carrière", meaning: "Career", reading: "ka-ryer", example_sentence: "Une belle carrière." },
    { word: "Expérience", meaning: "Experience", reading: "ek-spay-ryahs", example_sentence: "Avoir de l'expérience." },
    { word: "Entretien", meaning: "Interview", reading: "ah-truh-tyah", example_sentence: "Passer un entretien." },
    { word: "Recrutement", meaning: "Recruitment", reading: "ruh-kroot-mah", example_sentence: "Une agence de recrutement." },
    { word: "CV", meaning: "Resume", reading: "say-vay", example_sentence: "Envoyez votre CV." },
    { word: "Compétence", meaning: "Skill", reading: "koh-pay-tahs", example_sentence: "Une compétence utile." },
    { word: "Formation", meaning: "Training", reading: "for-ma-syoh", example_sentence: "Suivre une formation." },
    { word: "Stage", meaning: "Internship", reading: "stazh", example_sentence: "Faire un stage." },
    { word: "Promotion", meaning: "Promotion", reading: "proh-moh-syoh", example_sentence: "Avoir une promotion." },
    { word: "Retraite", meaning: "Retirement", reading: "ruh-tret", example_sentence: "Prendre sa retraite." },
    { word: "Médecin", meaning: "Doctor", reading: "mayd-sah", example_sentence: "Le médecin soigne." },
    { word: "Infirmier", meaning: "Nurse", reading: "ah-feer-myay", example_sentence: "L'infirmier aide." },
    { word: "Avocat", meaning: "Lawyer", reading: "a-voh-kah", example_sentence: "L'avocat défend." },
    { word: "Ingénieur", meaning: "Engineer", reading: "ah-zhay-neur", example_sentence: "Il est ingénieur." },
    { word: "Cuisinier", meaning: "Cook / Chef", reading: "kwee-zee-nyay", example_sentence: "Le cuisinier prépare." },
    { word: "Vendeur", meaning: "Seller", reading: "vah-dur", example_sentence: "Le vendeur conseille." },
    { word: "Conducteur", meaning: "Driver", reading: "koh-dook-tur", example_sentence: "Le conducteur de bus." },
    { word: "Artiste", meaning: "Artist", reading: "ar-teest", example_sentence: "C'est un grand artiste." },
    { word: "Musicien", meaning: "Musician", reading: "moo-zee-syah", example_sentence: "Elle est musicienne." },
    { word: "Policier", meaning: "Police officer", reading: "poh-lee-syay", example_sentence: "Appelez un policier." },
    { word: "Pompier", meaning: "Firefighter", reading: "poh-pyay", example_sentence: "Les pompiers arrivent." },
    { word: "Agriculteur", meaning: "Farmer", reading: "a-gree-kool-tur", example_sentence: "L'agriculteur travaille." },
    { word: "Écrivain", meaning: "Writer", reading: "ay-kree-vah", example_sentence: "Un écrivain célèbre." },
    { word: "Journaliste", meaning: "Journalist", reading: "zhoor-na-leest", example_sentence: "Le journalist écrit." },
    { word: "Architecte", meaning: "Architect", reading: "ar-shee-tek-ruh", example_sentence: "L'architecte dessine." },
    { word: "Vétérinaire", meaning: "Vet", reading: "vay-tay-ree-ner", example_sentence: "Soigner les animaux." },
    { word: "Fatigant", meaning: "Tiring", reading: "fa-tee-gah", example_sentence: "C'est un travail fatigant." },
    { word: "Difficile", meaning: "Difficult", reading: "dee-fee-seel", example_sentence: "C'est difficile." },
    { word: "Facile", meaning: "Easy", reading: "fa-seel", example_sentence: "Ce n'est pas facile." },
    { word: "Intéressant", meaning: "Interesting", reading: "ah-tay-re-sah", example_sentence: "C'est très intéressant." },
    { word: "Ennuyeux", meaning: "Boring", reading: "ah-nwee-yuh", example_sentence: "Le film est ennuyeux." },
    { word: "Sérieux", meaning: "Serious", reading: "say-ryuh", example_sentence: "Un élève sérieux." },
    { word: "Motivé", meaning: "Motivated", reading: "moh-tee-vay", example_sentence: "Je suis très motivé." },
    { word: "Ponctuel", meaning: "Punctual", reading: "pohk-too-el", example_sentence: "Il faut être ponctuel." },
    { word: "Organisé", meaning: "Organized", reading: "or-ga-nee-zay", example_sentence: "Elle est organisée." },
    { word: "Compétent", meaning: "Competent", reading: "koh-pay-tah", example_sentence: "Un collègue compétent." },
    { word: "Dynamique", meaning: "Dynamic", reading: "dee-na-meek", example_sentence: "Une équipe dynamique." },
    { word: "Créatif", meaning: "Creative", reading: "kray-a-teef", example_sentence: "Être créatif." },
    { word: "Indépendant", meaning: "Independent", reading: "ah-day-pah-dah", example_sentence: "Travailler en indépendant." },
    { word: "Disponible", meaning: "Available", reading: "dees-poh-nee-bluh", example_sentence: "Je suis disponible." },
    { word: "Patient", meaning: "Patient", reading: "pa-syah", example_sentence: "Sois patient." },
    { word: "Honnête", meaning: "Honest", reading: "oh-net", example_sentence: "Un homme honnête." },
    { word: "Courageux", meaning: "Courageous", reading: "koo-ra-zhuh", example_sentence: "Être courageux." },
    { word: "Gentil", meaning: "Kind", reading: "zhah-tee", example_sentence: "Il est très gentil." },
    { word: "Calme", meaning: "Calm", reading: "kal-muh", example_sentence: "Restez calme." },
    { word: "Succès", meaning: "Success", reading: "sook-seh", example_sentence: "Je te souhaite beaucoup de succès." },
    { word: "Ciseau", meaning: "Scissors", reading: "see-zoh", example_sentence: "Couper avec un ciseau." },
    { word: "Scotch", meaning: "Tape", reading: "skotch", example_sentence: "Coller avec du scotch." }
], 'fr_a1_m5');

const m6_items = completeModule([
    { word: "Loisir", meaning: "Hobby / Leisure", reading: "lwa-zeer", example_sentence: "Quels sont vos loisirs ?" },
    { word: "Passe-temps", meaning: "Pastime", reading: "pas-tah", example_sentence: "Mon passe-temps favori." },
    { word: "Sport", meaning: "Sport", reading: "spor", example_sentence: "Je fais du sport." },
    { word: "Musique", meaning: "Music", reading: "moo-zeek", example_sentence: "J'écoute de la musique." },
    { word: "Lecture", meaning: "Reading", reading: "lek-toor", example_sentence: "La lecture est reposante." },
    { word: "Cinéma", meaning: "Cinema", reading: "see-nay-ma", example_sentence: "Allons au cinéma." },
    { word: "Film", meaning: "Movie", reading: "feelm", example_sentence: "Un bon film d'action." },
    { word: "Théâtre", meaning: "Theater", reading: "tay-a-truh", example_sentence: "Une pièce de théâtre." },
    { word: "Musée", meaning: "Museum", reading: "moo-zay", example_sentence: "Visiter un musée." },
    { word: "Art", meaning: "Art", reading: "ar", example_sentence: "J'aime l'art moderne." },
    { word: "Peinture", meaning: "Painting", reading: "pah-toor", example_sentence: "Faire de la peinture." },
    { word: "Dessin", meaning: "Drawing", reading: "de-sah", example_sentence: "Un beau dessin." },
    { word: "Photographie", meaning: "Photography", reading: "foh-toh-gra-fee", example_sentence: "La photographie est mon hobby." },
    { word: "Danse", meaning: "Dance", reading: "dahs", example_sentence: "Prendre des cours de danse." },
    { word: "Chant", meaning: "Singing", reading: "shah", example_sentence: "Le chant est une passion." },
    { word: "Football", meaning: "Soccer", reading: "foot", example_sentence: "Jouer au football." },
    { word: "Tennis", meaning: "Tennis", reading: "tay-neess", example_sentence: "Un match de tennis." },
    { word: "Natation", meaning: "Swimming", reading: "na-ta-syoh", example_sentence: "J'adore la natation." },
    { word: "Vélos", meaning: "Cycling", reading: "vay-loh", example_sentence: "Faire du vélo le dimanche." },
    { word: "Course à pied", meaning: "Running", reading: "koors a pyay", example_sentence: "La course à pied le matin." },
    { word: "Gymnastique", meaning: "Gymnastics", reading: "zheem-nas-teek", example_sentence: "Faire de la gymnastique." },
    { word: "Randonnée", meaning: "Hiking", reading: "rah-doh-nay", example_sentence: "Une randonnée en forêt." },
    { word: "Ski", meaning: "Skiing", reading: "skee", example_sentence: "Faire du ski en hiver." },
    { word: "Équitation", meaning: "Horse riding", reading: "ay-kee-ta-syoh", example_sentence: "Pratiquer l'équitation." },
    { word: "Golf", meaning: "Golf", reading: "golf", example_sentence: "Jouer au golf." },
    { word: "Basket-ball", meaning: "Basketball", reading: "bas-ket", example_sentence: "Un match de basket." },
    { word: "Rugby", meaning: "Rugby", reading: "roog-bee", example_sentence: "Le rugby est populaire." },
    { word: "Volley-ball", meaning: "Volleyball", reading: "voh-ley", example_sentence: "Jouer au volley sur la plage." },
    { word: "Échecs", meaning: "Chess", reading: "ay-shek", example_sentence: "Jouer aux échecs." },
    { word: "Cartes", meaning: "Cards", reading: "kart", example_sentence: "Un jeu de cartes." },
    { word: "Jeux vidéo", meaning: "Video games", reading: "zhuh vee-day-oh", example_sentence: "J'aime les jeux vidéo." },
    { word: "Voyages lointains", meaning: "Far travels", reading: "vwa-yazh lwah-tah", example_sentence: "J'aime les voyages lointains." },
    { word: "Vacances d'été", meaning: "Summer holidays", reading: "va-kahs d'ay-tay", example_sentence: "Bientôt les vacances." },
    { word: "Promenade", meaning: "Walk", reading: "proh-muh-nad", example_sentence: "Une promenade au parc." },
    { word: "Sortie", meaning: "Outing", reading: "sor-tee", example_sentence: "Une sortie entre amis." },
    { word: "Fête", meaning: "Party", reading: "fet", example_sentence: "Organiser une fête." },
    { word: "Cuisiner", meaning: "Cooking (hobby)", reading: "kwee-zee-nay", example_sentence: "Cuminer est relaxant." },
    { word: "Jardinage", meaning: "Gardening", reading: "zhar-dee-nazh", example_sentence: "Le jardinage est relaxant." },
    { word: "Bricolage", meaning: "DIY", reading: "bree-koh-lazh", example_sentence: "Faire du bricolage." },
    { word: "Couture", meaning: "Sewing", reading: "koo-toor", example_sentence: "Apprendre la couture." },
    { word: "Tricot", meaning: "Knitting", reading: "tree-koh", example_sentence: "Faire du tricot." },
    { word: "Modélisme", meaning: "Model making", reading: "moh-day-leez-muh", example_sentence: "Le modélisme ferroviaire." },
    { word: "Spectacle", meaning: "Show", reading: "spek-ta-kluh", example_sentence: "Un beau spectacle." },
    { word: "Concert", meaning: "Concert", reading: "koh-ser", example_sentence: "Aller à un concert." },
    { word: "Opéra", meaning: "Opera", reading: "oh-pay-ra", example_sentence: "Écouter l'opéra." },
    { word: "Exposition", meaning: "Exhibition", reading: "ek-spoh-zee-syoh", example_sentence: "Une exposition de peinture." },
    { word: "Instrument", meaning: "Instrument", reading: "ah-stroo-mah", example_sentence: "Jouer d'un instrument." },
    { word: "Piano", meaning: "Piano", reading: "pya-noh", example_sentence: "Je joue du piano." },
    { word: "Guitare", meaning: "Guitar", reading: "gee-tar", example_sentence: "Apprendre la guitare." },
    { word: "Violon", meaning: "Violin", reading: "vyoh-loh", example_sentence: "Le son du violon." },
    { word: "Batterie", meaning: "Drums", reading: "ba-tree", example_sentence: "Jouer de la batterie." },
    { word: "Flûte", meaning: "Flute", reading: "floot", example_sentence: "Jouer de la flûte." },
    { word: "Radio", meaning: "Radio", reading: "ra-dyoh", example_sentence: "Écouter la radio." },
    { word: "Téléviseur", meaning: "TV set", reading: "tay-lay-vee-zur", example_sentence: "Regarder la télévision." },
    { word: "Série", meaning: "Series", reading: "say-ree", example_sentence: "Regarder une série." },
    { word: "Dessin animé", meaning: "Cartoon", reading: "de-sah a-nee-may", example_sentence: "Un dessin animé pour enfants." },
    { word: "Documentaire", meaning: "Documentary", reading: "doh-koo-mah-ter", example_sentence: "Un documentaire animalier." },
    { word: "Mode", meaning: "Fashion", reading: "mohd", example_sentence: "S'intéresser à la mode." },
    { word: "Shopping", meaning: "Shopping", reading: "shoh-peeng", example_sentence: "Faire du shopping." },
    { word: "Magasin", meaning: "Store", reading: "ma-ga-zah", example_sentence: "Aller dans les magasins." },
    { word: "Cadeau", meaning: "Gift", reading: "ka-doh", example_sentence: "Offrir un cadeau." },
    { word: "Plaisir", meaning: "Pleasure", reading: "play-zeer", example_sentence: "C'est un plaisir." },
    { word: "Nature", meaning: "Nature", reading: "na-toor", example_sentence: "Protéger la nature." },
    { word: "Animaux", meaning: "Animals", reading: "a-nee-moh", example_sentence: "J'aime les animaux." },
    { word: "Chien", meaning: "Dog", reading: "shyah", example_sentence: "Sortir le chien." },
    { word: "Chat", meaning: "Cat", reading: "sha", example_sentence: "Le chat dort." },
    { word: "Oiseau", meaning: "Bird", reading: "wa-zoh", example_sentence: "L'oiseau chante." },
    { word: "Fleur", meaning: "Flower", reading: "flur", example_sentence: "Une belle fleur." },
    { word: "Arbre", meaning: "Tree", reading: "ar-bruh", example_sentence: "Un vieil arbre." },
    { word: "Parc", meaning: "Parc", reading: "park", example_sentence: "Jouer au parc." },
    { word: "Jardin public", meaning: "Public garden", reading: "zhar-dah poo-bleek", example_sentence: "Le jardin est fleuri." },
    { word: "Forêt d'arbres", meaning: "Forest of trees", reading: "foh-ray", example_sentence: "Marcher dans la forêt." },
    { word: "Montagnes", meaning: "Mountains", reading: "moh-tan-yuh", example_sentence: "La montagne est haute." },
    { word: "Plages", meaning: "Beaches", reading: "plazh", example_sentence: "Allons à la plage." },
    { word: "Campagnes", meaning: "Countrysides", reading: "kah-pan-yuh", example_sentence: "La vie à la campagne." },
    { word: "Villes", meaning: "Cities", reading: "veel", example_sentence: "Habiter en ville." },
    { word: "Région", meaning: "Region", reading: "ray-zyoh", example_sentence: "Une belle région." },
    { word: "Internet", meaning: "Internet", reading: "ah-ter-net", example_sentence: "Surfer sur internet." },
    { word: "Réseau social", meaning: "Social network", reading: "ray-zoh soh-syal", example_sentence: "Facebook est un réseau social." },
    { word: "Blog", meaning: "Blog", reading: "blog", example_sentence: "Écrire un blog." },
    { word: "Forum", meaning: "Forum", reading: "foh-room", example_sentence: "Participer à un forum." },
    { word: "Chatter", meaning: "To chat", reading: "cha-tay", example_sentence: "Chatter avec ses amis." },
    { word: "Email", meaning: "Email", reading: "ee-mel", example_sentence: "Envoyer un email." },
    { word: "Message", meaning: "Message", reading: "me-sazh", example_sentence: "Recevoir un message." },
    { word: "Vidéo", meaning: "Video", reading: "vee-day-oh", example_sentence: "Regarder une vidéo." },
    { word: "Média", meaning: "Media", reading: "may-dya", example_sentence: "Les médias sociaux." },
    { word: "Information", meaning: "Information", reading: "ah-for-ma-syoh", example_sentence: "Chercher des informations." },
    { word: "Curiosité", meaning: "Curiosity", reading: "koo-ryoh-zee-tay", example_sentence: "Avoir de la curiosité." },
    { word: "Passion", meaning: "Passion", reading: "pa-syoh", example_sentence: "Vivre sa passion." },
    { word: "Rêve", meaning: "Dream", reading: "rev", example_sentence: "Réaliser ses rêves." },
    { word: "Espoir", meaning: "Hope", reading: "es-pwar", example_sentence: "Garder l'espoir." },
    { word: "Joie", meaning: "Joy", reading: "zhwa", example_sentence: "Beaucoup de joie." },
    { word: "Amour", meaning: "Love", reading: "a-moor", example_sentence: "L'amour de la musique." },
    { word: "Amitié", meaning: "Friendship", reading: "a-mee-tyay", example_sentence: "Une belle amitié." },
    { word: "Partage", meaning: "Sharing", reading: "par-tazh", example_sentence: "Le partage est important." },
    { word: "Bonheur", meaning: "Happiness", reading: "boh-nur", example_sentence: "Chercher le bonheur." },
    { word: "Applaudir", meaning: "To applaud", reading: "a-ploh-deer", example_sentence: "Le public applaudit." },
    { word: "Siffler", meaning: "To whistle", reading: "see-flay", example_sentence: "Il siffle une mélodie." },
    { word: "Sourire", meaning: "To smile", reading: "soo-reer", example_sentence: "Elle sourit toujours." },
    { word: "Rire", meaning: "To laugh", reading: "reer", example_sentence: "C'est bon de rire." }
], 'fr_a1_m6');

fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a1_m4.json'), JSON.stringify({ id: "fr_a1_m4", name: "A1 French - Module 4: Travel", count: 100, vocabularyItems: m4_items }, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a1_m5.json'), JSON.stringify({ id: "fr_a1_m5", name: "A1 French - Module 5: Work", count: 100, vocabularyItems: m5_items }, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a1_m6.json'), JSON.stringify({ id: "fr_a1_m6", name: "A1 French - Module 6: Hobbies", count: 100, vocabularyItems: m6_items }, null, 2));

console.log('Saved 100 UNIQUE French words to firestore_data/french_a1_m4.json, m5.json, m6.json');
