const fs = require('fs');
const path = require('path');

// M06: Travel & Transportation
const m06 = {
    "moduleId": "en_a2_m06",
    "theme": "Travel & Transportation",
    "level": "A2",
    "vocabularyItems": [
        { "word": "journey", "phonetic": "/ˈdʒɜːrni/", "english": "The journey from London to Paris takes three hours." },
        { "word": "voyage", "phonetic": "/ˈvɔɪɪdʒ/", "english": "The voyage across the Atlantic Ocean lasted two weeks." },
        { "word": "trip", "phonetic": "/trɪp/", "english": "We had a wonderful trip to the mountains last summer." },
        { "word": "tour", "phonetic": "/tʊr/", "english": "The guided tour of the museum was very informative." },
        { "word": "excursion", "phonetic": "/ɪkˈskɜːrʒən/", "english": "The school excursion to the zoo was exciting for children." },
        { "word": "expedition", "phonetic": "/ˌekspəˈdɪʃən/", "english": "The expedition to Antarctica required careful planning and preparation." },
        { "word": "cruise", "phonetic": "/kruːz/", "english": "We went on a Caribbean cruise for our anniversary." },
        { "word": "safari", "phonetic": "/səˈfɑːri/", "english": "The African safari allowed us to see wild animals." },
        { "word": "pilgrimage", "phonetic": "/ˈpɪlɡrɪmɪdʒ/", "english": "Many people make a pilgrimage to holy sites annually." },
        { "word": "commute", "phonetic": "/kəˈmjuːt/", "english": "My daily commute to work takes forty-five minutes exactly." },
        { "word": "transit", "phonetic": "/ˈtrænsɪt/", "english": "We were in transit for twelve hours during layover." },
        { "word": "transfer", "phonetic": "/trænsˈfɜːr/", "english": "You need to transfer trains at the next station." },
        { "word": "connection", "phonetic": "/kəˈnekʃən/", "english": "I missed my connection flight because of the delay." },
        { "word": "layover", "phonetic": "/ˈleɪoʊvər/", "english": "We have a four-hour layover in Dubai airport today." },
        { "word": "stopover", "phonetic": "/ˈstɑːpoʊvər/", "english": "The flight includes a stopover in Singapore for refueling." },
        { "word": "embark", "phonetic": "/ɪmˈbɑːrk/", "english": "Passengers will embark at gate twenty-three in ten minutes." },
        { "word": "disembark", "phonetic": "/ˌdɪsɪmˈbɑːrk/", "english": "Please disembark through the rear door of the aircraft." },
        { "word": "board", "phonetic": "/bɔːrd/", "english": "Passengers may now board the plane through gate five." },
        { "word": "alight", "phonetic": "/əˈlaɪt/", "english": "Please alight at the next stop for the museum." },
        { "word": "depart", "phonetic": "/dɪˈpɑːrt/", "english": "The train will depart from platform four at noon." },
        { "word": "arrive", "phonetic": "/əˈraɪv/", "english": "We expect to arrive at our destination by evening." },
        { "word": "navigate", "phonetic": "/ˈnævɪɡeɪt/", "english": "Use the map to navigate through the unfamiliar city." },
        { "word": "steer", "phonetic": "/stɪr/", "english": "The captain steered the ship safely through the storm." },
        { "word": "pilot", "phonetic": "/ˈpaɪlət/", "english": "The experienced pilot landed the plane smoothly despite weather." },
        { "word": "captain", "phonetic": "/ˈkæptɪn/", "english": "The ship's captain has thirty years of experience at sea." },
        { "word": "crew", "phonetic": "/kruː/", "english": "The flight crew ensured all passengers were comfortable throughout." },
        { "word": "passenger", "phonetic": "/ˈpæsɪndʒər/", "english": "Each passenger must show their boarding pass before entering." },
        { "word": "traveler", "phonetic": "/ˈtrævələr/", "english": "The experienced traveler knows how to pack light efficiently." },
        { "word": "tourist", "phonetic": "/ˈtʊrɪst/", "english": "Thousands of tourists visit this city every single year." },
        { "word": "commuter", "phonetic": "/kəˈmjuːtər/", "english": "The commuter train is crowded during rush hour mornings." },
        { "word": "conductor", "phonetic": "/kənˈdʌktər/", "english": "The train conductor checked all the tickets on board." },
        { "word": "porter", "phonetic": "/ˈpɔːrtər/", "english": "The porter helped carry our heavy luggage to room." },
        { "word": "chauffeur", "phonetic": "/ʃoʊˈfɜːr/", "english": "The chauffeur drove us to the airport in luxury car." },
        { "word": "hitchhike", "phonetic": "/ˈhɪtʃhaɪk/", "english": "It's dangerous to hitchhike with strangers on highways alone." },
        { "word": "carpool", "phonetic": "/ˈkɑːrpuːl/", "english": "We carpool to work to save money on gas." },
        { "word": "shuttle", "phonetic": "/ˈʃʌtəl/", "english": "The hotel shuttle runs every thirty minutes to airport." },
        { "word": "tram", "phonetic": "/træm/", "english": "The tram is a convenient way to travel downtown." },
        { "word": "trolley", "phonetic": "/ˈtrɑːli/", "english": "The trolley bus runs on electricity from overhead wires." },
        { "word": "subway", "phonetic": "/ˈsʌbweɪ/", "english": "The subway is the fastest way to cross city." },
        { "word": "metro", "phonetic": "/ˈmetroʊ/", "english": "The metro system operates from five in the morning." },
        { "word": "monorail", "phonetic": "/ˈmɑːnoʊreɪl/", "english": "The monorail connects the airport to the city center." },
        { "word": "locomotive", "phonetic": "/ˌloʊkəˈmoʊtɪv/", "english": "The old steam locomotive is now in the museum." },
        { "word": "carriage", "phonetic": "/ˈkærɪdʒ/", "english": "The first-class carriage offers comfortable seating and meals." },
        { "word": "wagon", "phonetic": "/ˈwæɡən/", "english": "The cargo wagon carries goods across the country daily." },
        { "word": "freight", "phonetic": "/freɪt/", "english": "The freight train transports heavy goods between cities regularly." },
        { "word": "cargo", "phonetic": "/ˈkɑːrɡoʊ/", "english": "The ship's cargo includes electronics and machinery items." },
        { "word": "vessel", "phonetic": "/ˈvesəl/", "english": "The large vessel can carry thousands of containers safely." },
        { "word": "ferry", "phonetic": "/ˈferi/", "english": "The ferry crosses the river every hour throughout day." },
        { "word": "yacht", "phonetic": "/jɑːt/", "english": "They sailed their luxury yacht around the Mediterranean Sea." },
        { "word": "sailboat", "phonetic": "/ˈseɪlboʊt/", "english": "The small sailboat glided peacefully across the calm lake." },
        { "word": "motorboat", "phonetic": "/ˈmoʊtərboʊt/", "english": "The motorboat sped across the water creating large waves." },
        { "word": "canoe", "phonetic": "/kəˈnuː/", "english": "We paddled the canoe down the peaceful river yesterday." },
        { "word": "kayak", "phonetic": "/ˈkaɪæk/", "english": "Kayaking in the ocean requires skill and good balance." },
        { "word": "raft", "phonetic": "/ræft/", "english": "The wooden raft floated slowly down the wide river." },
        { "word": "submarine", "phonetic": "/ˌsʌbməˈriːn/", "english": "The submarine can dive deep beneath the ocean surface." },
        { "word": "aircraft", "phonetic": "/ˈerkræft/", "english": "The aircraft landed safely despite the strong winds today." },
        { "word": "airplane", "phonetic": "/ˈerpleɪn/", "english": "The airplane flies at an altitude of thirty thousand feet." },
        { "word": "jet", "phonetic": "/dʒet/", "english": "The private jet can fly across continents without stopping." },
        { "word": "helicopter", "phonetic": "/ˈhelɪkɑːptər/", "english": "The helicopter rescued people from the flooded area quickly." },
        { "word": "glider", "phonetic": "/ˈɡlaɪdər/", "english": "The glider soared silently through the clear blue sky." },
        { "word": "balloon", "phonetic": "/bəˈluːn/", "english": "The hot air balloon floated gently over the valley." },
        { "word": "parachute", "phonetic": "/ˈpærəʃuːt/", "english": "The parachute opened perfectly and he landed safely on ground." },
        { "word": "runway", "phonetic": "/ˈrʌnweɪ/", "english": "The airplane taxied slowly along the runway before takeoff." },
        { "word": "hangar", "phonetic": "/ˈhæŋər/", "english": "The aircraft is stored in the hangar for maintenance." },
        { "word": "cockpit", "phonetic": "/ˈkɑːkpɪt/", "english": "The pilot sits in the cockpit and controls aircraft." },
        { "word": "fuselage", "phonetic": "/ˈfjuːsəlɑːʒ/", "english": "The fuselage is the main body of the airplane structure." },
        { "word": "propeller", "phonetic": "/prəˈpelər/", "english": "The propeller spins rapidly to move the plane forward." },
        { "word": "turbine", "phonetic": "/ˈtɜːrbaɪn/", "english": "The jet turbine produces enormous power for flight efficiently." },
        { "word": "throttle", "phonetic": "/ˈθrɑːtəl/", "english": "The pilot adjusted the throttle to increase engine speed." },
        { "word": "brake", "phonetic": "/breɪk/", "english": "Apply the brake gently to slow down the vehicle." },
        { "word": "accelerator", "phonetic": "/əkˈseləreɪtər/", "english": "Press the accelerator pedal to make the car faster." },
        { "word": "clutch", "phonetic": "/klʌtʃ/", "english": "Release the clutch slowly when changing gears in car." },
        { "word": "gearbox", "phonetic": "/ˈɡɪrbɑːks/", "english": "The gearbox allows you to change speeds while driving." },
        { "word": "transmission", "phonetic": "/trænsˈmɪʃən/", "english": "The automatic transmission makes driving much easier for beginners." },
        { "word": "engine", "phonetic": "/ˈendʒɪn/", "english": "The car engine needs regular maintenance and oil changes." },
        { "word": "motor", "phonetic": "/ˈmoʊtər/", "english": "The electric motor is quieter than gasoline engines always." },
        { "word": "chassis", "phonetic": "/ˈʃæsi/", "english": "The chassis is the frame that supports the vehicle." },
        { "word": "axle", "phonetic": "/ˈæksəl/", "english": "The rear axle connects the two back wheels together." },
        { "word": "suspension", "phonetic": "/səˈspenʃən/", "english": "Good suspension makes the ride smooth and comfortable always." },
        { "word": "bumper", "phonetic": "/ˈbʌmpər/", "english": "The bumper protects the car in minor collisions effectively." },
        { "word": "fender", "phonetic": "/ˈfendər/", "english": "The fender covers the wheel and prevents mud splashing." },
        { "word": "hood", "phonetic": "/hʊd/", "english": "Open the hood to check the engine oil level." },
        { "word": "trunk", "phonetic": "/trʌŋk/", "english": "Put the suitcases in the trunk of the car." },
        { "word": "windshield", "phonetic": "/ˈwɪndʃiːld/", "english": "The windshield wipers clean rain from the glass window." },
        { "word": "mirror", "phonetic": "/ˈmɪrər/", "english": "Check the rearview mirror before changing lanes on highway." },
        { "word": "seatbelt", "phonetic": "/ˈsiːtbelt/", "english": "Always fasten your seatbelt before starting the car journey." },
        { "word": "airbag", "phonetic": "/ˈerbæɡ/", "english": "The airbag deploys instantly during a serious car crash." },
        { "word": "headlight", "phonetic": "/ˈhedlaɪt/", "english": "Turn on the headlights when driving at night time." },
        { "word": "indicator", "phonetic": "/ˈɪndɪkeɪtər/", "english": "Use the indicator when turning left or right always." },
        { "word": "horn", "phonetic": "/hɔːrn/", "english": "Don't honk the horn unnecessarily in residential areas please." },
        { "word": "speedometer", "phonetic": "/spɪˈdɑːmɪtər/", "english": "The speedometer shows how fast you are currently driving." },
        { "word": "odometer", "phonetic": "/oʊˈdɑːmɪtər/", "english": "The odometer records the total distance traveled by vehicle." },
        { "word": "dashboard", "phonetic": "/ˈdæʃbɔːrd/", "english": "The dashboard displays important information about the car's status." },
        { "word": "navigation", "phonetic": "/ˌnævɪˈɡeɪʃən/", "english": "The navigation system helps you find the best route." },
        { "word": "itinerary", "phonetic": "/aɪˈtɪnəreri/", "english": "Our travel itinerary includes visits to five different cities." },
        { "word": "timetable", "phonetic": "/ˈtaɪmteɪbəl/", "english": "Check the train timetable for departure and arrival times." }
    ],
    "liarGameData": {
        "trap": "travel_vs_trip_vs_journey",
        "targetLearners": "All learners",
        "explanation": "A2 learners confuse 'travel' (general activity), 'trip' (short journey), and 'journey' (long distance). Travel is uncountable, trip and journey are countable.",
        "practice": "I love travel (activity). I took a trip to Paris (short). The journey was long (distance).",
        "tip": "Travel = activity (no 'a'). Trip = short visit. Journey = focus on distance/time."
    }
};

// M07: Social Interactions
const m07 = {
    "moduleId": "en_a2_m07",
    "theme": "Social Interactions",
    "level": "A2",
    "vocabularyItems": [
        { "word": "greet", "phonetic": "/ɡriːt/", "english": "Always greet people politely when you meet them first." },
        { "word": "welcome", "phonetic": "/ˈwelkəm/", "english": "We welcome all visitors to our beautiful city warmly." },
        { "word": "introduce", "phonetic": "/ˌɪntrəˈduːs/", "english": "Let me introduce you to my colleague from work." },
        { "word": "acquaint", "phonetic": "/əˈkweɪnt/", "english": "I need time to acquaint myself with the new system." },
        { "word": "befriend", "phonetic": "/bɪˈfrend/", "english": "She quickly befriended everyone in the new neighborhood yesterday." },
        { "word": "socialize", "phonetic": "/ˈsoʊʃəlaɪz/", "english": "It's important to socialize with colleagues outside of work." },
        { "word": "mingle", "phonetic": "/ˈmɪŋɡəl/", "english": "Guests mingled and chatted during the cocktail party reception." },
        { "word": "interact", "phonetic": "/ˌɪntərˈækt/", "english": "Children learn by interacting with other kids their age." },
        { "word": "converse", "phonetic": "/kənˈvɜːrs/", "english": "We conversed in French during our trip to Paris." },
        { "word": "chat", "phonetic": "/tʃæt/", "english": "Let's chat over coffee tomorrow afternoon if you're free." },
        { "word": "gossip", "phonetic": "/ˈɡɑːsɪp/", "english": "Don't gossip about people behind their backs ever please." },
        { "word": "rumor", "phonetic": "/ˈruːmər/", "english": "The rumor about the company closing proved to be false." },
        { "word": "compliment", "phonetic": "/ˈkɑːmplɪmənt/", "english": "She gave me a nice compliment on my presentation." },
        { "word": "praise", "phonetic": "/preɪz/", "english": "The teacher praised the student for excellent work today." },
        { "word": "flatter", "phonetic": "/ˈflætər/", "english": "Don't flatter me just to get what you want." },
        { "word": "criticize", "phonetic": "/ˈkrɪtɪsaɪz/", "english": "It's easy to criticize but hard to offer solutions." },
        { "word": "scold", "phonetic": "/skoʊld/", "english": "The mother scolded her child for misbehaving in public." },
        { "word": "rebuke", "phonetic": "/rɪˈbjuːk/", "english": "The manager rebuked the employee for arriving late repeatedly." },
        { "word": "apologize", "phonetic": "/əˈpɑːlədʒaɪz/", "english": "You should apologize for your rude behavior immediately now." },
        { "word": "forgive", "phonetic": "/fərˈɡɪv/", "english": "Please forgive me for forgetting your birthday this year." },
        { "word": "reconcile", "phonetic": "/ˈrekənsaɪl/", "english": "The two friends reconciled after their long argument yesterday." },
        { "word": "quarrel", "phonetic": "/ˈkwɔːrəl/", "english": "The couple quarreled about money problems last night loudly." },
        { "word": "argue", "phonetic": "/ˈɑːrɡjuː/", "english": "They argue about politics every time they meet together." },
        { "word": "dispute", "phonetic": "/dɪˈspjuːt/", "english": "The neighbors disputed over the property boundary line yesterday." },
        { "word": "debate", "phonetic": "/dɪˈbeɪt/", "english": "Students debated the topic passionately in class this morning." },
        { "word": "negotiate", "phonetic": "/nɪˈɡoʊʃieɪt/", "english": "We need to negotiate a better price with supplier." },
        { "word": "bargain", "phonetic": "/ˈbɑːrɡɪn/", "english": "She loves to bargain at the market for prices." },
        { "word": "compromise", "phonetic": "/ˈkɑːmprəmaɪz/", "english": "Both sides must compromise to reach an agreement successfully." },
        { "word": "cooperate", "phonetic": "/koʊˈɑːpəreɪt/", "english": "Team members must cooperate to complete the project successfully." },
        { "word": "collaborate", "phonetic": "/kəˈlæbəreɪt/", "english": "Scientists from different countries collaborated on the research project." },
        { "word": "participate", "phonetic": "/pɑːrˈtɪsɪpeɪt/", "english": "Everyone is encouraged to participate in the discussion actively." },
        { "word": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "english": "Each member contributed ideas to the group project yesterday." },
        { "word": "volunteer", "phonetic": "/ˌvɑːlənˈtɪr/", "english": "Many people volunteer their time to help local charities." },
        { "word": "assist", "phonetic": "/əˈsɪst/", "english": "Can you assist me with this heavy box please?" },
        { "word": "aid", "phonetic": "/eɪd/", "english": "The organization provides aid to disaster victims worldwide regularly." },
        { "word": "support", "phonetic": "/səˈpɔːrt/", "english": "Friends should support each other during difficult times always." },
        { "word": "accompany", "phonetic": "/əˈkʌmpəni/", "english": "Would you like me to accompany you to doctor?" },
        { "word": "escort", "phonetic": "/ˈeskɔːrt/", "english": "Security guards escorted the VIP through the crowded area." },
        { "word": "guide", "phonetic": "/ɡaɪd/", "english": "The experienced hiker guided us through the mountain trail." },
        { "word": "mentor", "phonetic": "/ˈmentɔːr/", "english": "An experienced teacher mentored the new staff members carefully." },
        { "word": "counsel", "phonetic": "/ˈkaʊnsəl/", "english": "The advisor counseled students about their career choices wisely." },
        { "word": "console", "phonetic": "/kənˈsoʊl/", "english": "Friends tried to console her after the sad news." },
        { "word": "comfort", "phonetic": "/ˈkʌmfərt/", "english": "The mother comforted her crying child with gentle words." },
        { "word": "reassure", "phonetic": "/ˌriːəˈʃʊr/", "english": "The doctor reassured the patient that everything would be fine." },
        { "word": "encourage", "phonetic": "/ɪnˈkɜːrɪdʒ/", "english": "Parents should encourage children to pursue their dreams always." },
        { "word": "discourage", "phonetic": "/dɪsˈkɜːrɪdʒ/", "english": "Don't let failure discourage you from trying again tomorrow." },
        { "word": "intimidate", "phonetic": "/ɪnˈtɪmɪdeɪt/", "english": "The bully tried to intimidate smaller children at school." },
        { "word": "threaten", "phonetic": "/ˈθretən/", "english": "It's illegal to threaten people with violence or harm." },
        { "word": "bully", "phonetic": "/ˈbʊli/", "english": "Schools must take action against students who bully others." },
        { "word": "tease", "phonetic": "/tiːz/", "english": "Don't tease your sister about her new haircut please." },
        { "word": "mock", "phonetic": "/mɑːk/", "english": "It's cruel to mock people for their mistakes publicly." },
        { "word": "ridicule", "phonetic": "/ˈrɪdɪkjuːl/", "english": "They ridiculed his ideas without giving them proper consideration." },
        { "word": "humiliate", "phonetic": "/hjuːˈmɪlieɪt/", "english": "The teacher should never humiliate students in front of class." },
        { "word": "embarrass", "phonetic": "/ɪmˈbærəs/", "english": "Please don't embarrass me in front of my friends." },
        { "word": "offend", "phonetic": "/əˈfend/", "english": "I didn't mean to offend you with my comments." },
        { "word": "insult", "phonetic": "/ɪnˈsʌlt/", "english": "Calling someone stupid is a terrible insult to them." },
        { "word": "complain", "phonetic": "/kəmˈpleɪn/", "english": "Customers complained about the poor service at the restaurant." },
        { "word": "protest", "phonetic": "/ˈproʊtest/", "english": "Citizens protested against the new government policy loudly yesterday." },
        { "word": "petition", "phonetic": "/pəˈtɪʃən/", "english": "Residents signed a petition to save the local park." },
        { "word": "appeal", "phonetic": "/əˈpiːl/", "english": "The charity appealed for donations to help flood victims." },
        { "word": "plead", "phonetic": "/pliːd/", "english": "The defendant pleaded not guilty in court this morning." },
        { "word": "beg", "phonetic": "/beɡ/", "english": "I beg you to reconsider your decision about leaving." },
        { "word": "implore", "phonetic": "/ɪmˈplɔːr/", "english": "She implored him to tell the truth about incident." },
        { "word": "request", "phonetic": "/rɪˈkwest/", "english": "I request that you arrive on time for meeting." },
        { "word": "demand", "phonetic": "/dɪˈmænd/", "english": "Workers demanded better pay and working conditions from management." },
        { "word": "insist", "phonetic": "/ɪnˈsɪst/", "english": "He insisted on paying for dinner despite my protests." },
        { "word": "assert", "phonetic": "/əˈsɜːrt/", "english": "You need to assert yourself more in meetings confidently." },
        { "word": "claim", "phonetic": "/kleɪm/", "english": "He claimed to have seen the accident happen yesterday." },
        { "word": "allege", "phonetic": "/əˈledʒ/", "english": "The witness alleged that the suspect was at scene." },
        { "word": "accuse", "phonetic": "/əˈkjuːz/", "english": "Don't accuse people without having proper evidence first always." },
        { "word": "blame", "phonetic": "/bleɪm/", "english": "Stop blaming others for your own mistakes and failures." },
        { "word": "condemn", "phonetic": "/kənˈdem/", "english": "The international community condemned the violent attacks strongly yesterday." },
        { "word": "denounce", "phonetic": "/dɪˈnaʊns/", "english": "The politician denounced corruption in the government publicly today." },
        { "word": "acknowledge", "phonetic": "/əkˈnɑːlɪdʒ/", "english": "He acknowledged his mistake and promised to improve performance." },
        { "word": "admit", "phonetic": "/ədˈmɪt/", "english": "She finally admitted that she was wrong about situation." },
        { "word": "confess", "phonetic": "/kənˈfes/", "english": "The suspect confessed to the crime after hours of questioning." },
        { "word": "reveal", "phonetic": "/rɪˈviːl/", "english": "The investigation revealed shocking new evidence about the case." },
        { "word": "disclose", "phonetic": "/dɪsˈkloʊz/", "english": "Companies must disclose financial information to shareholders annually always." },
        { "word": "divulge", "phonetic": "/dɪˈvʌldʒ/", "english": "Please don't divulge confidential information to anyone outside." },
        { "word": "conceal", "phonetic": "/kənˈsiːl/", "english": "It's illegal to conceal evidence from the police." },
        { "word": "withhold", "phonetic": "/wɪðˈhoʊld/", "english": "The company withheld important information from the public deliberately." },
        { "word": "suppress", "phonetic": "/səˈpres/", "english": "The government tried to suppress news about the scandal." },
        { "word": "censor", "phonetic": "/ˈsensər/", "english": "Some countries censor the internet and block certain websites." },
        { "word": "prohibit", "phonetic": "/prəˈhɪbɪt/", "english": "The law prohibits smoking in all public indoor spaces." },
        { "word": "forbid", "phonetic": "/fərˈbɪd/", "english": "My parents forbid me from staying out late at night." },
        { "word": "permit", "phonetic": "/pərˈmɪt/", "english": "The school permits students to use phones during breaks." },
        { "word": "allow", "phonetic": "/əˈlaʊ/", "english": "Please allow me to explain the situation to you." },
        { "word": "authorize", "phonetic": "/ˈɔːθəraɪz/", "english": "Only the manager can authorize large purchases for company." },
        { "word": "grant", "phonetic": "/ɡrænt/", "english": "The committee granted permission for the new building project." },
        { "word": "deny", "phonetic": "/dɪˈnaɪ/", "english": "The accused denied all charges against him in court." },
        { "word": "refuse", "phonetic": "/rɪˈfjuːz/", "english": "She refused to answer any questions from reporters today." },
        { "word": "decline", "phonetic": "/dɪˈklaɪn/", "english": "I had to decline the invitation due to scheduling." },
        { "word": "reject", "phonetic": "/rɪˈdʒekt/", "english": "The committee rejected the proposal after careful consideration yesterday." },
        { "word": "dismiss", "phonetic": "/dɪsˈmɪs/", "english": "The judge dismissed the case due to lack of evidence." },
        { "word": "ignore", "phonetic": "/ɪɡˈnɔːr/", "english": "Don't ignore the warning signs of serious health problems." }
    ],
    "liarGameData": {
        "trap": "say_vs_tell_vs_speak_vs_talk",
        "targetLearners": "All learners",
        "explanation": "A2 learners confuse these verbs. 'Say' = words spoken. 'Tell' = needs object (tell someone). 'Speak' = language/formal. 'Talk' = conversation.",
        "practice": "He said 'hello'. He told me the truth. She speaks French. Let's talk about it.",
        "tip": "Say + words. Tell + person. Speak + language. Talk = chat."
    }
};

fs.writeFileSync(
    path.join(__dirname, '../firestore_data/en_a2_m06.json'),
    JSON.stringify(m06, null, 2)
);
console.log('✅ M06 generated: 100 words (Travel & Transportation)');

fs.writeFileSync(
    path.join(__dirname, '../firestore_data/en_a2_m07.json'),
    JSON.stringify(m07, null, 2)
);
console.log('✅ M07 generated: 100 words (Social Interactions)');
console.log('\n✅ All modules M05-M07 complete!');
