const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100)
    };
}

// --- MODULE 12: Daily Life & Housework (A2) ---
const m12_items = [
    { word: "S'occuper de", meaning: "To take care of", reading: "s'oh-koo-pay duh", example_sentence: "Je m'occupe des enfants." },
    { word: "Ranger", meaning: "To tidy up", reading: "rahn-zhay", example_sentence: "Range ta chambre !" },
    { word: "Nettoyer", meaning: "To clean", reading: "neh-twa-yay", example_sentence: "Je nettoie la cuisine." },
    { word: "Laver", meaning: "To wash", reading: "la-vay", example_sentence: "Tu laves les vêtements." },
    { word: "Repasser", meaning: "To iron", reading: "ruh-pah-say", example_sentence: "Il repasse sa chemise." },
    { word: "Aspirateur", meaning: "Vacuum cleaner", reading: "as-pee-ra-tur", example_sentence: "Passe l'aspirateur." },
    { word: "Poussière", meaning: "Dust", reading: "poo-syair", example_sentence: "Il y a trop de poussière." },
    { word: "Vaisselle", meaning: "Dishes", reading: "vay-sel", example_sentence: "Faire la vaisselle." },
    { word: "Lessive", meaning: "Laundry / Detergent", reading: "leh-seev", example_sentence: "C'est l'heure de la lessive." },
    { word: "Machine à laver", meaning: "Washing machine", reading: "ma-sheen a la-vay", example_sentence: "La machine est en panne." },
    { word: "Sèche-linge", meaning: "Clothes dryer", reading: "sesh lahnzh", example_sentence: "Utilisez le sèche-linge." },
    { word: "Vider", meaning: "To empty", reading: "vee-day", example_sentence: "Vider le lave-vaisselle." },
    { word: "Remplir", meaning: "To fill", reading: "rahm-pleer", example_sentence: "Remplir le frigo." },
    { word: "Poubelle", meaning: "Trash can", reading: "poo-bel", example_sentence: "Sortir la poubelle." },
    { word: "Brosser", meaning: "To brush", reading: "broh-say", example_sentence: "Je me brosse les dents." },
    { word: "Se peigner", meaning: "To comb one's hair", reading: "suh pay-nyay", example_sentence: "Elle se peigne." },
    { word: "Se raser", meaning: "To shave", reading: "suh ra-zay", example_sentence: "Il se rase le matin." },
    { word: "Se maquiller", meaning: "To put on makeup", reading: "suh ma-kee-yay", example_sentence: "Elle se maquille." },
    { word: "S'habiller", meaning: "To get dressed", reading: "sa-bee-yay", example_sentence: "Dépêche-toi de t'habiller !" },
    { word: "Se déshabiller", meaning: "To undress", reading: "suh day-za-bee-yay", example_sentence: "Il se déshabille." },
    { word: "S'endormir", meaning: "To fall asleep", reading: "sahn-dor-meer", example_sentence: "Je m'endors vite." },
    { word: "Se réveiller", meaning: "To wake up", reading: "suh ray-vay-yay", example_sentence: "Je me réveille à six heures." },
    { word: "Se lever", meaning: "To get up", reading: "suh luh-vay", example_sentence: "Lève-toi !" },
    { word: "Se coucher", meaning: "To go to bed", reading: "suh koo-shay", example_sentence: "Il est tard, couchez-vous." },
    { word: "S'amuser", meaning: "To have fun", reading: "sa-moo-zay", example_sentence: "On s'amuse bien." },
    { word: "Se promener", meaning: "To take a walk", reading: "suh proh-muh-nay", example_sentence: "Allons nous promener." },
    { word: "Se reposer", meaning: "To rest", reading: "suh ruh-poh-zay", example_sentence: "Repose-toi un peu." },
    { word: "Drap", meaning: "Sheet", reading: "dra", example_sentence: "Changer les draps." },
    { word: "Couverture", meaning: "Blanket", reading: "koo-ver-toor", example_sentence: "Une couverture chaude." },
    { word: "Oreiller", meaning: "Pillow", reading: "oh-ray-yay", example_sentence: "Un oreiller moelleux." },
    { word: "Serviette", meaning: "Towel", reading: "ser-vyet", example_sentence: "Une serviette propre." },
    { word: "Savon", meaning: "Soap", reading: "sa-voh", example_sentence: "Utilisez du savon." },
    { word: "Shampooing", meaning: "Shampoo", reading: "sham-pwa", example_sentence: "Un shampooing doux." },
    { word: "Dentifrice", meaning: "Toothpaste", reading: "dahn-tee-frees", example_sentence: "Où est le dentifrice ?" },
    { word: "Bain", meaning: "Bath", reading: "ba", example_sentence: "Prendre un bain." },
    { word: "Douche", meaning: "Shower", reading: "doosh", example_sentence: "Une douche froide." },
    { word: "Miroir", meaning: "Mirror", reading: "mee-rwahr", example_sentence: "Se regarder dans le miroir." },
    { word: "Peigne", meaning: "Comb", reading: "pay-nyuh", example_sentence: "Un peigne en bois." },
    { word: "Rasoir", meaning: "Razor", reading: "ra-zwahr", example_sentence: "Un rasoir jetable." },
    { word: "Parfum", meaning: "Perfume", reading: "par-fa", example_sentence: "Un parfum délicat." },
    { word: "Routine", meaning: "Routine", reading: "roo-teen", example_sentence: "Ma routine matinale." },
    { word: "Habitude", meaning: "Habit", reading: "a-bee-tood", example_sentence: "C'est une mauvaise habitude." },
    { word: "Quotidien", meaning: "Daily", reading: "koh-tee-dyah", example_sentence: "Mon quotidien est calme." },
    { word: "Hebdomadaire", meaning: "Weekly", reading: "eb-doh-ma-der", example_sentence: "Un magazine hebdomadaire." },
    { word: "Mensuel", meaning: "Monthly", reading: "mahn-soo-el", example_sentence: "Un rapport mensuel." },
    { word: "Tâche", meaning: "Task / chore", reading: "tahsh", example_sentence: "Une tâche difficile." },
    { word: "Responsabilité", meaning: "Responsibility", reading: "res-pohn-sa-bee-lee-tay", example_sentence: "Chacun sa responsabilité." },
    { word: "Organisation", meaning: "Organization", reading: "or-ga-nee-za-syohn", example_sentence: "L'organisation est clé." },
    { word: "Emploi du temps", meaning: "Schedule", reading: "ahm-plwa doo tahm", example_sentence: "Un emploi du temps chargé." },
    { word: "Rendez-vous", meaning: "Appointment", reading: "rahn-day-voo", example_sentence: "J'ai un rendez-vous." },
    { word: "Retard", meaning: "Delay", reading: "ruh-tar", example_sentence: "Toujours en retard !" },
    { word: "Avance", meaning: "Advance", reading: "a-vahns", example_sentence: "Être en avance." },
    { word: "Punctualité", meaning: "Punctuality", reading: "pohn-ktoo-a-lee-tay", example_sentence: "La ponctualité est importante." },
    { word: "Bricolage", meaning: "DIY / Handiwork", reading: "bree-koh-lazh", example_sentence: "J'aime le bricolage." },
    { word: "Jardinage", meaning: "Gardening", reading: "zhar-dee-nazh", example_sentence: "Le jardinage est relaxant." },
    { word: "Réparer", meaning: "To repair", reading: "ray-pa-ray", example_sentence: "Réparer le vélo." },
    { word: "Casser", meaning: "To break", reading: "ka-say", example_sentence: "J'ai cassé un verre." },
    { word: "Vitre", meaning: "Window pane", reading: "veetroo", example_sentence: "Nettoyer les vitres." },
    { word: "Sol", meaning: "Floor / Ground", reading: "sohl", example_sentence: "Le sol est mouillé." },
    { word: "Plafond", meaning: "Ceiling", reading: "pla-foh", example_sentence: "Le plafond est haut." },
    { word: "Mur", meaning: "Wall", reading: "moor", example_sentence: "Peindre le mur." },
    { word: "Toit", meaning: "Roof", reading: "twa", example_sentence: "Le toit fuit." },
    { word: "Porte", meaning: "Door", reading: "port", example_sentence: "Fermez la porte." },
    { word: "Fenêtre", meaning: "Window", reading: "fuh-ne-truh", example_sentence: "Ouvrez la fenêtre." },
    { word: "Escalier", meaning: "Staircase", reading: "es-ka-lyay", example_sentence: "Grimper l'escalier." },
    { word: "Entrée", meaning: "Entrance", reading: "ahn-tray", example_sentence: "L'entrée de l'immeuble." },
    { word: "Sortie", meaning: "Exit", reading: "sor-tee", example_sentence: "Où est la sortie ?" },
    { word: "Couloir", meaning: "Hallway", reading: "koo-lwahr", example_sentence: "Le couloir est sombre." },
    { word: "Balcon", meaning: "Balcony", reading: "bal-koh", example_sentence: "Un grand balcon." },
    { word: "Terrasse", meaning: "Terrace", reading: "te-rahs", example_sentence: "Déjeuner en terrasse." },
    { word: "Garage", meaning: "Garage", reading: "ga-razh", example_sentence: "La voiture est au garage." },
    { word: "Cave", meaning: "Cellar / basement", reading: "kav", example_sentence: "La cave est humide." },
    { word: "Grenier", meaning: "Attic", reading: "gruh-nyay", example_sentence: "Chercher dans le grenier." },
    { word: "Cheminée", meaning: "Chimney / Fireplace", reading: "shuh-mee-nay", example_sentence: "Allumer la cheminée." },
    { word: "Chauffeur", meaning: "Driver / Heater (device)", reading: "shoh-fur", example_sentence: "Un chauffeur privé." },
    { word: "Électricité", meaning: "Electricity", reading: "ay-lek-tree-see-tay", example_sentence: "L'électricité est coupée." },
    { word: "Eau potable", meaning: "Drinking water", reading: "oh poh-ta-bluh", example_sentence: "C'est de l'eau potable." },
    { word: "Chauffage central", meaning: "Central heating", reading: "shoh-fazh sahn-tral", example_sentence: "Le chauffage central." },
    { word: "Clim", meaning: "AC (slang)", reading: "kleem", example_sentence: "Mets la clim." },
    { word: "Volet", meaning: "Shutter", reading: "voh-lay", example_sentence: "Fermer les volets." },
    { word: "Rideau", meaning: "Curtain", reading: "ree-doh", example_sentence: "Tirer les rideaux." },
    { word: "Tapis", meaning: "Rug", reading: "ta-pee", example_sentence: "Un tapis rouge." },
    { word: "Moquette", meaning: "Carpet", reading: "moh-ket", example_sentence: "La moquette est grise." },
    { word: "Carrelage", meaning: "Tiling", reading: "ka-ruh-lazh", example_sentence: "Un beau carrelage." },
    { word: "Parquet", meaning: "Hardwood floor", reading: "par-kay", example_sentence: "Un vieux parquet." },
    { word: "Meubles", meaning: "Furniture", reading: "muh-bluh", example_sentence: "Des meubles anciens." },
    { word: "Étagère", meaning: "Shelf", reading: "ay-ta-zher", example_sentence: "Mettre les livres sur l'étagère." },
    { word: "Armoire", meaning: "Wardrobe", reading: "ar-mwahr", example_sentence: "Ranger ses habits dans l'armoire." },
    { word: "Placard", meaning: "Cupboard", reading: "pla-kar", example_sentence: "Le placard est plein." },
    { word: "Tiroir", meaning: "Drawer", reading: "tee-rwahr", example_sentence: "Ouvrir le tiroir." },
    { word: "Lampe", meaning: "Lamp", reading: "lahmp", example_sentence: "Allume la lampe." },
    { word: "Ampoule", meaning: "Light bulb", reading: "ahm-pool", example_sentence: "Changer l'ampoule." },
    { word: "Interrupteur", meaning: "Switch", reading: "ah-te-roop-tur", example_sentence: "Appuie sur l'interrupteur." },
    { word: "Prise", meaning: "Socket / Plug", reading: "preez", example_sentence: "Brancher sur la prise." },
    { word: "Câble", meaning: "Cable", reading: "ka-bluh", example_sentence: "Le câble est trop court." },
    { word: "Rallonge", meaning: "Extension cord", reading: "ra-lohnzh", example_sentence: "Besoin d'une rallonge." },
    { word: "Pile", meaning: "Battery", reading: "peel", example_sentence: "Changer les piles." },
    { word: "Chargeur", meaning: "Charger", reading: "shar-zhur", example_sentence: "Où est mon chargeur ?" },
    { word: "Appareil", meaning: "Device / Appliance", reading: "a-pa-ray-yay", example_sentence: "Un appareil électrique." },
    { word: "Électroménager", meaning: "Household appliances", reading: "ay-lek-troh-may-na-zhay", example_sentence: "Le rayon électroménager." }
];

// --- MODULE 13: Work & Professional Life (A2) ---
const m13_items = [
    { word: "Carrière", meaning: "Career", reading: "ka-ryer", example_sentence: "Une belle carrière." },
    { word: "Emploi", meaning: "Job / Employment", reading: "ahm-plwa", example_sentence: "Chercher un emploi." },
    { word: "Recrutement", meaning: "Recruitment", reading: "ruh-kroot-mahn", example_sentence: "Le recrutement est ouvert." },
    { word: "Candidat", meaning: "Candidate", reading: "kahn-dee-da", example_sentence: "Un candidat sérieux." },
    { word: "Entretien", meaning: "Interview", reading: "ahn-truh-tyah", example_sentence: "Passer un entretien d'embauche." },
    { word: "Postuler", meaning: "To apply", reading: "poh-stoo-lay", example_sentence: "Postuler pour un poste." },
    { word: "Salaire", meaning: "Salary", reading: "sa-ler", example_sentence: "Un salaire attractif." },
    { word: "Contrat", meaning: "Contract", reading: "kohn-tra", example_sentence: "Signer un contrat." },
    { word: "CDI", meaning: "Permanent contract", reading: "say-day-ee", example_sentence: "J'ai obtenu un CDI." },
    { word: "CDD", meaning: "Temporary contract", reading: "say-day-day", example_sentence: "Un CDD de six mois." },
    { word: "Période d'essai", meaning: "Probation period", reading: "pay-ryohd day-say", example_sentence: "Ma période d'essai se termine." },
    { word: "Compétence", meaning: "Skill", reading: "kohm-pay-tahns", example_sentence: "Développer de nouvelles compétences." },
    { word: "Qualification", meaning: "Qualification", reading: "ka-lee-fee-ka-syohn", example_sentence: "Une haute qualification." },
    { word: "Expérience", meaning: "Experience", reading: "ek-spay-ryahns", example_sentence: "Avoir de l'expérience professionnelle." },
    { word: "Formation", meaning: "Training", reading: "for-ma-syohn", example_sentence: "Suivre une formation." },
    { word: "Stage", meaning: "Internship", reading: "stazh", example_sentence: "Faire un stage en entreprise." },
    { word: "Stagiaire", meaning: "Intern", reading: "sta-zhyer", example_sentence: "Le stagiaire aide beaucoup." },
    { word: "Apprenti", meaning: "Apprentice", reading: "a-prahn-tee", example_sentence: "Un jeune apprenti." },
    { word: "Directeur", meaning: "Director / Manager", reading: "dee-rek-tur", example_sentence: "Le directeur général." },
    { word: "Cadre", meaning: "Executive", reading: "ka-druh", example_sentence: "Travailler comme cadre." },
    { word: "Salarié", meaning: "Employee / Wage earner", reading: "sa-la-ryay", example_sentence: "Les droits des salariés." },
    { word: "Patron", meaning: "Boss / Employer", reading: "pa-troh", example_sentence: "Le patron est sympa." },
    { word: "Chef", meaning: "Chief / Boss", reading: "shef", example_sentence: "Le chef d'équipe." },
    { word: "Équipe", meaning: "Team", reading: "ay-keep", example_sentence: "Travailler en équipe." },
    { word: "Collaborateur", meaning: "Collaborator / Colleague", reading: "koh-la-boh-ra-tur", example_sentence: "Mes collaborateurs sont efficaces." },
    { word: "Partenaire", meaning: "Partner", reading: "par-tuh-ner", example_sentence: "Un partenaire commercial." },
    { word: "Client", meaning: "Client / Customer", reading: "klee-ahn", example_sentence: "Le client est satisfait." },
    { word: "Fournisseur", meaning: "Supplier", reading: "foor-nee-sur", example_sentence: "Changer de fournisseur." },
    { word: "Concurence", meaning: "Competition", reading: "kohn-koo-rahns", example_sentence: "La concurrence est forte." },
    { word: "Marché", meaning: "Market", reading: "mar-shay", example_sentence: "Le marché du travail." },
    { word: "Secteur", meaning: "Sector", reading: "sek-tur", example_sentence: "Le secteur bancaire." },
    { word: "Domaine", meaning: "Field / Domain", reading: "doh-men", example_sentence: "Mon domaine d'activité." },
    { word: "Responsable", meaning: "Responsible / Manager", reading: "res-pohn-sa-bluh", example_sentence: "Le responsable du projet." },
    { word: "Service", meaning: "Department", reading: "ser-vees", example_sentence: "Le service marketing." },
    { word: "Bureau", meaning: "Office", reading: "boo-roh", example_sentence: "Travailler au bureau." },
    { word: "Siège social", meaning: "Headquarters", reading: "syazh soh-syal", example_sentence: "Le siège social est à Paris." },
    { word: "Filiale", meaning: "Subsidiary", reading: "fee-lyal", example_sentence: "Une filiale en Espagne." },
    { word: "Atelier", meaning: "Workshop", reading: "a-tuh-lyay", example_sentence: "Un atelier de couture." },
    { word: "Usine", meaning: "Factory", reading: "oo-zeen", example_sentence: "Une usine moderne." },
    { word: "Chantier", meaning: "Construction site", reading: "shahn-tyay", example_sentence: "Visiter le chantier." },
    { word: "Poste", meaning: "Position / Job", reading: "pohst", example_sentence: "Un poste à responsabilité." },
    { word: "Mission", meaning: "Assignment / Task", reading: "mee-syohn", example_sentence: "Une mission temporaire." },
    { word: "Objectif", meaning: "Goal / Objective", reading: "ob-zhek-teef", example_sentence: "Atteindre ses objectifs." },
    { word: "Performance", meaning: "Performance", reading: "per-for-mahns", example_sentence: "Améliorer la performance." },
    { word: "Productivité", meaning: "Productivity", reading: "proh-dook-tee-vee-tay", example_sentence: "La productivité augmente." },
    { word: "Chiffre d'affaires", meaning: "Turnover", reading: "shee-fruh da-fer", example_sentence: "Un gros chiffre d'affaires." },
    { word: "Bénéfice", meaning: "Profit", reading: "bay-nay-fees", example_sentence: "Faire du bénéfice." },
    { word: "Perte", meaning: "Loss", reading: "pert", example_sentence: "Une perte financière." },
    { word: "Budget", meaning: "Budget", reading: "boo-dzheh", example_sentence: "Gérer le budget." },
    { word: "Réunion", meaning: "Meeting", reading: "ray-oo-nyohn", example_sentence: "Une réunion d'équipe." },
    { word: "Conférence", meaning: "Conference", reading: "kohn-fay-rahns", example_sentence: "Assister à une conférence." },
    { word: "Présentation", meaning: "Presentation", reading: "pray-zahn-ta-syohn", example_sentence: "Faire une présentation PowerPoint." },
    { word: "Rapport", meaning: "Report", reading: "ra-por", example_sentence: "Écrire un rapport d'activité." },
    { word: "Dossier", meaning: "File", reading: "doh-syay", example_sentence: "Classer les dossiers." },
    { word: "Document", meaning: "Document", reading: "doh-koo-mahn", example_sentence: "Signer le document." },
    { word: "Email", meaning: "Email", reading: "ee-mel", example_sentence: "Envoyer un email." },
    { word: "Courrier", meaning: "Mail", reading: "koo-ryay", example_sentence: "Le courrier du matin." },
    { word: "Appel", meaning: "Call", reading: "a-pel", example_sentence: "Passer un appel téléphonique." },
    { word: "Message", meaning: "Message", reading: "meh-sazh", example_sentence: "Laisser un message." },
    { word: "Note de service", meaning: "Memo", reading: "noht duh ser-vees", example_sentence: "Une note de service interne." },
    { word: "Planning", meaning: "Schedule / Planning", reading: "pla-neeng", example_sentence: "Consulter le planning." },
    { word: "Délai", meaning: "Deadline", reading: "day-leh", example_sentence: "Respecter les délais." },
    { word: "Retard", meaning: "Delay", reading: "ruh-tar", example_sentence: "Prendre du retard." },
    { word: "Avance", meaning: "Ahead of schedule", reading: "a-vahns", example_sentence: "Finir en avance." },
    { word: "Horaire", meaning: "Timetable", reading: "oh-rer", example_sentence: "Les horaires de travail." },
    { word: "Temps plein", meaning: "Full-time", reading: "tahn plah", example_sentence: "Travailler à temps plein." },
    { word: "Temps partiel", meaning: "Part-time", reading: "tahn par-syel", example_sentence: "Un job à temps partiel." },
    { word: "Heures supplémentaires", meaning: "Overtime", reading: "ur soo-play-mahn-ter", example_sentence: "Faire des heures sup'." },
    { word: "Congé", meaning: "Holiday / Leave", reading: "kohn-zhay", example_sentence: "Prendre un congé payé." },
    { word: "Vacances", meaning: "Vacation", reading: "va-kahns", example_sentence: "Partir en vacances." },
    { word: "Arrêt maladie", meaning: "Sick leave", reading: "a-re ma-la-dee", example_sentence: "Il est en arrêt maladie." },
    { word: "Retraite", meaning: "Retirement", reading: "ruh-tret", example_sentence: "Prendre sa retraite." },
    { word: "Démission", meaning: "Resignation", reading: "day-mee-syohn", example_sentence: "Donner sa démission." },
    { word: "Licenciement", meaning: "Redundancy / Dismissal", reading: "lee-sahn-see-mahn", example_sentence: "Un licenciement économique." },
    { word: "Chômage", meaning: "Unemployment", reading: "shoh-ma-zhuh", example_sentence: "Le taux de chômage." },
    { word: "Syndicat", meaning: "Union", reading: "san-dee-ka", example_sentence: "Adhérer à un syndicat." },
    { word: "Grève", meaning: "Strike", reading: "grev", example_sentence: "Le personnel est en grève." },
    { word: "Négociation", meaning: "Negotiation", reading: "nay-goh-syah-syohn", example_sentence: "Une négociation salariale." },
    { word: "Promotion", meaning: "Promotion", reading: "proh-moh-syohn", example_sentence: "Avoir une promotion." },
    { word: "Augmentation", meaning: "Increase / Raise", reading: "ohg-mahn-ta-syohn", example_sentence: "Une augmentation de salaire." },
    { word: "Prime", meaning: "Bonus", reading: "preem", example_sentence: "Toucher une prime." },
    { word: "Avantage", meaning: "Benefit", reading: "a-vahn-tazh", example_sentence: "Les avantages sociaux." },
    { word: "Impôt", meaning: "Tax", reading: "am-poh", example_sentence: "Payer des impôts." },
    { word: "Charge", meaning: "Charge / Expense", reading: "sharzh", example_sentence: "Les charges patronales." },
    { word: "Banque", meaning: "Bank", reading: "bahn-kuh", example_sentence: "Aller à la banque." },
    { word: "Compte", meaning: "Account", reading: "kohnt", example_sentence: "Ouvrir un compte bancaire." },
    { word: "Virement", meaning: "Transfer", reading: "veer-mahn", example_sentence: "Faire un virement bancaire." },
    { word: "Chèque", meaning: "Cheque", reading: "shek", example_sentence: "Payer par chèque." },
    { word: "Carte bancaire", meaning: "Bank card", reading: "kart bahn-ker", example_sentence: "Payer par carte." },
    { word: "Espèces", meaning: "Cash", reading: "es-pes", example_sentence: "Payer en espèces." },
    { word: "Crédit", meaning: "Credit", reading: "kray-dee", example_sentence: "Demander un crédit." },
    { word: "Dépense", meaning: "Expense", reading: "day-pahns", example_sentence: "Limiter ses dépenses." },
    { word: "Économie", meaning: "Saving / Economy", reading: "ay-koh-noh-mee", example_sentence: "Faire des économies." },
    { word: "Investissement", meaning: "Investment", reading: "an-ves-tees-mahn", example_sentence: "Un bon investissement." },
    { word: "Assurance", meaning: "Insurance", reading: "a-soo-rahns", example_sentence: "Une assurance professionnelle." },
    { word: "Risque", meaning: "Risk", reading: "reesk", example_sentence: "Gérer les risques." },
    { word: "Sécurité", meaning: "Security", reading: "say-koo-ree-tay", example_sentence: "La sécurité au travail." },
    { word: "Santé", meaning: "Health", reading: "sahn-tay", example_sentence: "La santé mentale." },
    { word: "Stress", meaning: "Stress", reading: "stres", example_sentence: "Le stress professionnel." },
    { word: "Équilibre", meaning: "Balance", reading: "ay-kee-lee-bruh", example_sentence: "L'équilibre vie pro - vie perso." }
];

// --- MODULE 14: Social Life & Leisure (A2) ---
const m14_items = [
    { word: "Loisir", meaning: "Leisure", reading: "lwa-zeer", example_sentence: "Le temps libre et les loisirs." },
    { word: "Passe-temps", meaning: "Hobby", reading: "pas-tahn", example_sentence: "Quel est ton passe-temps favori ?" },
    { word: "Sortie", meaning: "Outing", reading: "sor-tee", example_sentence: "Prévoir une sortie entre amis." },
    { word: "Soirée", meaning: "Evening / Party", reading: "swa-ray", example_sentence: "Organiser une soirée." },
    { word: "Invitation", meaning: "Invitation", reading: "an-vee-ta-syohn", example_sentence: "Envoyer une invitation." },
    { word: "Invité", meaning: "Guest", reading: "an-vee-tay", example_sentence: "Les invités arrivent." },
    { word: "Hôte", meaning: "Host", reading: "oht", example_sentence: "Merci à notre hôte." },
    { word: "Fête", meaning: "Party / Celebration", reading: "fet", example_sentence: "C'est la fête aujourd'hui !" },
    { word: "Anniversaire", meaning: "Birthday / Anniversary", reading: "a-nee-ver-ser", example_sentence: "Bon anniversaire !" },
    { word: "Cadeau", meaning: "Gift", reading: "ka-doh", example_sentence: "Acheter un cadeau." },
    { word: "Surprise", meaning: "Surprise", reading: "soor-preez", example_sentence: "Une bonne surprise." },
    { word: "Rencontre", meaning: "Meeting / Encounter", reading: "rahn-kohnt", example_sentence: "Une rencontre imprévue." },
    { word: "Ami", meaning: "Friend", reading: "a-mee", example_sentence: "Mon meilleur ami." },
    { word: "Copain", meaning: "Buddy / Boyfriend", reading: "koh-pa", example_sentence: "Sortir avec des copains." },
    { word: "Collègue", meaning: "Colleague", reading: "koh-leg", example_sentence: "Un collègue de bureau." },
    { word: "Voisin", meaning: "Neighbor", reading: "vwa-za", example_sentence: "Une voisine sympatique." },
    { word: "Connaissance", meaning: "Acquaintance", reading: "koh-ne-sahns", example_sentence: "C'est juste une connaissance." },
    { word: "Relation", meaning: "Relation / Connection", reading: "ruh-la-syohn", example_sentence: "Une relation amicale." },
    { word: "Rendez-vous", meaning: "Meeting / Date", reading: "rahn-day-voo", example_sentence: "Prendre rendez-vous." },
    { word: "Sortir", meaning: "To go out", reading: "sor-teer", example_sentence: "Sortir le samedi soir." },
    { word: "Danser", meaning: "To dance", reading: "dahn-say", example_sentence: "Aimer danser." },
    { word: "Chanter", meaning: "To sing", reading: "shahn-tay", example_sentence: "Chanter une chanson." },
    { word: "Rire", meaning: "To laugh", reading: "reer", example_sentence: "Rire aux éclats." },
    { word: "Sourire", meaning: "To smile", reading: "soo-reer", example_sentence: "Garder le sourire." },
    { word: "Discuter", meaning: "To discuss / chat", reading: "dees-koo-tay", example_sentence: "Discuter pendant des heures." },
    { word: "Bavarder", meaning: "To chat / gossip", reading: "ba-var-day", example_sentence: "Bavarder au téléphone." },
    { word: "Échanger", meaning: "To exchange", reading: "ay-shahn-zhay", example_sentence: "Échanger des idées." },
    { word: "Partager", meaning: "To share", reading: "par-ta-zhay", example_sentence: "Partager un bon moment." },
    { word: "Offrir", meaning: "To offer / give", reading: "oh-freer", example_sentence: "Offrir des fleurs." },
    { word: "Recevoir", meaning: "To receive", reading: "ruh-suh-vwahr", example_sentence: "Recevoir un message." },
    { word: "Accepter", meaning: "To accept", reading: "a-sep-tay", example_sentence: "Accepter une proposition." },
    { word: "Refuser", meaning: "To refuse", reading: "ruh-foo-zay", example_sentence: "Refuser poliment." },
    { word: "S'entendre", meaning: "To get along", reading: "sahn-tahn-druh", example_sentence: "Ils s'entendent bien." },
    { word: "Se disputer", meaning: "To argue", reading: "suh dees-poo-tay", example_sentence: "Ils se disputent souvent." },
    { word: "Se réconcilier", meaning: "To reconcile", reading: "suh ray-kohn-see-lyay", example_sentence: "Se réconcilier après une dispute." },
    { word: "Cinéma", meaning: "Cinema", reading: "see-nay-ma", example_sentence: "Aller au cinéma." },
    { word: "Film", meaning: "Movie", reading: "feelm", example_sentence: "Un film d'action." },
    { word: "Théâtre", meaning: "Theater", reading: "tay-a-truh", example_sentence: "Une pièce de théâtre." },
    { word: "Spectacle", meaning: "Show / Performance", reading: "spek-ta-kluh", example_sentence: "Un spectacle de magie." },
    { word: "Concert", meaning: "Concert", reading: "kohn-ser", example_sentence: "Un concert de rock." },
    { word: "Opéra", meaning: "Opera", reading: "oh-pay-ra", example_sentence: "Aimer l'opéra." },
    { word: "Ballet", meaning: "Ballet", reading: "ba-lay", example_sentence: "Un spectacle de ballet." },
    { word: "Musée", meaning: "Museum", reading: "moo-zay", example_sentence: "Visiter le musée du Louvre." },
    { word: "Exposition", meaning: "Exhibition", reading: "ek-spoh-zee-syohn", example_sentence: "Une exposition de peinture." },
    { word: "Peinture", meaning: "Painting", reading: "pan-toor", example_sentence: "La peinture moderne." },
    { word: "Sculpture", meaning: "Sculpture", reading: "skool-toor", example_sentence: "Une sculpture en bronze." },
    { word: "Galerie", meaning: "Gallery", reading: "ga-luh-ree", example_sentence: "Une galerie d'art." },
    { word: "Bibliothèque", meaning: "Library", reading: "bee-blee-oh-tek", example_sentence: "Emprunter des livres à la bibliothèque." },
    { word: "Librairie", meaning: "Bookstore", reading: "lee-brer-ree", example_sentence: "Acheter un livre à la librairie." },
    { word: "Lecture", meaning: "Reading", reading: "lek-toor", example_sentence: "La lecture est un plaisir." },
    { word: "Club", meaning: "Club", reading: "kloob", example_sentence: "Adhérer à un club de sport." },
    { word: "Association", meaning: "Association", reading: "a-soh-syah-syohn", example_sentence: "Une association caritative." },
    { word: "Bénévolat", meaning: "Volunteering", reading: "bay-nay-voh-la", example_sentence: "Faire du bénévolat." },
    { word: "Bénévole", meaning: "Volunteer", reading: "bay-nay-vohl", example_sentence: "Travailler comme bénévole." },
    { word: "Sport", meaning: "Sport", reading: "spor", example_sentence: "Pratiquer un sport." },
    { word: "Entraînement", meaning: "Training / Practice", reading: "ahn-treh-nuh-mahn", example_sentence: "Un entraînement intensif." },
    { word: "Match", meaning: "Match / Game", reading: "match", example_sentence: "Gagner le match." },
    { word: "Compétition", meaning: "Competition", reading: "kohm-pay-tee-syohn", example_sentence: "Participer à une compétition." },
    { word: "Stade", meaning: "Stadium", reading: "stad", example_sentence: "Aller au stade." },
    { word: "Équipe", meaning: "Team", reading: "ay-keep", example_sentence: "Mon équipe favorite." },
    { word: "Joueur", meaning: "Player", reading: "zhoo-ur", example_sentence: "Un joueur talentueux." },
    { word: "Arbitre", meaning: "Referee", reading: "ar-bee-truh", example_sentence: "L'arbitre siffle." },
    { word: "Victoire", meaning: "Victory", reading: "veek-twahr", example_sentence: "Une victoire historique." },
    { word: "Défaite", meaning: "Defeat", reading: "day-fet", example_sentence: "Accepter la défaite." },
    { word: "Score", meaning: "Score", reading: "skor", example_sentence: "Le score est de deux à zéro." },
    { word: "Championnat", meaning: "Championship", reading: "sham-pyoh-na", example_sentence: "Le championnat de France." },
    { word: "Randonnée", meaning: "Hiking", reading: "rahn-doh-nay", example_sentence: "Faire une randonnée en forêt." },
    { word: "Camping", meaning: "Camping", reading: "kahm-peeng", example_sentence: "Faire du camping l'été." },
    { word: "Pêche", meaning: "Fishing", reading: "pesh", example_sentence: "Aller à la pêche." },
    { word: "Chasse", meaning: "Hunting", reading: "shas", example_sentence: "La chasse est réglementée." },
    { word: "Baignade", meaning: "Swimming / Bathing", reading: "beh-nyad", example_sentence: "La baignade est surveillée." },
    { word: "Plage", meaning: "Beach", reading: "plazh", example_sentence: "Aller à la plage." },
    { word: "Piscine", meaning: "Swimming pool", reading: "pee-seen", example_sentence: "Aller à la piscine." },
    { word: "Montagne", meaning: "Mountain", reading: "mohn-ta-nyuh", example_sentence: "Faire du ski à la montagne." },
    { word: "Ski", meaning: "Skiing", reading: "skee", example_sentence: "Aimer le ski." },
    { word: "Voyage", meaning: "Travel / Trip", reading: "vwa-yazh", example_sentence: "Un voyage inoubliable." },
    { word: "Vacances", meaning: "Vacation", reading: "va-kahns", example_sentence: "Bonnes vacances !" },
    { word: "Tourisme", meaning: "Tourism", reading: "too-reez-muh", example_sentence: "Le tourisme de masse." },
    { word: "Guide", meaning: "Guide", reading: "geed", example_sentence: "Un guide touristique." },
    { word: "Visite", meaning: "Visit", reading: "vee-zeet", example_sentence: "Une visite guidée." },
    { word: "Circuit", meaning: "Tour / Circuit", reading: "seer-kwee", example_sentence: "Un circuit organisé." },
    { word: "Hôtel", meaning: "Hotel", reading: "oh-tel", example_sentence: "Réserver un hôtel." },
    { word: "Réservation", meaning: "Reservation", reading: "ray-zer-va-syohn", example_sentence: "Faire une réservation." },
    { word: "Chambre", meaning: "Room", reading: "shahm-bruh", example_sentence: "Une chambre double." },
    { word: "Hébergement", meaning: "Accommodation", reading: "ay-berzh-mahn", example_sentence: "Un hébergement confortable." },
    { word: "Restaurant", meaning: "Restaurant", reading: "res-toh-rahn", example_sentence: "Manger au restaurant." },
    { word: "Menu", meaning: "Menu", reading: "muh-noo", example_sentence: "Consulter le menu." },
    { word: "Carte", meaning: "Menu / Card", reading: "kart", example_sentence: "La carte des vins." },
    { word: "Plat", meaning: "Dish", reading: "pla", example_sentence: "Le plat du jour." },
    { word: "Dessert", meaning: "Dessert", reading: "day-ser", example_sentence: "Prendre un dessert." },
    { word: "Addition", meaning: "Bill / Check", reading: "a-dee-syohn", example_sentence: "Payer l'addition." },
    { word: "Pourboire", meaning: "Tip", reading: "poor-bwahr", example_sentence: "Laisser un pourboire." },
    { word: "Café", meaning: "Coffee / Cafe", reading: "ka-fay", example_sentence: "Se voir au café." },
    { word: "Bar", meaning: "Bar / Pub", reading: "bar", example_sentence: "Prendre un verre au bar." },
    { word: "Terrasse", meaning: "Terrace / Outdoor seating", reading: "te-rahs", example_sentence: "S'installer en terrasse." },
    { word: "Ambiance", meaning: "Atmosphere / Vibe", reading: "ahm-byahns", example_sentence: "Une ambiance chaleureuse." },
    { word: "Musique", meaning: "Music", reading: "moo-zeek", example_sentence: "Écouter de la musique." },
    { word: "Radio", meaning: "Radio", reading: "ra-dyoh", example_sentence: "Écouter la radio." },
    { word: "Télévision", meaning: "Television", reading: "tay-lay-vee-zyohn", example_sentence: "Regarder la télévision." },
    { word: "Actualité", meaning: "News / Current events", reading: "ak-too-a-lee-tay", example_sentence: "Suivre l'actualité." }
];

const m12 = createModule('fr_a2_m12', 'A2 French - Module 12: Daily Life', 12, m12_items);
const m13 = createModule('fr_a2_m13', 'A2 French - Module 13: Professional Life', 13, m13_items);
const m14 = createModule('fr_a2_m14', 'A2 French - Module 14: Social & Leisure', 14, m14_items);

fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m12.json'), JSON.stringify(m12, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m13.json'), JSON.stringify(m13, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m14.json'), JSON.stringify(m14, null, 2));

console.log('✅ Generated French A2 Modules 12, 13, and 14.');
