const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100)
    };
}

// --- MODULE 18: Arts & Culture (A2) ---
const m18_items = [
    { word: "Culture", meaning: "Culture", reading: "kool-toor", example_sentence: "La culture française est riche." },
    { word: "Artiste", meaning: "Artist", reading: "ar-teest", example_sentence: "Un artiste talentueux." },
    { word: "Peintre", meaning: "Painter", reading: "pan-truh", example_sentence: "Mon frère est peintre." },
    { word: "Écrivain", meaning: "Writer", reading: "ay-kree-vah", example_sentence: "Un écrivain célèbre." },
    { word: "Musicien", meaning: "Musician", reading: "moo-zee-syah", example_sentence: "Elle est musicienne." },
    { word: "Acteur", meaning: "Actor", reading: "ak-tur", example_sentence: "Un acteur connu." },
    { word: "Actrice", meaning: "Actress", reading: "ak-trees", example_sentence: "Une excellente actrice." },
    { word: "Spectacle", meaning: "Show / Performance", reading: "spek-ta-kluh", example_sentence: "Quel beau spectacle !" },
    { word: "Théâtre", meaning: "Theater", reading: "tay-a-truh", example_sentence: "Aller au théâtre." },
    { word: "Cinéma", meaning: "Cinema / Movies", reading: "see-nay-ma", example_sentence: "Le septième art." },
    { word: "Musée", meaning: "Museum", reading: "moo-zay", example_sentence: "Visiter une galerie au musée." },
    { word: "Exposition", meaning: "Exhibition", reading: "ek-spoh-zee-syohn", example_sentence: "Une expo de photos." },
    { word: "Peinture", meaning: "Painting", reading: "pan-toor", example_sentence: "Une peinture à l'huile." },
    { word: "Dessin", meaning: "Drawing", reading: "day-sa", example_sentence: "Faire un dessin." },
    { word: "Sculpture", meaning: "Sculpture", reading: "skool-toor", example_sentence: "Une sculpture moderne." },
    { word: "Architecture", meaning: "Architecture", reading: "ar-shee-tek-toor", example_sentence: "L'architecture gothique." },
    { word: "Musique", meaning: "Music", reading: "moo-zeek", example_sentence: "Écouter de la musique classique." },
    { word: "Chanson", meaning: "Song", reading: "shahn-soh", example_sentence: "Une chanson d'amour." },
    { word: "Chanteur", meaning: "Singer", reading: "shahn-tur", example_sentence: "Un chanteur populaire." },
    { word: "Concert", meaning: "Concert", reading: "kohn-ser", example_sentence: "Le concert commence à 20h." },
    { word: "Instrument", meaning: "Instrument", reading: "an-stroo-mahn", example_sentence: "Jouer d'un instrument." },
    { word: "Piano", meaning: "Piano", reading: "pya-noh", example_sentence: "Jouer du piano." },
    { word: "Guitare", meaning: "Guitar", reading: "gee-tar", example_sentence: "Apprendre la guitare." },
    { word: "Violon", meaning: "Violin", reading: "vyoh-loh", example_sentence: "Un beau son de violon." },
    { word: "Batterie", meaning: "Drums", reading: "ba-tree", example_sentence: "Jouer de la batterie." },
    { word: "Danse", meaning: "Dance", reading: "dahns", example_sentence: "Prendre des cours de danse." },
    { word: "Ballet", meaning: "Ballet", reading: "ba-lay", example_sentence: "Une danseuse de ballet." },
    { word: "Opéra", meaning: "Opera", reading: "oh-pay-ra", example_sentence: "Aller à l'opéra." },
    { word: "Festival", meaning: "Festival", reading: "fes-tee-val", example_sentence: "Un festival de jazz." },
    { word: "Littérature", meaning: "Literature", reading: "lee-tay-ra-toor", example_sentence: "Aimer la littérature française." },
    { word: "Roman", meaning: "Novel", reading: "roh-mahn", example_sentence: "Lire un roman policier." },
    { word: "Poésie", meaning: "Poetry", reading: "poh-ay-zee", example_sentence: "Écrire de la poésie." },
    { word: "Poème", meaning: "Poem", reading: "poh-em", example_sentence: "Réciter un poème." },
    { word: "Livre", meaning: "Book", reading: "lee-vruh", example_sentence: "Un livre passionnant." },
    { word: "Bande dessinée", meaning: "Comic book", reading: "bahnd day-see-nay", example_sentence: "Lire une BD." },
    { word: "Histoire", meaning: "History / Story", reading: "ees-twahr", example_sentence: "Une histoire drôle." },
    { word: "Conte", meaning: "Tale / Story", reading: "kohnt", example_sentence: "Un conte de fées." },
    { word: "Bibliothèque", meaning: "Library", reading: "bee-blee-oh-tek", example_sentence: "Réviser à la bibliothèque." },
    { word: "Patrimoine", meaning: "Heritage", reading: "pa-tree-mwan", example_sentence: "Le patrimoine mondial." },
    { word: "Monument", meaning: "Monument", reading: "moh-noo-mahn", example_sentence: "Un monument historique." },
    { word: "Château", meaning: "Castle", reading: "sha-toh", example_sentence: "Visiter les châteaux de la Loire." },
    { word: "Cathédrale", meaning: "Cathedral", reading: "ka-tay-dral", example_sentence: "Une cathédrale immense." },
    { word: "Église", meaning: "Church", reading: "ay-gleez", example_sentence: "L'église du village." },
    { word: "Tradition", meaning: "Tradition", reading: "tra-dee-syohn", example_sentence: "Respecter les traditions." },
    { word: "Coutume", meaning: "Custom", reading: "koo-toom", example_sentence: "Une coutume locale." },
    { word: "Folklore", meaning: "Folklore", reading: "fohl-klor", example_sentence: "Le folklore régional." },
    { word: "Fête populaire", meaning: "Folk festival", reading: "fet poh-poo-ler", example_sentence: "Une fête populaire." },
    { word: "Gastronomie", meaning: "Gastronomy", reading: "gas-troh-noh-mee", example_sentence: "La gastronomie française." },
    { word: "Cuisine", meaning: "Cuisine / Kitchen", reading: "kwee-zeen", example_sentence: "La cuisine du monde." },
    { word: "Spécialité", meaning: "Specialty", reading: "spay-syah-lee-tay", example_sentence: "Quelle est la spécialité locale ?" },
    { word: "Recette", meaning: "Recipe", reading: "ruh-set", example_sentence: "Une recette de grand-mère." },
    { word: "Ingrédient", meaning: "Ingredient", reading: "an-gray-dyah", example_sentence: "Acheter les ingrédients." },
    { word: "Dégustation", meaning: "Tasting", reading: "day-goos-ta-syohn", example_sentence: "Une dégustation de vin." },
    { word: "Saveur", meaning: "Flavor", reading: "sa-vur", example_sentence: "Une saveur épicée." },
    { word: "Parfum", meaning: "Scent / Flavor", reading: "par-fa", example_sentence: "Une glace parfum vanille." },
    { word: "Élégance", meaning: "Elegance", reading: "ay-lay-gahns", example_sentence: "L'élégance à la française." },
    { word: "Mode", meaning: "Fashion", reading: "mohd", example_sentence: "La mode de Paris." },
    { word: "Style", meaning: "Style", reading: "steel", example_sentence: "Avoir du style." },
    { word: "Vêtement", meaning: "Clothing", reading: "vet-mahn", example_sentence: "Un vêtement de marque." },
    { word: "Créateur", meaning: "Creator / Designer", reading: "kray-a-tur", example_sentence: "Un créateur de mode." },
    { word: "Défilé", meaning: "Parade / Fashion show", reading: "day-fee-lay", example_sentence: "Assister à un défilé." },
    { word: "Luxe", meaning: "Luxury", reading: "looks", example_sentence: "Un hôtel de luxe." },
    { word: "Beauté", meaning: "Beauty", reading: "boh-tay", example_sentence: "La beauté d'un paysage." },
    { word: "Inspiration", meaning: "Inspiration", reading: "an-spee-ra-syohn", example_sentence: "Trouver l'inspiration." },
    { word: "Créativité", meaning: "Creativity", reading: "kray-a-tee-vee-tay", example_sentence: "Manquer de créativité." },
    { word: "Imagination", meaning: "Imagination", reading: "ee-ma-zhee-na-syohn", example_sentence: "Utiliser son imagination." },
    { word: "Talent", meaning: "Talent", reading: "ta-lah", example_sentence: "Un grand talent musical." },
    { word: "Don", meaning: "Gift / Talent", reading: "doh", example_sentence: "Elle a un don pour le dessin." },
    { word: "Apprécier", meaning: "To appreciate", reading: "a-pray-syay", example_sentence: "J'apprécie cet art." },
    { word: "Critiquer", meaning: "To criticize", reading: "kree-tee-kay", example_sentence: "Ne critiquez pas sans savoir." },
    { word: "Collection", meaning: "Collection", reading: "koh-lek-syohn", example_sentence: "Une collection d'art." },
    { word: "Objet d'art", meaning: "Work of art", reading: "ob-zhay dar", example_sentence: "Un bel objet d'art." },
    { word: "Original", meaning: "Original", reading: "oh-ree-zhee-nal", example_sentence: "Un tableau original." },
    { word: "Copie", meaning: "Copy", reading: "koh-pee", example_sentence: "C'est une simple copie." },
    { word: "Chef-d'œuvre", meaning: "Masterpiece", reading: "she-duh-vruh", example_sentence: "Le Louvre possède des chefs-d'œuvre." },
    { word: "Caduque", meaning: "Obsolete / Caducous", reading: "ka-dook", example_sentence: "Un style caduque." },
    { word: "Moderne", meaning: "Modern", reading: "moh-dern", example_sentence: "L'art moderne." },
    { word: "Contemporain", meaning: "Contemporary", reading: "kohn-tahm-poh-rah", example_sentence: "L'art contemporain." },
    { word: "Classique", meaning: "Classic", reading: "kla-seek", example_sentence: "La musique classique." },
    { word: "Populaire", meaning: "Popular / Folk", reading: "poh-poo-ler", example_sentence: "La culture populaire." },
    { word: "Élitiste", meaning: "Elitist", reading: "ay-lee-teest", example_sentence: "Un art élitiste." },
    { word: "Public", meaning: "Public / Audience", reading: "poo-bleek", example_sentence: "Le public applaudit." },
    { word: "Spectateur", meaning: "Spectator", reading: "spek-ta-tur", example_sentence: "Un spectateur attentif." },
    { word: "Auditeur", meaning: "Listener", reading: "oh-dee-tur", example_sentence: "Les auditeurs de la radio." },
    { word: "Lecteur", meaning: "Reader", reading: "lek-tur", example_sentence: "Un lecteur assidu." },
    { word: "Amateur", meaning: "Amateur / Lover of art", reading: "a-ma-tur", example_sentence: "Un amateur d'art." },
    { word: "Passionné", meaning: "Passionate / Fan", reading: "pa-syoh-nay", example_sentence: "Un passionné de cinéma." },
    { word: "Curieux", meaning: "Curious", reading: "koo-ryuh", example_sentence: "Soyez curieux de tout." },
    { word: "Ouverture d'esprit", meaning: "Open-mindedness", reading: "oo-ver-toor des-pree", example_sentence: "L'ouverture d'esprit est nécessaire." },
    { word: "Diversité", meaning: "Diversity", reading: "dee-ver-see-tay", example_sentence: "La diversité culturelle." },
    { word: "Échange", meaning: "Exchange", reading: "ay-shahnzh", example_sentence: "Un échange culturel." },
    { word: "Voyage", meaning: "Voyage / Travel", reading: "vwa-yazh", example_sentence: "Le voyage forme la jeunesse." },
    { word: "Découverte", meaning: "Discovery", reading: "day-koo-vert", example_sentence: "Une belle découverte." },
    { word: "Apprentissage", meaning: "Learning", reading: "a-prahn-tee-sazh", example_sentence: "L'apprentissage d'une langue." },
    { word: "Éducation", meaning: "Education", reading: "ay-doo-ka-syohn", example_sentence: "L'éducation artistique." },
    { word: "Savoir", meaning: "Knowledge / To know", reading: "sa-vwahr", example_sentence: "Le savoir est une richesse." },
    { word: "Connaissance", meaning: "Knowledge", reading: "koh-ne-sahns", example_sentence: "Approfondir ses connaissances." },
    { word: "Esprit", meaning: "Spirit / Mind", reading: "es-pree", example_sentence: "Un esprit critique." },
    { word: "Société", meaning: "Society", reading: "soh-syay-tay", example_sentence: "Vivre en société." },
    { word: "Valeur", meaning: "Value", reading: "va-lur", example_sentence: "Les valeurs morales." }
];

// --- MODULE 19: Future Plans & Ambitions (A2) ---
const m19_items = [
    { word: "Futur", meaning: "Future", reading: "foo-toor", example_sentence: "Penser au futur." },
    { word: "Avenir", meaning: "Future / Prospects", reading: "a-vuh-neer", example_sentence: "L'avenir nous le dira." },
    { word: "Projet", meaning: "Project / Plan", reading: "proh-zhay", example_sentence: "J'ai un nouveau projet." },
    { word: "Plan", meaning: "Plan", reading: "plahn", example_sentence: "Faire un plan." },
    { word: "Ambition", meaning: "Ambition", reading: "ahm-bee-syohn", example_sentence: "Avoir de l'ambition." },
    { word: "Rêve", meaning: "Dream", reading: "rev", example_sentence: "Réaliser ses rêves." },
    { word: "Voeu", meaning: "Wish / Vow", reading: "vuh", example_sentence: "Faire un voeu." },
    { word: "Objectif", meaning: "Objective / Goal", reading: "ob-zhek-teef", example_sentence: "Se fixer des objectifs." },
    { word: "But", meaning: "Goal / Aim", reading: "boot", example_sentence: "Quel est ton but ?" },
    { word: "Intention", meaning: "Intention", reading: "an-tahn-syohn", example_sentence: "C'est mon intention." },
    { word: "Décision", meaning: "Decision", reading: "day-see-zyohn", example_sentence: "Prendre une décision." },
    { word: "Choix", meaning: "Choice", reading: "shwa", example_sentence: "C'est ton choix." },
    { word: "Option", meaning: "Option", reading: "op-syohn", example_sentence: "Considérer les options." },
    { word: "Possibilité", meaning: "Possibility", reading: "poh-see-bee-lee-tay", example_sentence: "Une possibilité réelle." },
    { word: "Opportunité", meaning: "Opportunity", reading: "oh-por-too-nee-tay", example_sentence: "Saisir l'opportunité." },
    { word: "Changement", meaning: "Change", reading: "shahn-zhuh-mahn", example_sentence: "Le changement est bon." },
    { word: "Évolution", meaning: "Evolution", reading: "ay-voh-loo-syohn", example_sentence: "L'évolution de la situation." },
    { word: "Développement", meaning: "Development", reading: "day-vuh-lohp-mahn", example_sentence: "Le développement personnel." },
    { word: "Progrès", meaning: "Progress", reading: "proh-gray", example_sentence: "Faire des progrès." },
    { word: "Succès", meaning: "Success", reading: "sook-say", example_sentence: "Un succès mérité." },
    { word: "Réussite", meaning: "Success / Achievement", reading: "ray-oo-seet", example_sentence: "La réussite aux examens." },
    { word: "Échec", meaning: "Failure", reading: "ay-shek", example_sentence: "Un échec constructif." },
    { word: "Effort", meaning: "Effort", reading: "ay-for", example_sentence: "Faire un effort." },
    { word: "Travail", meaning: "Work / Effort", reading: "tra-vahy", example_sentence: "Le travail paie." },
    { word: "Motivation", meaning: "Motivation", reading: "moh-tee-va-syohn", example_sentence: "Manquer de motivation." },
    { word: "Détermination", meaning: "Determination", reading: "day-ter-mee-na-syohn", example_sentence: "Une forte détermination." },
    { word: "Persévérance", meaning: "Perseverance", reading: "per-say-vay-rahns", example_sentence: "La persévérance est la clé." },
    { word: "Confiance", meaning: "Confidence / Trust", reading: "kohn-fyahns", example_sentence: "Avoir confiance en soi." },
    { word: "Courage", meaning: "Courage", reading: "koo-razh", example_sentence: "Prendre son courage à deux mains." },
    { word: "Espoir", meaning: "Hope", reading: "es-pwahr", example_sentence: "Garder espoir." },
    { word: "Optimisme", meaning: "Optimism", reading: "op-tee-meez-muh", example_sentence: "Faire preuve d'optimisme." },
    { word: "Chance", meaning: "Luck / Chance", reading: "shahns", example_sentence: "Bonne chance !" },
    { word: "Destin", meaning: "Destiny", reading: "des-tah", example_sentence: "Suivre son destin." },
    { word: "Sort", meaning: "Fate / Luck", reading: "sor", example_sentence: "Le sort en est jeté." },
    { word: "Vie", meaning: "Life", reading: "vee", example_sentence: "C'est la vie !" },
    { word: "Parcours", meaning: "Path / Career", reading: "par-koor", example_sentence: "Un parcours atypique." },
    { word: "Route", meaning: "Road / Way", reading: "root", example_sentence: "Sur la bonne route." },
    { word: "Direction", meaning: "Direction", reading: "dee-rek-syohn", example_sentence: "Prendre une direction." },
    { word: "Orientation", meaning: "Orientation", reading: "oh-ryahn-ta-syohn", example_sentence: "Une orientation professionnelle." },
    { word: "Formation", meaning: "Training", reading: "for-ma-syohn", example_sentence: "Faire une formation." },
    { word: "Étude", meaning: "Study", reading: "ay-tood", example_sentence: "Faire des études supérieures." },
    { word: "Diplôme", meaning: "Diploma", reading: "dee-plohm", example_sentence: "Obtenir son diplôme." },
    { word: "Carrière", meaning: "Career", reading: "ka-ryer", example_sentence: "Une carrière internationale." },
    { word: "Échelon", meaning: "Step / Level", reading: "ay-shuh-loh", example_sentence: "Monter les échelons." },
    { word: "Promotion", meaning: "Promotion", reading: "proh-moh-syohn", example_sentence: "Une promotion méritée." },
    { word: "Responsabilité", meaning: "Responsibility", reading: "res-pohn-sa-bee-lee-tay", example_sentence: "Prendre ses responsabilités." },
    { word: "Défi", meaning: "Challenge", reading: "day-fee", example_sentence: "Relever un défi." },
    { word: "Obstacle", meaning: "Obstacle", reading: "ob-sta-kluh", example_sentence: "Surmonter les obstacles." },
    { word: "Solution", meaning: "Solution", reading: "soh-loo-syohn", example_sentence: "Trouver une solution." },
    { word: "Moyen", meaning: "Mean / Way", reading: "mwa-yah", example_sentence: "Un moyen efficace." },
    { word: "Ressource", meaning: "Resource", reading: "ruh-soors", example_sentence: "Utiliser toutes ses ressources." },
    { word: "Appui", meaning: "Support", reading: "a-pwee", example_sentence: "Chercher un appui." },
    { word: "Aide", meaning: "Help", reading: "ed", example_sentence: "Besoin d'aide ?" },
    { word: "Collaboration", meaning: "Collaboration", reading: "koh-la-boh-ra-syohn", example_sentence: "Une collaboration réussie." },
    { word: "Partenariat", meaning: "Partnership", reading: "par-tuh-na-rya", example_sentence: "Créer un partenariat." },
    { word: "Réseautage", meaning: "Networking", reading: "ray-zoh-tazh", example_sentence: "Le réseautage est utile." },
    { word: "Relation", meaning: "Relation", reading: "ruh-la-syohn", example_sentence: "Une bonne relation." },
    { word: "Communication", meaning: "Communication", reading: "koh-moo-nee-ka-syohn", example_sentence: "Une communication fluide." },
    { word: "Indépendance", meaning: "Independence", reading: "an-day-pahn-dahns", example_sentence: "Chercher l'indépendance." },
    { word: "Liberté", meaning: "Liberty", reading: "lee-ber-tay", example_sentence: "La liberté d'entreprendre." },
    { word: "Autonomie", meaning: "Autonomy", reading: "oh-toh-noh-mee", example_sentence: "Travailler en autonomie." },
    { word: "Sécurité", meaning: "Security", reading: "say-koo-ree-tay", example_sentence: "La sécurité de l'emploi." },
    { word: "Stabilité", meaning: "Stability", reading: "sta-bee-lee-tay", example_sentence: "Une situation stable." },
    { word: "Confort", meaning: "Comfort", reading: "kohn-for", example_sentence: "Un certain confort de vie." },
    { word: "Bonheur", meaning: "Happiness", reading: "boh-noor", example_sentence: "Le bonheur avant tout." },
    { word: "Santé", meaning: "Health", reading: "sahn-tay", example_sentence: "La santé est une priorité." },
    { word: "Équilibre", meaning: "Balance", reading: "ay-kee-lee-bruh", example_sentence: "Trouver son équilibre." },
    { word: "Temps", meaning: "Time", reading: "tah", example_sentence: "Prendre le temps." },
    { word: "Priorité", meaning: "Priority", reading: "pree-oh-ree-tay", example_sentence: "Définir ses priorités." },
    { word: "Organisation", meaning: "Organization", reading: "or-ga-nee-za-syohn", example_sentence: "Une bonne organisation." },
    { word: "Gestion", meaning: "Management", reading: "zhes-tyohn", example_sentence: "La gestion du stress." },
    { word: "Efficacité", meaning: "Efficiency", reading: "ay-fee-ka-see-tay", example_sentence: "Gagner en efficacité." },
    { word: "Productivité", meaning: "Productivity", reading: "proh-dook-tee-vee-tay", example_sentence: "Améliorer sa productivité." },
    { word: "Créativité", meaning: "Creativity", reading: "kray-a-tee-vee-tay", example_sentence: "Stimuler sa créativité." },
    { word: "Inspiration", meaning: "Inspiration", reading: "an-spee-ra-syohn", example_sentence: "Une source d'inspiration." },
    { word: "Innovation", meaning: "Innovation", reading: "ee-noh-va-syohn", example_sentence: "L'innovation technologique." },
    { word: "Vision", meaning: "Vision", reading: "vee-zyohn", example_sentence: "Avoir une vision claire." },
    { word: "Perspectives", meaning: "Perspectives", reading: "per-spek-teev", example_sentence: "De nouvelles perspectives." },
    { word: "Horizon", meaning: "Horizon", reading: "oh-ree-zoh", example_sentence: "L'horizon s'éclaire." },
    { word: "Conviction", meaning: "Conviction", reading: "kohn-veek-syohn", example_sentence: "Agir par conviction." },
    { word: "Engagement", meaning: "Engagement", reading: "ahn-ga-zhuh-mahn", example_sentence: "Un engagement total." },
    { word: "Passion", meaning: "Passion", reading: "pa-syohn", example_sentence: "Vivre sa passion." },
    { word: "Vocation", meaning: "Vocation", reading: "voh-ka-syohn", example_sentence: "Une vocation tardive." },
    { word: "Aventure", meaning: "Adventure", reading: "a-vahn-toor", example_sentence: "Une grande aventure." },
    { word: "Voyage", meaning: "Voyage", reading: "vwa-yazh", example_sentence: "Un voyage de découverte." },
    { word: "Migration", meaning: "Migration", reading: "mee-gra-syohn", example_sentence: "Une migration forcée." },
    { word: "Installation", meaning: "Installation", reading: "ah-sta-la-syohn", example_sentence: "Son installation à l'étranger." },
    { word: "Adieu", meaning: "Farewell", reading: "a-dyuh", example_sentence: "Dire adieu." },
    { word: "Au revoir", meaning: "Goodbye", reading: "ohr-vwahr", example_sentence: "Un simple au revoir." },
    { word: "Retour", meaning: "Return", reading: "ruh-toor", example_sentence: "Le retour au pays." },
    { word: "Nostalgie", meaning: "Nostalgia", reading: "noh-stal-zhee", example_sentence: "Un peu de nostalgie." },
    { word: "Souvenir", meaning: "Memory", reading: "soo-vuh-neer", example_sentence: "Un bon souvenir." },
    { word: "Passé", meaning: "Past", reading: "pa-say", example_sentence: "Le passé est passé." },
    { word: "Présent", meaning: "Present", reading: "pray-zah", example_sentence: "Vivre le présent." },
    { word: "Instant", meaning: "Instant / Moment", reading: "ah-stah", example_sentence: "Profiter de l'instant." },
    { word: "Moment", meaning: "Moment", reading: "moh-mahn", example_sentence: "Un moment magique." },
    { word: "Temps qui passe", meaning: "Passing time", reading: "tah kee pahs", example_sentence: "Le temps qui passe vite." },
    { word: "Éternité", meaning: "Eternity", reading: "ay-ter-nee-tay", example_sentence: "L'éternité devant nous." },
    { word: "Fin", meaning: "End", reading: "fa", example_sentence: "La fin d'une histoire." },
    { word: "Nouveau départ", meaning: "New start", reading: "noo-voh day-par", example_sentence: "Un nouveau départ possible." }
];

// --- MODULE 20: Advanced A2 Synthesis & Wrap-up ---
const m20_items = [
    { word: "Synthèse", meaning: "Synthesis", reading: "san-tez", example_sentence: "Faire une synthèse." },
    { word: "Révision", meaning: "Revision", reading: "ray-vee-zyohn", example_sentence: "Une révision complète." },
    { word: "Bilan", meaning: "Assessment / Balance sheet", reading: "bee-lah", example_sentence: "Faire le bilan." },
    { word: "Résumé", meaning: "Summary", reading: "ray-zoo-may", example_sentence: "Un résumé court." },
    { word: "Conclusion", meaning: "Conclusion", reading: "kohn-kloo-zyohn", example_sentence: "En conclusion." },
    { word: "Résultat", meaning: "Result", reading: "ray-zool-ta", example_sentence: "Le résultat final." },
    { word: "Niveau", meaning: "Level", reading: "nee-voh", example_sentence: "Un bon niveau de français." },
    { word: "Progrès", meaning: "Progress", reading: "proh-gray", example_sentence: "Des progrès visibles." },
    { word: "Évaluation", meaning: "Evaluation", reading: "ay-va-loo-a-syohn", example_sentence: "Une évaluation régulière." },
    { word: "Compétence", meaning: "Competence / Skill", reading: "kohm-pay-tahns", example_sentence: "Valider ses compétences." },
    { word: "Aptitude", meaning: "Aptitude", reading: "ap-tee-tood", example_sentence: "Une aptitude naturelle." },
    { word: "Savoir-faire", meaning: "Know-how", reading: "sa-vwahr fer", example_sentence: "Un savoir-faire artisanal." },
    { word: "Maîtrise", meaning: "Mastery", reading: "me-treez", example_sentence: "La maîtrise d'une langue." },
    { word: "Perfectionnement", meaning: "Improvement", reading: "per-fek-syohn-mahn", example_sentence: "Un stage de perfectionnement." },
    { word: "Pratique", meaning: "Practice", reading: "pra-teek", example_sentence: "La pratique est essentielle." },
    { word: "Exercice", meaning: "Exercise", reading: "eg-zer-sees", example_sentence: "Faire un exercice de grammaire." },
    { word: "Apprentissage", meaning: "Learning", reading: "a-prahn-tee-sazh", example_sentence: "L'apprentissage continu." },
    { word: "Expérience", meaning: "Experience", reading: "ek-spay-ryahns", example_sentence: "Gagner de l'expérience." },
    { word: "Cultures", meaning: "Cultures", reading: "kool-toor", example_sentence: "Le respect des cultures." },
    { word: "Langage", meaning: "Language", reading: "lahn-gazh", example_sentence: "Le langage corporel." },
    { word: "Expression", meaning: "Expression", reading: "ek-spres-yohn", example_sentence: "Une expression idiomatique." },
    { word: "Communication", meaning: "Communication", reading: "koh-moo-nee-ka-syohn", example_sentence: "Une communication efficace." },
    { word: "Dialogue", meaning: "Dialogue", reading: "dyah-lohg", example_sentence: "Instaurer un dialogue." },
    { word: "Échange", meaning: "Exchange", reading: "ay-shahnzh", example_sentence: "Un échange de vues." },
    { word: "Interaction", meaning: "Interaction", reading: "an-ter-ak-syohn", example_sentence: "Favoriser l'interaction." },
    { word: "Inclusion", meaning: "Inclusion", reading: "an-kloo-zyohn", example_sentence: "L'inclusion sociale." },
    { word: "Tolérance", meaning: "Tolerance", reading: "toh-lay-rahns", example_sentence: "Faire preuve de tolérance." },
    { word: "Respect", meaning: "Respect", reading: "res-peh", example_sentence: "Le respect mutuel." },
    { word: "Égalité", meaning: "Equality", reading: "ay-ga-lee-tay", example_sentence: "L'égalité des chances." },
    { word: "Liberté", meaning: "Liberty", reading: "lee-ber-tay", example_sentence: "La liberté d'expression." },
    { word: "Fraternité", meaning: "Fraternity", reading: "fra-ter-nee-tay", example_sentence: "Un sentiment de fraternité." },
    { word: "Solidarité", meaning: "Solidarity", reading: "soh-lee-da-ree-tay", example_sentence: "Un geste de solidarité." },
    { word: "Paix", meaning: "Peace", reading: "peh", example_sentence: "Vivre en paix." },
    { word: "Justice", meaning: "Justice", reading: "zhoos-tees", example_sentence: "Réclamer la justice." },
    { word: "Vérité", meaning: "Truth", reading: "vay-ree-tay", example_sentence: "La vérité éclate." },
    { word: "Valeur", meaning: "Value", reading: "va-lur", example_sentence: "Une valeur fondamentale." },
    { word: "Principe", meaning: "Principle", reading: "prah-seep", example_sentence: "Une question de principe." },
    { word: "Responsabilité", meaning: "Responsibility", reading: "res-pohn-sa-bee-lee-tay", example_sentence: "Engager sa responsabilité." },
    { word: "Engagement", meaning: "Engagement / Commitment", reading: "ah-ga-zhuh-mahn", example_sentence: "Un engagement durable." },
    { word: "Participation", meaning: "Participation", reading: "par-tee-see-pah-syohn", example_sentence: "Une large participation." },
    { word: "Action", meaning: "Action", reading: "ak-syohn", example_sentence: "Passer à l'action." },
    { word: "Mouvement", meaning: "Movement", reading: "moov-mahn", example_sentence: "Un mouvement de foule." },
    { word: "Changement", meaning: "Change", reading: "shahn-zhuh-mahn", example_sentence: "Un changement radical." },
    { word: "Transformer", meaning: "To transform", reading: "trahns-for-may", example_sentence: "Transformer son mode de vie." },
    { word: "Évoluer", meaning: "To evolve", reading: "ay-voh-loo-ay", example_sentence: "Évoluer positivement." },
    { word: "Avancer", meaning: "To advance", reading: "a-vahn-say", example_sentence: "Avancer vers son but." },
    { word: "Recommencer", meaning: "To start again", reading: "ruh-koh-mahn-say", example_sentence: "Recommencer à zéro." },
    { word: "Continuer", meaning: "To continue", reading: "kohn-tee-noo-ay", example_sentence: "Continuer ses efforts." },
    { word: "Persister", meaning: "To persist", reading: "per-sees-tay", example_sentence: "Persister dans son choix." },
    { word: "Réussir", meaning: "To succeed", reading: "ray-oo-seer", example_sentence: "Réussir son examen." },
    { word: "Féliciter", meaning: "To congratulate", reading: "fay-lee-see-tay", example_sentence: "Féliciter le gagnant." },
    { word: "Encourager", meaning: "To encourage", reading: "ahn-koo-ra-zhay", example_sentence: "Encourager les jeunes." },
    { word: "Inspirer", meaning: "To inspire", reading: "an-spee-ray", example_sentence: "Inspirer confiance." },
    { word: "Partager", meaning: "To share", reading: "par-ta-zhay", example_sentence: "Partager son savoir." },
    { word: "Collaborer", meaning: "To collaborate", reading: "koh-la-boh-ray", example_sentence: "Collaborer sur un projet." },
    { word: "Soutenir", meaning: "To support", reading: "soo-tuh-neer", example_sentence: "Soutenir une cause." },
    { word: "Aider", meaning: "To help", reading: "ay-day", example_sentence: "Aider son prochain." },
    { word: "Servir", meaning: "To serve", reading: "ser-veer", example_sentence: "Servir l'intérêt général." },
    { word: "Protéger", meaning: "To protect", reading: "proh-tay-zhay", example_sentence: "Protéger les plus faibles." },
    { word: "Assurer", meaning: "To assure / insure", reading: "a-soo-ray", example_sentence: "Assurer sa réussite." },
    { word: "Garantir", meaning: "To guarantee", reading: "ga-rahn-teer", example_sentence: "Garantir un résultat." },
    { word: "Promettre", meaning: "To promise", reading: "proh-me-truh", example_sentence: "Promettre de revenir." },
    { word: "Juridique", meaning: "Legal", reading: "zhoo-ree-deek", example_sentence: "Le cadre juridique." },
    { word: "Social", meaning: "Social", reading: "soh-syal", example_sentence: "Le lien social." },
    { word: "Politique", meaning: "Policy / Political", reading: "poh-lee-teek", example_sentence: "La politique environnementale." },
    { word: "Économique", meaning: "Economic", reading: "ay-koh-noh-meek", example_sentence: "La crise économique." },
    { word: "Environnemental", meaning: "Environmental", reading: "ahn-vee-rohn-mahn-tal", example_sentence: "Un enjeu environnemental." },
    { word: "Culturel", meaning: "Cultural", reading: "kool-too-rel", example_sentence: "Un événement culturel." },
    { word: "International", meaning: "International", reading: "an-ter-na-syoh-nal", example_sentence: "Un accord international." },
    { word: "Mondial", meaning: "Global", reading: "mohn-dyal", example_sentence: "Le réchauffement mondial." },
    { word: "Universel", meaning: "Universal", reading: "oo-nee-ver-sel", example_sentence: "Un droit universel." },
    { word: "Précieux", meaning: "Precious", reading: "pray-syuh", example_sentence: "Un temps précieux." },
    { word: "Indispensable", meaning: "Indispensable", reading: "an-dees-pahn-sa-bluh", example_sentence: "Une aide indispensable." },
    { word: "Essentiel", meaning: "Essential", reading: "ay-sahn-syel", example_sentence: "Le point essentiel." },
    { word: "Crucial", meaning: "Crucial", reading: "kroo-syal", example_sentence: "Un moment crucial." },
    { word: "Vital", meaning: "Vital", reading: "vee-tal", example_sentence: "Une question vitale." },
    { word: "Unique", meaning: "Unique", reading: "oo-neek", example_sentence: "Une occasion unique." },
    { word: "Rare", meaning: "Rare", reading: "rar", example_sentence: "Une fleur rare." },
    { word: "Fréquent", meaning: "Frequent", reading: "fray-kahn", example_sentence: "Un cas fréquent." },
    { word: "Courant", meaning: "Common / Running", reading: "koo-rah", example_sentence: "C'est un usage courant." },
    { word: "Habituel", meaning: "Habitual", reading: "a-bee-too-el", example_sentence: "Mon trajet habituel." },
    { word: "Normalement", meaning: "Normally", reading: "nor-mal-mahn", example_sentence: "Normalement, ça marche." },
    { word: "Probablement", meaning: "Probably", reading: "proh-ba-bluh-mahn", example_sentence: "Probablement ce soir." },
    { word: "Peut-être", meaning: "Perhaps", reading: "puh-tetruh", example_sentence: "Peut-être bien." },
    { word: "Sûrement", meaning: "Surely", reading: "soor-mahn", example_sentence: "Sûrement pas." },
    { word: "Certainement", meaning: "Certainly", reading: "ser-ten-mahn", example_sentence: "Certainement oui." },
    { word: "Clairement", meaning: "Clearly", reading: "kler-mahn", example_sentence: "S'exprimer clairement." },
    { word: "Directement", meaning: "Directly", reading: "dee-rek-tuh-mahn", example_sentence: "Aller directement au but." },
    { word: "Rapidement", meaning: "Rapidly", reading: "ra-peed-mahn", example_sentence: "Répondre rapidement." },
    { word: "Lentement", meaning: "Slowly", reading: "lahnt-mahn", example_sentence: "Marcher lentement." },
    { word: "Doucement", meaning: "Gently / Softly", reading: "doos-mahn", example_sentence: "Parler doucement." },
    { word: "Fort", meaning: "Strong / Loud", reading: "for", example_sentence: "Parler plus fort." },
    { word: "Vite", meaning: "Quickly", reading: "veet", example_sentence: "Rouler trop vite." },
    { word: "Bientôt", meaning: "Soon", reading: "byan-toh", example_sentence: "À bientôt !" },
    { word: "Déjà", meaning: "Already", reading: "day-zha", example_sentence: "C'est déjà fini." },
    { word: "Encore", meaning: "Still / Again", reading: "ahn-kor", example_sentence: "Pas encore." },
    { word: "Souvent", meaning: "Often", reading: "soo-vahn", example_sentence: "Je le vois souvent." },
    { word: "Rarement", meaning: "Rarely", reading: "rar-mahn", example_sentence: "Je sors rarement." },
    { word: "Jamais", meaning: "Never", reading: "zha-meh", example_sentence: "Jamais de la vie !" },
    { word: "Toujours", meaning: "Always / Still", reading: "too-zhoor", example_sentence: "Pour toujours." }
];

const m18 = createModule('fr_a2_m18', 'A2 French - Module 18: Arts & Culture', 18, m18_items);
const m19 = createModule('fr_a2_m19', 'A2 French - Module 19: Future Plans', 19, m19_items);
const m20 = createModule('fr_a2_m20', 'A2 French - Module 20: Advanced Wrap-up', 20, m20_items);

fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m18.json'), JSON.stringify(m18, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m19.json'), JSON.stringify(m19, null, 2));
fs.writeFileSync(path.join(__dirname, '../firestore_data/french_a2_m20.json'), JSON.stringify(m20, null, 2));

console.log('✅ Generated French A2 Modules 18, 19, and 20.');
