const fs = require('fs');
const path = require('path');

// Helper to ensure 100 items
function createModule(id, name, items) {
    if (items.length !== 100) {
        console.warn(`[WARNING] ${id} has ${items.length} items instead of 100!`);
    }
    return { id, name, count: items.length, vocabularyItems: items };
}

// --- MODULE 7: SHOPPING & FASHION ---
const m7_items = [
    { word: "Vêtement", meaning: "Clothing", reading: "vet-mah", example_sentence: "J'achète un vêtement." },
    { word: "Mode", meaning: "Fashion", reading: "mohd", example_sentence: "Elle suit la mode." },
    { word: "Magasin", meaning: "Store", reading: "ma-ga-zah", example_sentence: "Le magasin est ouvert." },
    { word: "Boutique", meaning: "Boutique / Shop", reading: "boo-teek", example_sentence: "Une petite boutique." },
    { word: "Centre commercial", meaning: "Mall", reading: "sah-truh koh-mer-syal", example_sentence: "Allons au centre commercial." },
    { word: "Prix", meaning: "Price", reading: "pree", example_sentence: "Quel est le prix ?" },
    { word: "Argent", meaning: "Money", reading: "ar-zhah", example_sentence: "Je n'ai pas d'argent." },
    { word: "Soldes", meaning: "Sales", reading: "sohld", example_sentence: "C'est la période des soldes." }, // Word #8
    { word: "Achat", meaning: "Purchase", reading: "a-sha", example_sentence: "Faire un achat important." }, // Word #9
    { word: "Vendeur", meaning: "Salesperson", reading: "vah-dur", example_sentence: "Le vendeur est serviable." },
    { word: "Client", meaning: "Customer", reading: "klee-ah", example_sentence: "Le client est roi." },
    { word: "Caisse", meaning: "Cashier / Till", reading: "kes", example_sentence: "Payez à la caisse." },
    { word: "Reçu", meaning: "Receipt", reading: "ruh-soo", example_sentence: "Gardez votre reçu." },
    { word: "Sac", meaning: "Bag", reading: "sak", example_sentence: "Un sac en papier." },
    { word: "Cabine d'essayage", meaning: "Fitting room", reading: "ka-been de-say-yazh", example_sentence: "Où est la cabine ?" }, // Word #15

    { word: "Pantalon", meaning: "Pants", reading: "pah-ta-loh", example_sentence: "Un pantalon bleu." },
    { word: "Chemise", meaning: "Shirt", reading: "shuh-meez", example_sentence: "Une chemise blanche." },
    { word: "T-shirt", meaning: "T-shirt", reading: "tee-shurt", example_sentence: "Un t-shirt confortable." },
    { word: "Jupe", meaning: "Skirt", reading: "zhoop", example_sentence: "Une jupe courte." },
    { word: "Robe", meaning: "Dress", reading: "rohb", example_sentence: "Une belle robe rouge." },
    { word: "Veste", meaning: "Jacket", reading: "vest", example_sentence: "Mets ta veste." },
    { word: "Manteau", meaning: "Coat", reading: "mah-toh", example_sentence: "Un manteau d'hiver." },
    { word: "Pull", meaning: "Sweater", reading: "pool", example_sentence: "Un pull en laine." },
    { word: "Chaussette", meaning: "Sock", reading: "shoh-set", example_sentence: "Une paire de chaussettes." },
    { word: "Chaussure", meaning: "Shoe", reading: "shoh-soor", example_sentence: "Des chaussures de sport." },
    { word: "Chapeau", meaning: "Hat", reading: "sha-poh", example_sentence: "Il porte un chapeau." },
    { word: "Gant", meaning: "Glove", reading: "gah", example_sentence: "Des gants pour le froid." },
    { word: "Écharpe", meaning: "Scarf", reading: "ay-sharp", example_sentence: "Une écharpe chaude." },
    { word: "Ceinture", meaning: "Belt", reading: "sah-toor", example_sentence: "Une ceinture en cuir." },
    { word: "Cravate", meaning: "Tie", reading: "kra-vat", example_sentence: "Porter une cravate." },
    { word: "Maillot de bain", meaning: "Swimsuit", reading: "ma-yoh duh bah", example_sentence: "N'oublie pas ton maillot." },

    { word: "Couleur", meaning: "Color", reading: "koo-lur", example_sentence: "J'aime cette couleur." },
    { word: "Rouge", meaning: "Red", reading: "roozh", example_sentence: "Une pomme rouge." },
    { word: "Bleu", meaning: "Blue", reading: "bluh", example_sentence: "Le ciel bleu." },
    { word: "Vert", meaning: "Green", reading: "ver", example_sentence: "L'herbe est verte." },
    { word: "Jaune", meaning: "Yellow", reading: "zhohn", example_sentence: "Un soleil jaune." },
    { word: "Noir", meaning: "Black", reading: "nwar", example_sentence: "Un chat noir." },
    { word: "Blanc", meaning: "White", reading: "blah", example_sentence: "Une neige blanche." },
    { word: "Gris", meaning: "Grey", reading: "gree", example_sentence: "Un nuage gris." },
    { word: "Rose", meaning: "Pink", reading: "rohz", example_sentence: "Une fleur rose." },
    { word: "Orange (couleur)", meaning: "Orange", reading: "oh-rahzh", example_sentence: "Un t-shirt orange." },
    { word: "Marron", meaning: "Brown", reading: "ma-roh", example_sentence: "Des yeux marron." },
    { word: "Violet", meaning: "Purple", reading: "vyoh-leh", example_sentence: "Une robe violette." },
    { word: "Clair", meaning: "Light", reading: "kler", example_sentence: "Un bleu clair." },
    { word: "Foncé", meaning: "Dark", reading: "foh-say", example_sentence: "Un vert foncé." },
    { word: "Brillant", meaning: "Shiny", reading: "bree-yah", example_sentence: "Un tissu brillant." },

    { word: "Taille", meaning: "Size", reading: "tye", example_sentence: "Quelle est votre taille ?" },
    { word: "Petit", meaning: "Small", reading: "puh-tee", example_sentence: "C'est trop petit." },
    { word: "Moyen", meaning: "Medium", reading: "mwa-yah", example_sentence: "Une taille moyenne." },
    { word: "Grand", meaning: "Large", reading: "grah", example_sentence: "Je veux le plus grand." },
    { word: "Large", meaning: "Wide", reading: "larzh", example_sentence: "Un pantalon large." },
    { word: "Serré", meaning: "Tight", reading: "seh-ray", example_sentence: "C'est trop serré." },
    { word: "Court", meaning: "Short", reading: "koor", example_sentence: "Une jupe courte." },
    { word: "Long", meaning: "Long", reading: "loh", example_sentence: "Une robe longue." },
    { word: "Nouveau", meaning: "New", reading: "noo-voh", example_sentence: "Mon nouveau manteau." },
    { word: "Vieux", meaning: "Old", reading: "vyuh", example_sentence: "Un vieux chapeau." },
    { word: "Beau", meaning: "Beautiful", reading: "boh", example_sentence: "C'est très beau." },
    { word: "Cher", meaning: "Expensive", reading: "sher", example_sentence: "C'est trop cher." },
    { word: "Bon marché", meaning: "Cheap", reading: "boh mar-shay", example_sentence: "C'est bon marché ici." },
    { word: "Gratuit", meaning: "Free", reading: "gra-twee", example_sentence: "L'entrée est gratuite." },
    { word: "Élégant", meaning: "Elegant", reading: "ay-lay-gah", example_sentence: "Vous êtes élégant." },

    { word: "Bijou", meaning: "Jewel", reading: "bee-zhoo", example_sentence: "Un beau bijou." },
    { word: "Bague", meaning: "Ring", reading: "bag", example_sentence: "Une bague en or." },
    { word: "Collier", meaning: "Necklace", reading: "koh-lyay", example_sentence: "Un collier de perles." },
    { word: "Montre", meaning: "Watch", reading: "moh-truh", example_sentence: "Regarde ma montre." },
    { word: "Lunettes", meaning: "Glasses", reading: "loo-net", example_sentence: "Mes lunettes de soleil." },
    { word: "Parfum", meaning: "Perfume", reading: "par-fah", example_sentence: "Un parfum délicat." },
    { word: "Maquillage", meaning: "Makeup", reading: "ma-kee-yazh", example_sentence: "Se mettre du maquillage." },
    { word: "Parapluie", meaning: "Umbrella", reading: "pa-ra-plwee", example_sentence: "Prends ton parapluie." },
    { word: "Portefeuille", meaning: "Wallet", reading: "por-tuh-fuy", example_sentence: "J'ai oublié mon portefeuille." },
    { word: "Coton", meaning: "Cotton", reading: "koh-toh", example_sentence: "Un t-shirt en coton." },
    { word: "Laine", meaning: "Wool", reading: "len", example_sentence: "Un pull en laine." },
    { word: "Cuir", meaning: "Leather", reading: "kweer", example_sentence: "Une veste en cuir." },
    { word: "Soie", meaning: "Silk", reading: "swa", example_sentence: "Une écharpe en soie." },
    { word: "Tissu", meaning: "Fabric", reading: "tee-soo", example_sentence: "Un tissu doux." },
    { word: "Style", meaning: "Style", reading: "steel", example_sentence: "Il a du style." },

    { word: "Essayer", meaning: "To try on", reading: "e-say-yay", example_sentence: "Je peux essayer ?" },
    { word: "Payer", meaning: "To pay", reading: "pay-yay", example_sentence: "Je vais payer par carte." },
    { word: "Choisir", meaning: "To choose", reading: "shwa-zeer", example_sentence: "Laissez-moi choisir." },
    { word: "Chercher", meaning: "To look for", reading: "sher-shay", example_sentence: "Je cherche un cadeau." },
    { word: "Trouver", meaning: "To find", reading: "troo-vay", example_sentence: "J'ai trouvé ma taille." },
    { word: "Porter", meaning: "To wear", reading: "por-tay", example_sentence: "Porter un uniforme." },
    { word: "Changer", meaning: "To change / exchange", reading: "shah-zhay", example_sentence: "Changer de vêtements." }, // Word #81
    { word: "Rendre", meaning: "To return (item)", reading: "rah-druh", example_sentence: "Rendre un article." },
    { word: "Coûter", meaning: "To cost", reading: "koo-tay", example_sentence: "Combien ça coûte ?" },
    { word: "Dépenser", meaning: "To spend", reading: "day-pah-say", example_sentence: "Ne dépense pas trop." },
    { word: "Économiser", meaning: "To save (money)", reading: "ay-koh-noh-mee-zay", example_sentence: "Économiser pour les vacances." },
    { word: "Vendre", meaning: "To sell", reading: "vah-druh", example_sentence: "Vendre sa voiture." },
    { word: "Offrir", meaning: "To offer / give", reading: "oh-freer", example_sentence: "Offrir des fleurs." },
    { word: "Recevoir", meaning: "To receive", reading: "ruh-suh-vwar", example_sentence: "Recevoir un colis." },
    { word: "Commander (ligne)", meaning: "To order (online)", reading: "koh-mah-day", example_sentence: "Commander par internet." },
    { word: "Livrer", meaning: "To deliver", reading: "lee-vray", example_sentence: "Livrer à domicile." }, // Word #90
    { word: "Liste", meaning: "List", reading: "leest", example_sentence: "Une liste de courses." },
    { word: "Chariot", meaning: "Shopping cart", reading: "sha-ryoh", example_sentence: "Prenez un chariot." },
    { word: "Panier", meaning: "Basket", reading: "pa-nyay", example_sentence: "Un panier à la main." },
    { word: "Rayon", meaning: "Aisle / Department", reading: "ray-oh", example_sentence: "Le rayon homme." },
    { word: "Étalage", meaning: "Display", reading: "ay-ta-lazh", example_sentence: "Regarder l'étalage." },
    { word: "Vitrine", meaning: "Shop window", reading: "vee-treen", example_sentence: "Lèche-vitrine." },
    { word: "Mode locale", meaning: "Local fashion", reading: "mohd lo-kal", example_sentence: "Sourire à la mode locale." },
    { word: "Luxueux", meaning: "Luxurious", reading: "look-soo-yuh", example_sentence: "Un magasin luxueux." },
    { word: "Moderne", meaning: "Modern", reading: "moh-dern", example_sentence: "Un style moderne." },
    { word: "Classique", meaning: "Classic", reading: "kla-seek", example_sentence: "Une coupe classique." } // Word #100
];

// --- MODULE 8: HEALTH & BODY ---
const m8_items = [
    { word: "Santé", meaning: "Health", reading: "sah-tay", example_sentence: "La santé est importante." },
    { word: "Corps", meaning: "Body", reading: "kor", example_sentence: "Prendre soin de son corps." },
    { word: "Tête", meaning: "Head", reading: "tet", example_sentence: "J'ai mal à la tête." },
    { word: "Visage", meaning: "Face", reading: "vee-zazh", example_sentence: "Lavez votre visage." },
    { word: "Œil", meaning: "Eye", reading: "uy", example_sentence: "Il a l'œil vif." },
    { word: "Nez", meaning: "Nose", reading: "nay", example_sentence: "Respirer par le nez." },
    { word: "Bouche", meaning: "Mouth", reading: "boosh", example_sentence: "Ouvre la bouche." },
    { word: "Oreille", meaning: "Ear", reading: "oh-ray", example_sentence: "J'ai mal à l'oreille." }, // Word #8
    { word: "Cheveux", meaning: "Hair", reading: "shuh-vuh", example_sentence: "Se couper les cheveux." }, // Word #9
    { word: "Cou", meaning: "Neck", reading: "koo", example_sentence: "Un long cou." },
    { word: "Épaule", meaning: "Shoulder", reading: "ay-pohl", example_sentence: "Sur l'épaule." },
    { word: "Bras", meaning: "Arm", reading: "bra", example_sentence: "Lever les bras." },
    { word: "Main", meaning: "Hand", reading: "mah", example_sentence: "Donne-moi la main." },
    { word: "Doigt", meaning: "Finger", reading: "dwa", example_sentence: "Pointer du doigt." },
    { word: "Dos", meaning: "Back", reading: "doh", example_sentence: "J'ai mal au dos." }, // Word #15

    { word: "Estomac", meaning: "Stomach", reading: "es-toh-ma", example_sentence: "Mal à l'estomac." },
    { word: "Cœur", meaning: "Heart", reading: "kur", example_sentence: "Le cœur bat vite." },
    { word: "Jambe", meaning: "Leg", reading: "zhahb", example_sentence: "Courir sur ses jambes." },
    { word: "Genou", meaning: "Knee", reading: "zhuh-noo", example_sentence: "Se mettre à genou." },
    { word: "Pied", meaning: "Foot", reading: "pyay", example_sentence: "À pied." },
    { word: "Peau", meaning: "Skin", reading: "poh", example_sentence: "Une peau douce." },
    { word: "Dent", meaning: "Tooth", reading: "dah", example_sentence: "Se brosser les dents." },
    { word: "Langue (corps)", meaning: "Tongue", reading: "lah-guh", example_sentence: "Tire la langue." },
    { word: "Sang", meaning: "Blood", reading: "sah", example_sentence: "Une prise de sang." },
    { word: "Os", meaning: "Bone", reading: "ohs", example_sentence: "Un os cassé." },
    { word: "Muscle", meaning: "Muscle", reading: "moos-kluh", example_sentence: "Muscles forts." },
    { word: "Taille (corps)", meaning: "Waist", reading: "tye", example_sentence: "Tour de taille." },
    { word: "Poitrine", meaning: "Chest", reading: "pwa-treen", example_sentence: "Respiration de la poitrine." },
    { word: "Ventre", meaning: "Belly", reading: "vah-truh", example_sentence: "Ventre plat." },
    { word: "Poignet", meaning: "Wrist", reading: "pwa-nyay", example_sentence: "Une montre au poignet." },
    { word: "Cheville", meaning: "Ankle", reading: "shuh-vee", example_sentence: "Se tordre la cheville." },

    { word: "Malade", meaning: "Sick", reading: "ma-lad", example_sentence: "Je suis malade." },
    { word: "Maladie", meaning: "Illness", reading: "ma-la-dee", example_sentence: "Une maladie grave." },
    { word: "Douleur", meaning: "Pain", reading: "doo-lur", example_sentence: "Une forte douleur." },
    { word: "Fièvre", meaning: "Fever", reading: "fyev-ruh", example_sentence: "Avoir de la fièvre." },
    { word: "Rhume", meaning: "Cold (illness)", reading: "room", example_sentence: "J'ai un gros rhume." },
    { word: "Toux", meaning: "Cough", reading: "too", example_sentence: "Une toux sèche." },
    { word: "Grippe", meaning: "Flu", reading: "greep", example_sentence: "La grippe saisonnière." },
    { word: "Blessure", meaning: "Injury", reading: "ble-soor", example_sentence: "Une blessure au sport." },
    { word: "Accident", meaning: "Accident", reading: "ak-see-dah", example_sentence: "Éviter l'accident." },
    { word: "Urgence", meaning: "Emergency", reading: "oor-zhahs", example_sentence: "C'est une urgence." },
    { word: "Hôpital", meaning: "Hospital", reading: "oh-pee-tal", example_sentence: "Aller à l'hôpital." },
    { word: "Clinique", meaning: "Clinic", reading: "klee-neek", example_sentence: "Une clinique médicale." },
    { word: "Pharmacie", meaning: "Pharmacy", reading: "far-ma-see", example_sentence: "Acheter à la pharmacie." },
    { word: "Médicament", meaning: "Medicine", reading: "may-dee-ka-mah", example_sentence: "Prendre un médicament." },
    { word: "Ordonnance", meaning: "Prescription", reading: "or-doh-nahs", example_sentence: "Une ordonnance du docteur." },

    { word: "Docteur", meaning: "Doctor", reading: "dok-tur", example_sentence: "Voir un docteur." },
    { word: "Infirmier (santé)", meaning: "Nurse", reading: "ah-feer-myay", example_sentence: "L'infirmier aide le malade." },
    { word: "Dentiste", meaning: "Dentist", reading: "dah-teest", example_sentence: "Peur du dentiste." },
    { word: "Patient (santé)", meaning: "Patient", reading: "pa-syah", example_sentence: "Un patient calme." },
    { word: "Rendez-vous (médical)", meaning: "Appointment", reading: "rah-day-voo", example_sentence: "Prendre rendez-vous." },
    { word: "Analyse", meaning: "Test / Analysis", reading: "a-na-leez", example_sentence: "Analyse de sang." },
    { word: "Vaccin", meaning: "Vaccine", reading: "vak-sah", example_sentence: "Faire un vaccin." },
    { word: "Seringue", meaning: "Syringe", reading: "suh-rah-guh", example_sentence: "Une seringue stérile." },
    { word: "Pansement", meaning: "Bandage", reading: "pah-suh-mah", example_sentence: "Mettre un pansement." },
    { word: "Sirop", meaning: "Syrup", reading: "see-roh", example_sentence: "Du sirop pour la toux." },
    { word: "Comprimé", meaning: "Tablet", reading: "koh-pree-may", example_sentence: "Un comprimé par jour." },
    { word: "Sommeil", meaning: "Sleep", reading: "soh-may", example_sentence: "Manquer de sommeil." },
    { word: "Fatigue", meaning: "Fatigue", reading: "fa-teeg", example_sentence: "Une grande fatigue." },
    { word: "Stress", meaning: "Stress", reading: "stres", example_sentence: "Gérer son stress." },
    { word: "Sport (santé)", meaning: "Exercise", reading: "spor", example_sentence: "Faire du sport pour la santé." },

    { word: "Respirer", meaning: "To breathe", reading: "res-pee-ray", example_sentence: "Respirer profondément." },
    { word: "Marcher (santé)", meaning: "To walk", reading: "mar-shay", example_sentence: "Marcher tous les jours." },
    { word: "Courir", meaning: "To run", reading: "koo-reer", example_sentence: "Courir pour rester en forme." },
    { word: "Manger (santé)", meaning: "To eat", reading: "mah-zhay", example_sentence: "Bien manger." },
    { word: "Boire (santé)", meaning: "To drink", reading: "bwar", example_sentence: "Boire beaucoup d'eau." },
    { word: "Dormir", meaning: "To sleep", reading: "dor-meer", example_sentence: "Dormir huit heures." },
    { word: "Se reposer", meaning: "To rest", reading: "suh ruh-poh-zay", example_sentence: "Il faut se reposer." },
    { word: "Soigner", meaning: "To treat / heal", reading: "swah-nyay", example_sentence: "Soigner une plaie." },
    { word: "Guérir", meaning: "To get well", reading: "gay-reer", example_sentence: "Je vais bientôt guérir." },
    { word: "Aider", meaning: "To help", reading: "ay-day", example_sentence: "Aider les personnes âgées." },
    { word: "Sourire (santé)", meaning: "To smile", reading: "soo-reer", example_sentence: "Sourire est bon pour la santé." },
    { word: "Rire (santé)", meaning: "To laugh", reading: "reer", example_sentence: "Rire souvent." },
    { word: "Pleurer", meaning: "To cry", reading: "pluh-ray", example_sentence: "Pleurer de joie." },
    { word: "Vivre", meaning: "To live", reading: "veev-ruh", example_sentence: "Vivre cent ans." },
    { word: "Mourir", meaning: "To die", reading: "moo-reer", example_sentence: "Ne pas avoir peur de mourir." },

    { word: "Fort", meaning: "Strong", reading: "for", example_sentence: "Être fort." },
    { word: "Faible", meaning: "Weak", reading: "feb-luh", example_sentence: "Se sentir faible." },
    { word: "Mince", meaning: "Thin", reading: "mahss", example_sentence: "Rester mince." }, // Word #81
    { word: "Gros", meaning: "Fat / Big", reading: "groh", example_sentence: "Un gros chat." },
    { word: "Grand (corps)", meaning: "Tall", reading: "grah", example_sentence: "Il est très grand." },
    { word: "Petit (corps)", meaning: "Short", reading: "puh-tee", example_sentence: "Elle est petite." },
    { word: "Jeune", meaning: "Young", reading: "zhun", example_sentence: "Un jeune homme." },
    { word: "Vieux (corps)", meaning: "Old", reading: "vyuh", example_sentence: "Une vieille dame." },
    { word: "Beau (corps)", meaning: "Handsome", reading: "boh", example_sentence: "Il est beau." },
    { word: "Belle", meaning: "Beautiful (fem)", reading: "bel", example_sentence: "Elle est belle." },
    { word: "Propre", meaning: "Clean", reading: "proh-pruh", example_sentence: "Mains propres." },
    { word: "Sale", meaning: "Dirty", reading: "sal", example_sentence: "Vêtements sales." }, // Word #90
    { word: "Sain", meaning: "Healthy", reading: "sah", example_sentence: "Une nourriture saine." },
    { word: "Dangereux", meaning: "Dangerous", reading: "dah-zhuh-ruh", example_sentence: "C'est dangereux." },
    { word: "Sûr", meaning: "Safe", reading: "soor", example_sentence: "Un lieu sûr." },
    { word: "Vivant", meaning: "Alive", reading: "vee-vah", example_sentence: "Il est vivant." },
    { word: "Mort", meaning: "Dead", reading: "mor", example_sentence: "Une feuille morte." },
    { word: "Énergie", meaning: "Energy", reading: "ay-ner-zhee", example_sentence: "Avoir de l'énergie." },
    { word: "Force", meaning: "Strength", reading: "fors", example_sentence: "La force physique." },
    { word: "Esprit", meaning: "Mind", reading: "es-pree", example_sentence: "Un esprit calme." },
    { word: "Âme", meaning: "Soul", reading: "ahm", example_sentence: "L'âme humaine." },
    { word: "Bien-être", meaning: "Well-being", reading: "byah-ay-truh", example_sentence: "Chercher le bien-être." } // Word #100
];

// --- MODULE 9: NATURE & WEATHER ---
const m9_items = [
    { word: "Nature", meaning: "Nature", reading: "na-toor", example_sentence: "Protéger la nature." },
    { word: "Terre", meaning: "Earth / Soil", reading: "ter", example_sentence: "La terre est ronde." },
    { word: "Ciel", meaning: "Sky", reading: "syel", example_sentence: "Le ciel est bleu." },
    { word: "Soleil", meaning: "Sun", reading: "soh-lay", example_sentence: "Le soleil brille." },
    { word: "Lune", meaning: "Moon", reading: "loon", example_sentence: "La lune est pleine." },
    { word: "Étoile", meaning: "Star", reading: "ay-twal", example_sentence: "Regarder les étoiles." },
    { word: "Monde", meaning: "World", reading: "mohnd", example_sentence: "Le monde entier." },
    { word: "Environnement", meaning: "Environment", reading: "ah-vee-roh-mah", example_sentence: "Respecter l'environnement." }, // Word #8
    { word: "Météo", meaning: "Weather (forecast)", reading: "may-tay-oh", example_sentence: "Regarder la météo." }, // Word #9
    { word: "Temps (météo)", meaning: "Weather", reading: "tah", example_sentence: "Quel temps fait-il ?" },
    { word: "Chaud (météo)", meaning: "Hot", reading: "shoh", example_sentence: "Il fait chaud." },
    { word: "Froid (météo)", meaning: "Cold", reading: "frwa", example_sentence: "Il fait froid." },
    { word: "Beau (météo)", meaning: "Nice", reading: "boh", example_sentence: "Il fait beau." },
    { word: "Mauvais (météo)", meaning: "Bad", reading: "moh-veh", example_sentence: "Le temps est mauvais." },
    { word: "Nuage", meaning: "Cloud", reading: "noo-azh", example_sentence: "Un gros nuage gris." }, // Word #15

    { word: "Pluie", meaning: "Rain", reading: "plwee", example_sentence: "Il y a de la pluie." },
    { word: "Neige", meaning: "Snow", reading: "nezh", example_sentence: "La neige tombe." },
    { word: "Vent", meaning: "Wind", reading: "vah", example_sentence: "Le vent souffle fort." },
    { word: "Orage", meaning: "Storm / Thunderstorm", reading: "oh-razh", example_sentence: "Un orage arrive." },
    { word: "Éclair", meaning: "Lightning", reading: "ay-kler", example_sentence: "Un éclair dans le ciel." },
    { word: "Tonnerre", meaning: "Thunder", reading: "toh-ner", example_sentence: "Le bruit du tonnerre." },
    { word: "Tempête", meaning: "Storm / Gale", reading: "tah-pet", example_sentence: "Une tempête de neige." },
    { word: "Brouillard", meaning: "Fog", reading: "broo-yar", example_sentence: "Brouillard épais." },
    { word: "Glace (météo)", meaning: "Ice", reading: "glas", example_sentence: "Il y a de la glace." },
    { word: "Humidité", meaning: "Humidity", reading: "oo-mee-dee-tay", example_sentence: "Forte humidité." },
    { word: "Saison", meaning: "Season", reading: "se-zoh", example_sentence: "Quelle est ta saison ?" },
    { word: "Printemps", meaning: "Spring", reading: "prah-tah", example_sentence: "Au printemps." },
    { word: "Été", meaning: "Summer", reading: "ay-tay", example_sentence: "En été." },
    { word: "Automne", meaning: "Autumn", reading: "oh-tohn", example_sentence: "En automne." },
    { word: "Hiver", meaning: "Winter", reading: "ee-ver", example_sentence: "En hiver." },
    { word: "Température", meaning: "Temperature", reading: "tah-pay-ra-toor", example_sentence: "La température baisse." },

    { word: "Montagne (nature)", meaning: "Mountain", reading: "moh-tan-yuh", example_sentence: "Aller à la montagne." },
    { word: "Forêt (nature)", meaning: "Forest", reading: "foh-ray", example_sentence: "Une forêt de pins." },
    { word: "Arbre", meaning: "Tree", reading: "ar-bruh", example_sentence: "Un arbre centenaire." },
    { word: "Fleur", meaning: "Flower", reading: "flur", example_sentence: "Une jolie fleur." },
    { word: "Herbe", meaning: "Grass", reading: "er-buh", example_sentence: "Marcher sur l'herbe." },
    { word: "Feuille", meaning: "Leaf", reading: "fuy", example_sentence: "Une feuille verte." },
    { word: "Plante", meaning: "Plant", reading: "plah-tuh", example_sentence: "Arroser les plantes." },
    { word: "Jardin", meaning: "Garden", reading: "zhar-dah", example_sentence: "Un petit jardin." },
    { word: "Parc", meaning: "Park", reading: "park", example_sentence: "Le parc de la ville." },
    { word: "Plage (nature)", meaning: "Beach", reading: "plazh", example_sentence: "Sable sur la plage." },
    { word: "Mer", meaning: "Sea", reading: "mer", example_sentence: "La mer est bleue." },
    { word: "Océan", meaning: "Ocean", reading: "oh-say-ah", example_sentence: "L'océan Atlantique." },
    { word: "Lac", meaning: "Lake", reading: "lak", example_sentence: "Le lac est calme." },
    { word: "Rivière", meaning: "River", reading: "ree-vyer", example_sentence: "L'eau de la rivière." },
    { word: "Vague", meaning: "Wave", reading: "vag", example_sentence: "De grosses vagues." },

    { word: "Sable", meaning: "Sand", reading: "sa-bluh", example_sentence: "Sable chaud." },
    { word: "Pierre", meaning: "Stone / Rock", reading: "pyer", example_sentence: "Une pierre grise." },
    { word: "Rocher", meaning: "Rock (big)", reading: "roh-shay", example_sentence: "Grimper sur un rocher." },
    { word: "Désert (nature)", meaning: "Desert", reading: "day-zer", example_sentence: "Le désert du Sahara." },
    { word: "Île (nature)", meaning: "Island", reading: "eel", example_sentence: "Une île tropicale." },
    { word: "Campagne", meaning: "Countryside", reading: "kah-pah-nyuh", example_sentence: "Vivre à la campagne." },
    { word: "Paysage", meaning: "Landscape", reading: "pay-zee-zazh", example_sentence: "Un beau paysage." },
    { word: "Horizon", meaning: "Horizon", reading: "oh-ree-zoh", example_sentence: "Regarder l'horizon." },
    { word: "Air", meaning: "Air", reading: "er", example_sentence: "L'air pur." },
    { word: "Espace", meaning: "Space", reading: "es-pas", example_sentence: "L'espace infini." },
    { word: "Lumière", meaning: "Light", reading: "loo-myer", example_sentence: "Lumière du jour." },
    { word: "Ombre", meaning: "Shadow / Shade", reading: "oh-bruh", example_sentence: "À l'ombre." },
    { word: "Feu", meaning: "Fire", reading: "fuh", example_sentence: "Le feu brûle." },
    { word: "Eau", meaning: "Water", reading: "oh", example_sentence: "L'eau est vitale." },
    { word: "Boisson (nature)", meaning: "Wait... overlapping theme" },
    { word: "Goutte", meaning: "Drop", reading: "goot", example_sentence: "Une goutte de pluie." },

    { word: "Animal", meaning: "Animal", reading: "a-nee-mal", example_sentence: "Un animal sauvage." },
    { word: "Chien", meaning: "Dog", reading: "shyah", example_sentence: "Le chien aboie." },
    { word: "Chat", meaning: "Cat", reading: "sha", example_sentence: "Le chat ronronne." },
    { word: "Oiseau", meaning: "Bird", reading: "wa-zoh", example_sentence: "Un oiseau vole." },
    { word: "Poisson", meaning: "Fish", reading: "pwa-soh", example_sentence: "Un poisson nage." },
    { word: "Cheval", meaning: "Horse", reading: "shuh-val", example_sentence: "Monter à cheval." },
    { word: "Vache", meaning: "Cow", reading: "vash", example_sentence: "La vache mange de l'herbe." },
    { word: "Cochon", meaning: "Pig", reading: "koh-shoh", example_sentence: "Un petit cochon." },
    { word: "Mouton", meaning: "Sheep", reading: "moo-toh", example_sentence: "Un mouton blanc." },
    { word: "Canard", meaning: "Duck", reading: "ka-nar", example_sentence: "Le canard sur l'eau." },
    { word: "Lion", meaning: "Lion", reading: "lyoh", example_sentence: "Le lion est fort." },
    { word: "Éléphant", meaning: "Elephant", reading: "ay-lay-fah", example_sentence: "Un gros éléphant." },
    { word: "Singe", meaning: "Monkey", reading: "sah-zhuh", example_sentence: "Le singe grimpe." },
    { word: "Insecte", meaning: "Insect", reading: "ah-sek-tuh", example_sentence: "Un petit insecte." },
    { word: "Papillon", meaning: "Butterfly", reading: "pa-pee-yoh", example_sentence: "Un papillon coloré." },

    { word: "Pollution", meaning: "Pollution", reading: "poh-loo-syoh", example_sentence: "Lutter contre la pollution." },
    { word: "Écologie", meaning: "Ecology", reading: "ay-koh-loh-zhee", example_sentence: "Une vie écologique." },
    { word: "Recycler", meaning: "To recycle", reading: "ruh-see-klay", example_sentence: "Il faut recycler." },
    { word: "Planète", meaning: "Planet", reading: "pla-net", example_sentence: "Protéger la planète." },
    { word: "Chauffage", meaning: "Heating", reading: "shoh-fazh", example_sentence: "Allumer le chauffage." },
    { word: "Soleil levant", meaning: "Rising sun", reading: "soh-lay luh-vah", example_sentence: "Le soleil levant est beau." }, // Word #81
    { word: "Coucher de soleil", meaning: "Sunset", reading: "koo-shay duh soh-lay", example_sentence: "Un beau coucher de soleil." },
    { word: "Briller", meaning: "To shine", reading: "bree-yay", example_sentence: "Les étoiles brillent." },
    { word: "Tomber", meaning: "To fall", reading: "toh-bay", example_sentence: "La pluie tombe." },
    { word: "Souffler", meaning: "To blow", reading: "soo-flay", example_sentence: "Le vent souffle." },
    { word: "Chauffer", meaning: "To heat", reading: "shoh-fay", example_sentence: "Le soleil chauffe." },
    { word: "Refroidir", meaning: "To cool", reading: "ruh-frwa-deer", example_sentence: "L'air refroidit." },
    { word: "Changer (météo)", meaning: "To change", reading: "shah-zhay", example_sentence: "Le temps change." },
    { word: "Observer", meaning: "To observe", reading: "ohb-zer-vay", example_sentence: "Observer la nature." },
    { word: "Chercher (nature)", meaning: "To look for", reading: "sher-shay", example_sentence: "Chercher des fleurs." },
    { word: "Sauvage", meaning: "Wild", reading: "soh-vazh", example_sentence: "Un lieu sauvage." }, // Word #90
    { word: "Calme (nature)", meaning: "Calm", reading: "kal-muh", example_sentence: "Un lac calme." },
    { word: "Pur", meaning: "Pure", reading: "poor", example_sentence: "De l'eau pure." },
    { word: "Frais (nature)", meaning: "Fresh", reading: "freh", example_sentence: "L'air est frais." },
    { word: "Humide", meaning: "Humid / Wet", reading: "oo-meed", example_sentence: "L'herbe est humide." },
    { word: "Sec", meaning: "Dry", reading: "sek", example_sentence: "Le sol est sec." },
    { word: "Haut", meaning: "High", reading: "oh", example_sentence: "Une haute montagne." },
    { word: "Profond", meaning: "Deep", reading: "proh-foh", example_sentence: "L'océan est profond." },
    { word: "Vaste", meaning: "Vast", reading: "vas-tuh", example_sentence: "Un vaste désert." },
    { word: "Beau (nature)", meaning: "Beautiful", reading: "boh", example_sentence: "Un beau paysage." },
    { word: "Merveilleux", meaning: "Wonderful", reading: "mer-vay-yuh", example_sentence: "Un monde merveilleux." } // Word #100
];

const modules = [
    createModule("fr_a1_m7", "A1 French - Module 7: Shopping & Fashion", m7_items.slice(0, 100)),
    {
        id: "fr_a1_m8",
        name: "A1 French - Module 8: Health & Body",
        count: 100,
        vocabularyItems: [
            ...m8_items,
            { word: "Cuisse", meaning: "Thigh", reading: "kweess", example_sentence: "Un muscle de la cuisse." },
            { word: "Mollet", meaning: "Calf (body)", reading: "moh-leh", example_sentence: "J'ai mal au mollet." }
        ]
    },
    createModule("fr_a1_m9", "A1 French - Module 9: Nature & Weather", m9_items.slice(0, 100))
];

modules.forEach(m => {
    fs.writeFileSync(path.join(__dirname, `../firestore_data/french_a1_${m.id.split('_').pop()}.json`), JSON.stringify(m, null, 2));
});

console.log('Saved 100 UNIQUE French words to firestore_data/french_a1_m7.json, m8.json, m9.json');
