const fs = require('fs');
const path = require('path');

const realN3Words = [
    { word: "恩恵", reading: "onkei", meaning: "Benefit/Blessing", example_sentence: "自然の恩恵を受ける反面、災害の脅威にも常に備えなければなりません。" },
    { word: "介入", reading: "kainyuu", meaning: "Intervention", example_sentence: "政府が介入することによって、市場の混乱を最小限に抑え込みました。" },
    { word: "介護", reading: "kaigo", meaning: "Nursing care", example_sentence: "介護を続けるうちに、精神的なゆとりの重要性を再認識しました。" },
    { word: "該当", reading: "gaitou", meaning: "Corresponding", example_sentence: "条件に該当する反面、提出書類の不備で受理されないケースもあります。" },
    { word: "改訂", reading: "kaitei", meaning: "Revision", example_sentence: "教科書を改訂することによって、最新の科学的知見を反映させます。" },
    { word: "獲得", reading: "kakutoku", meaning: "Acquisition", example_sentence: "メダルを獲得する反面、そこに至るまでの過酷な練習は想像を絶します。" },
    { word: "確保", reading: "kakuho", meaning: "Ensuring", example_sentence: "座席を確保することによって、長い旅も快適に過ごせました。" },
    { word: "活性", reading: "kassei", meaning: "Activity/Activation", example_sentence: "地域を活性化することによって、若者の流出を食い止めることができます。" },
    { word: "過剰", reading: "kajou", meaning: "Excess", example_sentence: "過剰な包装を控えるうちに、環境への意識が自然と高まってきました。" },
    { word: "稼働", reading: "kadou", meaning: "Operation", example_sentence: "工場がフル稼働する反面、電力消費の増大が懸念材料となっています。" },
    { word: "管轄", reading: "kankatsu", meaning: "Jurisdiction", example_sentence: "管轄を明確にする反面、縦割り行政の弊害も指摘されています。" },
    { word: "看過", reading: "kanka", meaning: "Pass over/Overlook", example_sentence: "重大なミスを看過することによって、取り返しのつかない事態を招きました。" },
    { word: "還元", reading: "kangen", meaning: "Resolution/Return", example_sentence: "利益を社会に還元する反面、株主への配当とのバランスも重要です。" },
    { word: "慣行", reading: "kankou", meaning: "Customary practice", example_sentence: "商慣行を見直すことによって、取引の透明性を高めていきます。" },
    { word: "勧告", reading: "kankoku", meaning: "Advice/Counsel", example_sentence: "是正勧告を受けるうちに、社内体制の不備が次々と露呈しました。" },
    { word: "観測", reading: "kansoku", meaning: "Observation", example_sentence: "気象を観測する反面、予報が外れた際の社会的影響も考慮します。" },
    { word: "甘受", reading: "kanju", meaning: "Be resigned to", example_sentence: "厳しい条件を甘受することによって、交渉を辛うじて成立させました。" },
    { word: "官僚", reading: "kanryou", meaning: "Bureaucracy", example_sentence: "官僚制度を刷新する反面、行政の継続性をどう担保するかが課題です。" },
    { word: "寛容", reading: "kan'you", meaning: "Tolerance/Generosity", example_sentence: "他者に寛容であるうちに、心のゆとりが周囲にも伝わっていきました。" },
    { word: "既往", reading: "kiou", meaning: "Past history", example_sentence: "既往歴を確認することによって、最適な治療方針を決定します。" },
    { word: "危害", reading: "kigai", meaning: "Hazard/Harm", example_sentence: "危害を及ぼすうちに、社会的な制裁を受けることになりかねません。" },
    { word: "棄却", reading: "kikyaku", meaning: "Rejection/Dismissal", example_sentence: "請求を棄却する反面、判決理由には和解への含みも持たされました。" },
    { word: "規格", reading: "kikaku", meaning: "Standard/Norm", example_sentence: "世界規格を統一することによって、貿易の更なる活性化を図ります。" },
    { word: "危惧", reading: "kigu", meaning: "Fear/Apprehension", example_sentence: "将来を危惧することによって、今取るべき行動が明確になってきました。" },
    { word: "寄稿", reading: "kikou", meaning: "Contribution", example_sentence: "雑誌に寄稿するうちに、自分の考えを整理する良い機会となりました。" },
    { word: "寄贈", reading: "kizou", meaning: "Donation/Gift", example_sentence: "図書を寄贈する反面、管理の手間が増えるという側面も無視できません。" },
    { word: "起点", reading: "kiten", meaning: "Starting point", example_sentence: "ここを起点とすることによって、新しい探検のルートが開かれました。" },
    { word: "機微", reading: "kibi", meaning: "Subtleties", example_sentence: "人情の機微に触れる反面、社会の非情さも同時に学ぶことになりました。" },
    { word: "急務", reading: "kyuumu", meaning: "Urgent business", example_sentence: "対策が急務であるうちに、実行可能なプランを早急に策定します。" },
    { word: "救済", reading: "kyuusai", meaning: "Relief/Salvation", example_sentence: "弱者を救済することによって、社会全体の安定を維持しようとしています。" },
    { word: "共鳴", reading: "kyoumei", meaning: "Resonance/Sympathy", example_sentence: "その理念に共鳴するうちに、多くの賛同者が集まり、大きな力となりました。" },
    { word: "驚異", reading: "kyouyi", meaning: "Wonder/Miracle", example_sentence: "生命の驚異を目の当たりにする反面、その脆さについても考えさせられます。" },
    { word: "享楽", reading: "kyouraku", meaning: "Enjoyment/Pleasure", example_sentence: "享楽に耽るうちに、本来の目的を忘れてしまうことは避けたい。" },
    { word: "強要", reading: "kyouyou", meaning: "Compulsion/Coercion", example_sentence: "意見を強要することによって、部下との信頼関係が完全に失われてしまいました。" },
    { word: "局面", reading: "kyokumen", meaning: "Phase/Situation", example_sentence: "新しい局面に差し掛かるうちに、当初の目標を再確認する必要が出てきました。" },
    { word: "虚偽", reading: "kyogi", meaning: "Falsehood/Fallacy", example_sentence: "虚偽の報告する反面、いずれ露呈することへの不安も消えませんでした。" },
    { word: "挙行", reading: "kyokou", meaning: "Celebration/Performance", example_sentence: "式典を挙行することによって、正式に新しいプロジェクトがスタートしました。" },
    { word: "拒否", reading: "kyohi", meaning: "Refusal/Rejection", example_sentence: "要求を拒否する反面、話し合いの余地は残しておくという高度な交渉です。" },
    { word: "寄与", reading: "kiyo", meaning: "Contribution", example_sentence: "地域社会に寄与することによって、企業のブランド価値を向上させます。" },
    { word: "極致", reading: "kyokuchi", meaning: "Zenith/Climax", example_sentence: "美の極致を追求するうちに、人間業とは思えない芸術作品が誕生しました。" },
    { word: "督促", reading: "tokusoku", meaning: "Urge/Demand", example_sentence: "支払いを督促する反面、相手の事情にも配慮した柔軟な対応を心がけます。" },
    { word: "牽引", reading: "ken'in", meaning: "Traction/Driving force", example_sentence: "リーダーがチームを牽引するうちに、全員のやる気に火がつきました。" },
    { word: "健勝", reading: "kenshou", meaning: "Good health", example_sentence: "皆様のご健勝を祈ることによって、手紙を締めくくるのが礼儀です。" },
    { word: "現像", reading: "genzou", meaning: "Developing (photos)", example_sentence: "写真を現像するうちに、撮影時の感動が鮮やかに蘇ってきました。" },
    { word: "解雇", reading: "kaiko", meaning: "Dismissal/Discharge", example_sentence: "不況により解雇されるうちに、自分自身のスキルを磨く必要性を痛感しました。" },
    { word: "厚情", reading: "koujou", meaning: "Courtesy/Kindness", example_sentence: "皆様のご厚情に感謝する反面、自らの未熟さを深く恥じるばかりです。" },
    { word: "更生", reading: "kousei", meaning: "Rehabilitation", example_sentence: "社会的に更生する反面、過去の過ちを完全に消し去ることは不可能です。" },
    { word: "更迭", reading: "koutetsu", meaning: "Change/Shuffle", example_sentence: "閣僚を更迭することによって、政権の刷新を図ろうとしています。" },
    { word: "抗争", reading: "kousou", meaning: "Dispute/Strife", example_sentence: "内部抗争が激化するうちに、組織そのものの存立が危うくなりました。" },
    { word: "拘束", reading: "kousoku", meaning: "Restriction/Restraint", example_sentence: "行動を拘束する反面、それによって万が一の事故を防ぐという目的もあります。" },
    { word: "校閲", reading: "kouetsu", meaning: "Proofreading", example_sentence: "原稿を校閲するうちに、自分の知識不足を痛感させられる毎日です。" },
    { word: "公認", reading: "kounin", meaning: "Official recognition", example_sentence: "公認を得る反面、これからは厳しい成績が常に求められることになります。" },
    { word: "荒廃", reading: "kouhai", meaning: "Ruin/Decay", example_sentence: "街が荒廃することによって、治安の悪化が深刻な社会問題となっています。" },
    { word: "狡猾", reading: "koukatsu", meaning: "Cunning/Crafty", example_sentence: "狡猾な手段を用いるうちに、周囲の信頼を完全に失ってしまいました。" },
    { word: "降格", reading: "koukaku", meaning: "Demotion/Degradation", example_sentence: "二部リーグへ降格する反面、一から出直そうという結束力も生まれました。" },
    { word: "好況", reading: "koukyou", meaning: "Prosperity/Good times", example_sentence: "好況に沸くうちに、市場がバブル化しているという警鐘も鳴らされました。" },
    { word: "功労", reading: "kourou", meaning: "Merit/Valuable service", example_sentence: "長年の功労を称える反面、後進の育成が滞っている現状も直視すべきです。" },
    { word: "考察", reading: "kousatsu", meaning: "Consideration", example_sentence: "考察を深めることによって、論理的な裏付けが得られました。" },
    { word: "講習", reading: "koushuu", meaning: "Short course/Training", example_sentence: "講習を受けるうちに、最新の技術を習得することができました。" },
    { word: "更新", reading: "koushin", meaning: "Renewal/Update", example_sentence: "記録を更新する反面、ライバルも着実に力をつけています。" },
    { word: "公正", reading: "kousei", meaning: "Justice/Fairness", example_sentence: "公正な判断を下すことによって、市民の信頼を勝ち得ました。" },
    { word: "構成", reading: "kousei", meaning: "Organization/Composition", example_sentence: "文章を構成するうちに、論理的な矛盾に気づくことがよくあります。" },
    { word: "控訴", reading: "kouso", meaning: "Appeal (court)", example_sentence: "判決に不服で控訴する反面、長期化する裁判への不安も募ります。" },
    { word: "降参", reading: "kousan", meaning: "Surrender", example_sentence: "降参することによって、これ以上の無駄な争いを避けました。" },
    { word: "考慮", reading: "koryo", meaning: "Consideration", example_sentence: "事情を考慮するうちに、当初の決定を柔軟に変更しました。" },
    { word: "巧妙", reading: "koumyou", meaning: "Ingenious/Skilled", example_sentence: "巧妙な罠を仕掛ける反面、自分も墓穴を掘らないよう細心の注意を払います。" },
    { word: "拘留", reading: "kouryuu", meaning: "Detention", example_sentence: "容疑者を拘留することによって、証拠隠滅を防ぎます。" },
    { word: "交流", reading: "kouryuu", meaning: "Exchange/Intercourse", example_sentence: "文化交流を進めるうちに、互いの違いを認め合えるようになりました。" },
    { word: "公衆", reading: "koushuu", meaning: "Public", example_sentence: "公衆の面前で失態を演じる反面、そこから学ぶことも多かったです。" },
    { word: "効率", reading: "kouritsu", meaning: "Efficiency", example_sentence: "効率を追求することによって、残業時間を大幅に削減できました。" },
    { word: "荒野", reading: "kouya", meaning: "Wilderness/Waste land", example_sentence: "荒野を彷徨ううちに、孤独の深さを知ることになりました。" },
    { word: "合流", reading: "gouryuu", meaning: "Confluence/Union", example_sentence: "本隊と合流する反面、食料の配分が課題となりました。" },
    { word: "高騰", reading: "koutou", meaning: "Sudden rise (price)", example_sentence: "物価が高騰することによって、庶民の暮らしは圧迫されています。" },
    { word: "号令", reading: "gourei", meaning: "Command/Order", example_sentence: "号令を下すうちに、組織全体が一致団結して動き出しました。" },
    { word: "誇張", reading: "kochou", meaning: "Exaggeration", example_sentence: "事実を誇張する反面、聞き手の注意を惹きつけるテクニックでもあります。" },
    { word: "誇り", reading: "hokori", meaning: "Pride", example_sentence: "誇りを持つことによって、困難な状況でも品位を保つことができます。" },
    { word: "顧客", reading: "kokyaku", meaning: "Customer/Client", example_sentence: "顧客の声を聴くうちに、製品の改良すべき点が明確になりました。" },
    { word: "呼応", reading: "koou", meaning: "Cooperation/Response", example_sentence: "呼びかけに呼応する反面、具体的な行動に移すには勇気が必要です。" },
    { word: "孤児", reading: "koji", meaning: "Orphan", example_sentence: "孤児を支援することによって、未来のリーダーを育てる活動です。" },
    { word: "個室", reading: "koshitsu", meaning: "Private room", example_sentence: "個室で集中するうちに、懸案だった論文を書き上げることができました。" },
    { word: "古文書", reading: "komonjo", meaning: "Ancient document", example_sentence: "古文書を解読する反面、当時の歴史の生々しさに圧倒されます。" },
    { word: "雇用", reading: "koyou", meaning: "Employment", example_sentence: "雇用を創出することによって、地域の経済を活性化させます。" },
    { word: "困窮", reading: "konkyuu", meaning: "Poverty/Distress", example_sentence: "生活が困窮するうちに、かつての友人たちは去っていきました。" },
    { word: "昆虫", reading: "konchuu", meaning: "Insect", example_sentence: "昆虫を観察する反面、自然界の弱肉強食の厳しさも知りました。" },
    { word: "根底", reading: "kontei", meaning: "Root/Basis", example_sentence: "思想の根底を問うことによって、自己の存在意義を再確認します。" },
    { word: "混沌", reading: "konton", meaning: "Chaos/Confusion", example_sentence: "混沌とした状況が続くうちに、ようやく一筋の光明が見えてきました。" },
    { word: "婚約", reading: "kon'yaku", meaning: "Engagement", example_sentence: "婚約を解消する反面、お互いの人生への理解は深まりました。" },
    { word: "混乱", reading: "konran", meaning: "Confusion/Disorder", example_sentence: "指示が混乱することによって、現場はパニックに陥ってしまいました。" },
    { word: "策略", reading: "sakuryaku", meaning: "Stratagem/Scheme", example_sentence: "策略を巡らせるうちに、自分自身が誰を信じていいか分からなくなりました。" },
    { word: "削減", reading: "sakugen", meaning: "Reduction/Cut", example_sentence: "コストを削減する反面、サービスの質を落とさない工夫が求められます。" },
    { word: "錯覚", reading: "sakkaku", meaning: "Illusion/Hallucination", example_sentence: "錯覚を起こすことによって、平面の絵が立体的に見えてきます。" },
    { word: "察知", reading: "satchi", meaning: "Sense/Infer", example_sentence: "危険を察知するうちに、素早く避難することが可能になりました。" },
    { word: "殺風景", reading: "sappuukei", meaning: "Bleak/Desolate", example_sentence: "殺風景な部屋に花を飾る反面、心の寂しさは埋められないままでした。" },
    { word: "悟り", reading: "satori", meaning: "Enlightenment", example_sentence: "悟りを開くことによって、世俗の悩みから解放されると言われています。" },
    { word: "裁量", reading: "sairyou", meaning: "Discretion", example_sentence: "個人の裁量に任せるうちに、意外な才能が開花することもあります。" },
    { word: "再編", reading: "saihen", meaning: "Reorganization", example_sentence: "業界を再編する反面、余剰人員の削減という痛みを伴います。" },
    { word: "採掘", reading: "saikutsu", meaning: "Mining", example_sentence: "鉱石を採掘することによって、国の近代化を支えてきました。" },
    { word: "催促", reading: "saisoku", meaning: "Pressing/Urge", example_sentence: "提出を催促するうちに、相手との関係がぎくしゃくし始めました。" },
    { word: "採択", reading: "saitaku", meaning: "Adoption/Selection", example_sentence: "決議を採択する反面、反対派の不満は依然として残っています。" },
    { word: "栽培", reading: "saibai", meaning: "Cultivation", example_sentence: "野菜を栽培することによって、食の安全の大切さを学びました。" },
    { word: "再発", reading: "saihatsu", meaning: "Recurrence", example_sentence: "病気が再発するうちに、日常の平穏がいかに貴重か痛感しました。" },
    { word: "細部", reading: "saibu", meaning: "Details", example_sentence: "細部にこだわる反面、全体像を見失わないバランス感覚が必要です。" },
    { word: "細胞", reading: "saibou", meaning: "Cell", example_sentence: "細胞の動きを観察することによって、生命の神秘に迫ります。" },
    { word: "遮断", reading: "shadan", meaning: "Interception/Cut-off", example_sentence: "連絡を遮断するうちに、外部の情報から取り残されてしまいました。" },
    { word: "搾取", reading: "sakushu", meaning: "Exploitation", example_sentence: "労働者を搾取する反面、自らは贅沢な暮らしを謳歌していました。" },
    { word: "昨今", reading: "sakkon", meaning: "Nowadays", example_sentence: "昨今の社会情勢を鑑みることによって、新たな戦略を立て直します。" },
    { word: "錯綜", reading: "saksou", meaning: "Complication", example_sentence: "情報が錯綜するうちに、何が真実か見極めるのが困難になりました。" },
    { word: "索引", reading: "sakuin", meaning: "Index", example_sentence: "索引を活用する反面、本文を隅々まで読むことも忘れてはなりません。" },
    { word: "策定", reading: "sakutei", meaning: "Formulation", example_sentence: "計画を策定することによって、組織の目標が明確になりました。" },
    { word: "削除", reading: "sakujo", meaning: "Deletion", example_sentence: "不要なファイルを削除するうちに、パソコンの動作が軽くなりました。" },
    { word: "炸裂", reading: "sakuretsu", meaning: "Explosion", example_sentence: "爆弾が炸裂する反面、平和を願う声も日増しに強まっています。" },
    { word: "挫折", reading: "zasetsu", meaning: "Setback/Frustration", example_sentence: "挫折を経験することによって、人間として一回り大きく成長しました。" },
    { word: "殺到", reading: "sattou", meaning: "Rush/Flood", example_sentence: "注文が殺到するうちに、配送システムの不備が露呈しました。" }
];

const fsPool = JSON.parse(fs.readFileSync(path.join('scripts', 'n3_pool.json'), 'utf8') || '[]');
const combinedPool = [...realN3Words, ...fsPool];
fs.writeFileSync(path.join('scripts', 'n3_pool.json'), JSON.stringify(combinedPool, null, 4));
console.log('N3 Pool size:', combinedPool.length);
