const fs = require('fs');
const path = require('path');

function createModule(moduleId, name, order, items, culturalTraps) {
    if (items.length !== 100) {
        console.warn(`⚠️ Warning: ${moduleId} has ${items.length} items. Expected 100.`);
    }
    return {
        id: moduleId,
        moduleId: moduleId,
        name: name,
        theme: name,
        order: order,
        count: 100,
        vocabularyItems: items.slice(0, 100),
        liarGameData: {
            culturalTraps: culturalTraps
        }
    };
}

// MODULE 22: Literature & Written Expression
const m22_items = [
    { word: "Littérature", meaning: "Literature", reading: "lee-tay-ra-toor", example_sentence: "J'étudie la littérature française." },
    { word: "Œuvre", meaning: "Work (of art)", reading: "uh-vruh", example_sentence: "Une œuvre magistrale." },
    { word: "Auteur", meaning: "Author", reading: "oh-tur", example_sentence: "L'auteur de ce roman est célèbre." },
    { word: "Écrivain", meaning: "Writer", reading: "ay-kree-vah", example_sentence: "Un écrivain talentueux." },
    { word: "Romancier", meaning: "Novelist", reading: "roh-mahn-syay", example_sentence: "Un romancier contemporain." },
    { word: "Poète", meaning: "Poet", reading: "poh-et", example_sentence: "Un grand poète français." },
    { word: "Dramaturge", meaning: "Playwright", reading: "dra-ma-toorzh", example_sentence: "Molière était un dramaturge." },
    { word: "Essayiste", meaning: "Essayist", reading: "ay-say-eest", example_sentence: "Un essayiste politique." },
    { word: "Critique", meaning: "Critic / Critical", reading: "kree-teek", example_sentence: "Un critique littéraire." },
    { word: "Manuscrit", meaning: "Manuscript", reading: "ma-noo-skree", example_sentence: "Le manuscrit original." },
    { word: "Brouillon", meaning: "Draft", reading: "broo-yoh", example_sentence: "Faire un brouillon." },
    { word: "Rédaction", meaning: "Writing / Essay", reading: "ray-dak-syoh", example_sentence: "La rédaction d'un texte." },
    { word: "Rédiger", meaning: "To write / Draft", reading: "ray-dee-zhay", example_sentence: "Rédiger une lettre." },
    { word: "Composer", meaning: "To compose", reading: "kohm-poh-zay", example_sentence: "Composer un poème." },
    { word: "Réviser", meaning: "To revise", reading: "ray-vee-zay", example_sentence: "Réviser son texte." },
    { word: "Corriger", meaning: "To correct", reading: "koh-ree-zhay", example_sentence: "Corriger les fautes." },
    { word: "Améliorer", meaning: "To improve", reading: "a-may-lyoh-ray", example_sentence: "Améliorer son style." },
    { word: "Peaufiner", meaning: "To polish / Perfect", reading: "poh-fee-nay", example_sentence: "Peaufiner un texte." },
    { word: "Publier", meaning: "To publish", reading: "poo-blee-ay", example_sentence: "Publier un livre." },
    { word: "Éditer", meaning: "To edit / Publish", reading: "ay-dee-tay", example_sentence: "Éditer un ouvrage." },
    { word: "Édition", meaning: "Edition / Publishing", reading: "ay-dee-syoh", example_sentence: "Une nouvelle édition." },
    { word: "Éditeur", meaning: "Publisher / Editor", reading: "ay-dee-tur", example_sentence: "Trouver un éditeur." },
    { word: "Maison d'édition", meaning: "Publishing house", reading: "may-zoh day-dee-syoh", example_sentence: "Une grande maison d'édition." },
    { word: "Tirage", meaning: "Print run / Circulation", reading: "tee-razh", example_sentence: "Un tirage limité." },
    { word: "Exemplaire", meaning: "Copy (of book)", reading: "eg-zahm-pler", example_sentence: "Un exemplaire dédicacé." },
    { word: "Chapitre", meaning: "Chapter", reading: "sha-pee-truh", example_sentence: "Le premier chapitre." },
    { word: "Paragraphe", meaning: "Paragraph", reading: "pa-ra-graf", example_sentence: "Un paragraphe bien structuré." },
    { word: "Phrase", meaning: "Sentence", reading: "fraz", example_sentence: "Une phrase complexe." },
    { word: "Proposition", meaning: "Clause", reading: "proh-poh-zee-syoh", example_sentence: "Une proposition subordonnée." },
    { word: "Vocabulaire", meaning: "Vocabulary", reading: "voh-ka-boo-ler", example_sentence: "Enrichir son vocabulaire." },
    { word: "Syntaxe", meaning: "Syntax", reading: "san-taks", example_sentence: "La syntaxe française." },
    { word: "Grammaire", meaning: "Grammar", reading: "gra-mer", example_sentence: "Réviser la grammaire." },
    { word: "Orthographe", meaning: "Spelling", reading: "or-toh-graf", example_sentence: "Une faute d'orthographe." },
    { word: "Ponctuation", meaning: "Punctuation", reading: "pohnk-too-a-syoh", example_sentence: "La ponctuation correcte." },
    { word: "Virgule", meaning: "Comma", reading: "veer-gool", example_sentence: "Mettre une virgule." },
    { word: "Point", meaning: "Period / Point", reading: "pwa", example_sentence: "Terminer par un point." },
    { word: "Point-virgule", meaning: "Semicolon", reading: "pwa veer-gool", example_sentence: "Utiliser un point-virgule." },
    { word: "Deux-points", meaning: "Colon", reading: "duh pwa", example_sentence: "Les deux-points introduisent." },
    { word: "Guillemets", meaning: "Quotation marks", reading: "gee-meh", example_sentence: "Mettre entre guillemets." },
    { word: "Parenthèses", meaning: "Parentheses", reading: "pa-rahn-tez", example_sentence: "Entre parenthèses." },
    { word: "Tiret", meaning: "Dash", reading: "tee-ray", example_sentence: "Un tiret long." },
    { word: "Apostrophe", meaning: "Apostrophe", reading: "a-poh-strof", example_sentence: "L'apostrophe est nécessaire." },
    { word: "Majuscule", meaning: "Capital letter", reading: "ma-zhoos-kool", example_sentence: "Écrire en majuscule." },
    { word: "Minuscule", meaning: "Lowercase letter", reading: "mee-noos-kool", example_sentence: "En minuscule." },
    { word: "Accent", meaning: "Accent", reading: "ak-sah", example_sentence: "L'accent aigu." },
    { word: "Cédille", meaning: "Cedilla", reading: "say-dee-yuh", example_sentence: "Le ç avec cédille." },
    { word: "Tréma", meaning: "Diaeresis", reading: "tray-ma", example_sentence: "Le tréma sur le ï." },
    { word: "Style", meaning: "Style", reading: "steel", example_sentence: "Un style élégant." },
    { word: "Ton", meaning: "Tone", reading: "toh", example_sentence: "Le ton du texte." },
    { word: "Registre", meaning: "Register / Level of language", reading: "ruh-zhees-truh", example_sentence: "Un registre soutenu." },
    { word: "Familier", meaning: "Familiar / Informal", reading: "fa-mee-lyay", example_sentence: "Un langage familier." },
    { word: "Soutenu", meaning: "Formal / Elevated", reading: "soo-tuh-noo", example_sentence: "Un style soutenu." },
    { word: "Courant", meaning: "Current / Standard", reading: "koo-rah", example_sentence: "Le français courant." },
    { word: "Littéraire", meaning: "Literary", reading: "lee-tay-rer", example_sentence: "Un style littéraire." },
    { word: "Narratif", meaning: "Narrative", reading: "na-ra-teef", example_sentence: "Un texte narratif." },
    { word: "Descriptif", meaning: "Descriptive", reading: "des-kreep-teef", example_sentence: "Un passage descriptif." },
    { word: "Argumentatif", meaning: "Argumentative", reading: "ar-goo-mahn-ta-teef", example_sentence: "Un texte argumentatif." },
    { word: "Explicatif", meaning: "Explanatory", reading: "eks-plee-ka-teef", example_sentence: "Un texte explicatif." },
    { word: "Injonctif", meaning: "Injunctive / Instructional", reading: "an-zhohnk-teef", example_sentence: "Un texte injonctif." },
    { word: "Narration", meaning: "Narration", reading: "na-ra-syoh", example_sentence: "La narration du récit." },
    { word: "Description", meaning: "Description", reading: "des-kreep-syoh", example_sentence: "Une description détaillée." },
    { word: "Dialogue", meaning: "Dialogue", reading: "dyah-lohg", example_sentence: "Un dialogue vivant." },
    { word: "Monologue", meaning: "Monologue", reading: "moh-noh-lohg", example_sentence: "Un long monologue." },
    { word: "Discours", meaning: "Speech / Discourse", reading: "dees-koor", example_sentence: "Un discours direct." },
    { word: "Récit", meaning: "Story / Narrative", reading: "ray-see", example_sentence: "Un récit captivant." },
    { word: "Conte", meaning: "Tale / Story", reading: "kohnt", example_sentence: "Un conte de fées." },
    { word: "Nouvelle", meaning: "Short story / News", reading: "noo-vel", example_sentence: "Une nouvelle fantastique." },
    { word: "Roman", meaning: "Novel", reading: "roh-mah", example_sentence: "Un roman policier." },
    { word: "Poésie", meaning: "Poetry", reading: "poh-ay-zee", example_sentence: "La poésie lyrique." },
    { word: "Vers", meaning: "Verse / Line of poetry", reading: "ver", example_sentence: "Un vers alexandrin." },
    { word: "Strophe", meaning: "Stanza", reading: "strohf", example_sentence: "Une strophe de quatre vers." },
    { word: "Rime", meaning: "Rhyme", reading: "reem", example_sentence: "Des rimes croisées." },
    { word: "Rythme", meaning: "Rhythm", reading: "reetm", example_sentence: "Le rythme du poème." },
    { word: "Métaphore", meaning: "Metaphor", reading: "may-ta-for", example_sentence: "Une belle métaphore." },
    { word: "Comparaison", meaning: "Comparison / Simile", reading: "kohm-pa-ray-zoh", example_sentence: "Une comparaison poétique." },
    { word: "Personnification", meaning: "Personification", reading: "per-soh-nee-fee-ka-syoh", example_sentence: "La personnification de la nature." },
    { word: "Symbole", meaning: "Symbol", reading: "sam-bohl", example_sentence: "Un symbole puissant." },
    { word: "Allégorie", meaning: "Allegory", reading: "a-lay-goh-ree", example_sentence: "Une allégorie morale." },
    { word: "Ironie", meaning: "Irony", reading: "ee-roh-nee", example_sentence: "L'ironie du sort." },
    { word: "Satire", meaning: "Satire", reading: "sa-teer", example_sentence: "Une satire sociale." },
    { word: "Humour", meaning: "Humor", reading: "oo-moor", example_sentence: "Un texte plein d'humour." },
    { word: "Tragédie", meaning: "Tragedy", reading: "tra-zhay-dee", example_sentence: "Une tragédie classique." },
    { word: "Comédie", meaning: "Comedy", reading: "koh-may-dee", example_sentence: "Une comédie de Molière." },
    { word: "Drame", meaning: "Drama", reading: "dram", example_sentence: "Un drame romantique." },
    { word: "Genre", meaning: "Genre", reading: "zhahn-ruh", example_sentence: "Le genre littéraire." },
    { word: "Thème", meaning: "Theme", reading: "tem", example_sentence: "Le thème principal." },
    { word: "Motif", meaning: "Motif / Pattern", reading: "moh-teef", example_sentence: "Un motif récurrent." },
    { word: "Intrigue", meaning: "Plot", reading: "an-treeg", example_sentence: "L'intrigue du roman." },
    { word: "Péripétie", meaning: "Plot twist / Event", reading: "pay-ree-pay-see", example_sentence: "Une péripétie inattendue." },
    { word: "Dénouement", meaning: "Denouement / Ending", reading: "day-noo-mah", example_sentence: "Le dénouement de l'histoire." },
    { word: "Personnage", meaning: "Character", reading: "per-soh-nazh", example_sentence: "Le personnage principal." },
    { word: "Protagoniste", meaning: "Protagonist", reading: "proh-ta-goh-neest", example_sentence: "Le protagoniste du récit." },
    { word: "Antagoniste", meaning: "Antagonist", reading: "ahn-ta-goh-neest", example_sentence: "L'antagoniste du héros." },
    { word: "Narrateur", meaning: "Narrator", reading: "na-ra-tur", example_sentence: "Le narrateur omniscient." },
    { word: "Point de vue", meaning: "Point of view", reading: "pwa duh voo", example_sentence: "Le point de vue interne." },
    { word: "Contexte", meaning: "Context", reading: "kohn-tekst", example_sentence: "Le contexte historique." },
    { word: "Époque", meaning: "Era / Period", reading: "ay-pohk", example_sentence: "L'époque romantique." },
    { word: "École littéraire", meaning: "Literary school", reading: "ay-kohl lee-tay-rer", example_sentence: "L'école littéraire réaliste." },
    { word: "Mouvement", meaning: "Movement", reading: "moov-mah", example_sentence: "Le mouvement surréaliste." },
    { word: "Siècle", meaning: "Century", reading: "syeh-kluh", example_sentence: "Le siècle des Lumières." }
];

const m22_traps = [
    { trap: "French literary style values flowery, ornate language above all.", correctVersion: "French literary style values clarity ('clarté') and precision. Overly ornate language is seen as pretentious, not elegant.", explanation: "The French ideal is 'le mot juste' (the right word). Simplicity and precision are prized over excessive decoration." },
    { trap: "'Éditeur' only means 'editor' in French.", correctVersion: "'Éditeur' means 'publisher' in French. An editor who edits text is 'rédacteur' or 'correcteur'.", explanation: "This false friend causes confusion in publishing contexts. The roles are distinct in French." },
    { trap: "In French writing, you can use 'tu' and 'vous' interchangeably in formal texts.", correctVersion: "Consistency is crucial. Mixing 'tu' and 'vous' in the same text is a serious error. Choose one and stick with it.", explanation: "French writing demands coherence in register. Switching between formal and informal is jarring and unprofessional." }
];

// MODULE 23: Abstract Concepts & Philosophy
const m23_items = [
    { word: "Concept", meaning: "Concept", reading: "kohn-sept", example_sentence: "Un concept abstrait." },
    { word: "Idée", meaning: "Idea", reading: "ee-day", example_sentence: "Une idée originale." },
    { word: "Notion", meaning: "Notion", reading: "noh-syoh", example_sentence: "La notion de liberté." },
    { word: "Théorie", meaning: "Theory", reading: "tay-oh-ree", example_sentence: "Une théorie scientifique." },
    { word: "Hypothèse", meaning: "Hypothesis", reading: "ee-poh-tez", example_sentence: "Formuler une hypothèse." },
    { word: "Principe", meaning: "Principle", reading: "pran-seep", example_sentence: "Un principe fondamental." },
    { word: "Valeur", meaning: "Value", reading: "va-lur", example_sentence: "Les valeurs morales." },
    { word: "Morale", meaning: "Morals / Ethics", reading: "moh-ral", example_sentence: "La morale de l'histoire." },
    { word: "Éthique", meaning: "Ethics", reading: "ay-teek", example_sentence: "L'éthique professionnelle." },
    { word: "Philosophie", meaning: "Philosophy", reading: "fee-loh-zoh-fee", example_sentence: "Étudier la philosophie." },
    { word: "Philosophe", meaning: "Philosopher", reading: "fee-loh-zohf", example_sentence: "Un grand philosophe." },
    { word: "Pensée", meaning: "Thought / Thinking", reading: "pahn-say", example_sentence: "La pensée critique." },
    { word: "Réflexion", meaning: "Reflection / Thought", reading: "ray-flek-syoh", example_sentence: "Une profonde réflexion." },
    { word: "Méditation", meaning: "Meditation", reading: "may-dee-ta-syoh", example_sentence: "La méditation philosophique." },
    { word: "Contemplation", meaning: "Contemplation", reading: "kohn-tahm-pla-syoh", example_sentence: "La contemplation de la nature." },
    { word: "Raison", meaning: "Reason", reading: "ray-zoh", example_sentence: "La raison et l'émotion." },
    { word: "Logique", meaning: "Logic", reading: "loh-zheek", example_sentence: "Un raisonnement logique." },
    { word: "Rationnel", meaning: "Rational", reading: "ra-syoh-nel", example_sentence: "Une approche rationnelle." },
    { word: "Irrationnel", meaning: "Irrational", reading: "ee-ra-syoh-nel", example_sentence: "Une peur irrationnelle." },
    { word: "Conscience", meaning: "Consciousness / Conscience", reading: "kohn-syahns", example_sentence: "La conscience morale." },
    { word: "Inconscient", meaning: "Unconscious", reading: "an-kohn-syah", example_sentence: "L'inconscient collectif." },
    { word: "Esprit", meaning: "Mind / Spirit", reading: "es-pree", example_sentence: "L'esprit humain." },
    { word: "Âme", meaning: "Soul", reading: "ahm", example_sentence: "L'âme et le corps." },
    { word: "Corps", meaning: "Body", reading: "kor", example_sentence: "Le corps et l'esprit." },
    { word: "Matière", meaning: "Matter / Material", reading: "ma-tyer", example_sentence: "La matière et l'esprit." },
    { word: "Essence", meaning: "Essence", reading: "ay-sahns", example_sentence: "L'essence de l'être." },
    { word: "Existence", meaning: "Existence", reading: "eg-zees-tahns", example_sentence: "L'existence précède l'essence." },
    { word: "Être", meaning: "Being / To be", reading: "etruh", example_sentence: "L'être et le néant." },
    { word: "Néant", meaning: "Nothingness", reading: "nay-ah", example_sentence: "Le néant existentiel." },
    { word: "Absolu", meaning: "Absolute", reading: "ab-soh-loo", example_sentence: "Une vérité absolue." },
    { word: "Relatif", meaning: "Relative", reading: "ruh-la-teef", example_sentence: "Tout est relatif." },
    { word: "Universel", meaning: "Universal", reading: "oo-nee-ver-sel", example_sentence: "Un principe universel." },
    { word: "Particulier", meaning: "Particular / Specific", reading: "par-tee-koo-lyay", example_sentence: "Un cas particulier." },
    { word: "Général", meaning: "General", reading: "zhay-nay-ral", example_sentence: "Une règle générale." },
    { word: "Abstrait", meaning: "Abstract", reading: "ab-stray", example_sentence: "Un concept abstrait." },
    { word: "Concret", meaning: "Concrete", reading: "kohn-kray", example_sentence: "Un exemple concret." },
    { word: "Objectif", meaning: "Objective", reading: "ob-zhek-teef", example_sentence: "Un point de vue objectif." },
    { word: "Subjectif", meaning: "Subjective", reading: "soob-zhek-teef", example_sentence: "Une opinion subjective." },
    { word: "Réel", meaning: "Real", reading: "ray-el", example_sentence: "Le monde réel." },
    { word: "Virtuel", meaning: "Virtual", reading: "veer-too-el", example_sentence: "La réalité virtuelle." },
    { word: "Apparence", meaning: "Appearance", reading: "a-pa-rahns", example_sentence: "L'apparence et la réalité." },
    { word: "Illusion", meaning: "Illusion", reading: "ee-loo-zyoh", example_sentence: "Une illusion d'optique." },
    { word: "Vérité", meaning: "Truth", reading: "vay-ree-tay", example_sentence: "La vérité absolue." },
    { word: "Mensonge", meaning: "Lie", reading: "mahn-sohnzh", example_sentence: "Dire un mensonge." },
    { word: "Certitude", meaning: "Certainty", reading: "ser-tee-tood", example_sentence: "Une certitude absolue." },
    { word: "Doute", meaning: "Doubt", reading: "doot", example_sentence: "Le doute méthodique." },
    { word: "Croyance", meaning: "Belief", reading: "krwa-yahns", example_sentence: "Une croyance religieuse." },
    { word: "Foi", meaning: "Faith", reading: "fwa", example_sentence: "La foi en Dieu." },
    { word: "Religion", meaning: "Religion", reading: "ruh-lee-zhyoh", example_sentence: "La liberté de religion." },
    { word: "Spiritualité", meaning: "Spirituality", reading: "spee-ree-too-a-lee-tay", example_sentence: "La spiritualité orientale." },
    { word: "Sacré", meaning: "Sacred", reading: "sa-kray", example_sentence: "Un lieu sacré." },
    { word: "Profane", meaning: "Profane / Secular", reading: "proh-fan", example_sentence: "L'art profane." },
    { word: "Divin", meaning: "Divine", reading: "dee-va", example_sentence: "La providence divine." },
    { word: "Humain", meaning: "Human", reading: "oo-ma", example_sentence: "La nature humaine." },
    { word: "Humanité", meaning: "Humanity", reading: "oo-ma-nee-tay", example_sentence: "L'humanité tout entière." },
    { word: "Individu", meaning: "Individual", reading: "an-dee-vee-doo", example_sentence: "L'individu et la société." },
    { word: "Collectif", meaning: "Collective", reading: "koh-lek-teef", example_sentence: "L'inconscient collectif." },
    { word: "Société", meaning: "Society", reading: "soh-syay-tay", example_sentence: "La société moderne." },
    { word: "Communauté", meaning: "Community", reading: "koh-moo-noh-tay", example_sentence: "Une communauté solidaire." },
    { word: "Liberté", meaning: "Freedom / Liberty", reading: "lee-ber-tay", example_sentence: "La liberté d'expression." },
    { word: "Contrainte", meaning: "Constraint", reading: "kohn-trant", example_sentence: "Les contraintes sociales." },
    { word: "Déterminisme", meaning: "Determinism", reading: "day-ter-mee-neez-muh", example_sentence: "Le déterminisme social." },
    { word: "Libre arbitre", meaning: "Free will", reading: "lee-bruh ar-bee-truh", example_sentence: "Croire au libre arbitre." },
    { word: "Destin", meaning: "Destiny / Fate", reading: "des-ta", example_sentence: "Accepter son destin." },
    { word: "Hasard", meaning: "Chance / Randomness", reading: "a-zar", example_sentence: "Le hasard et la nécessité." },
    { word: "Nécessité", meaning: "Necessity", reading: "nay-say-see-tay", example_sentence: "Une nécessité absolue." },
    { word: "Possibilité", meaning: "Possibility", reading: "poh-see-bee-lee-tay", example_sentence: "Explorer toutes les possibilités." },
    { word: "Contingence", meaning: "Contingency", reading: "kohn-tan-zhahns", example_sentence: "La contingence de l'existence." },
    { word: "Causalité", meaning: "Causality", reading: "koh-za-lee-tay", example_sentence: "Le principe de causalité." },
    { word: "Conséquence", meaning: "Consequence", reading: "kohn-say-kahns", example_sentence: "Les conséquences de nos actes." },
    { word: "Finalité", meaning: "Purpose / Finality", reading: "fee-na-lee-tay", example_sentence: "La finalité de l'existence." },
    { word: "Sens", meaning: "Meaning / Sense", reading: "sahns", example_sentence: "Le sens de la vie." },
    { word: "Signification", meaning: "Meaning / Significance", reading: "see-nyee-fee-ka-syoh", example_sentence: "La signification profonde." },
    { word: "Absurde", meaning: "Absurd", reading: "ab-soord", example_sentence: "L'absurde de l'existence." },
    { word: "Paradoxe", meaning: "Paradox", reading: "pa-ra-doks", example_sentence: "Un paradoxe logique." },
    { word: "Contradiction", meaning: "Contradiction", reading: "kohn-tra-deek-syoh", example_sentence: "Une contradiction interne." },
    { word: "Cohérence", meaning: "Coherence", reading: "koh-ay-rahns", example_sentence: "La cohérence du système." },
    { word: "Harmonie", meaning: "Harmony", reading: "ar-moh-nee", example_sentence: "L'harmonie universelle." },
    { word: "Équilibre", meaning: "Balance", reading: "ay-kee-lee-bruh", example_sentence: "L'équilibre des forces." },
    { word: "Chaos", meaning: "Chaos", reading: "ka-oh", example_sentence: "Le chaos originel." },
    { word: "Ordre", meaning: "Order", reading: "or-druh", example_sentence: "L'ordre naturel." },
    { word: "Désordre", meaning: "Disorder", reading: "day-zor-druh", example_sentence: "Le désordre apparent." },
    { word: "Complexité", meaning: "Complexity", reading: "kohm-plek-see-tay", example_sentence: "La complexité du réel." },
    { word: "Simplicité", meaning: "Simplicity", reading: "sam-plee-see-tay", example_sentence: "La simplicité élégante." },
    { word: "Unité", meaning: "Unity", reading: "oo-nee-tay", example_sentence: "L'unité dans la diversité." },
    { word: "Diversité", meaning: "Diversity", reading: "dee-ver-see-tay", example_sentence: "La diversité culturelle." },
    { word: "Identité", meaning: "Identity", reading: "ee-dahn-tee-tay", example_sentence: "L'identité personnelle." },
    { word: "Altérité", meaning: "Otherness", reading: "al-tay-ree-tay", example_sentence: "Le respect de l'altérité." },
    { word: "Différence", meaning: "Difference", reading: "dee-fay-rahns", example_sentence: "La différence culturelle." },
    { word: "Ressemblance", meaning: "Resemblance", reading: "ruh-sahm-blahns", example_sentence: "Une ressemblance frappante." },
    { word: "Analogie", meaning: "Analogy", reading: "a-na-loh-zhee", example_sentence: "Raisonner par analogie." },
    { word: "Métaphysique", meaning: "Metaphysics", reading: "may-ta-fee-zeek", example_sentence: "La métaphysique occidentale." },
    { word: "Ontologie", meaning: "Ontology", reading: "ohn-toh-loh-zhee", example_sentence: "L'ontologie de l'être." },
    { word: "Épistémologie", meaning: "Epistemology", reading: "ay-pees-tay-moh-loh-zhee", example_sentence: "L'épistémologie des sciences." },
    { word: "Phénoménologie", meaning: "Phenomenology", reading: "fay-noh-may-noh-loh-zhee", example_sentence: "La phénoménologie husserlienne." },
    { word: "Existentialisme", meaning: "Existentialism", reading: "eg-zees-tahn-sya-leez-muh", example_sentence: "L'existentialisme sartrien." },
    { word: "Rationalisme", meaning: "Rationalism", reading: "ra-syoh-na-leez-muh", example_sentence: "Le rationalisme cartésien." },
    { word: "Empirisme", meaning: "Empiricism", reading: "ahm-pee-reez-muh", example_sentence: "L'empirisme anglais." },
    { word: "Idéalisme", meaning: "Idealism", reading: "ee-day-a-leez-muh", example_sentence: "L'idéalisme platonicien." },
    { word: "Matérialisme", meaning: "Materialism", reading: "ma-tay-rya-leez-muh", example_sentence: "Le matérialisme dialectique." }
];

const m23_traps = [
    { trap: "French philosophy is all about being pessimistic and depressing.", correctVersion: "French philosophy explores profound questions about existence, but it's not inherently pessimistic. It values rigorous thinking and clarity.", explanation: "Existentialism is often misunderstood. Thinkers like Sartre emphasized freedom and responsibility, not just despair." },
    { trap: "'Conscience' in French only means 'conscience' (moral sense).", correctVersion: "'Conscience' means both 'consciousness' and 'conscience' in French. Context determines the meaning.", explanation: "This dual meaning can confuse English speakers. 'Perdre conscience' means 'to lose consciousness', not 'to lose one's conscience'." },
    { trap: "In French academic writing, you should use 'je' (I) to express your opinions.", correctVersion: "French academic writing traditionally avoids 'je'. Use 'on', 'nous', or impersonal constructions instead.", explanation: "French academic style values objectivity. Using 'je' is seen as too subjective, though this is slowly changing." }
];

// MODULE 24: Science & Technology
const m24_items = [
    { word: "Science", meaning: "Science", reading: "syahns", example_sentence: "Les progrès de la science." },
    { word: "Scientifique", meaning: "Scientific / Scientist", reading: "syahn-tee-feek", example_sentence: "Une méthode scientifique." },
    { word: "Chercheur", meaning: "Researcher", reading: "sher-shur", example_sentence: "Un chercheur en biologie." },
    { word: "Recherche", meaning: "Research", reading: "ruh-shersh", example_sentence: "La recherche fondamentale." },
    { word: "Laboratoire", meaning: "Laboratory", reading: "la-boh-ra-twahr", example_sentence: "Travailler en laboratoire." },
    { word: "Expérience", meaning: "Experiment / Experience", reading: "eks-pay-ryahns", example_sentence: "Mener une expérience." },
    { word: "Expérimentation", meaning: "Experimentation", reading: "eks-pay-ree-mahn-ta-syoh", example_sentence: "L'expérimentation scientifique." },
    { word: "Observation", meaning: "Observation", reading: "ob-ser-va-syoh", example_sentence: "L'observation des phénomènes." },
    { word: "Analyse", meaning: "Analysis", reading: "a-na-leez", example_sentence: "Une analyse approfondie." },
    { word: "Synthèse", meaning: "Synthesis", reading: "san-tez", example_sentence: "La synthèse des résultats." },
    { word: "Méthode", meaning: "Method", reading: "may-tohd", example_sentence: "La méthode expérimentale." },
    { word: "Protocole", meaning: "Protocol", reading: "proh-toh-kohl", example_sentence: "Suivre le protocole." },
    { word: "Procédure", meaning: "Procedure", reading: "proh-say-door", example_sentence: "Une procédure stricte." },
    { word: "Mesure", meaning: "Measurement / Measure", reading: "muh-zoor", example_sentence: "Prendre des mesures." },
    { word: "Donnée", meaning: "Data / Given", reading: "doh-nay", example_sentence: "Analyser les données." },
    { word: "Résultat", meaning: "Result", reading: "ray-zool-ta", example_sentence: "Les résultats de l'étude." },
    { word: "Conclusion", meaning: "Conclusion", reading: "kohn-kloo-zyoh", example_sentence: "Tirer une conclusion." },
    { word: "Découverte", meaning: "Discovery", reading: "day-koo-vert", example_sentence: "Une découverte majeure." },
    { word: "Invention", meaning: "Invention", reading: "an-vahn-syoh", example_sentence: "Une invention révolutionnaire." },
    { word: "Innovation", meaning: "Innovation", reading: "ee-noh-va-syoh", example_sentence: "L'innovation technologique." },
    { word: "Technologie", meaning: "Technology", reading: "tek-noh-loh-zhee", example_sentence: "Les nouvelles technologies." },
    { word: "Technique", meaning: "Technique / Technical", reading: "tek-neek", example_sentence: "Une technique avancée." },
    { word: "Ingénieur", meaning: "Engineer", reading: "an-zhay-nyur", example_sentence: "Un ingénieur informaticien." },
    { word: "Ingénierie", meaning: "Engineering", reading: "an-zhay-nyuh-ree", example_sentence: "L'ingénierie génétique." },
    { word: "Développement", meaning: "Development", reading: "day-vuh-lohp-mah", example_sentence: "Le développement durable." },
    { word: "Progrès", meaning: "Progress", reading: "proh-gray", example_sentence: "Le progrès scientifique." },
    { word: "Avancée", meaning: "Advance / Breakthrough", reading: "a-vahn-say", example_sentence: "Une avancée majeure." },
    { word: "Évolution", meaning: "Evolution", reading: "ay-voh-loo-syoh", example_sentence: "L'évolution des espèces." },
    { word: "Révolution", meaning: "Revolution", reading: "ray-voh-loo-syoh", example_sentence: "La révolution industrielle." },
    { word: "Transformation", meaning: "Transformation", reading: "trahns-for-ma-syoh", example_sentence: "Une transformation radicale." },
    { word: "Physique", meaning: "Physics / Physical", reading: "fee-zeek", example_sentence: "La physique quantique." },
    { word: "Chimie", meaning: "Chemistry", reading: "shee-mee", example_sentence: "La chimie organique." },
    { word: "Biologie", meaning: "Biology", reading: "byoh-loh-zhee", example_sentence: "La biologie moléculaire." },
    { word: "Mathématiques", meaning: "Mathematics", reading: "ma-tay-ma-teek", example_sentence: "Les mathématiques appliquées." },
    { word: "Informatique", meaning: "Computer science", reading: "an-for-ma-teek", example_sentence: "L'informatique théorique." },
    { word: "Astronomie", meaning: "Astronomy", reading: "as-troh-noh-mee", example_sentence: "L'astronomie moderne." },
    { word: "Géologie", meaning: "Geology", reading: "zhay-oh-loh-zhee", example_sentence: "La géologie structurale." },
    { word: "Écologie", meaning: "Ecology", reading: "ay-koh-loh-zhee", example_sentence: "L'écologie scientifique." },
    { word: "Génétique", meaning: "Genetics", reading: "zhay-nay-teek", example_sentence: "La génétique humaine." },
    { word: "Médecine", meaning: "Medicine", reading: "mayd-seen", example_sentence: "La médecine moderne." },
    { word: "Atome", meaning: "Atom", reading: "a-tohm", example_sentence: "La structure de l'atome." },
    { word: "Molécule", meaning: "Molecule", reading: "moh-lay-kool", example_sentence: "Une molécule complexe." },
    { word: "Cellule", meaning: "Cell", reading: "say-lool", example_sentence: "La cellule vivante." },
    { word: "Organisme", meaning: "Organism", reading: "or-ga-neez-muh", example_sentence: "Un organisme unicellulaire." },
    { word: "Énergie", meaning: "Energy", reading: "ay-ner-zhee", example_sentence: "L'énergie renouvelable." },
    { word: "Matière", meaning: "Matter", reading: "ma-tyer", example_sentence: "Les états de la matière." },
    { word: "Force", meaning: "Force", reading: "fors", example_sentence: "La force gravitationnelle." },
    { word: "Vitesse", meaning: "Speed", reading: "vee-tes", example_sentence: "La vitesse de la lumière." },
    { word: "Masse", meaning: "Mass", reading: "mas", example_sentence: "La masse d'un corps." },
    { word: "Volume", meaning: "Volume", reading: "voh-loom", example_sentence: "Calculer le volume." },
    { word: "Température", meaning: "Temperature", reading: "tahm-pay-ra-toor", example_sentence: "Mesurer la température." },
    { word: "Pression", meaning: "Pressure", reading: "pray-syoh", example_sentence: "La pression atmosphérique." },
    { word: "Densité", meaning: "Density", reading: "dahn-see-tay", example_sentence: "La densité d'un liquide." },
    { word: "Gravité", meaning: "Gravity", reading: "gra-vee-tay", example_sentence: "La loi de la gravité." },
    { word: "Électricité", meaning: "Electricity", reading: "ay-lek-tree-see-tay", example_sentence: "L'électricité statique." },
    { word: "Magnétisme", meaning: "Magnetism", reading: "ma-nyay-teez-muh", example_sentence: "Le magnétisme terrestre." },
    { word: "Radiation", meaning: "Radiation", reading: "ra-dya-syoh", example_sentence: "La radiation solaire." },
    { word: "Onde", meaning: "Wave", reading: "ohnd", example_sentence: "Les ondes électromagnétiques." },
    { word: "Fréquence", meaning: "Frequency", reading: "fray-kahns", example_sentence: "La fréquence d'une onde." },
    { word: "Amplitude", meaning: "Amplitude", reading: "ahm-plee-tood", example_sentence: "L'amplitude du signal." },
    { word: "Réaction", meaning: "Reaction", reading: "ray-ak-syoh", example_sentence: "Une réaction chimique." },
    { word: "Équation", meaning: "Equation", reading: "ay-kwa-syoh", example_sentence: "Résoudre une équation." },
    { word: "Formule", meaning: "Formula", reading: "for-mool", example_sentence: "La formule chimique." },
    { word: "Calcul", meaning: "Calculation", reading: "kal-kool", example_sentence: "Faire un calcul." },
    { word: "Variable", meaning: "Variable", reading: "va-rya-bluh", example_sentence: "Une variable indépendante." },
    { word: "Constante", meaning: "Constant", reading: "kohn-stahnt", example_sentence: "Une constante universelle." },
    { word: "Fonction", meaning: "Function", reading: "fohnk-syoh", example_sentence: "Une fonction mathématique." },
    { word: "Graphique", meaning: "Graph / Graphic", reading: "gra-feek", example_sentence: "Tracer un graphique." },
    { word: "Diagramme", meaning: "Diagram", reading: "dya-gram", example_sentence: "Un diagramme explicatif." },
    { word: "Schéma", meaning: "Diagram / Scheme", reading: "shay-ma", example_sentence: "Un schéma technique." },
    { word: "Modèle", meaning: "Model", reading: "moh-del", example_sentence: "Un modèle théorique." },
    { word: "Simulation", meaning: "Simulation", reading: "see-moo-la-syoh", example_sentence: "Une simulation informatique." },
    { word: "Algorithme", meaning: "Algorithm", reading: "al-goh-reetm", example_sentence: "Un algorithme efficace." },
    { word: "Programme", meaning: "Program", reading: "proh-gram", example_sentence: "Un programme informatique." },
    { word: "Logiciel", meaning: "Software", reading: "loh-zhee-syel", example_sentence: "Un logiciel performant." },
    { word: "Matériel", meaning: "Hardware / Material", reading: "ma-tay-ryel", example_sentence: "Le matériel informatique." },
    { word: "Système", meaning: "System", reading: "sees-tem", example_sentence: "Un système complexe." },
    { word: "Réseau", meaning: "Network", reading: "ray-zoh", example_sentence: "Un réseau informatique." },
    { word: "Base de données", meaning: "Database", reading: "baz duh doh-nay", example_sentence: "Gérer une base de données." },
    { word: "Intelligence artificielle", meaning: "Artificial intelligence", reading: "an-tay-lee-zhahns ar-tee-fee-syel", example_sentence: "L'intelligence artificielle progresse." },
    { word: "Robot", meaning: "Robot", reading: "roh-boh", example_sentence: "Un robot industriel." },
    { word: "Automatisation", meaning: "Automation", reading: "oh-toh-ma-tee-za-syoh", example_sentence: "L'automatisation des tâches." },
    { word: "Numérique", meaning: "Digital", reading: "noo-may-reek", example_sentence: "La révolution numérique." },
    { word: "Virtuel", meaning: "Virtual", reading: "veer-too-el", example_sentence: "La réalité virtuelle." },
    { word: "Cybernétique", meaning: "Cybernetics", reading: "see-ber-nay-teek", example_sentence: "La cybernétique moderne." },
    { word: "Biotechnologie", meaning: "Biotechnology", reading: "byoh-tek-noh-loh-zhee", example_sentence: "Les biotechnologies médicales." },
    { word: "Nanotechnologie", meaning: "Nanotechnology", reading: "na-noh-tek-noh-loh-zhee", example_sentence: "La nanotechnologie avancée." },
    { word: "Télécommunication", meaning: "Telecommunication", reading: "tay-lay-koh-moo-nee-ka-syoh", example_sentence: "Les télécommunications modernes." },
    { word: "Satellite", meaning: "Satellite", reading: "sa-tay-leet", example_sentence: "Un satellite de communication." },
    { word: "Laser", meaning: "Laser", reading: "la-zer", example_sentence: "Un rayon laser." },
    { word: "Microscope", meaning: "Microscope", reading: "mee-kroh-skohp", example_sentence: "Observer au microscope." },
    { word: "Télescope", meaning: "Telescope", reading: "tay-lay-skohp", example_sentence: "Un télescope spatial." },
    { word: "Instrument", meaning: "Instrument", reading: "an-stroo-mah", example_sentence: "Un instrument de mesure." },
    { word: "Appareil", meaning: "Device / Apparatus", reading: "a-pa-ray", example_sentence: "Un appareil sophistiqué." },
    { word: "Outil", meaning: "Tool", reading: "oo-tee", example_sentence: "Un outil indispensable." },
    { word: "Machine", meaning: "Machine", reading: "ma-sheen", example_sentence: "Une machine complexe." },
    { word: "Mécanisme", meaning: "Mechanism", reading: "may-ka-neez-muh", example_sentence: "Le mécanisme interne." },
    { word: "Processus", meaning: "Process", reading: "proh-say-soos", example_sentence: "Un processus automatisé." },
    { word: "Dispositif", meaning: "Device", reading: "dees-poh-zee-teef", example_sentence: "Un dispositif électronique." },
    { word: "Composant", meaning: "Component", reading: "kohm-poh-zah", example_sentence: "Les composants du système." }
];

const m24_traps = [
    { trap: "'Expérience' always means 'experiment' in French.", correctVersion: "'Expérience' means both 'experiment' and 'experience'. Context determines which. 'Expérimentation' is specifically for experiments.", explanation: "This dual meaning confuses English speakers. 'J'ai de l'expérience' means 'I have experience', not 'I have an experiment'." },
    { trap: "French scientists use English terms for all modern technology.", correctVersion: "France actively creates French terms for new technology. 'Ordinateur' (computer), 'logiciel' (software), etc. Using English is often seen as lazy.", explanation: "The Académie française works to preserve French in technical fields. Using French terms shows respect for the language." },
    { trap: "'Informatique' means 'informatics' (information science) in French.", correctVersion: "'Informatique' is the standard French word for 'computer science'. It's not a specialized subfield.", explanation: "This false friend causes confusion. 'Informatique' covers all aspects of computing, not just information theory." }
];

// Generate and save all three modules
const modules = [
    createModule('fr_b1_m22', 'B1 French - Module 22: Literature & Writing', 22, m22_items, m22_traps),
    createModule('fr_b1_m23', 'B1 French - Module 23: Philosophy & Abstract Thought', 23, m23_items, m23_traps),
    createModule('fr_b1_m24', 'B1 French - Module 24: Science & Technology', 24, m24_items, m24_traps)
];

modules.forEach(module => {
    const outputPath = path.join(__dirname, `../firestore_data/${module.id}.json`);
    fs.writeFileSync(outputPath, JSON.stringify(module, null, 2));
    console.log(`✅ ${module.id} generated: ${module.vocabularyItems.length} words, ${module.liarGameData.culturalTraps.length} traps`);
});

console.log('\n🎯 All three modules generated successfully!');
