const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}
const db = admin.firestore();

async function uploadPart3() {
    const modules = [
        {
            moduleId: "spanish_a2_m7",
            theme: "Direct & Indirect Object Pronouns",
            order: 7,
            vocabularyItems: [
                { targetText: "me", english: "me", phoneticTranscription: "meh" },
                { targetText: "te", english: "you (informal)", phoneticTranscription: "teh" },
                { targetText: "lo", english: "him / it (masculine)", phoneticTranscription: "loh" },
                { targetText: "la", english: "her / it (feminine)", phoneticTranscription: "lah" },
                { targetText: "nos", english: "us", phoneticTranscription: "nohs" },
                { targetText: "os", english: "you all (informal, Spain)", phoneticTranscription: "ohs" },
                { targetText: "los", english: "them (masculine)", phoneticTranscription: "lohs" },
                { targetText: "las", english: "them (feminine)", phoneticTranscription: "lahs" },
                { targetText: "me (indirect)", english: "to me", phoneticTranscription: "meh" },
                { targetText: "te (indirect)", english: "to you", phoneticTranscription: "teh" },
                { targetText: "le", english: "to him / to her / to you formal", phoneticTranscription: "leh" },
                { targetText: "nos (indirect)", english: "to us", phoneticTranscription: "nohs" },
                { targetText: "les", english: "to them / to you all", phoneticTranscription: "lehs" },
                { targetText: "se", english: "himself / herself / themselves / each other", phoneticTranscription: "seh" },
                { targetText: "se (substitution)", english: "to him / to her (before lo/la)", phoneticTranscription: "seh" },
                { targetText: "lo veo", english: "I see him", phoneticTranscription: "loh BEH-oh" },
                { targetText: "la compro", english: "I buy it", phoneticTranscription: "lah KOHM-proh" },
                { targetText: "nos invitan", english: "they invite us", phoneticTranscription: "nohs een-BEE-tahn" },
                { targetText: "te llamo", english: "I call you", phoneticTranscription: "teh YAH-moh" },
                { targetText: "los tengo", english: "I have them", phoneticTranscription: "lohs TEHN-goh" },
                { targetText: "las quiero", english: "I want them", phoneticTranscription: "lahs KYEH-roh" },
                { targetText: "me gusta", english: "it pleases me (I like)", phoneticTranscription: "meh GOOS-tah" },
                { targetText: "te gusta", english: "it pleases you (you like)", phoneticTranscription: "teh GOOS-tah" },
                { targetText: "le encanta", english: "it enchants him/her (he/she loves)", phoneticTranscription: "leh ehn-KAHN-tah" },
                { targetText: "nos parece", english: "it seems to us", phoneticTranscription: "nohs pah-REH-seh" },
                { targetText: "les importa", english: "it matters to them", phoneticTranscription: "lehs eem-POHR-tah" },
                { targetText: "me duele", english: "it hurts me", phoneticTranscription: "meh DWEH-leh" },
                { targetText: "te falta", english: "you are missing", phoneticTranscription: "teh FAHL-tah" },
                { targetText: "nos hace falta", english: "we need it", phoneticTranscription: "nohs AH-seh FAHL-tah" },
                { targetText: "me queda", english: "it fits me / I have left", phoneticTranscription: "meh KEH-dah" },
                { targetText: "le sobra", english: "he/she has left over", phoneticTranscription: "leh SOH-brah" },
                { targetText: "me lo das", english: "you give it to me", phoneticTranscription: "meh loh DAHS" },
                { targetText: "te la vendo", english: "I sell it to you", phoneticTranscription: "teh lah BEHN-doh" },
                { targetText: "se lo digo", english: "I say it to him/her", phoneticTranscription: "seh loh DEE-goh" },
                { targetText: "nos los manda", english: "he/she sends them to us", phoneticTranscription: "nohs lohs MAHN-dah" },
                { targetText: "se las traigo", english: "I bring them to him/her", phoneticTranscription: "seh lahs TRAH-ee-goh" },
                { targetText: "para mí", english: "for me", phoneticTranscription: "PAH-rah MEE" },
                { targetText: "para ti", english: "for you", phoneticTranscription: "PAH-rah TEE" },
                { targetText: "para él", english: "for him", phoneticTranscription: "PAH-rah EHL" },
                { targetText: "para ella", english: "for her", phoneticTranscription: "PAH-rah EH-yah" },
                { targetText: "para usted", english: "for you (formal)", phoneticTranscription: "PAH-rah oos-TEHD" },
                { targetText: "para nosotros", english: "for us", phoneticTranscription: "PAH-rah noh-SOH-trohs" },
                { targetText: "para ustedes", english: "for you all", phoneticTranscription: "PAH-rah oos-TEH-dehs" },
                { targetText: "para ellos", english: "for them", phoneticTranscription: "PAH-rah EH-yohs" },
                { targetText: "conmigo", english: "with me", phoneticTranscription: "kohn-MEE-goh" },
                { targetText: "contigo", english: "with you", phoneticTranscription: "kohn-TEE-goh" },
                { targetText: "con él", english: "with him", phoneticTranscription: "kohn EHL" },
                { targetText: "consigo", english: "with himself / herself", phoneticTranscription: "kohn-SEE-goh" },
                { targetText: "sin mí", english: "without me", phoneticTranscription: "seen MEE" },
                { targetText: "sin ti", english: "without you", phoneticTranscription: "seen TEE" },
                { targetText: "según yo", english: "according to me", phoneticTranscription: "seh-GOON YOH" },
                { targetText: "entre tú y yo", english: "between you and me", phoneticTranscription: "EHN-treh TOO ee YOH" },
                { targetText: "a mí me gusta", english: "to me it pleases (emphasis)", phoneticTranscription: "ah MEE meh GOOS-tah" },
                { targetText: "a ti te gusta", english: "to you it pleases", phoneticTranscription: "ah TEE teh GOOS-tah" },
                { targetText: "a él le gusta", english: "to him it pleases", phoneticTranscription: "ah EHL leh GOOS-tah" },
                { targetText: "a ella le gusta", english: "to her it pleases", phoneticTranscription: "ah EH-yah leh GOOS-tah" },
                { targetText: "a usted le gusta", english: "to you formal it pleases", phoneticTranscription: "ah oos-TEHD leh GOOS-tah" },
                { targetText: "a nosotros nos gusta", english: "to us it pleases", phoneticTranscription: "ah noh-SOH-trohs nohs GOOS-tah" },
                { targetText: "a ustedes les gusta", english: "to you all it pleases", phoneticTranscription: "ah oos-TEH-dehs lehs GOOS-tah" },
                { targetText: "a ellos les gusta", english: "to them it pleases", phoneticTranscription: "ah EH-yohs lehs GOOS-tah" },
                { targetText: "dámelo", english: "give it to me", phoneticTranscription: "DAH-meh-loh" },
                { targetText: "tráelo", english: "bring it", phoneticTranscription: "TRAH-eh-loh" },
                { targetText: "hazlo", english: "do it", phoneticTranscription: "AHS-loh" },
                { targetText: "díselo", english: "tell it to him/her", phoneticTranscription: "DEE-seh-loh" },
                { targetText: "cómpralo", english: "buy it", phoneticTranscription: "KOHM-prah-loh" },
                { targetText: "vende", english: "sell it", phoneticTranscription: "BEHN-deh" },
                { targetText: "espérame", english: "wait for me", phoneticTranscription: "ehs-PEH-rah-meh" },
                { targetText: "ayúdame", english: "help me", phoneticTranscription: "ah-YOO-dah-meh" },
                { targetText: "déjame", english: "let me / leave me", phoneticTranscription: "DEH-hah-meh" },
                { targetText: "mírame", english: "look at me", phoneticTranscription: "MEE-rah-meh" },
                { targetText: "óyeme", english: "listen to me", phoneticTranscription: "OH-yeh-meh" },
                { targetText: "llámame", english: "call me", phoneticTranscription: "YAH-mah-meh" },
                { targetText: "escríbeme", english: "write to me", phoneticTranscription: "ehs-KREE-beh-meh" },
                { targetText: "mándame", english: "send me", phoneticTranscription: "MAHN-dah-meh" },
                { targetText: "pregúntale", english: "ask him/her", phoneticTranscription: "preh-GOON-tah-leh" },
                { targetText: "respóndeme", english: "answer me", phoneticTranscription: "rehs-POHN-deh-meh" },
                { targetText: "créeme", english: "believe me", phoneticTranscription: "KREH-eh-meh" },
                { targetText: "entiéndeme", english: "understand me", phoneticTranscription: "ehn-TYEHN-deh-meh" },
                { targetText: "perdóname", english: "forgive me", phoneticTranscription: "pehr-DOH-nah-meh" },
                { targetText: "olvídalo", english: "forget it", phoneticTranscription: "ohl-BEE-dah-loh" },
                { targetText: "recuérdalo", english: "remember it", phoneticTranscription: "reh-KWEHR-dah-loh" },
                { targetText: "piénsalo", english: "think about it", phoneticTranscription: "PYEHN-sah-loh" },
                { targetText: "pruébalo", english: "try it / taste it", phoneticTranscription: "PRWEH-bah-loh" },
                { targetText: "úsalo", english: "use it", phoneticTranscription: "OO-sah-loh" },
                { targetText: "téngalo", english: "have it", phoneticTranscription: "TEHN-gah-loh" },
                { targetText: "póngalo", english: "put it", phoneticTranscription: "POHN-gah-loh" },
                { targetText: "hágalo", english: "do it formal", phoneticTranscription: "AH-gah-loh" },
                { targetText: "tráiganos", english: "bring us", phoneticTranscription: "TRAH-ee-gah-nohs" },
                { targetText: "muéstramelo", english: "show it to me", phoneticTranscription: "MWEHS-trah-meh-loh" },
                { targetText: "explícamelo", english: "explain it to me", phoneticTranscription: "ehks-PLEE-kah-meh-loh" },
                { targetText: "estoy viéndolo", english: "I am seeing it", phoneticTranscription: "ehs-TOY BYEHN-doh-loh" },
                { targetText: "quiero comprarlo", english: "I want to buy it", phoneticTranscription: "KYEH-roh kohm-PRAHR-loh" },
                { targetText: "puedo hacerlo", english: "I can do it", phoneticTranscription: "PWEH-doh ah-SEHR-loh" },
                { targetText: "vas a verlo", english: "you are going to see it", phoneticTranscription: "BAHS ah BEHR-loh" },
                { targetText: "tengo que saberlo", english: "I must know it", phoneticTranscription: "TEHN-goh KEH sah-BEHR-loh" },
                { targetText: "déjalo allí", english: "leave it there", phoneticTranscription: "DEH-hah-loh ah-YEE" },
                { targetText: "guárdalo bien", english: "keep it well", phoneticTranscription: "GWAHR-dah-loh BYEHN" },
                { targetText: "sácalo ahora", english: "take it out now", phoneticTranscription: "SAH-kah-loh ah-OH-rah" },
                { targetText: "ponlo aquí", english: "put it here", phoneticTranscription: "POHN-loh ah-KEE" },
                { targetText: "mantenlo limpio", english: "keep it clean", phoneticTranscription: "mahn-TEHN-loh LEEM-pyoh" }
            ]
        },
        {
            moduleId: "spanish_a2_m8",
            theme: "Imperativo (Commands)",
            order: 8,
            vocabularyItems: [
                { targetText: "habla", english: "speak (tú)", phoneticTranscription: "AH-blah" },
                { targetText: "no hables", english: "don't speak (tú)", phoneticTranscription: "NO AH-blehs" },
                { targetText: "hable", english: "speak (usted)", phoneticTranscription: "AH-bleh" },
                { targetText: "no hable", english: "don't speak (usted)", phoneticTranscription: "NO AH-bleh" },
                { targetText: "hablad", english: "speak (vosotros)", phoneticTranscription: "ah-BLAHD" },
                { targetText: "no habléis", english: "don't speak (vosotros)", phoneticTranscription: "NO ah-BLEH-ees" },
                { targetText: "hablen", english: "speak (ustedes)", phoneticTranscription: "AH-blehn" },
                { targetText: "no hablen", english: "don't speak (ustedes)", phoneticTranscription: "NO AH-blehn" },
                { targetText: "come", english: "eat (tú)", phoneticTranscription: "KOH-meh" },
                { targetText: "no comas", english: "don't eat (tú)", phoneticTranscription: "NO KOH-mahs" },
                { targetText: "coma", english: "eat (usted)", phoneticTranscription: "KOH-mah" },
                { targetText: "escribe", english: "write (tú)", phoneticTranscription: "ehs-KREE-beh" },
                { targetText: "no escribas", english: "don't write (tú)", phoneticTranscription: "NO ehs-KREE-bahs" },
                { targetText: "escriba", english: "write (usted)", phoneticTranscription: "ehs-KREE-bah" },
                { targetText: "ten", english: "have / hold (tú)", phoneticTranscription: "TEHN" },
                { targetText: "no tengas", english: "don't have (tú)", phoneticTranscription: "NO TEHN-gahs" },
                { targetText: "tenga", english: "have (usted)", phoneticTranscription: "TEHN-gah" },
                { targetText: "ven", english: "come (tú)", phoneticTranscription: "BEHN" },
                { targetText: "no vengas", english: "don't come (tú)", phoneticTranscription: "NO BEHN-gahs" },
                { targetText: "venga", english: "come (usted)", phoneticTranscription: "BEHN-gah" },
                { targetText: "haz", english: "do / make (tú)", phoneticTranscription: "AHS" },
                { targetText: "no hagas", english: "don't do (tú)", phoneticTranscription: "NO AH-gahs" },
                { targetText: "haga", english: "do (usted)", phoneticTranscription: "AH-gah" },
                { targetText: "di", english: "say / tell (tú)", phoneticTranscription: "DEE" },
                { targetText: "no digas", english: "don't say (tú)", phoneticTranscription: "NO DEE-gahs" },
                { targetText: "diga", english: "say (usted)", phoneticTranscription: "DEE-gah" },
                { targetText: "pon", english: "put (tú)", phoneticTranscription: "POHN" },
                { targetText: "no pongas", english: "don't put (tú)", phoneticTranscription: "NO POHN-gahs" },
                { targetText: "ponga", english: "put (usted)", phoneticTranscription: "POHN-gah" },
                { targetText: "sal", english: "leave / go out (tú)", phoneticTranscription: "SAHL" },
                { targetText: "no salgas", english: "don't leave (tú)", phoneticTranscription: "NO SAHL-gahs" },
                { targetText: "salga", english: "leave (usted)", phoneticTranscription: "SAHL-gah" },
                { targetText: "ve", english: "go (tú)", phoneticTranscription: "BEH" },
                { targetText: "no vayas", english: "don't go (tú)", phoneticTranscription: "NO BAH-yahs" },
                { targetText: "vaya", english: "go (usted)", phoneticTranscription: "BAH-yah" },
                { targetText: "sé", english: "be (tú)", phoneticTranscription: "SEH" },
                { targetText: "no seas", english: "don't be (tú)", phoneticTranscription: "NO SEH-ahs" },
                { targetText: "sea", english: "be (usted)", phoneticTranscription: "SEH-ah" },
                { targetText: "escucha", english: "listen (tú)", phoneticTranscription: "ehs-KOO-chah" },
                { targetText: "mira", english: "look (tú)", phoneticTranscription: "MEE-rah" },
                { targetText: "trae", english: "bring (tú)", phoneticTranscription: "TRAH-eh" },
                { targetText: "pide", english: "ask for (tú)", phoneticTranscription: "PEE-deh" },
                { targetText: "duerme", english: "sleep (tú)", phoneticTranscription: "DWEHR-meh" },
                { targetText: "despierta", english: "wake up (tú)", phoneticTranscription: "dehs-PYEHR-tah" },
                { targetText: "espera", english: "wait (tú)", phoneticTranscription: "ehs-PEH-rah" },
                { targetText: "pasa", english: "pass / come in (tú)", phoneticTranscription: "PAH-sah" },
                { targetText: "entra", english: "enter (tú)", phoneticTranscription: "EHN-trah" },
                { targetText: "baja", english: "go down (tú)", phoneticTranscription: "BAH-hah" },
                { targetText: "sube", english: "go up (tú)", phoneticTranscription: "SOO-beh" },
                { targetText: "dobla", english: "turn (tú)", phoneticTranscription: "DOH-blah" },
                { targetText: "gira", english: "turn / spin (tú)", phoneticTranscription: "HEE-rah" },
                { targetText: "sigue", english: "continue (tú)", phoneticTranscription: "SEE-geh" },
                { targetText: "para", english: "stop (tú)", phoneticTranscription: "PAH-rah" },
                { targetText: "detente", english: "stop yourself (tú)", phoneticTranscription: "deh-TEHN-teh" },
                { targetText: "disfruta", english: "enjoy (tú)", phoneticTranscription: "dees-FROO-tah" },
                { targetText: "relájate", english: "relax (tú)", phoneticTranscription: "reh-LAH-ha-teh" },
                { targetText: "diviértete", english: "have fun (tú)", phoneticTranscription: "dee-BYEHR-teh-teh" },
                { targetText: "siéntate", english: "sit down (tú)", phoneticTranscription: "SYEHN-tah-teh" },
                { targetText: "levántate", english: "get up (tú)", phoneticTranscription: "leh-BAHN-tah-teh" },
                { targetText: "acuéstate", english: "go to bed (tú)", phoneticTranscription: "ah-KWEHS-tah-teh" },
                { targetText: "láva-te", english: "wash yourself (tú)", phoneticTranscription: "LAH-bah-teh" },
                { targetText: "báñate", english: "bathe (tú)", phoneticTranscription: "BAH-nya-teh" },
                { targetText: "cepíllate", english: "brush yourself (tú)", phoneticTranscription: "seh-PEE-ya-teh" },
                { targetText: "ayúdame", english: "help me", phoneticTranscription: "ah-YOO-dah-meh" },
                { targetText: "dame", english: "give me", phoneticTranscription: "DAH-meh" },
                { targetText: "dime", english: "tell me", phoneticTranscription: "DEE-meh" },
                { targetText: "hazme un favor", english: "do me a favor", phoneticTranscription: "AHS-meh oon fah-BOHR" },
                { targetText: "tráeme", english: "bring me", phoneticTranscription: "TRAH-eh-meh" },
                { targetText: "mándame", english: "send me", phoneticTranscription: "MAHN-dah-meh" },
                { targetText: "llámame", english: "call me", phoneticTranscription: "YAH-mah-meh" },
                { targetText: "escríbeme", english: "write to me", phoneticTranscription: "ehs-KREE-beh-meh" },
                { targetText: "pruébalo", english: "try it", phoneticTranscription: "PRWEH-bah-loh" },
                { targetText: "úsalos", english: "use them", phoneticTranscription: "OO-sah-lohs" },
                { targetText: "cómpralo", english: "buy it", phoneticTranscription: "KOHM-prah-loh" },
                { targetText: "recuerda", english: "remember", phoneticTranscription: "reh-KWEHR-dah" },
                { targetText: "no olvides", english: "don't forget", phoneticTranscription: "NO ohl-BEE-dehs" },
                { targetText: "aprende", english: "learn", phoneticTranscription: "ah-PREHN-deh" },
                { targetText: "estudia", english: "study", phoneticTranscription: "ehs-TOO-dyah" },
                { targetText: "trabaja", english: "work", phoneticTranscription: "trah-BAH-hah" },
                { targetText: "juega", english: "play", phoneticTranscription: "HWEH-gah" },
                { targetText: "practica", english: "practice", phoneticTranscription: "prahk-TEE-kah" },
                { targetText: "lee", english: "read", phoneticTranscription: "LEH-eh" },
                { targetText: "baila", english: "dance", phoneticTranscription: "BAH-ee-lah" },
                { targetText: "canta", english: "sing", phoneticTranscription: "KAHN-tah" },
                { targetText: "sonríe", english: "smile", phoneticTranscription: "sohn-REE-eh" },
                { targetText: "ríe", english: "laugh", phoneticTranscription: "REE-eh" },
                { targetText: "corre", english: "run", phoneticTranscription: "KOH-rreh" },
                { targetText: "camina", english: "walk", phoneticTranscription: "kah-MEE-nah" },
                { targetText: "nada", english: "swim", phoneticTranscription: "NAH-dah" },
                { targetText: "viaja", english: "travel", phoneticTranscription: "BYAH-hah" },
                { targetText: "conoce", english: "know / meet", phoneticTranscription: "koh-NOH-seh" },
                { targetText: "sabe", english: "know (fact)", phoneticTranscription: "SAH-beh" },
                { targetText: "entiende", english: "understand", phoneticTranscription: "ehn-TYEHN-deh" },
                { targetText: "piensa", english: "think", phoneticTranscription: "PYEHN-sah" },
                { targetText: "cree", english: "believe", phoneticTranscription: "KREH-eh" },
                { targetText: "imagina", english: "imagine", phoneticTranscription: "ee-mah-HEE-nah" },
                { targetText: "sueña", english: "dream", phoneticTranscription: "SWEH-nyah" },
                { targetText: "vive", english: "live", phoneticTranscription: "BEE-beh" },
                { targetText: "perdona", english: "forgive", phoneticTranscription: "pehr-DOH-nah" },
                { targetText: "cuídate", english: "take care of yourself", phoneticTranscription: "KWEE-dah-teh" }
            ]
        },
        {
            moduleId: "spanish_a2_m9",
            theme: "Progressive Tenses",
            order: 9,
            vocabularyItems: [
                { targetText: "estoy hablando", english: "I am speaking", phoneticTranscription: "ehs-TOY ah-BLAN-doh" },
                { targetText: "estás hablando", english: "you are speaking", phoneticTranscription: "ehs-TAHS ah-BLAN-doh" },
                { targetText: "está hablando", english: "he/she is speaking", phoneticTranscription: "ehs-TAH ah-BLAN-doh" },
                { targetText: "estamos hablando", english: "we are speaking", phoneticTranscription: "ehs-TAH-mohs ah-BLAN-doh" },
                { targetText: "están hablando", english: "they/you all are speaking", phoneticTranscription: "ehs-TAHN ah-BLAN-doh" },
                { targetText: "estoy comiendo", english: "I am eating", phoneticTranscription: "ehs-TOY koh-MYEHN-doh" },
                { targetText: "estás comiendo", english: "you are eating", phoneticTranscription: "ehs-TAHS koh-MYEHN-doh" },
                { targetText: "está comiendo", english: "he/she is eating", phoneticTranscription: "ehs-TAH koh-MYEHN-doh" },
                { targetText: "estamos comiendo", english: "we are eating", phoneticTranscription: "ehs-TAH-mohs koh-MYEHN-doh" },
                { targetText: "están comiendo", english: "they/you all are eating", phoneticTranscription: "ehs-TAHN koh-MYEHN-doh" },
                { targetText: "estoy viviendo", english: "I am living", phoneticTranscription: "ehs-TOY bee-BYEHN-doh" },
                { targetText: "estás viviendo", english: "you are living", phoneticTranscription: "ehs-TAHS bee-BYEHN-doh" },
                { targetText: "está viviendo", english: "he/she is living", phoneticTranscription: "ehs-TAH bee-BYEHN-doh" },
                { targetText: "estamos viviendo", english: "we are living", phoneticTranscription: "ehs-TAH-mohs bee-BYEHN-doh" },
                { targetText: "están viviendo", english: "they/you all are living", phoneticTranscription: "ehs-TAHN bee-BYEHN-doh" },
                { targetText: "están haciendo", english: "they are doing", phoneticTranscription: "ehs-TAHN ah-SYEHN-doh" },
                { targetText: "está diciendo", english: "he/she is saying", phoneticTranscription: "ehs-TAH dee-SYEHN-doh" },
                { targetText: "estás pidiendo", english: "you are asking for", phoneticTranscription: "ehs-TAHS pee-DYEHN-doh" },
                { targetText: "estamos sirviendo", english: "we are serving", phoneticTranscription: "ehs-TAH-mohs seer-BYEHN-doh" },
                { targetText: "estoy durmiendo", english: "I am sleeping", phoneticTranscription: "ehs-TOY door-MYEHN-doh" },
                { targetText: "está durmiendo", english: "he/she is sleeping", phoneticTranscription: "ehs-TAH door-MYEHN-doh" },
                { targetText: "están durmiendo", english: "they are sleeping", phoneticTranscription: "ehs-TAHN door-MYEHN-doh" },
                { targetText: "estás leyendo", english: "you are reading", phoneticTranscription: "ehs-TAHS leh-YEHN-doh" },
                { targetText: "estamos leyendo", english: "we are reading", phoneticTranscription: "ehs-TAH-mohs leh-YEHN-doh" },
                { targetText: "están leyendo", english: "they are reading", phoneticTranscription: "ehs-TAHN leh-YEHN-doh" },
                { targetText: "estamos oyendo", english: "we are hearing", phoneticTranscription: "ehs-TAH-mohs oh-YEHN-doh" },
                { targetText: "está trayendo", english: "he/she is bringing", phoneticTranscription: "ehs-TAH trah-YEHN-doh" },
                { targetText: "estoy cayendo", english: "I am falling", phoneticTranscription: "ehs-TOY kah-YEHN-doh" },
                { targetText: "está yendo", english: "he/she is going", phoneticTranscription: "ehs-TAH YEHN-doh" },
                { targetText: "estamos yendo", english: "we are going", phoneticTranscription: "ehs-TAH-mohs YEHN-doh" },
                { targetText: "estoy esperando", english: "I am waiting", phoneticTranscription: "ehs-TOY ehs-peh-RAN-doh" },
                { targetText: "estás buscando", english: "you are searching", phoneticTranscription: "ehs-TAHS boos-KAN-doh" },
                { targetText: "está pagando", english: "he/she is paying", phoneticTranscription: "ehs-TAH pah-GAN-doh" },
                { targetText: "estamos trabajando", english: "we are working", phoneticTranscription: "ehs-TAH-mohs trah-ba-HAN-doh" },
                { targetText: "están jugando", english: "they are playing", phoneticTranscription: "ehs-TAHN hoo-GAN-doh" },
                { targetText: "estoy estudiando", english: "I am studying", phoneticTranscription: "ehs-TOY ehs-too-DYAN-doh" },
                { targetText: "está aprendiendo", english: "he/she is learning", phoneticTranscription: "ehs-TAH ah-prehn-DYEHN-doh" },
                { targetText: "están escribiendo", english: "they are writing", phoneticTranscription: "ehs-TAHN ehs-kree-BYEHN-doh" },
                { targetText: "estamos escuchando", english: "we are listening", phoneticTranscription: "ehs-TAH-mohs ehs-koo-CHAN-doh" },
                { targetText: "está mirando", english: "he/she is looking", phoneticTranscription: "ehs-TAH mee-RAN-doh" },
                { targetText: "estoy pensando", english: "I am thinking", phoneticTranscription: "ehs-TOY pehn-SAN-doh" },
                { targetText: "está ocurriendo", english: "it is occurring", phoneticTranscription: "ehs-TAH oh-koo-RYEHN-doh" },
                { targetText: "está lloviendo", english: "it is raining", phoneticTranscription: "ehs-TAH yoh-BYEHN-doh" },
                { targetText: "está nevando", english: "it is snowing", phoneticTranscription: "ehs-TAH neh-BAN-doh" },
                { targetText: "estamos ganando", english: "we are winning", phoneticTranscription: "ehs-TAH-mohs gah-NAN-doh" },
                { targetText: "están perdiendo", english: "they are losing", phoneticTranscription: "ehs-TAHN pehr-DYEHN-doh" },
                { targetText: "estoy riendo", english: "I am laughing", phoneticTranscription: "ehs-TOY rye-YEHN-doh" },
                { targetText: "están sonriendo", english: "they are smiling", phoneticTranscription: "ehs-TAHN sohn-rye-YEHN-doh" },
                { targetText: "está divirtiéndose", english: "he/she is having fun", phoneticTranscription: "ehs-TAH dee-beer-TYEHN-doh-seh" },
                { targetText: "estamos durmiendo", english: "we are sleeping", phoneticTranscription: "ehs-TAH-mohs door-MYEHN-doh" },
                { targetText: "estoy vistiéndome", english: "I am getting dressed", phoneticTranscription: "ehs-TOY bees-TYEHN-doh-meh" },
                { targetText: "está bañándose", english: "he/she is bathing", phoneticTranscription: "ehs-TAH bah-NYAN-doh-seh" },
                { targetText: "estamos sentándonos", english: "we are sitting down", phoneticTranscription: "ehs-TAH-mohs sehn-TAN-doh-nohs" },
                { targetText: "están yéndose", english: "they are leaving", phoneticTranscription: "ehs-TAHN YEHN-doh-seh" },
                { targetText: "estoy relajándome", english: "I am relaxing", phoneticTranscription: "ehs-TOY reh-la-HAN-doh-meh" },
                { targetText: "está preparándose", english: "he/she is getting ready", phoneticTranscription: "ehs-TAH preh-pa-RAN-doh-seh" },
                { targetText: "estoy conduciendo", english: "I am driving", phoneticTranscription: "ehs-TOY kohn-doo-SYEHN-doh" },
                { targetText: "está volando", english: "he/she is flying", phoneticTranscription: "ehs-TAH boh-LAN-doh" },
                { targetText: "estamos viajando", english: "we are traveling", phoneticTranscription: "ehs-TAH-mohs byyah-HAN-doh" },
                { targetText: "están caminando", english: "they are walking", phoneticTranscription: "ehs-TAHN kah-mee-NAN-doh" },
                { targetText: "estoy corriendo", english: "I am running", phoneticTranscription: "ehs-TOY koh-RYEHN-doh" },
                { targetText: "está saltando", english: "he/she is jumping", phoneticTranscription: "ehs-TAH sahl-TAN-doh" },
                { targetText: "están bailando", english: "they are dancing", phoneticTranscription: "ehs-TAHN bye-LAN-doh" },
                { targetText: "estamos cantando", english: "we are singing", phoneticTranscription: "ehs-TAH-mohs kan-TAN-doh" },
                { targetText: "estoy cocinando", english: "I am cooking", phoneticTranscription: "ehs-TOY koh-see-NAN-doh" },
                { targetText: "está limpiando", english: "he/she is cleaning", phoneticTranscription: "ehs-TAH leem-PYAN-doh" },
                { targetText: "estamos cenando", english: "we are having dinner", phoneticTranscription: "ehs-TAH-mohs se-NAN-doh" },
                { targetText: "están desayunando", english: "they are having breakfast", phoneticTranscription: "ehs-TAHN de-sah-yoo-NAN-doh" },
                { targetText: "estoy bebiendo", english: "I am drinking", phoneticTranscription: "ehs-TOY beh-BYEHN-doh" },
                { targetText: "está comprando", english: "he/she is buying", phoneticTranscription: "ehs-TAH kohm-PRAN-doh" },
                { targetText: "estamos vendiendo", english: "we are selling", phoneticTranscription: "ehs-TAH-mohs behn-DYEHN-doh" },
                { targetText: "están llamando", english: "they are calling", phoneticTranscription: "ehs-TAHN yah-MAN-doh" },
                { targetText: "estoy respondiendo", english: "I am responding", phoneticTranscription: "ehs-TOY rehs-pohn-DYEHN-doh" },
                { targetText: "está prometiendo", english: "he/she is promising", phoneticTranscription: "ehs-TAH proh-meh-TYEHN-doh" },
                { targetText: "estamos cuidando", english: "we are taking care of", phoneticTranscription: "ehs-TAH-mohs kwee-DAN-doh" },
                { targetText: "están rompiendo", english: "they are breaking", phoneticTranscription: "ehs-TAHN rohm-PYEHN-doh" },
                { targetText: "estoy arreglando", english: "I am fixing", phoneticTranscription: "ehs-TOY ah-rre-GLAN-doh" },
                { targetText: "está construyendo", english: "he/she is building", phoneticTranscription: "ehs-TAH kohn-stroo-YEHN-doh" },
                { targetText: "estamos destruyendo", english: "we are destroying", phoneticTranscription: "ehs-TAH-mohs dehs-troo-YEHN-doh" },
                { targetText: "están buscando", english: "they are searching", phoneticTranscription: "ehs-TAHN boos-KAN-doh" },
                { targetText: "estoy encontrando", english: "I am finding", phoneticTranscription: "ehs-TOY ehn-kohn-TRAN-doh" },
                { targetText: "está subiendo", english: "he/she is going up", phoneticTranscription: "ehs-TAH soo-BYEHN-doh" },
                { targetText: "estamos bajando", english: "we are going down", phoneticTranscription: "ehs-TAH-mohs ba-HAN-doh" },
                { targetText: "están saliendo", english: "they are leaving", phoneticTranscription: "ehs-TAHN sah-LYEHN-doh" },
                { targetText: "estoy entrando", english: "I am entering", phoneticTranscription: "ehs-TOY ehn-TRAN-doh" },
                { targetText: "está abriendo", english: "he/she is opening", phoneticTranscription: "ehs-TAH ah-BRYEHN-doh" },
                { targetText: "estamos cerrando", english: "we are closing", phoneticTranscription: "ehs-TAH-mohs se-RRAN-doh" },
                { targetText: "están pidiendo ayuda", english: "they are asking for help", phoneticTranscription: "ehs-TAHN pee-DYEHN-doh ah-YOO-da" },
                { targetText: "estoy ayudando", english: "I am helping", phoneticTranscription: "ehs-TOY ah-yoo-DAN-doh" },
                { targetText: "está funcionando", english: "it is working / functioning", phoneticTranscription: "ehs-TAH foon-syoh-NAN-doh" },
                { targetText: "está pasando", english: "it is happening", phoneticTranscription: "ehs-TAH pa-SAN-doh" },
                { targetText: "estamos creciendo", english: "we are growing", phoneticTranscription: "ehs-TAH-mohs kre-SYEHN-doh" },
                { targetText: "están mejorando", english: "they are improving", phoneticTranscription: "ehs-TAHN me-ho-RAN-doh" },
                { targetText: "estoy disfrutando", english: "I am enjoying", phoneticTranscription: "ehs-TOY dees-froo-TAN-doh" },
                { targetText: "está soñando", english: "he/she is dreaming", phoneticTranscription: "ehs-TAH so-NYAN-doh" },
                { targetText: "estamos amando", english: "we are loving", phoneticTranscription: "ehs-TAH-mohs a-MAN-doh" },
                { targetText: "están odiando", english: "they are hating", phoneticTranscription: "ehs-TAHN o-DYAN-doh" },
                { targetText: "estoy prefiriendo", english: "I am preferring", phoneticTranscription: "ehs-TOY pre-fe-RYEHN-doh" },
                { targetText: "está sintiendo", english: "he/she is feeling", phoneticTranscription: "ehs-TAH seen-TYEHN-doh" },
                { targetText: "estamos perdiendo tiempo", english: "we are wasting time", phoneticTranscription: "ehs-TAH-mohs pehr-DYEHN-doh TYEM-po" }
            ]
        },
        {
            moduleId: "spanish_a2_m10",
            theme: "Practical Conversations & Idioms",
            order: 10,
            vocabularyItems: [
                { targetText: "¿Cómo te sientes?", english: "How do you feel?", phoneticTranscription: "ko-mo te SYEHN-tes" },
                { targetText: "¿Qué te pasa?", english: "What's wrong with you?", phoneticTranscription: "KE te PA-sa" },
                { targetText: "No me importa", english: "I don't care", phoneticTranscription: "NO me eem-POHR-ta" },
                { targetText: "Me da igual", english: "It's all the same to me / I don't care", phoneticTranscription: "ME DA ee-GWAL" },
                { targetText: "¿De qué se trata?", english: "What is it about?", phoneticTranscription: "DE KE se TRA-ta" },
                { targetText: "Por si acaso", english: "Just in case", phoneticTranscription: "POHR SEE ah-KA-so" },
                { targetText: "Vale la pena", english: "It's worth it", phoneticTranscription: "BA-le la PE-na" },
                { targetText: "No tiene sentido", english: "It doesn't make sense", phoneticTranscription: "NO TYE-ne sen-TEE-doh" },
                { targetText: "Me parece bien", english: "That seems fine to me", phoneticTranscription: "ME pa-RE-se BYEHN" },
                { targetText: "¿Estás de acuerdo?", english: "Do you agree?", phoneticTranscription: "es-TAS de a-KWER-doh" },
                { targetText: "Por supuesto", english: "Of course", phoneticTranscription: "POHR soo-PWES-toh" },
                { targetText: "¡Qué sorpresa!", english: "What a surprise!", phoneticTranscription: "KE sohr-PRE-sa" },
                { targetText: "No lo creo", english: "I don't believe it", phoneticTranscription: "NO LO KRE-o" },
                { targetText: "Puede ser", english: "Could be / maybe", phoneticTranscription: "PWE-de SER" },
                { targetText: "Tal vez", english: "Perhaps / maybe", phoneticTranscription: "TAL BES" },
                { targetText: "A lo mejor", english: "Probably", phoneticTranscription: "AH LO meh-HOHR" },
                { targetText: "Sin duda", english: "Without a doubt", phoneticTranscription: "SEEN DOO-da" },
                { targetText: "Lo antes posible", english: "As soon as possible", phoneticTranscription: "LO AN-tes po-SEE-ble" },
                { targetText: "Tan pronto como sea posible", english: "As soon as possible (long)", phoneticTranscription: "TAN PRON-to KO-mo se-a po-SEE-ble" },
                { targetText: "Poco a poco", english: "Little by little", phoneticTranscription: "PO-ko a PO-ko" },
                { targetText: "De vez en cuando", english: "Once in a while", phoneticTranscription: "DE BES EN KWAN-doh" },
                { targetText: "A menudo", english: "Often", phoneticTranscription: "A me-NOO-doh" },
                { targetText: "En realidad", english: "Actually / In reality", phoneticTranscription: "EN re-a-lee-DAHD" },
                { targetText: "De hecho", english: "In fact", phoneticTranscription: "DE E-cho" },
                { targetText: "Por desgracia", english: "Unfortunately", phoneticTranscription: "POHR des-GRA-sya" },
                { targetText: "Afortunadamente", english: "Fortunately", phoneticTranscription: "a-fohr-too-na-da-MEN-te" },
                { targetText: "En resumen", english: "In summary", phoneticTranscription: "EN re-SOO-men" },
                { targetText: "Finalmente", english: "Finally", phoneticTranscription: "fee-nal-MEN-te" },
                { targetText: "Por último", english: "Lastly", phoneticTranscription: "POHR UL-tee-mo" },
                { targetText: "Sobre todo", english: "Above all / especially", phoneticTranscription: "SOH-bre TOH-doh" },
                { targetText: "Además", english: "Furthermore", phoneticTranscription: "a-de-MAS" },
                { targetText: "Sin embargo", english: "However", phoneticTranscription: "SEEN em-BAR-go" },
                { targetText: "Aunque", english: "Although", phoneticTranscription: "OWN-ke" },
                { targetText: "A pesar de que", english: "Despite the fact that", phoneticTranscription: "A pe-SAR DE KE" },
                { targetText: "O sea", english: "In other words / I mean", phoneticTranscription: "O SE-a" },
                { targetText: "Es decir", english: "That is to say", phoneticTranscription: "ES de-SEER" },
                { targetText: "Por ejemplo", english: "For example", phoneticTranscription: "POHR e-HEM-plo" },
                { targetText: "Etcétera", english: "Et cetera", phoneticTranscription: "et-SE-te-ra" },
                { targetText: "Y así sucesivamente", english: "And so on", phoneticTranscription: "EE a-SEE soo-se-SEE-ba-men-te" },
                { targetText: "Lo que sea", english: "Whatever", phoneticTranscription: "LO KE SE-a" },
                { targetText: "Donde sea", english: "Wherever", phoneticTranscription: "DON-de SE-a" },
                { targetText: "Cuando sea", english: "Whenever", phoneticTranscription: "KWAN-do SE-a" },
                { targetText: "Quien sea", english: "Whoever", phoneticTranscription: "KYEN SE-a" },
                { targetText: "Como sea", english: "However / Anyway", phoneticTranscription: "KO-mo SE-a" },
                { targetText: "De ninguna manera", english: "No way", phoneticTranscription: "DE neen-GOO-na ma-NE-ra" },
                { targetText: "Para nada", english: "Not at all", phoneticTranscription: "PA-ra NA-da" },
                { targetText: "Por supuesto que sí", english: "Of course (yes)", phoneticTranscription: "POHR soo-PWES-to KE SEE" },
                { targetText: "Claro que no", english: "Of course not", phoneticTranscription: "KLA-ro KE NO" },
                { targetText: "¡Ni hablar!", english: "Don't even talk about it! (No way!)", phoneticTranscription: "NEE a-BLAR" },
                { targetText: "¡Qué pena!", english: "What a pity!", phoneticTranscription: "KE PE-na" },
                { targetText: "¡Qué lástima!", english: "What a shame!", phoneticTranscription: "KE LAS-tee-ma" },
                { targetText: "¡Qué mala suerte!", english: "What bad luck!", phoneticTranscription: "KE MA-la SWER-te" },
                { targetText: "¡Qué bien!", english: "How good!", phoneticTranscription: "KE BYEHN" },
                { targetText: "¡Qué alegría!", english: "What a joy!", phoneticTranscription: "KE a-le-GREE-a" },
                { targetText: "¡Enhorabuena!", english: "Congratulations!", phoneticTranscription: "en-o-ra-BWEN-a" },
                { targetText: "¡Felicidades!", english: "Congratulations / Happy birthday!", phoneticTranscription: "fe-lee-see-DA-des" },
                { targetText: "¡Buena suerte!", english: "Good luck!", phoneticTranscription: "BWEN-a SWER-te" },
                { targetText: "¡Buen viaje!", english: "Have a good trip!", phoneticTranscription: "BWEN BYA-he" },
                { targetText: "¡Buen provecho!", english: "Enjoy your meal!", phoneticTranscription: "BWEN pro-BE-cho" },
                { targetText: "Salud", english: "Cheers / Health", phoneticTranscription: "sa-LOOD" },
                { targetText: "Cuídate", english: "Take care", phoneticTranscription: "KWEE-da-te" },
                { targetText: "Nos vemos", english: "See you later", phoneticTranscription: "nos BE-mos" },
                { targetText: "Hasta luego", english: "See you later", phoneticTranscription: "AS-ta LWE-go" },
                { targetText: "Hasta pronto", english: "See you soon", phoneticTranscription: "AS-ta PRON-to" },
                { targetText: "Hasta mañana", english: "See you tomorrow", phoneticTranscription: "AS-ta ma-NYA-na" },
                { targetText: "Hasta la vista", english: "See you next time", phoneticTranscription: "AS-ta la BEES-ta" },
                { targetText: "Adiós", english: "Goodbye", phoneticTranscription: "a-DYOS" },
                { targetText: "Chao", english: "Bye", phoneticTranscription: "CHOW" },
                { targetText: "Hacer las maletas", english: "To pack suitcases", phoneticTranscription: "a-SER las ma-LE-tas" },
                { targetText: "Echar de menos", english: "To miss someone", phoneticTranscription: "e-CHAR de ME-nos" },
                { targetText: "Dar un paseo", english: "To take a walk", phoneticTranscription: "DAR oon pa-SE-o" },
                { targetText: "Tener sueño", english: "To be sleepy", phoneticTranscription: "te-NER SWE-nyo" },
                { targetText: "Tener prisa", english: "To be in a hurry", phoneticTranscription: "te-NER PREE-sa" },
                { targetText: "Tener éxito", english: "To be successful", phoneticTranscription: "te-NER EK-see-to" },
                { targetText: "Tener cuidado", english: "To be careful", phoneticTranscription: "te-NER kwee-DA-doh" },
                { targetText: "Tener hambre", english: "To be hungry", phoneticTranscription: "te-NER AM-bre" },
                { targetText: "Tener sed", english: "To be thirsty", phoneticTranscription: "te-NER SED" },
                { targetText: "Tener miedo", english: "To be afraid", phoneticTranscription: "te-NER MYE-doh" },
                { targetText: "Tener calor", english: "To be hot", phoneticTranscription: "te-NER ka-LOR" },
                { targetText: "Tener frío", english: "To be cold", phoneticTranscription: "te-NER FREE-o" },
                { targetText: "Tener razón", english: "To be right", phoneticTranscription: "te-NER ra-SON" },
                { targetText: "No tener razón", english: "To be wrong", phoneticTranscription: "NO te-NER ra-SON" },
                { targetText: "Tener suerte", english: "To be lucky", phoneticTranscription: "te-NER SWER-te" },
                { targetText: "Darse cuenta de", english: "To realize", phoneticTranscription: "DAR-se KWEN-ta de" },
                { targetText: "Ponerse de acuerdo", english: "To come to an agreement", phoneticTranscription: "po-NER-se de a-KWER-doh" },
                { targetText: "Ponerse en contacto", english: "To get in touch", phoneticTranscription: "po-NER-se en kohn-TAK-toh" },
                { targetText: "Estar de acuerdo", english: "To agree", phoneticTranscription: "es-TAR de a-KWER-doh" },
                { targetText: "Estar cansado", english: "To be tired", phoneticTranscription: "es-TAR kan-SA-doh" },
                { targetText: "Estar listo", english: "To be ready", phoneticTranscription: "es-TAR LEES-toh" },
                { targetText: "Estar ocupado", english: "To be busy", phoneticTranscription: "es-TAR o-koo-PA-doh" },
                { targetText: "Estar seguro", english: "To be sure", phoneticTranscription: "es-TAR se-GOO-ro" },
                { targetText: "Estar equivocado", english: "To be wrong", phoneticTranscription: "es-TAR e-kee-bo-KA-doh" },
                { targetText: "Ir de compras", english: "To go shopping", phoneticTranscription: "EER de KOM-pras" },
                { targetText: "Ir de vacaciones", english: "To go on vacation", phoneticTranscription: "EER de ba-ka-SYO-nes" },
                { targetText: "Llegar tarde", english: "To arrive late", phoneticTranscription: "ye-GAR TAR-de" },
                { targetText: "Llegar a tiempo", english: "To arrive on time", phoneticTranscription: "ye-GAR a TYEM-po" },
                { targetText: "Pasarlo bien", english: "To have a good time", phoneticTranscription: "pa-SAR-lo BYEHN" },
                { targetText: "Dejar de", english: "To stop (doing something)", phoneticTranscription: "de-HAR de" },
                { targetText: "Tratar de", english: "To try to", phoneticTranscription: "tra-TAR de" },
                { targetText: "Acabar de", english: "To have just (done something)", phoneticTranscription: "a-ka-BAR de" }
            ]
        }
    ];

    for (const module of modules) {
        await db.collection('languages').doc('spanish')
            .collection('levels').doc('a2')
            .collection('modules').doc(module.moduleId).set(module);
        console.log(`Uploaded ${module.moduleId}: ${module.theme} with ${module.vocabularyItems.length} words.`);
    }
}

uploadPart3().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
