const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}
const db = admin.firestore();

async function uploadPart2() {
    const modules = [
        {
            moduleId: "spanish_a2_m4",
            theme: "Por vs Para & Prepositions",
            order: 4,
            vocabularyItems: [
                { targetText: "por la mañana", english: "in the morning", phoneticTranscription: "pohr lah mah-NYAH-nah" },
                { targetText: "por la tarde", english: "in the afternoon", phoneticTranscription: "pohr lah TAHR-deh" },
                { targetText: "por la noche", english: "at night", phoneticTranscription: "pohr lah NOH-cheh" },
                { targetText: "por favor", english: "please", phoneticTranscription: "pohr fah-BOHR" },
                { targetText: "por ejemplo", english: "for example", phoneticTranscription: "pohr eh-HEHM-ploh" },
                { targetText: "por supuesto", english: "of course", phoneticTranscription: "pohr soo-PWEHS-toh" },
                { targetText: "por fin", english: "finally", phoneticTranscription: "pohr FEEN" },
                { targetText: "por cierto", english: "by the way", phoneticTranscription: "pohr SYEHR-toh" },
                { targetText: "por eso", english: "that's why", phoneticTranscription: "pohr EH-soh" },
                { targetText: "por lo menos", english: "at least", phoneticTranscription: "pohr loh MEH-nohs" },
                { targetText: "por todas partes", english: "everywhere", phoneticTranscription: "pohr TOH-dahs PAHR-tehs" },
                { targetText: "gracias por", english: "thanks for", phoneticTranscription: "GRAH-syahs pohr" },
                { targetText: "por aquí", english: "around here", phoneticTranscription: "pohr ah-KEE" },
                { targetText: "por allí", english: "around there", phoneticTranscription: "pohr ah-YEE" },
                { targetText: "por teléfono", english: "by phone", phoneticTranscription: "pohr teh-LEH-foh-noh" },
                { targetText: "por correo", english: "by mail", phoneticTranscription: "pohr koh-RREH-oh" },
                { targetText: "por avión", english: "by plane", phoneticTranscription: "pohr ah-BYOHN" },
                { targetText: "por casualidad", english: "by chance", phoneticTranscription: "pohr kah-swah-lee-DAHD" },
                { targetText: "por ciento", english: "percent", phoneticTranscription: "pohr SYEHN-toh" },
                { targetText: "para mí", english: "for me / in my opinion", phoneticTranscription: "PAH-rah MEE" },
                { targetText: "para ti", english: "for you", phoneticTranscription: "PAH-rah TEE" },
                { targetText: "para siempre", english: "forever", phoneticTranscription: "PAH-rah SYEHM-preh" },
                { targetText: "para mañana", english: "for tomorrow", phoneticTranscription: "PAH-rah mah-NYAH-nah" },
                { targetText: "para qué", english: "what for", phoneticTranscription: "PAH-rah KEH" },
                { targetText: "para que", english: "so that", phoneticTranscription: "PAH-rah KEH" },
                { targetText: "trabajar para", english: "to work for", phoneticTranscription: "trah-bah-HAHR PAH-rah" },
                { targetText: "estudiar para", english: "to study for", phoneticTranscription: "es-too-DYAR PAH-rah" },
                { targetText: "ir para", english: "to go towards", phoneticTranscription: "EER PAH-rah" },
                { targetText: "salir para", english: "to leave for", phoneticTranscription: "sah-LEER PAH-rah" },
                { targetText: "listo para", english: "ready for", phoneticTranscription: "LEES-toh PAH-rah" },
                { targetText: "un regalo para", english: "a gift for", phoneticTranscription: "oon reh-GAH-loh PAH-rah" },
                { targetText: "sobre", english: "about / on top of", phoneticTranscription: "SOH-breh" },
                { targetText: "debajo de", english: "underneatch", phoneticTranscription: "deh-BAH-hoh deh" },
                { targetText: "encima de", english: "on top of", phoneticTranscription: "ehn-SEE-mah deh" },
                { targetText: "dentro de", english: "inside of", phoneticTranscription: "DEHN-troh deh" },
                { targetText: "fuera de", english: "outside of", phoneticTranscription: "FWEH-rah deh" },
                { targetText: "al lado de", english: "next to", phoneticTranscription: "ahl LAH-doh deh" },
                { targetText: "cerca de", english: "near to", phoneticTranscription: "SEHR-kah deh" },
                { targetText: "lejos de", english: "far from", phoneticTranscription: "LEH-hohs deh" },
                { targetText: "delante de", english: "in front of", phoneticTranscription: "deh-LAHN-teh deh" },
                { targetText: "detrás de", english: "behind", phoneticTranscription: "deh-TRAHS deh" },
                { targetText: "entre", english: "between / among", phoneticTranscription: "EHN-treh" },
                { targetText: "hacia", english: "towards", phoneticTranscription: "AH-syah" },
                { targetText: "hasta", english: "until / even", phoneticTranscription: "AHS-tah" },
                { targetText: "desde", english: "from / since", phoneticTranscription: "DEHS-deh" },
                { targetText: "desde hace", english: "for (time duration)", phoneticTranscription: "DEHS-deh AH-seh" },
                { targetText: "ante", english: "before / in the presence of", phoneticTranscription: "AHN-teh" },
                { targetText: "bajo", english: "under / low", phoneticTranscription: "BAH-hoh" },
                { targetText: "contra", english: "against", phoneticTranscription: "KOHN-trah" },
                { targetText: "según", english: "according to", phoneticTranscription: "seh-GOON" },
                { targetText: "sin", english: "without", phoneticTranscription: "SEEN" },
                { targetText: "con", english: "with", phoneticTranscription: "KOHN" },
                { targetText: "como", english: "as / like", phoneticTranscription: "KOH-moh" },
                { targetText: "durante", english: "during", phoneticTranscription: "doo-RAHN-teh" },
                { targetText: "inmediatamente", english: "immediately", phoneticTranscription: "een-meh-dyah-tah-MEHN-teh" },
                { targetText: "especialmente", english: "especially", phoneticTranscription: "es-peh-syahl-MEHN-teh" },
                { targetText: "frente a", english: "facing / across from", phoneticTranscription: "FREHN-teh ah" },
                { targetText: "a través de", english: "through / across", phoneticTranscription: "ah trah-BEHS deh" },
                { targetText: "debido a", english: "due to", phoneticTranscription: "deh-BEE-doh ah" },
                { targetText: "a pesar de", english: "despite", phoneticTranscription: "ah peh-SAHR deh" },
                { targetText: "pese a", english: "in spite of", phoneticTranscription: "PEH-seh ah" },
                { targetText: "acerca de", english: "regarding / about", phoneticTranscription: "ah-SEHR-kah deh" },
                { targetText: "con respecto a", english: "with respect to", phoneticTranscription: "kohn rehs-PEHK-toh ah" },
                { targetText: "a favor de", english: "in favor of", phoneticTranscription: "ah fah-BOHR deh" },
                { targetText: "en contra de", english: "against", phoneticTranscription: "ehn KOHN-trah deh" },
                { targetText: "en lugar de", english: "instead of", phoneticTranscription: "ehn loo-GAHR deh" },
                { targetText: "en vez de", english: "instead of", phoneticTranscription: "ehn BEHS deh" },
                { targetText: "en medio de", english: "in the middle of", phoneticTranscription: "ehn MEH-dyoh deh" },
                { targetText: "alrededor de", english: "around", phoneticTranscription: "ahl-reh-deh-DOHR deh" },
                { targetText: "encima", english: "above / on top", phoneticTranscription: "ehn-SEE-mah" },
                { targetText: "abajo", english: "below / down", phoneticTranscription: "ah-BAH-hoh" },
                { targetText: "atrás", english: "back / behind", phoneticTranscription: "ah-TRAHS" },
                { targetText: "adelante", english: "forward", phoneticTranscription: "ah-deh-LAHN-teh" },
                { targetText: "arriba", english: "up / upstairs", phoneticTranscription: "ah-RREE-bah" },
                { targetText: "hacia adelante", english: "forward", phoneticTranscription: "AH-syah ah-deh-LAHN-teh" },
                { targetText: "hacia atrás", english: "backward", phoneticTranscription: "AH-syah ah-TRAHS" },
                { targetText: "hacia arriba", english: "upward", phoneticTranscription: "AH-syah ah-RREE-bah" },
                { targetText: "hacia abajo", english: "downward", phoneticTranscription: "AH-syah ah-BAH-hoh" },
                { targetText: "adentro", english: "inside", phoneticTranscription: "ah-DEHN-troh" },
                { targetText: "afuera", english: "outside", phoneticTranscription: "ah-FWEH-rah" },
                { targetText: "por fuera", english: "on the outside", phoneticTranscription: "pohr FWEH-rah" },
                { targetText: "por dentro", english: "on the inside", phoneticTranscription: "pohr DEHN-troh" },
                { targetText: "cerca", english: "near", phoneticTranscription: "SEHR-kah" },
                { targetText: "lejos", english: "far", phoneticTranscription: "LEH-hohs" },
                { targetText: "aquí", english: "here", phoneticTranscription: "ah-KEE" },
                { targetText: "allí", english: "there", phoneticTranscription: "ah-YEE" },
                { targetText: "acá", english: "here (directional)", phoneticTranscription: "ah-KAH" },
                { targetText: "allá", english: "there (farther)", phoneticTranscription: "ah-YAH" },
                { targetText: "en casa", english: "at home", phoneticTranscription: "ehn KAH-sah" },
                { targetText: "en el trabajo", english: "at work", phoneticTranscription: "ehn ehl trah-BAH-hoh" },
                { targetText: "en la escuela", english: "at school", phoneticTranscription: "ehn lah es-KWEH-lah" },
                { targetText: "en el cine", english: "at the cinema", phoneticTranscription: "ehn ehl SEE-neh" },
                { targetText: "en la calle", english: "in the street", phoneticTranscription: "ehn lah KAH-yeh" },
                { targetText: "en el parque", english: "in the park", phoneticTranscription: "ehn ehl PAHR-keh" },
                { targetText: "en la ciudad", english: "in the city", phoneticTranscription: "ehn lah syoo-DAHD" },
                { targetText: "en el país", english: "in the country", phoneticTranscription: "ehn ehl pah-EES" },
                { targetText: "por el mundo", english: "around the world", phoneticTranscription: "pohr ehl MOON-doh" },
                { targetText: "en todas partes", english: "everywhere", phoneticTranscription: "ehn TOH-dahs PAHR-tehs" },
                { targetText: "donde sea", english: "anywhere", phoneticTranscription: "DOHN-deh SEH-ah" },
                { targetText: "a donde sea", english: "anywhere (directional)", phoneticTranscription: "ah DOHN-deh SEH-ah" }
            ]
        },
        {
            moduleId: "spanish_a2_m5",
            theme: "Reflexive Verbs & Routine",
            order: 5,
            vocabularyItems: [
                { targetText: "levantarse", english: "to get up", phoneticTranscription: "leh-bahn-TAHR-seh" },
                { targetText: "despertarse", english: "to wake up", phoneticTranscription: "dehs-pehr-TAHR-seh" },
                { targetText: "lavarse", english: "to wash oneself", phoneticTranscription: "lah-BAHR-seh" },
                { targetText: "bañarse", english: "to bathe", phoneticTranscription: "bah-NYAHR-seh" },
                { targetText: "ducharse", english: "to shower", phoneticTranscription: "doo-CHAHR-seh" },
                { targetText: "afeitarse", english: "to shave", phoneticTranscription: "ah-fej-TAHR-seh" },
                { targetText: "maquillarse", english: "to put on makeup", phoneticTranscription: "mah-kee-YAHR-seh" },
                { targetText: "vestirse", english: "to get dressed", phoneticTranscription: "behs-TEER-seh" },
                { targetText: "desvestirse", english: "to undress", phoneticTranscription: "dehs-behs-TEER-seh" },
                { targetText: "ponerse la ropa", english: "to put on clothes", phoneticTranscription: "poh-NEHR-seh lah ROH-pah" },
                { targetText: "quitarse la ropa", english: "to take off clothes", phoneticTranscription: "kee-TAHR-seh lah ROH-pah" },
                { targetText: "peinarse", english: "to comb one's hair", phoneticTranscription: "pej-NAHR-seh" },
                { targetText: "cepillarse los dientes", english: "to brush teeth", phoneticTranscription: "seh-pee-YAHR-seh lohs DYEN-tehs" },
                { targetText: "secarse", english: "to dry oneself", phoneticTranscription: "seh-KAHR-seh" },
                { targetText: "sentarse", english: "to sit down", phoneticTranscription: "sehn-TAHR-seh" },
                { targetText: "acostarse", english: "to go to bed", phoneticTranscription: "ah-kohs-TAHR-seh" },
                { targetText: "dormirse", english: "to fall asleep", phoneticTranscription: "dohr-MEER-seh" },
                { targetText: "despertarse temprano", english: "to wake up early", phoneticTranscription: "dehs-pehr-TAHR-seh tehm-PRAH-noh" },
                { targetText: "acostarse tarde", english: "to go to bed late", phoneticTranscription: "ah-kohs-TAHR-seh TAHR-deh" },
                { targetText: "mirarse al espejo", english: "to look at oneself in the mirror", phoneticTranscription: "mee-RAHR-seh ahl es-PEH-hoh" },
                { targetText: "llamarse", english: "to be called", phoneticTranscription: "yah-MAHR-seh" },
                { targetText: "sentirse", english: "to feel", phoneticTranscription: "sehn-TEER-seh" },
                { targetText: "preocuparse", english: "to worry", phoneticTranscription: "preh-oh-koo-PAHR-seh" },
                { targetText: "enojarse", english: "to get angry", phoneticTranscription: "eh-noh-HAHR-seh" },
                { targetText: "alegrarse", english: "to be happy", phoneticTranscription: "ah-leh-GRAHR-seh" },
                { targetText: "divertirse", english: "to have fun", phoneticTranscription: "dee-behr-TEER-seh" },
                { targetText: "aburrirse", english: "to get bored", phoneticTranscription: "ah-boo-RREER-seh" },
                { targetText: "olvidarse", english: "to forget", phoneticTranscription: "ohl-bee-DAHR-seh" },
                { targetText: "acordarse", english: "to remember", phoneticTranscription: "ah-kohr-DAHR-seh" },
                { targetText: "quedarse", english: "to stay", phoneticTranscription: "keh-DAHR-seh" },
                { targetText: "irse", english: "to leave", phoneticTranscription: "EER-seh" },
                { targetText: "marcharse", english: "to leave / depart", phoneticTranscription: "mar-CHAHR-seh" },
                { targetText: "reírse", english: "to laugh", phoneticTranscription: "reh-EER-seh" },
                { targetText: "quejarse", english: "to complain", phoneticTranscription: "keh-HAHR-seh" },
                { targetText: "enamorarse", english: "to fall in love", phoneticTranscription: "eh-nah-moh-RAHR-seh" },
                { targetText: "casarse", english: "to get married", phoneticTranscription: "kah-SAHR-seh" },
                { targetText: "cansarse", english: "to get tired", phoneticTranscription: "kahn-SAHR-seh" },
                { targetText: "relajarse", english: "to relax", phoneticTranscription: "reh-lah-HAHR-seh" },
                { targetText: "prepararse", english: "to get ready", phoneticTranscription: "preh-pah-RAHR-seh" },
                { targetText: "reunirse", english: "to meet", phoneticTranscription: "reh-oo-NEER-seh" },
                { targetText: "sorprenderse", english: "to be surprised", phoneticTranscription: "sohr-prehn-DEHR-seh" },
                { targetText: "asustarse", english: "to get scared", phoneticTranscription: "ah-soos-TAHR-seh" },
                { targetText: "equivocarse", english: "to make a mistake", phoneticTranscription: "eh-kee-boh-KAHR-seh" },
                { targetText: "darse cuenta", english: "to realize", phoneticTranscription: "DAHR-seh KWEHN-tah" },
                { targetText: "portarse bien", english: "to behave well", phoneticTranscription: "pohr-TAHR-seh BYEHN" },
                { targetText: "portarse mal", english: "to behave badly", phoneticTranscription: "pohr-TAHR-seh MAHL" },
                { targetText: "quemarse", english: "to get burned", phoneticTranscription: "keh-MAHR-seh" },
                { targetText: "cortarse", english: "to cut oneself", phoneticTranscription: "kohr-TAHR-seh" },
                { targetText: "romperse", english: "to break", phoneticTranscription: "rohm-PEHR-seh" },
                { targetText: "lastimarse", english: "to hurt oneself", phoneticTranscription: "lahs-tee-MAHR-seh" },
                { targetText: "curarse", english: "to heal", phoneticTranscription: "koo-RAHR-seh" },
                { targetText: "mojarse", english: "to get wet", phoneticTranscription: "moh-HAHR-seh" },
                { targetText: "ensuciarse", english: "to get dirty", phoneticTranscription: "ehn-soo-SYAHR-seh" },
                { targetText: "limpiarse", english: "to clean oneself", phoneticTranscription: "leem-PYAHR-seh" },
                { targetText: "cambiarse de ropa", english: "to change clothes", phoneticTranscription: "kahm-BYAHR-seh deh ROH-pah" },
                { targetText: "probarse", english: "to try on", phoneticTranscription: "proh-BAHR-seh" },
                { targetText: "quitarse los zapatos", english: "to take off shoes", phoneticTranscription: "kee-TAHR-seh lohs sah-PAH-tohs" },
                { targetText: "ponerse los zapatos", english: "to put on shoes", phoneticTranscription: "poh-NEHR-seh lohs sah-PAH-tohs" },
                { targetText: "mirarse", english: "to look at each other", phoneticTranscription: "mee-RAHR-seh" },
                { targetText: "ayudarse", english: "to help each other", phoneticTranscription: "ah-yoo-DAHR-seh" },
                { targetText: "quererse", english: "to love each other", phoneticTranscription: "keh-REHR-seh" },
                { targetText: "odiarse", english: "to hate each other", phoneticTranscription: "oh-DYAHR-seh" },
                { targetText: "escribirse", english: "to write to each other", phoneticTranscription: "ehs-kree-BEER-seh" },
                { targetText: "llamarse por teléfono", english: "to call each other", phoneticTranscription: "yah-MAHR-seh pohr teh-LEH-foh-noh" },
                { targetText: "conocerse", english: "to meet each other", phoneticTranscription: "koh-noh-SEHR-seh" },
                { targetText: "verse", english: "to see each other", phoneticTranscription: "BEHR-seh" },
                { targetText: "pelearse", english: "to fight", phoneticTranscription: "peh-leh-AHR-seh" },
                { targetText: "besarse", english: "to kiss each other", phoneticTranscription: "beh-SAHR-seh" },
                { targetText: "abrazarse", english: "to hug each other", phoneticTranscription: "ah-brah-SAHR-seh" },
                { targetText: "saludarse", english: "to greet each other", phoneticTranscription: "sah-loo-DAHR-seh" },
                { targetText: "despedirse", english: "to say goodbye", phoneticTranscription: "dehs-peh-DEER-seh" },
                { targetText: "entenderse", english: "to understand each other", phoneticTranscription: "ehn-tehn-DEHR-seh" },
                { targetText: "prometerse", english: "to promise each other", phoneticTranscription: "proh-meh-TEHR-seh" },
                { targetText: "hablarse", english: "to speak to each other", phoneticTranscription: "ah-BLAHR-seh" },
                { targetText: "escucharse", english: "to listen to each other", phoneticTranscription: "ehs-koo-CHAHR-seh" },
                { targetText: "gritarse", english: "to yell at each other", phoneticTranscription: "gree-TAHR-seh" },
                { targetText: "perdonarse", english: "to forgive each other", phoneticTranscription: "pehr-doh-NAHR-seh" },
                { targetText: "respetarse", english: "to respect each other", phoneticTranscription: "rehs-peh-TAHR-seh" },
                { targetText: "admirarse", english: "to admire each other", phoneticTranscription: "ahd-mee-RAHR-seh" },
                { targetText: "imaginarse", english: "to imagine", phoneticTranscription: "ee-mah-hee-NAHR-seh" },
                { targetText: "creerse", english: "to believe oneself", phoneticTranscription: "kreh-EHR-seh" },
                { targetText: "considerarse", english: "to consider oneself", phoneticTranscription: "kohn-see-deh-RAHR-seh" },
                { targetText: "sentirse solo", english: "to feel lonely", phoneticTranscription: "sehn-TEER-seh SOH-loh" },
                { targetText: "sentirse bien", english: "to feel well", phoneticTranscription: "sehn-TEER-seh BYEHN" },
                { targetText: "sentirse mal", english: "to feel bad", phoneticTranscription: "sehn-TEER-seh MAHL" },
                { targetText: "encontrarse con", english: "to meet up with", phoneticTranscription: "ehn-kohn-TRAHR-seh kohn" },
                { targetText: "cansarse de", english: "to get tired of", phoneticTranscription: "kahn-SAHR-seh deh" },
                { targetText: "quejarse de", english: "to complain about", phoneticTranscription: "keh-HAHR-seh deh" },
                { targetText: "olvidarse de", english: "to forget about", phoneticTranscription: "ohl-bee-DAHR-seh deh" },
                { targetText: "acordarse de", english: "to remember about", phoneticTranscription: "ah-kohr-DAHR-seh deh" },
                { targetText: "reírse de", english: "to laugh at", phoneticTranscription: "reh-EER-seh deh" },
                { targetText: "enamorarse de", english: "to fall in love with", phoneticTranscription: "eh-nah-moh-RAHR-seh deh" },
                { targetText: "preocuparse por", english: "to worry about", phoneticTranscription: "preh-oh-koo-PAHR-seh pohr" },
                { targetText: "interesarse por", english: "to be interested in", phoneticTranscription: "een-teh-reh-SAHR-seh pohr" },
                { targetText: "sorprenderse de", english: "to be surprised by", phoneticTranscription: "sohr-prehn-DEHR-seh deh" },
                { targetText: "asustarse de", english: "to be scared of", phoneticTranscription: "ah-soos-TAHR-seh deh" },
                { targetText: "burlarse de", english: "to make fun of", phoneticTranscription: "boor-LAHR-seh deh" },
                { targetText: "aprovecharse de", english: "to take advantage of", phoneticTranscription: "ah-proh-beh-CHAHR-seh deh" },
                { targetText: "atreverse a", english: "to dare to", phoneticTranscription: "ah-treh-BEHR-seh ah" },
                { targetText: "dedicarse a", english: "to dedicate oneself to", phoneticTranscription: "deh-dee-KAHR-seh ah" }
            ]
        },
        {
            moduleId: "spanish_a2_m6",
            theme: "Comparatives & Adjectives",
            order: 6,
            vocabularyItems: [
                { targetText: "más que", english: "more than", phoneticTranscription: "MAHS KEH" },
                { targetText: "menos que", english: "less than", phoneticTranscription: "MEH-nohs KEH" },
                { targetText: "tan ... como", english: "as ... as", phoneticTranscription: "TAHN KOH-moh" },
                { targetText: "tanto como", english: "as much as", phoneticTranscription: "TAHN-toh KOH-moh" },
                { targetText: "mejor que", english: "better than", phoneticTranscription: "meh-HOHR KEH" },
                { targetText: "peor que", english: "worse than", phoneticTranscription: "peh-OHR KEH" },
                { targetText: "mayor que", english: "older than", phoneticTranscription: "mah-YOHR KEH" },
                { targetText: "menor que", english: "younger than", phoneticTranscription: "meh-NOHR KEH" },
                { targetText: "el más", english: "the most", phoneticTranscription: "ehl MAHS" },
                { targetText: "el menos", english: "the least", phoneticTranscription: "ehl MEH-nohs" },
                { targetText: "el mejor", english: "the best", phoneticTranscription: "ehl meh-HOHR" },
                { targetText: "el peor", english: "the worst", phoneticTranscription: "ehl peh-OHR" },
                { targetText: "el mayor", english: "the oldest", phoneticTranscription: "ehl mah-YOHR" },
                { targetText: "el menor", english: "the youngest", phoneticTranscription: "ehl meh-NOHR" },
                { targetText: "buenísimo", english: "very good / great", phoneticTranscription: "bweh-NEE-see-moh" },
                { targetText: "malísimo", english: "very bad", phoneticTranscription: "mah-LEE-see-moh" },
                { targetText: "carísimo", english: "very expensive", phoneticTranscription: "kah-REE-see-moh" },
                { targetText: "baratísimo", english: "very cheap", phoneticTranscription: "bah-rah-TEE-see-moh" },
                { targetText: "grandísimo", english: "very big", phoneticTranscription: "grahn-DEE-see-moh" },
                { targetText: "pequeñísimo", english: "very small", phoneticTranscription: "peh-keh-NYEE-see-moh" },
                { targetText: "guapo", english: "handsome", phoneticTranscription: "GWAH-poh" },
                { targetText: "bonito", english: "pretty / beautiful", phoneticTranscription: "boh-NEE-toh" },
                { targetText: "feo", english: "ugly", phoneticTranscription: "FEH-oh" },
                { targetText: "inteligente", english: "intelligent", phoneticTranscription: "een-teh-lee-HEHN-teh" },
                { targetText: "tonto", english: "silly / dumb", phoneticTranscription: "TOHN-toh" },
                { targetText: "simpático", english: "nice", phoneticTranscription: "seem-PAH-tee-koh" },
                { targetText: "antipático", english: "unfriendly", phoneticTranscription: "ahn-tee-PAH-tee-koh" },
                { targetText: "trabajador", english: "hardworking", phoneticTranscription: "trah-bah-hah-DOHR" },
                { targetText: "vago", english: "lazy", phoneticTranscription: "BAH-goh" },
                { targetText: "divertido", english: "fun", phoneticTranscription: "dee-behr-TEE-doh" },
                { targetText: "aburrido", english: "boring", phoneticTranscription: "ah-boo-RREE-doh" },
                { targetText: "fuerte", english: "strong", phoneticTranscription: "FWEHR-teh" },
                { targetText: "débil", english: "weak", phoneticTranscription: "DEH-bee" },
                { targetText: "valiente", english: "brave", phoneticTranscription: "bah-LYEHN-teh" },
                { targetText: "cobarde", english: "cowardly", phoneticTranscription: "koh-BAHR-deh" },
                { targetText: "generoso", english: "generous", phoneticTranscription: "heh-neh-ROH-soh" },
                { targetText: "tacaño", english: "stingy", phoneticTranscription: "tah-KAH-nyoh" },
                { targetText: "amable", english: "kind / friendly", phoneticTranscription: "ah-MAH-bleh" },
                { targetText: "grosero", english: "rude", phoneticTranscription: "groh-SEH-roh" },
                { targetText: "paciente", english: "patient", phoneticTranscription: "pah-SYEHN-teh" },
                { targetText: "impaciente", english: "impatient", phoneticTranscription: "eem-pah-SYEHN-teh" },
                { targetText: "sincero", english: "sincere", phoneticTranscription: "seen-SEH-roh" },
                { targetText: "mentiroso", english: "liar", phoneticTranscription: "mehn-tee-ROH-soh" },
                { targetText: "optimista", english: "optimistic", phoneticTranscription: "ohp-tee-MEES-tah" },
                { targetText: "pesimista", english: "pessimistic", phoneticTranscription: "peh-see-MEES-tah" },
                { targetText: "alegre", english: "cheerful", phoneticTranscription: "ah-LEH-greh" },
                { targetText: "triste", english: "sad", phoneticTranscription: "TREES-teh" },
                { targetText: "enojado", english: "angry", phoneticTranscription: "eh-noh-HAH-doh" },
                { targetText: "feliz", english: "happy", phoneticTranscription: "feh-LEES" },
                { targetText: "contento", english: "happy / content", phoneticTranscription: "kohn-TEHN-toh" },
                { targetText: "nervioso", english: "nervous", phoneticTranscription: "nehr-BYOH-soh" },
                { targetText: "tranquilo", english: "calm", phoneticTranscription: "trahn-KEE-loh" },
                { targetText: "emocionado", english: "excited", phoneticTranscription: "eh-moh-syoh-NAH-doh" },
                { targetText: "preocupado", english: "worried", phoneticTranscription: "preh-oh-koo-PAH-doh" },
                { targetText: "cansado", english: "tired", phoneticTranscription: "kahn-SAH-doh" },
                { targetText: "enfermo", english: "sick", phoneticTranscription: "ehn-FEHR-moh" },
                { targetText: "sano", english: "healthy", phoneticTranscription: "SAH-noh" },
                { targetText: "ocupado", english: "busy", phoneticTranscription: "oh-koo-PAH-doh" },
                { targetText: "libre", english: "free / available", phoneticTranscription: "LEE-breh" },
                { targetText: "casado", english: "married", phoneticTranscription: "kah-SAH-doh" },
                { targetText: "soltero", english: "single", phoneticTranscription: "sohl-TEH-roh" },
                { targetText: "divorciado", english: "divorced", phoneticTranscription: "dee-bohr-SYA-doh" },
                { targetText: "viudo", english: "widowed", phoneticTranscription: "BYOO-doh" },
                { targetText: "joven", english: "young", phoneticTranscription: "HOH-behn" },
                { targetText: "viejo", english: "old", phoneticTranscription: "BYEH-hoh" },
                { targetText: "anciano", english: "elderly", phoneticTranscription: "ahn-SYA-noh" },
                { targetText: "rico", english: "rich", phoneticTranscription: "REE-koh" },
                { targetText: "pobre", english: "poor", phoneticTranscription: "POH-breh" },
                { targetText: "famoso", english: "famous", phoneticTranscription: "fah-MOH-soh" },
                { targetText: "desconocido", english: "unknown", phoneticTranscription: "dehs-koh-noh-SEE-doh" },
                { targetText: "importante", english: "important", phoneticTranscription: "eem-pohr-TAHN-teh" },
                { targetText: "insignificante", english: "insignificant", phoneticTranscription: "een-seeg-nee-fee-KAHN-teh" },
                { targetText: "útil", english: "useful", phoneticTranscription: "OO-teel" },
                { targetText: "inútil", english: "useless", phoneticTranscription: "ee-NOO-teel" },
                { targetText: "fácil", english: "easy", phoneticTranscription: "FAH-seel" },
                { targetText: "difícil", english: "difficult", phoneticTranscription: "dee-FEE-seel" },
                { targetText: "complicado", english: "complicated", phoneticTranscription: "kohm-plee-KAH-doh" },
                { targetText: "sencillo", english: "simple", phoneticTranscription: "sehn-SEE-yoh" },
                { targetText: "claro", english: "clear / light", phoneticTranscription: "KLAH-roh" },
                { targetText: "oscuro", english: "dark", phoneticTranscription: "ohs-KOO-roh" },
                { targetText: "limpio", english: "clean", phoneticTranscription: "LEEM-pyoh" },
                { targetText: "sucio", english: "dirty", phoneticTranscription: "SOO-syoh" },
                { targetText: "lleno", english: "full", phoneticTranscription: "YEH-noh" },
                { targetText: "vacío", english: "empty", phoneticTranscription: "bah-SEE-oh" },
                { targetText: "duro", english: "hard", phoneticTranscription: "DOO-roh" },
                { targetText: "suave", english: "soft / smooth", phoneticTranscription: "SWAH-beh" },
                { targetText: "blando", english: "soft / squishy", phoneticTranscription: "BLAHN-doh" },
                { targetText: "áspero", english: "rough", phoneticTranscription: "AHS-peh-roh" },
                { targetText: "pesado", english: "heavy", phoneticTranscription: "peh-SAH-doh" },
                { targetText: "ligero", english: "lightweight", phoneticTranscription: "lee-HEH-roh" },
                { targetText: "ancho", english: "wide", phoneticTranscription: "AHN-choh" },
                { targetText: "estrecho", english: "narrow", phoneticTranscription: "es-TREH-choh" },
                { targetText: "profundo", english: "deep", phoneticTranscription: "proh-FOON-doh" },
                { targetText: "superficial", english: "shallow", phoneticTranscription: "soo-pehr-fee-SYAHL" },
                { targetText: "seco", english: "dry", phoneticTranscription: "SEH-koh" },
                { targetText: "mojado", english: "wet", phoneticTranscription: "moh-HAH-doh" },
                { targetText: "abierto", english: "open", phoneticTranscription: "ah-BYEHR-toh" },
                { targetText: "cerrado", english: "closed", phoneticTranscription: "seh-RRAH-doh" },
                { targetText: "nuevo", english: "new", phoneticTranscription: "NWEH-boh" },
                { targetText: "viejo", english: "old", phoneticTranscription: "BYEH-hoh" }
            ]
        }
    ];

    for (const module of modules) {
        await db.collection('languages').doc('spanish')
            .collection('levels').doc('a2')
            .collection('modules').doc(module.moduleId).set(module);
        console.log(`Uploaded ${module.moduleId}: ${module.theme} with ${module.vocabularyItems.length} words.`);
    }
}

uploadPart2().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
