const admin = require('firebase-admin');
const serviceAccount = require('./serviceAccountKey.json');

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount)
    });
}
const db = admin.firestore();

async function uploadPart1() {
    const modules = [
        {
            moduleId: "spanish_a2_m1",
            theme: "Past Tense: Pretérito Indefinido",
            order: 1,
            vocabularyItems: [
                { targetText: "hablé", english: "I spoke", phoneticTranscription: "ah-BLEH" },
                { targetText: "hablaste", english: "you spoke", phoneticTranscription: "ah-BLAHS-teh" },
                { targetText: "habló", english: "he/she spoke", phoneticTranscription: "ah-BLOH" },
                { targetText: "hablamos", english: "we spoke", phoneticTranscription: "ah-BLAH-mohs" },
                { targetText: "hablaron", english: "they spoke", phoneticTranscription: "ah-BLAH-rohn" },
                { targetText: "comí", english: "I ate", phoneticTranscription: "koh-MEE" },
                { targetText: "comiste", english: "you ate", phoneticTranscription: "koh-MEES-teh" },
                { targetText: "comió", english: "he/she ate", phoneticTranscription: "koh-MYOH" },
                { targetText: "comimos", english: "we ate", phoneticTranscription: "koh-MEE-mohs" },
                { targetText: "comieron", english: "they ate", phoneticTranscription: "koh-MYE-rohn" },
                { targetText: "viví", english: "I lived", phoneticTranscription: "bee-BEE" },
                { targetText: "viviste", english: "you lived", phoneticTranscription: "bee-BEES-teh" },
                { targetText: "vivió", english: "he/she lived", phoneticTranscription: "bee-BYOH" },
                { targetText: "vivimos", english: "we lived", phoneticTranscription: "bee-BEE-mohs" },
                { targetText: "vivieron", english: "they lived", phoneticTranscription: "bee-BYE-rohn" },
                { targetText: "fui", english: "I went / I was", phoneticTranscription: "FWEE" },
                { targetText: "fuiste", english: "you went / you were", phoneticTranscription: "FWREES-teh" },
                { targetText: "fue", english: "he/she went / he/she was", phoneticTranscription: "FWEH" },
                { targetText: "fuimos", english: "we went / we were", phoneticTranscription: "FWEE-mohs" },
                { targetText: "fueron", english: "they went / they were", phoneticTranscription: "FWEH-rohn" },
                { targetText: "hice", english: "I did / I made", phoneticTranscription: "EE-seh" },
                { targetText: "hiciste", english: "you did / you made", phoneticTranscription: "ee-SEES-teh" },
                { targetText: "hizo", english: "he/she did / he/she made", phoneticTranscription: "EE-soh" },
                { targetText: "hicimos", english: "we did / we made", phoneticTranscription: "ee-SEE-mohs" },
                { targetText: "hicieron", english: "they did / they were", phoneticTranscription: "ee-SYE-rohn" },
                { targetText: "vine", english: "I came", phoneticTranscription: "BEE-neh" },
                { targetText: "viniste", english: "you came", phoneticTranscription: "bee-NEES-teh" },
                { targetText: "vino", english: "he/she came", phoneticTranscription: "BEE-noh" },
                { targetText: "dije", english: "I said", phoneticTranscription: "DEE-heh" },
                { targetText: "dijiste", english: "you said", phoneticTranscription: "dee-HEES-teh" },
                { targetText: "dijo", english: "he/she said", phoneticTranscription: "DEE-hoh" },
                { targetText: "pude", english: "I was able to", phoneticTranscription: "POO-deh" },
                { targetText: "puse", english: "I put", phoneticTranscription: "POO-seh" },
                { targetText: "supe", english: "I found out / knew", phoneticTranscription: "SOO-peh" },
                { targetText: "tuve", english: "I had", phoneticTranscription: "TOO-beh" },
                { targetText: "estuve", english: "I was (location)", phoneticTranscription: "es-TOO-beh" },
                { targetText: "anduve", english: "I walked", phoneticTranscription: "ahn-DOO-beh" },
                { targetText: "quise", english: "I wanted / tried", phoneticTranscription: "KEE-seh" },
                { targetText: "traje", english: "I brought", phoneticTranscription: "TRAH-heh" },
                { targetText: "conduje", english: "I drove", phoneticTranscription: "kohn-DOO-heh" },
                { targetText: "vi", english: "I saw", phoneticTranscription: "BEE" },
                { targetText: "diste", english: "you gave", phoneticTranscription: "DEES-teh" },
                { targetText: "ayer", english: "yesterday", phoneticTranscription: "ah-YEHR" },
                { targetText: "anteayer", english: "day before yesterday", phoneticTranscription: "ahn-teh-ah-YEHR" },
                { targetText: "anoche", english: "last night", phoneticTranscription: "ah-NOH-cheh" },
                { targetText: "el lunes pasado", english: "last Monday", phoneticTranscription: "ehl LOO-nes pah-SAH-doh" },
                { targetText: "la semana pasada", english: "last week", phoneticTranscription: "lah seh-MAH-nah pah-SAH-dah" },
                { targetText: "el mes pasado", english: "last month", phoneticTranscription: "ehl MEHS pah-SAH-doh" },
                { targetText: "el año pasado", english: "last year", phoneticTranscription: "ehl AH-nyoh pah-SAH-doh" },
                { targetText: "hace dos días", english: "two days ago", phoneticTranscription: "AH-seh dohs DEE-ahs" },
                { targetText: "una vez", english: "one time", phoneticTranscription: "OO-nah BEHS" },
                { targetText: "de repente", english: "suddenly", phoneticTranscription: "deh reh-PEHN-teh" },
                { targetText: "por fin", english: "at last", phoneticTranscription: "pohr FEEN" },
                { targetText: "finalmente", english: "finally", phoneticTranscription: "fee-nahl-MEHN-teh" },
                { targetText: "comenzó", english: "it started", phoneticTranscription: "koh-mehn-SOH" },
                { targetText: "terminó", english: "it ended", phoneticTranscription: "tehr-mee-NOH" },
                { targetText: "nació", english: "he/she was born", phoneticTranscription: "nah-SYOH" },
                { targetText: "murió", english: "he/she died", phoneticTranscription: "moo-RYOH" },
                { targetText: "compró", english: "he/she bought", phoneticTranscription: "kohm-PROH" },
                { targetText: "vendió", english: "he/she sold", phoneticTranscription: "behn-DYOH" },
                { targetText: "durmió", english: "he/she slept", phoneticTranscription: "door-MYOH" },
                { targetText: "pidió", english: "he/she asked for", phoneticTranscription: "pee-DYOH" },
                { targetText: "sirvió", english: "he/she served", phoneticTranscription: "seer-BYOH" },
                { targetText: "leyó", english: "he/she read", phoneticTranscription: "leh-YOH" },
                { targetText: "creyó", english: "he/she believed", phoneticTranscription: "kreh-YOH" },
                { targetText: "oyó", english: "he/she heard", phoneticTranscription: "oh-YOH" },
                { targetText: "cayó", english: "it fell", phoneticTranscription: "kah-YOH" },
                { targetText: "llegó", english: "he/she arrived", phoneticTranscription: "yeh-GOH" },
                { targetText: "busqué", english: "I searched", phoneticTranscription: "boos-KEH" },
                { targetText: "pagué", english: "I paid", phoneticTranscription: "pah-GEH" },
                { targetText: "almorcé", english: "I had lunch", phoneticTranscription: "ahl-mohr-SEH" },
                { targetText: "saqué", english: "I took out", phoneticTranscription: "sah-KEH" },
                { targetText: "toqué", english: "I played / touched", phoneticTranscription: "toh-KEH" },
                { targetText: "jugó", english: "he/she played", phoneticTranscription: "hoo-GOH" },
                { targetText: "explicó", english: "he/she explained", phoneticTranscription: "eks-plee-KOH" },
                { targetText: "bailó", english: "he/she danced", phoneticTranscription: "bah-ee-LOH" },
                { targetText: "cantó", english: "he/she sang", phoneticTranscription: "kahn-TOH" },
                { targetText: "nadó", phoneticTranscription: "nah-DOH", english: "he/she swam" },
                { targetText: "viajó", phoneticTranscription: "byah-HOH", english: "he/she traveled" },
                { targetText: "cenó", phoneticTranscription: "seh-NOH", english: "he/she had dinner" },
                { targetText: "desayunó", phoneticTranscription: "deh-sah-yoo-NOH", english: "he/she had breakfast" },
                { targetText: "limpió", phoneticTranscription: "leem-PYOH", english: "he/she cleaned" },
                { targetText: "cocinó", phoneticTranscription: "koh-see-NOH", english: "he/she cooked" },
                { targetText: "estudió", phoneticTranscription: "es-too-DYOH", english: "he/she studied" },
                { targetText: "aprendió", phoneticTranscription: "ah-prehn-DYOH", english: "he/she learned" },
                { targetText: "escribió", phoneticTranscription: "es-kree-BYOH", english: "he/she wrote" },
                { targetText: "abrió", phoneticTranscription: "ah-BRYOH", english: "he/she opened" },
                { targetText: "cerró", phoneticTranscription: "seh-RROH", english: "he/she closed" },
                { targetText: "miró", phoneticTranscription: "mee-ROH", english: "he/she looked" },
                { targetText: "escucho", phoneticTranscription: "es-koo-CHOH", english: "he/she listened" },
                { targetText: "bebió", phoneticTranscription: "beh-BYOH", english: "he/she drank" },
                { targetText: "perdió", phoneticTranscription: "pehr-DYOH", english: "he/she lost" },
                { targetText: "encontró", phoneticTranscription: "ehn-kohn-TROH", english: "he/she found" },
                { targetText: "corrió", phoneticTranscription: "koh-RYOH", english: "he/she ran" },
                { targetText: "subió", phoneticTranscription: "soo-BYOH", english: "he/she went up" },
                { targetText: "bajó", phoneticTranscription: "bah-HOH", english: "he/she went down" },
                { targetText: "saltó", phoneticTranscription: "sahl-TOH", english: "he/she jumped" },
                { targetText: "llamó", phoneticTranscription: "yah-MOH", english: "he/she called" },
                { targetText: "mandó", phoneticTranscription: "mahn-DOH", english: "he/she sent" },
                { targetText: "preguntó", phoneticTranscription: "preh-goon-TOH", english: "he/she asked" }
            ]
        },
        {
            moduleId: "spanish_a2_m2",
            theme: "Past Tense: Imperfecto",
            order: 2,
            vocabularyItems: [
                { targetText: "hablaba", english: "I/he used to speak", phoneticTranscription: "ah-BLAH-bah" },
                { targetText: "hablabas", english: "you used to speak", phoneticTranscription: "ah-BLAH-bahs" },
                { targetText: "hablábamos", english: "we used to speak", phoneticTranscription: "ah-BLAH-bah-mohs" },
                { targetText: "hablaban", english: "they used to speak", phoneticTranscription: "ah-BLAH-bahn" },
                { targetText: "comía", english: "I/he used to eat", phoneticTranscription: "koh-MEE-ah" },
                { targetText: "comías", english: "you used to eat", phoneticTranscription: "koh-MEE-ahs" },
                { targetText: "comíamos", english: "we used to eat", phoneticTranscription: "koh-MEE-ah-mohs" },
                { targetText: "comían", english: "they used to eat", phoneticTranscription: "koh-MEE-ahn" },
                { targetText: "vivía", english: "I used to live", phoneticTranscription: "bee-BEE-ah" },
                { targetText: "vivías", english: "you used to live", phoneticTranscription: "bee-BEE-ahs" },
                { targetText: "vivíamos", english: "we used to live", phoneticTranscription: "bee-BEE-ah-mohs" },
                { targetText: "vivían", english: "they used to live", phoneticTranscription: "bee-BEE-ahn" },
                { targetText: "era", english: "I/he used to be", phoneticTranscription: "EH-rah" },
                { targetText: "eras", english: "you used to be", phoneticTranscription: "EH-rahs" },
                { targetText: "éramos", english: "we used to be", phoneticTranscription: "EH-rah-mohs" },
                { targetText: "eran", english: "they used to be", phoneticTranscription: "EH-rahn" },
                { targetText: "iba", english: "I/he used to go", phoneticTranscription: "EE-bah" },
                { targetText: "ibas", english: "you used to go", phoneticTranscription: "EE-bahs" },
                { targetText: "íbamos", english: "we used to go", phoneticTranscription: "EE-bah-mohs" },
                { targetText: "iban", english: "they used to go", phoneticTranscription: "EE-bahn" },
                { targetText: "veía", english: "I/he used to see", phoneticTranscription: "be-EE-ah" },
                { targetText: "veías", english: "you used to see", phoneticTranscription: "be-EE-ahs" },
                { targetText: "veíamos", english: "we used to see", phoneticTranscription: "be-EE-ah-mohs" },
                { targetText: "veían", english: "they used to see", phoneticTranscription: "be-EE-ahn" },
                { targetText: "siempre", english: "always", phoneticTranscription: "SYEHM-preh" },
                { targetText: "nunca", english: "never", phoneticTranscription: "NOON-kah" },
                { targetText: "frecuentemente", english: "frequently", phoneticTranscription: "freh-kwehn-teh-MEHN-teh" },
                { targetText: "a menudo", english: "often", phoneticTranscription: "ah meh-NOO-doh" },
                { targetText: "a veces", english: "sometimes", phoneticTranscription: "ah BEH-sehs" },
                { targetText: "muchas veces", english: "many times", phoneticTranscription: "MOO-chahs BEH-sehs" },
                { targetText: "todos los días", english: "every day", phoneticTranscription: "TOH-dohs lohs DEE-ahs" },
                { targetText: "cada verano", english: "every summer", phoneticTranscription: "KAH-dah beh-RAH-noh" },
                { targetText: "mientras", english: "while", phoneticTranscription: "MYEHN-trahs" },
                { targetText: "de niño", english: "as a child", phoneticTranscription: "deh NEE-nyoh" },
                { targetText: "cuando era pequeño", english: "when I was small", phoneticTranscription: "KWAHN-doh EH-rah peh-KEH-nyoh" },
                { targetText: "hacía sol", english: "it was sunny", phoneticTranscription: "ah-SYE-ah SOHL" },
                { targetText: "hacía calor", english: "it was hot", phoneticTranscription: "ah-SYE-ah kah-LOHR" },
                { targetText: "hacía frío", english: "it was cold", phoneticTranscription: "ah-SYE-ah FREE-oh" },
                { targetText: "llovía", english: "it was raining", phoneticTranscription: "yoh-BEE-ah" },
                { targetText: "nevaba", english: "it was snowing", phoneticTranscription: "neh-BAH-bah" },
                { targetText: "estaba cansado", english: "I was tired", phoneticTranscription: "es-TAH-bah kahn-SAH-doh" },
                { targetText: "tenía hambre", english: "I was hungry", phoneticTranscription: "teh-NEE-ah AM-breh" },
                { targetText: "tenía sed", english: "I was thirsty", phoneticTranscription: "teh-NEE-ah SEHD" },
                { targetText: "tenía miedo", english: "I was afraid", phoneticTranscription: "teh-NEE-ah MYEH-doh" },
                { targetText: "estaba triste", english: "I was sad", phoneticTranscription: "es-TAH-bah TREES-teh" },
                { targetText: "estaba feliz", english: "I was happy", phoneticTranscription: "es-TAH-bah feh-LEES" },
                { targetText: "había", english: "there was/were", phoneticTranscription: "ah-BEE-ah" },
                { targetText: "parecía", english: "it seemed", phoneticTranscription: "pah-reh-SYE-ah" },
                { targetText: "pensaba", english: "I used to think", phoneticTranscription: "pehn-SAH-bah" },
                { targetText: "creía", english: "I used to believe", phoneticTranscription: "kreh-EE-ah" },
                { targetText: "quería", english: "I used to want", phoneticTranscription: "keh-REE-ah" },
                { targetText: "podía", english: "I was able to", phoneticTranscription: "poh-DEE-ah" },
                { targetText: "prefería", english: "I used to prefer", phoneticTranscription: "preh-feh-REE-ah" },
                { targetText: "me gustaba", english: "I used to like", phoneticTranscription: "meh goos-TAH-bah" },
                { targetText: "me encantaba", english: "I used to love", phoneticTranscription: "meh ehn-kahn-TAH-bah" },
                { targetText: "solía", english: "I tended to", phoneticTranscription: "soh-LEE-ah" },
                { targetText: "hacía ejercicio", english: "I used to exercise", phoneticTranscription: "ah-SYE-ah eh-hehr-SEE-syoh" },
                { targetText: "jugaba al fútbol", english: "I played soccer", phoneticTranscription: "hoo-GAH-bah ahl FOOT-bohl" },
                { targetText: "tocaba el piano", english: "I played piano", phoneticTranscription: "toh-KAH-bah ehl PYAH-noh" },
                { targetText: "leía libros", english: "I read books", phoneticTranscription: "leh-EE-ah LEE-brohs" },
                { targetText: "miraba la tele", english: "I watched TV", phoneticTranscription: "mee-RAH-bah lah TEH-leh" },
                { targetText: "escuchaba música", english: "I listened to music", phoneticTranscription: "es-koo-CHAH-bah MOO-see-kah" },
                { targetText: "dormía mucho", english: "I slept a lot", phoneticTranscription: "door-MEE-ah MOO-choh" },
                { targetText: "estudiaba mucho", english: "I studied a lot", phoneticTranscription: "es-too-DYAH-bah MOO-choh" },
                { targetText: "trabajaba allá", english: "I worked there", phoneticTranscription: "tra-ba-HA-ba a-YA" },
                { targetText: "vivía solo", english: "I lived alone", phoneticTranscription: "bee-BEE-ah SOH-loh" },
                { targetText: "tenía un perro", english: "I had a dog", phoneticTranscription: "teh-NEE-ah oon PEH-rroh" },
                { targetText: "viajaba cada año", english: "I traveled every year", phoneticTranscription: "byyah-HA-ba KA-da AN-yo" },
                { targetText: "comía pizza", phoneticTranscription: "koh-MEE-ah PEE-tsah", english: "I used to eat pizza" },
                { targetText: "bebía leche", phoneticTranscription: "beh-BEE-ah LEH-cheh", english: "I used to drink milk" },
                { targetText: "corría rápido", phoneticTranscription: "koh-RREE-ah RAH-pee-doh", english: "I used to run fast" },
                { targetText: "nadaba bien", phoneticTranscription: "nah-DAH-bah BYEHN", english: "I used to swim well" },
                { targetText: "subía al árbol", phoneticTranscription: "soo-BEE-ah ahl AR-bohl", english: "I used to climb the tree" },
                { targetText: "saltaba mucho", phoneticTranscription: "sahl-TAH-bah MOO-choh", english: "I used to jump a lot" },
                { targetText: "llamaba siempre", phoneticTranscription: "yah-MAH-bah SYEHM-preh", english: "I used to call always" },
                { targetText: "escribía cartas", phoneticTranscription: "es-kree-BEE-ah KAR-tahs", english: "I used to write letters" },
                { targetText: "abría la puerta", phoneticTranscription: "ah-BREE-ah lah PWEHR-tah", english: "I used to open the door" },
                { targetText: "limpiaba la casa", phoneticTranscription: "leem-PYAH-bah lah KAH-sah", english: "I used to clean the house" },
                { targetText: "cocinaba rico", phoneticTranscription: "koh-see-NAH-bah REE-koh", english: "I used to cook tasty" },
                { targetText: "cenaba tarde", phoneticTranscription: "seh-NAH-bah TAR-deh", english: "I used to have dinner late" },
                { targetText: "desayunaba temprano", phoneticTranscription: "deh-sah-yoo-NAH-bah tehm-PRAH-noh", english: "I used to have breakfast early" },
                { targetText: "era gordo", phoneticTranscription: "EH-rah GOHR-doh", english: "I used to be fat" },
                { targetText: "era flaco", phoneticTranscription: "EH-rah FLA-koh", english: "I used to be thin" },
                { targetText: "era alto", phoneticTranscription: "EH-rah AL-toh", english: "I used to be tall" },
                { targetText: "era bajo", phoneticTranscription: "EH-rah BA-ho", english: "I used to be short" },
                { targetText: "tenía el pelo largo", phoneticTranscription: "teh-NEE-ah ehl PEH-loh LAR-goh", english: "I had long hair" },
                { targetText: "vivía en el campo", phoneticTranscription: "bee-BEE-ah ehn ehl KAHM-poh", english: "I used to live in the country" },
                { targetText: "tenía muchos amigos", phoneticTranscription: "teh-NEE-ah MOO-chos ah-MEE-gohs", english: "I had many friends" },
                { targetText: "iba al cine", phoneticTranscription: "EE-bah ahl SEE-neh", english: "I used to go to the cinema" },
                { targetText: "veía los dibujos", phoneticTranscription: "beh-EE-ah lohs dee-BOO-hos", english: "I used to watch cartoons" },
                { targetText: "jugaba con juguetes", phoneticTranscription: "hoo-GAH-bah kohn hoo-GWEH-tehs", english: "I played with toys" },
                { targetText: "dormía con la luz", phoneticTranscription: "door-MEE-ah kohn lah LOOS", english: "I slept with the light" },
                { targetText: "prefería el chocolate", phoneticTranscription: "preh-feh-REE-ah ehl cho-koh-LA-teh", english: "I preferred chocolate" },
                { targetText: "odiaba los vegetales", phoneticTranscription: "oh-DYAH-bah lohs beh-he-TA-les", english: "I hated vegetables" },
                { targetText: "amaba a mi abuela", phoneticTranscription: "ah-MAH-bah ah mee a-BWE-la", english: "I loved my grandmother" },
                { targetText: "quería ser médico", phoneticTranscription: "keh-REE-ah sehr ME-dee-koh", english: "I wanted to be a doctor" },
                { targetText: "tenía cinco años", phoneticTranscription: "teh-NEE-ah SEENG-koh AN-yos", english: "I was five years old" }
            ]
        },
        {
            moduleId: "spanish_a2_m3",
            theme: "Future & Conditional Tenses",
            order: 3,
            vocabularyItems: [
                { targetText: "hablaré", english: "I will speak", phoneticTranscription: "ah-blah-REH" },
                { targetText: "hablarás", english: "you will speak", phoneticTranscription: "ah-blah-RAHS" },
                { targetText: "hablará", english: "he/she will speak", phoneticTranscription: "ah-blah-RAH" },
                { targetText: "hablaremos", english: "we will speak", phoneticTranscription: "ah-blah-REH-mohs" },
                { targetText: "hablaréis", english: "you all will speak (Spain)", phoneticTranscription: "ah-blah-REH-ees" },
                { targetText: "hablarán", english: "they will speak", phoneticTranscription: "ah-blah-RAHN" },
                { targetText: "comeré", english: "I will eat", phoneticTranscription: "koh-meh-REH" },
                { targetText: "viviré", english: "I will live", phoneticTranscription: "bee-bee-REH" },
                { targetText: "haré", english: "I will do / make", phoneticTranscription: "ah-REH" },
                { targetText: "harás", english: "you will do / make", phoneticTranscription: "ah-RAHS" },
                { targetText: "diré", english: "I will say", phoneticTranscription: "dee-REH" },
                { targetText: "dirás", english: "you will say", phoneticTranscription: "dee-RAHS" },
                { targetText: "podré", english: "I will be able to", phoneticTranscription: "poh-DREH" },
                { targetText: "pondré", english: "I will put", phoneticTranscription: "pohn-DREH" },
                { targetText: "saldré", english: "I will leave", phoneticTranscription: "sahl-DREH" },
                { targetText: "tendré", english: "I will have", phoneticTranscription: "tehn-DREH" },
                { targetText: "vendré", english: "I will come", phoneticTranscription: "behn-DREH" },
                { targetText: "sabré", english: "I will know", phoneticTranscription: "sah-BREH" },
                { targetText: "habrá", english: "there will be", phoneticTranscription: "ah-BRAH" },
                { targetText: "hablaría", english: "I would speak", phoneticTranscription: "ah-blah-REE-ah" },
                { targetText: "hablarías", english: "you would speak", phoneticTranscription: "ah-blah-REE-ahs" },
                { targetText: "comería", english: "I would eat", phoneticTranscription: "koh-meh-REE-ah" },
                { targetText: "viviría", english: "I would live", phoneticTranscription: "bee-bee-REE-ah" },
                { targetText: "haría", english: "I would do / make", phoneticTranscription: "ah-REE-ah" },
                { targetText: "diría", english: "I would say", phoneticTranscription: "dee-REE-ah" },
                { targetText: "podría", english: "I could / I would be able to", phoneticTranscription: "poh-DREE-ah" },
                { targetText: "pondría", english: "I would put", phoneticTranscription: "pohn-DREE-ah" },
                { targetText: "saldría", english: "I would leave", phoneticTranscription: "sahl-DREE-ah" },
                { targetText: "tendría", english: "I would have", phoneticTranscription: "tehn-DREE-ah" },
                { targetText: "vendría", english: "I would come", phoneticTranscription: "behn-DREE-ah" },
                { targetText: "mañana", english: "tomorrow", phoneticTranscription: "mah-NYA-nah" },
                { targetText: "pasado mañana", english: "day after tomorrow", phoneticTranscription: "pah-sa-do ma-NYA-na" },
                { targetText: "la próxima semana", english: "next week", phoneticTranscription: "la prok-see-ma se-MA-na" },
                { targetText: "el próximo año", english: "next year", phoneticTranscription: "el prok-see-mo AN-yo" },
                { targetText: "pronto", english: "soon", phoneticTranscription: "PROHN-toh" },
                { targetText: "más tarde", english: "later", phoneticTranscription: "mas TAR-de" },
                { targetText: "algún día", english: "some day", phoneticTranscription: "al-GOON DEE-a" },
                { targetText: "en el futuro", english: "in the future", phoneticTranscription: "en el foo-TOO-ro" },
                { targetText: "si tuviera tiempo", english: "if I had time", phoneticTranscription: "see too-BYE-ra TYEM-po" },
                { targetText: "si pudiera", english: "if I could", phoneticTranscription: "see poo-DYE-ra" },
                { targetText: "viajaré mucho", english: "I will travel a lot", phoneticTranscription: "byyah-ha-RE MOO-cho" },
                { targetText: "compraré una casa", english: "I will buy a house", phoneticTranscription: "kohm-pra-RE OO-na KA-sa" },
                { targetText: "aprenderé español", english: "I will learn Spanish", phoneticTranscription: "a-prehn-de-RE es-pa-NYOL" },
                { targetText: "seré rico", english: "I will be rich", phoneticTranscription: "se-RE REE-koh" },
                { targetText: "seré feliz", english: "I will be happy", phoneticTranscription: "se-RE fe-LEES" },
                { targetText: "me casaré", english: "I will get married", phoneticTranscription: "me ka-sa-RE" },
                { targetText: "tendré hijos", english: "I will have children", phoneticTranscription: "ten-DRE EE-hos" },
                { targetText: "trabajaré duro", english: "I will work hard", phoneticTranscription: "tra-ba-ha-RE DOO-ro" },
                { targetText: "estudiaré medicina", english: "I will study medicine", phoneticTranscription: "es-too-dya-RE me-dee-SEE-na" },
                { targetText: "iré a la playa", english: "I will go to the beach", phoneticTranscription: "ee-RE a la PLA-ya" },
                { targetText: "correré mañana", english: "I will run tomorrow", phoneticTranscription: "ko-re-RE ma-NYA-na" },
                { targetText: "leeré el libro", english: "I will read the book", phoneticTranscription: "le-e-RE el LEE-bro" },
                { targetText: "escribiré una carta", english: "I will write a letter", phoneticTranscription: "es-kree-bee-RE OO-na KAR-ta" },
                { targetText: "abriré la ventana", english: "I will open the window", phoneticTranscription: "a-bree-RE la ben-TA-na" },
                { targetText: "limpiaré mi cuarto", english: "I will clean my room", phoneticTranscription: "leem-pya-RE mee KWAR-to" },
                { targetText: "cocinaré pasta", english: "I will cook pasta", phoneticTranscription: "ko-see-na-RE PAS-ta" },
                { targetText: "cenaremos juntos", english: "we will have dinner together", phoneticTranscription: "se-na-RE-mos HOON-tos" },
                { targetText: "desayunaré cereal", english: "I will have cereal for breakfast", phoneticTranscription: "de-sa-yoo-na-RE se-re-AL" },
                { targetText: "correrías si pudieras", phoneticTranscription: "koh-re-REE-as see poo-DYE-ras", english: "you would run if you could" },
                { targetText: "él comería más", phoneticTranscription: "el koh-me-REE-ah MAS", english: "he would eat more" },
                { targetText: "viviríamos allí", phoneticTranscription: "bee-bee-REE-ah-mohs a-YEE", english: "we would live there" },
                { targetText: "ellos dirían la verdad", phoneticTranscription: "EH-yohs dee-REE-ahn lah behr-DAD", english: "they would tell the truth" },
                { targetText: "haría sol mañana", phoneticTranscription: "ah-REE-ah SOHL ma-NYA-na", english: "it would be sunny tomorrow" },
                { targetText: "compraría un coche", phoneticTranscription: "kohm-pra-REE-ah oon KO-che", english: "I would buy a car" },
                { targetText: "viajarían a España", phoneticTranscription: "byyah-ha-REE-ahn a es-PA-nya", english: "they would travel to Spain" },
                { targetText: "aprenderíamos rápido", phoneticTranscription: "a-prehn-de-REE-ah-mohs RA-pee-doh", english: "we would learn fast" },
                { targetText: "leería el periódico", phoneticTranscription: "le-e-REE-ah el pe-RYO-dee-koh", english: "I would read the newspaper" },
                { targetText: "escribiría un poema", phoneticTranscription: "es-kree-bee-REE-ah oon po-E-ma", english: "I would write a poem" },
                { targetText: "abriría el regalo", phoneticTranscription: "a-bree-REE-ah el re-GA-lo", english: "I would open the gift" },
                { targetText: "limpiaríamos mañana", phoneticTranscription: "leem-pya-REE-ah-mohs ma-NYA-na", english: "we would clean tomorrow" },
                { targetText: "cocinarían pollo", phoneticTranscription: "ko-see-na-REE-ahn PO-yo", english: "they would cook chicken" },
                { targetText: "cenaría contigo", phoneticTranscription: "se-na-REE-ah kohn-TEE-go", english: "I would have dinner with you" },
                { targetText: "beberíamos agua", phoneticTranscription: "be-be-REE-ah-mohs A-gwa", english: "we would drink water" },
                { targetText: "perdería las llaves", phoneticTranscription: "pehr-de-REE-ah las YA-bes", english: "I would lose the keys" },
                { targetText: "encontraría el camino", phoneticTranscription: "ehn-kohn-tra-REE-ah el ka-MEE-no", english: "I would find the way" },
                { targetText: "saltaríamos de alegría", phoneticTranscription: "sal-ta-REE-ah-mohs de a-le-GREE-a", english: "we would jump for joy" },
                { targetText: "llamarías a tu madre", phoneticTranscription: "ya-ma-REE-as a too MA-dre", english: "you would call your mother" },
                { targetText: "mandaríamos fotos", phoneticTranscription: "man-da-REE-ah-mohs FO-tos", english: "we would send photos" },
                { targetText: "preguntaría el precio", phoneticTranscription: "pre-goon-ta-REE-ah el PRE-syo", english: "I would ask the price" },
                { targetText: "sabría la respuesta", phoneticTranscription: "sa-BREE-ah la res-PWES-ta", english: "I would know the answer" },
                { targetText: "vendrían mañana", phoneticTranscription: "ben-DREE-ahn ma-NYA-na", english: "they would come tomorrow" },
                { targetText: "saldríamos tarde", phoneticTranscription: "sal-DREE-ah-mohs TAR-de", english: "we would leave late" },
                { targetText: "pondría la mesa", phoneticTranscription: "pohn-DREE-ah la ME-sa", english: "I would set the table" },
                { targetText: "podría ser", phoneticTranscription: "poh-DREE-ah SEHR", english: "it could be" },
                { targetText: "habrías llegado", phoneticTranscription: "ah-BREE-as yeh-GA-doh", english: "you would have arrived" },
                { targetText: "preferiría dormir", phoneticTranscription: "pre-fe-ree-REE-ah dor-MEER", english: "I would prefer to sleep" },
                { targetText: "encantaría viajar", phoneticTranscription: "ehn-kan-ta-REE-ah byyah-HAR", english: "it would enchant (I'd love) to travel" },
                { targetText: "gustaría comer", phoneticTranscription: "goos-ta-REE-ah koh-MER", english: "it would please (I'd like) to eat" },
                { targetText: "necesitaría ayuda", phoneticTranscription: "ne-se-see-ta-REE-ah a-YOO-da", english: "I would need help" },
                { targetText: "esperaría un poco", phoneticTranscription: "es-pe-ra-REE-ah oon PO-koh", english: "I would wait a bit" },
                { targetText: "miraría el mapa", phoneticTranscription: "mee-ra-REE-ah el MA-pa", english: "I would look at the map" },
                { targetText: "escucharíamos radio", phoneticTranscription: "es-koo-cha-REE-ah-mohs RA-dyo", english: "we would listen to radio" },
                { targetText: "vería un milagro", phoneticTranscription: "be-REE-ah oon mee-LA-gro", english: "I would see a miracle" },
                { targetText: "haría frío allá", phoneticTranscription: "ah-REE-ah FREE-oh a-YA", english: "it would be cold there" },
                { targetText: "habría esperanza", phoneticTranscription: "ah-BREE-ah es-pe-RAN-sa", english: "there would be hope" },
                { targetText: "podríamos ganar", phoneticTranscription: "poh-DREE-ah-mohs ga-NAR", english: "we could win" },
                { targetText: "sabrías qué hacer", phoneticTranscription: "sa-BREE-as KE a-SER", english: "you would know what to do" },
                { targetText: "tendría sentido", phoneticTranscription: "ten-DREE-ah sen-TEE-doh", english: "it would make sense" },
                { targetText: "valdría la pena", phoneticTranscription: "val-DREE-ah la PE-na", english: "it would be worth it" }
            ]
        }
    ];

    for (const module of modules) {
        await db.collection('languages').doc('spanish')
            .collection('levels').doc('a2')
            .collection('modules').doc(module.moduleId).set(module);
        console.log(`Uploaded ${module.moduleId}: ${module.theme} with ${module.vocabularyItems.length} words.`);
    }
}

uploadPart1().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
